### ISSUE TITLE
Changing Line colors based on some conditions

### ISSUE THREAD

**Issue by JahedulAnowar** [jsplumb/jsplumb#1002]
<img width="941" alt="Screen Shot 2020-12-11 at 16 06 59" src="https://user-images.githubusercontent.com/12004879/101874065-7c9d1000-3bcb-11eb-97c1-c18e21ae50a0.png">

In the above graph i want to assign different line color to the two groups of nodes. Is possible to do it using some conditions like the name of the nodes or something?
If yes, can you help me with it or maybe give me some hints.
TIA.

**Comment by sporritt** [comment]
Not in the community edition, no. In the Toolkit edition you'd use [UI States](https://docs.jsplumbtoolkit.com/toolkit/5.x/lib/ui-states) for this.
