### ISSUE TITLE
RC26 and 27 don't appear to contain any files

### ISSUE THREAD

**Issue by sebovzeoueb** [jsplumb/jsplumb#1005]
npm installing RC26 and 27 is resulting in a directory containing just a package.json and nothing else.

https://i.imgur.com/N53mW9w.png

**Comment by sporritt** [comment]
ah, whoops.  4.0.0-RC28 published now, it has files.

**Comment by antishov** [comment]
Hi
The same problem with RC29

**Comment by sporritt** [comment]
@antishov did you know there was no code change in RC29 though...you don't actually need to upgrade to it.

**Comment by sporritt** [comment]
@antishov RC-31 is the next version that doesn't have this packaging error.

I guess you have imported @jsplumb/community with a wildcard so you're getting each release as it comes out. Just a heads up on this: RC32 contains several breaking changes. They are detailed in the changelog.md.
