### ISSUE TITLE
IE11 compatibility?

### ISSUE THREAD

**Issue by brunnerh** [jsplumb/jsplumb#1006]
`@jsplumb/community` at version 4.0.0-RC28 uses various functions not supported in IE11.

My code got an error for a use of `Array.prototype.findIndex`, but there seem to be other unsupported array related function calls as well.

I saw these unsupported functions in the code, maybe there are more:
- `Array.from`
- `Array.prototype.find`
- `Array.prototype.findIndex`

So in case this version of the library is supposed to work in IE11 "out of the box" some integrated polyfills or workarounds would be required.

**Comment by brunnerh** [comment]
To clear the error in my code, I imported some `core-js` polyfills for now. Apart from the array functions there also appear to be uses of `Symbol`/`Symbol.iterator` that need to be polyfilled.

```js
import 'core-js/features/symbol';
import 'core-js/features/symbol/iterator';
import 'core-js/features/set'; // Use of Symbol.iterator on Set
import 'core-js/features/array/from';
import 'core-js/features/array/find';
import 'core-js/features/array/find-index';
```

**Comment by sporritt** [comment]
Thanks for this.  I've always been keen to support as many browsers as possible in jsPlumb so I'll look into it.  I imagine the solution will be kind of as you have it - a list of core js polyfills. I know that's what Angular does to support IE11 too.

**Comment by sporritt** [comment]
Just came across some IE11 stuff when working on the Toolkit, tracking some methods here:

- `forEach`
- `find`
- `findIndex`

all on Array, and `Object.assign`.

**Comment by sporritt** [comment]
also, `Map` does not support constructor args, eg

```
const m = new Map([
  ["foo", "bar"]
]);
```

it is necessary instead to construct the Map and set individual values on it:

```
const m = new Map();
m.set("foo", "bar");
```

**Comment by sporritt** [comment]
`Map` and `Set` both _do_ have `forEach` in IE11.

**Comment by sporritt** [comment]
@brunnerh version 4.0.0-RC51 has no need for polyfills for IE11.  Closing this.
