### ISSUE TITLE
Connection click event doesn't provide endpoint data

### ISSUE THREAD

**Issue by madsci77** [jsplumb/jsplumb#1008]
I've got a click handler taken straight from the example that deletes the clicked connection, but before it does that I need to determine which endpoints it's connected to.

For some reason, the connection provided by the click event always gives null for endpoints[]. source and target are also null. sourceId and targetId are set but I can see no way to determine which endpoints are associated with the connection. I have to query again for a matching connection and then get the endpoints from that. It seems like it ought to be simpler to determine what the connector connects to.

**Comment by sporritt** [comment]
that does seem odd, but since there's a workaround for it and this is not something that's been asked before, it's unlikely there'll be any change made to the code in the 2.x branch about this.
