### ISSUE TITLE
Version 4 documentation

### ISSUE THREAD

**Issue by thedatamineio** [jsplumb/jsplumb#1011]
Where is the community documentation for version 4?

**Comment by wederer** [comment]
I was also wondering that. It is really hard to test the alpha without any documentation.

**Comment by sporritt** [comment]
@wederer i like the idea of doing the demos in typescript.

what sort of docs do you need, beyond the .d.ts files?

**Comment by sporritt** [comment]
@wederer I've created a Typescript version of one of the jsPlumb demonstrations now:

https://github.com/jsplumb-demonstrations/flowchart/tree/main/ts

It needs 4.0.0-RC52, which was just released.  I'll be going through the rest of the demonstrations and creating Typescript versions of them over the next couple of weeks.

**Comment by wederer** [comment]
Hi @sporritt. The jsplumb-demonstrations repo seems to be private. Could you double-check?

Thanks in advance!

**Comment by sporritt** [comment]
@wederer try now...

**Comment by sporritt** [comment]
I thought i'd already made them public but i guess that was the Toolkit ones.  I'll make the others public as I get to doing their Typescript versions.

**Comment by sporritt** [comment]
version 4 - which ultimately ended up being version 5 - is documented here:

https://docs.jsplumbtoolkit.com/community
