### ISSUE TITLE
Shadow DOM

### ISSUE THREAD

**Issue by MarkoHari3716** [jsplumb/jsplumb#1012]
I work with jsPlumb community 4.x RC34. I tried to render svg element inside shadow dom but  it doesn't render right way, tried on two ways. First ways render svg element without instance.batch function, problem is that endpoint and connection not rendered in the right place. 
![image01](https://user-images.githubusercontent.com/48455134/105336119-2616ee80-5bd9-11eb-8c22-89f2e9303077.PNG)
Other way is render endpoint and connection inside instace.batch function, but problem is when render element, library tried to get element with document.getElementById. But my element is inside shadow dom, document get see this html element. 

If anyone knows please help.
Thank you!

**Comment by sporritt** [comment]
From RC34 jsPlumb doesn't use element IDs anymore. It uses a `jtk-id` attribute instead.  Can you provide example code for what you are doing?

**Comment by MarkoHari3716** [comment]
Thank you for the answer. This is code.

`setFlowCharDemo() {
        let root = this.shadowRoot;
        let container = root.querySelector('#canvas');

        let instance = (window.jsp = newInstance({
            dragOptions: { cursor: 'pointer', zIndex: 2000, grid: [20, 20] },
            connectionOverlays: [
                [
                    'Arrow',
                    {
                        location: 1,
                        visible: true,
                        width: 11,
                        length: 11,
                        id: 'ARROW',
                        events: {
                            click: function () {
                                alert('you clicked on the arrow overlay');
                            },
                        },
                    },
                ],
                [
                    'Label',
                    {
                        location: 0.1,
                        id: 'label',
                        cssClass: 'aLabel',
                        events: {
                            tap: function () {
                                alert('hey');
                            },
                        },
                    },
                ],
            ],
            container: container,
        }));

        let connectorPaintStyle = {
                strokeWidth: 2,
                stroke: '#61B7CF',
                joinstyle: 'round',
                outlineStroke: 'white',
                outlineWidth: 2,
            },
            connectorHoverStyle = {
                strokeWidth: 3,
                stroke: '#216477',
                outlineWidth: 5,
                outlineStroke: 'white',
            },
            endpointHoverStyle = {
                fill: '#216477',
                stroke: '#216477',
            },
            sourceEndpoint = {
                endpoint: 'Dot',
                paintStyle: {
                    stroke: '#7AB02C',
                    fill: 'transparent',
                    radius: 7,
                    strokeWidth: 1,
                },
                isSource: true,
                connector: ['Flowchart', { stub: [40, 60], gap: 10, cornerRadius: 5, alwaysRespectStubs: true }],
                connectorStyle: connectorPaintStyle,
                hoverPaintStyle: endpointHoverStyle,
                connectorHoverStyle: connectorHoverStyle,
                dragOptions: {},
                overlays: [
                    [
                        'Label',
                        {
                            location: [0.5, 1.5],
                            label: 'Drag',
                            cssClass: 'endpointSourceLabel',
                            visible: true,
                        },
                    ],
                ],
            },
            targetEndpoint = {
                endpoint: 'Dot',
                paintStyle: { fill: '#7AB02C', radius: 7 },
                hoverPaintStyle: endpointHoverStyle,
                maxConnections: -1,
                dropOptions: { hoverClass: 'hover', activeClass: 'active' },
                isTarget: true,
                overlays: [
                    ['Label', { location: [0.5, -0.5], label: 'Drop', cssClass: 'endpointTargetLabel', visible: true }],
                ],
            },
            init = function (connection) {
                connection
                    .getOverlay('label')
                    .setLabel(connection.sourceId.substring(10) + '-' + connection.targetId.substring(10));
            };

        let getFlowWindow = (windowId) => {
            return root.querySelector('#' + windowId);
        };

        let _addEndpoints = function (toId, sourceAnchors, targetAnchors) {
            for (var i = 0; i < sourceAnchors.length; i++) {
                var sourceUUID = toId + sourceAnchors[i];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), sourceEndpoint, {
                    anchor: sourceAnchors[i],
                    uuid: sourceUUID,
                }, root);
            }
            for (var j = 0; j < targetAnchors.length; j++) {
                var targetUUID = toId + targetAnchors[j];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), targetEndpoint, {
                    anchor: targetAnchors[j],
                    uuid: targetUUID,
                });
            }
        };

        instance.batch(function () {

            
        })

        instance.batch(function () {
            _addEndpoints('Window4', ['TopCenter', 'BottomCenter'], ['LeftMiddle', 'RightMiddle']);
            _addEndpoints('Window2', ['LeftMiddle', 'BottomCenter'], ['TopCenter', 'RightMiddle']);
            _addEndpoints('Window3', ['RightMiddle', 'BottomCenter'], ['LeftMiddle', 'TopCenter']);
            _addEndpoints('Window1', ['LeftMiddle', 'RightMiddle'], ['TopCenter', 'BottomCenter']);
    
            instance.bind('connection', function (connInfo, originalEvent) {
                init(connInfo.connection);
            });
    
            instance.connect({ uuids: ['Window2BottomCenter', 'Window3TopCenter'] });
            instance.connect({ uuids: ['Window2LeftMiddle', 'Window4LeftMiddle'] });
            instance.connect({ uuids: ['Window4TopCenter', 'Window4RightMiddle'] });
            instance.connect({ uuids: ['Window3RightMiddle', 'Window2RightMiddle'] });
            instance.connect({ uuids: ['Window4BottomCenter', 'Window1TopCenter'] });
            instance.connect({ uuids: ['Window3BottomCenter', 'Window1BottomCenter'] });
    
            instance.bind('click', function (conn, originalEvent) {
                if (confirm('Delete connection from ' + conn.sourceId + ' to ' + conn.targetId + '?')) {
                    instance.deleteConnection(conn);
                }
            });
    
            instance.bind('connectionDrag', function (connection) {
                console.log(
                    'connection ' + connection.id + ' is being dragged. suspendedElement is ',
                    connection.suspendedElement,
                    ' of type ',
                    connection.suspendedElementType
                );
            });
    
            instance.bind('connectionDragStop', function (connection) {
                console.log('connection ' + connection.id + ' was dragged');
            });
    
            instance.bind('connectionMoved', function (params) {
                console.log('connection ' + params.connection.id + ' was moved');
            });
        });
    }`

setFlowCharDemo() {
        let root = this.shadowRoot;
        let container = root.querySelector('#canvas');

        let instance = (window.jsp = newInstance({
            dragOptions: { cursor: 'pointer', zIndex: 2000, grid: [20, 20] },
            connectionOverlays: [
                [
                    'Arrow',
                    {
                        location: 1,
                        visible: true,
                        width: 11,
                        length: 11,
                        id: 'ARROW',
                        events: {
                            click: function () {
                                alert('you clicked on the arrow overlay');
                            },
                        },
                    },
                ],
                [
                    'Label',
                    {
                        location: 0.1,
                        id: 'label',
                        cssClass: 'aLabel',
                        events: {
                            tap: function () {
                                alert('hey');
                            },
                        },
                    },
                ],
            ],
            container: container,
        }));

        let connectorPaintStyle = {
                strokeWidth: 2,
                stroke: '#61B7CF',
                joinstyle: 'round',
                outlineStroke: 'white',
                outlineWidth: 2,
            },
            connectorHoverStyle = {
                strokeWidth: 3,
                stroke: '#216477',
                outlineWidth: 5,
                outlineStroke: 'white',
            },
            endpointHoverStyle = {
                fill: '#216477',
                stroke: '#216477',
            },
            sourceEndpoint = {
                endpoint: 'Dot',
                paintStyle: {
                    stroke: '#7AB02C',
                    fill: 'transparent',
                    radius: 7,
                    strokeWidth: 1,
                },
                isSource: true,
                connector: ['Flowchart', { stub: [40, 60], gap: 10, cornerRadius: 5, alwaysRespectStubs: true }],
                connectorStyle: connectorPaintStyle,
                hoverPaintStyle: endpointHoverStyle,
                connectorHoverStyle: connectorHoverStyle,
                dragOptions: {},
                overlays: [
                    [
                        'Label',
                        {
                            location: [0.5, 1.5],
                            label: 'Drag',
                            cssClass: 'endpointSourceLabel',
                            visible: true,
                        },
                    ],
                ],
            },
            targetEndpoint = {
                endpoint: 'Dot',
                paintStyle: { fill: '#7AB02C', radius: 7 },
                hoverPaintStyle: endpointHoverStyle,
                maxConnections: -1,
                dropOptions: { hoverClass: 'hover', activeClass: 'active' },
                isTarget: true,
                overlays: [
                    ['Label', { location: [0.5, -0.5], label: 'Drop', cssClass: 'endpointTargetLabel', visible: true }],
                ],
            },
            init = function (connection) {
                connection
                    .getOverlay('label')
                    .setLabel(connection.sourceId.substring(10) + '-' + connection.targetId.substring(10));
            };

        let getFlowWindow = (windowId) => {
            return root.querySelector('#' + windowId);
        };

        let _addEndpoints = function (toId, sourceAnchors, targetAnchors) {
            for (var i = 0; i < sourceAnchors.length; i++) {
                var sourceUUID = toId + sourceAnchors[i];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), sourceEndpoint, {
                    anchor: sourceAnchors[i],
                    uuid: sourceUUID,
                }, root);
            }
            for (var j = 0; j < targetAnchors.length; j++) {
                var targetUUID = toId + targetAnchors[j];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), targetEndpoint, {
                    anchor: targetAnchors[j],
                    uuid: targetUUID,
                });
            }
        };

        instance.batch(function () {

            
        })

        instance.batch(function () {
            _addEndpoints('Window4', ['TopCenter', 'BottomCenter'], ['LeftMiddle', 'RightMiddle']);
            _addEndpoints('Window2', ['LeftMiddle', 'BottomCenter'], ['TopCenter', 'RightMiddle']);
            _addEndpoints('Window3', ['RightMiddle', 'BottomCenter'], ['LeftMiddle', 'TopCenter']);
            _addEndpoints('Window1', ['LeftMiddle', 'RightMiddle'], ['TopCenter', 'BottomCenter']);
    
            instance.bind('connection', function (connInfo, originalEvent) {
                init(connInfo.connection);
            });
    
            instance.connect({ uuids: ['Window2BottomCenter', 'Window3TopCenter'] });
            instance.connect({ uuids: ['Window2LeftMiddle', 'Window4LeftMiddle'] });
            instance.connect({ uuids: ['Window4TopCenter', 'Window4RightMiddle'] });
            instance.connect({ uuids: ['Window3RightMiddle', 'Window2RightMiddle'] });
            instance.connect({ uuids: ['Window4BottomCenter', 'Window1TopCenter'] });
            instance.connect({ uuids: ['Window3BottomCenter', 'Window1BottomCenter'] });
    
            instance.bind('click', function (conn, originalEvent) {
                if (confirm('Delete connection from ' + conn.sourceId + ' to ' + conn.targetId + '?')) {
                    instance.deleteConnection(conn);
                }
            });
    
            instance.bind('connectionDrag', function (connection) {
                console.log(
                    'connection ' + connection.id + ' is being dragged. suspendedElement is ',
                    connection.suspendedElement,
                    ' of type ',
                    connection.suspendedElementType
                );
            });
    
            instance.bind('connectionDragStop', function (connection) {
                console.log('connection ' + connection.id + ' was dragged');
            });
    
            instance.bind('connectionMoved', function (params) {
                console.log('connection ' + params.connection.id + ' was moved');
            });
        });
    }

**Comment by MarkoHari3716** [comment]
Thank you for answer! 

`setFlowCharDemo() {

        let root = this.shadowRoot;
        let container = root.querySelector("#canvas");
        let instance = (window.jsp = newInstance({
            dragOptions: { cursor: 'pointer', zIndex: 2000, grid: [20, 20] },
            connectionOverlays: [
                [
                    'Arrow',
                    {
                        location: 1,
                        visible: true,
                        width: 11,
                        length: 11,
                        id: 'ARROW',
                        events: {
                            click: function () {
                                alert('you clicked on the arrow overlay');
                            },
                        },
                    },
                ],
                [
                    'Label',
                    {
                        location: 0.1,
                        id: 'label',
                        cssClass: 'aLabel',
                        events: {
                            tap: function () {
                                alert('hey');
                            },
                        },
                    },
                ],
            ],
            container: container,
        }));

        let connectorPaintStyle = {
                strokeWidth: 2,
                stroke: '#61B7CF',
                joinstyle: 'round',
                outlineStroke: 'white',
                outlineWidth: 2,
            },
            connectorHoverStyle = {
                strokeWidth: 3,
                stroke: '#216477',
                outlineWidth: 5,
                outlineStroke: 'white',
            },
            endpointHoverStyle = {
                fill: '#216477',
                stroke: '#216477',
            },
            sourceEndpoint = {
                endpoint: 'Dot',
                paintStyle: {
                    stroke: '#7AB02C',
                    fill: 'transparent',
                    radius: 7,
                    strokeWidth: 1,
                },
                isSource: true,
                connector: ['Flowchart', { stub: [40, 60], gap: 10, cornerRadius: 5, alwaysRespectStubs: true }],
                connectorStyle: connectorPaintStyle,
                hoverPaintStyle: endpointHoverStyle,
                connectorHoverStyle: connectorHoverStyle,
                dragOptions: {},
                overlays: [
                    [
                        'Label',
                        {
                            location: [0.5, 1.5],
                            label: 'Drag',
                            cssClass: 'endpointSourceLabel',
                            visible: true,
                        },
                    ],
                ],
            },
            targetEndpoint = {
                endpoint: 'Dot',
                paintStyle: { fill: '#7AB02C', radius: 7 },
                hoverPaintStyle: endpointHoverStyle,
                maxConnections: -1,
                dropOptions: { hoverClass: 'hover', activeClass: 'active' },
                isTarget: true,
                overlays: [
                    ['Label', { location: [0.5, -0.5], label: 'Drop', cssClass: 'endpointTargetLabel', visible: true }],
                ],
            },
            init = function (connection) {
                connection
                    .getOverlay('label')
                    .setLabel(connection.sourceId.substring(10) + '-' + connection.targetId.substring(10));
            };

        let getFlowWindow = (windowId) => {
            return root.querySelector('#' + windowId);
        };

        let _addEndpoints = function (toId, sourceAnchors, targetAnchors) {
            for (var i = 0; i < sourceAnchors.length; i++) {
                var sourceUUID = toId + sourceAnchors[i];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), sourceEndpoint, {
                    anchor: sourceAnchors[i],
                    uuid: sourceUUID,
                }, root);
            }
            for (var j = 0; j < targetAnchors.length; j++) {
                var targetUUID = toId + targetAnchors[j];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), targetEndpoint, {
                    anchor: targetAnchors[j],
                    uuid: targetUUID,
                });
            }
        };

        instance.batch(function () {

            
        })

        instance.batch(function () {
            _addEndpoints('Window4', ['TopCenter', 'BottomCenter'], ['LeftMiddle', 'RightMiddle']);
            _addEndpoints('Window2', ['LeftMiddle', 'BottomCenter'], ['TopCenter', 'RightMiddle']);
            _addEndpoints('Window3', ['RightMiddle', 'BottomCenter'], ['LeftMiddle', 'TopCenter']);
            _addEndpoints('Window1', ['LeftMiddle', 'RightMiddle'], ['TopCenter', 'BottomCenter']);
    
            instance.bind('connection', function (connInfo, originalEvent) {
                init(connInfo.connection);
            });
    
            instance.connect({ uuids: ['Window2BottomCenter', 'Window3TopCenter'] });
            instance.connect({ uuids: ['Window2LeftMiddle', 'Window4LeftMiddle'] });
            instance.connect({ uuids: ['Window4TopCenter', 'Window4RightMiddle'] });
            instance.connect({ uuids: ['Window3RightMiddle', 'Window2RightMiddle'] });
            instance.connect({ uuids: ['Window4BottomCenter', 'Window1TopCenter'] });
            instance.connect({ uuids: ['Window3BottomCenter', 'Window1BottomCenter'] });
    
            instance.bind('click', function (conn, originalEvent) {
                if (confirm('Delete connection from ' + conn.sourceId + ' to ' + conn.targetId + '?')) {
                    instance.deleteConnection(conn);
                }
            });
    
            instance.bind('connectionDrag', function (connection) {
                console.log(
                    'connection ' + connection.id + ' is being dragged. suspendedElement is ',
                    connection.suspendedElement,
                    ' of type ',
                    connection.suspendedElementType
                );
            });
    
            instance.bind('connectionDragStop', function (connection) {
                console.log('connection ' + connection.id + ' was dragged');
            });
    
            instance.bind('connectionMoved', function (params) {
                console.log('connection ' + params.connection.id + ' was moved');
            });
        });
    }
`

**Comment by MarkoHari3716** [comment]
Thank you for answer!

` let root = this.shadowRoot;

        let container = root.querySelector('#canvas');
        let instance = (window.jsp = newInstance({
            dragOptions: { cursor: 'pointer', zIndex: 2000, grid: [20, 20] },
            connectionOverlays: [
                [
                    'Arrow',
                    {
                        location: 1,
                        visible: true,
                        width: 11,
                        length: 11,
                        id: 'ARROW',
                        events: {
                            click: function () {
                                alert('you clicked on the arrow overlay');
                            },
                        },
                    },
                ],
                [
                    'Label',
                    {
                        location: 0.1,
                        id: 'label',
                        cssClass: 'aLabel',
                        events: {
                            tap: function () {
                                alert('hey');
                            },
                        },
                    },
                ],
            ],
            container: container,
        }));

        let connectorPaintStyle = {
                strokeWidth: 2,
                stroke: '#61B7CF',
                joinstyle: 'round',
                outlineStroke: 'white',
                outlineWidth: 2,
            },
            connectorHoverStyle = {
                strokeWidth: 3,
                stroke: '#216477',
                outlineWidth: 5,
                outlineStroke: 'white',
            },
            endpointHoverStyle = {
                fill: '#216477',
                stroke: '#216477',
            },
            sourceEndpoint = {
                endpoint: 'Dot',
                paintStyle: {
                    stroke: '#7AB02C',
                    fill: 'transparent',
                    radius: 7,
                    strokeWidth: 1,
                },
                isSource: true,
                connector: ['Flowchart', { stub: [40, 60], gap: 10, cornerRadius: 5, alwaysRespectStubs: true }],
                connectorStyle: connectorPaintStyle,
                hoverPaintStyle: endpointHoverStyle,
                connectorHoverStyle: connectorHoverStyle,
                dragOptions: {},
                overlays: [
                    [
                        'Label',
                        {
                            location: [0.5, 1.5],
                            label: 'Drag',
                            cssClass: 'endpointSourceLabel',
                            visible: true,
                        },
                    ],
                ],
            },
            targetEndpoint = {
                endpoint: 'Dot',
                paintStyle: { fill: '#7AB02C', radius: 7 },
                hoverPaintStyle: endpointHoverStyle,
                maxConnections: -1,
                dropOptions: { hoverClass: 'hover', activeClass: 'active' },
                isTarget: true,
                overlays: [
                    ['Label', { location: [0.5, -0.5], label: 'Drop', cssClass: 'endpointTargetLabel', visible: true }],
                ],
            },
            init = function (connection) {
                connection
                    .getOverlay('label')
                    .setLabel(connection.sourceId.substring(10) + '-' + connection.targetId.substring(10));
            };

        let getFlowWindow = (windowId) => {
            return root.querySelector('#' + windowId);
        };

        let _addEndpoints = function (toId, sourceAnchors, targetAnchors) {
            for (var i = 0; i < sourceAnchors.length; i++) {
                var sourceUUID = toId + sourceAnchors[i];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), sourceEndpoint, {
                    anchor: sourceAnchors[i],
                    uuid: sourceUUID,
                }, root);
            }
            for (var j = 0; j < targetAnchors.length; j++) {
                var targetUUID = toId + targetAnchors[j];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), targetEndpoint, {
                    anchor: targetAnchors[j],
                    uuid: targetUUID,
                });
            }
        };

        instance.batch(function () {
            _addEndpoints('Window4', ['TopCenter', 'BottomCenter'], ['LeftMiddle', 'RightMiddle']);
            _addEndpoints('Window2', ['LeftMiddle', 'BottomCenter'], ['TopCenter', 'RightMiddle']);
            _addEndpoints('Window3', ['RightMiddle', 'BottomCenter'], ['LeftMiddle', 'TopCenter']);
            _addEndpoints('Window1', ['LeftMiddle', 'RightMiddle'], ['TopCenter', 'BottomCenter']);
    
            instance.bind('connection', function (connInfo, originalEvent) {
                init(connInfo.connection);
            });
    
            instance.connect({ uuids: ['Window2BottomCenter', 'Window3TopCenter'] });
            instance.connect({ uuids: ['Window2LeftMiddle', 'Window4LeftMiddle'] });
            instance.connect({ uuids: ['Window4TopCenter', 'Window4RightMiddle'] });
            instance.connect({ uuids: ['Window3RightMiddle', 'Window2RightMiddle'] });
            instance.connect({ uuids: ['Window4BottomCenter', 'Window1TopCenter'] });
            instance.connect({ uuids: ['Window3BottomCenter', 'Window1BottomCenter'] });
    
            instance.bind('click', function (conn, originalEvent) {
                if (confirm('Delete connection from ' + conn.sourceId + ' to ' + conn.targetId + '?')) {
                    instance.deleteConnection(conn);
                }
            });
    
            instance.bind('connectionDrag', function (connection) {
                console.log(
                    'connection ' + connection.id + ' is being dragged. suspendedElement is ',
                    connection.suspendedElement,
                    ' of type ',
                    connection.suspendedElementType
                );
            });
    
            instance.bind('connectionDragStop', function (connection) {
                console.log('connection ' + connection.id + ' was dragged');
            });
    
            instance.bind('connectionMoved', function (params) {
                console.log('connection ' + params.connection.id + ' was moved');
            });
        });`

**Comment by MarkoHari3716** [comment]
Thank you for answer! Code is down below.

`let root = this.shadowRoot;

        let container = root.querySelector('#canvas');
        let instance = window.jsp = newInstance({
            dragOptions: { cursor: 'pointer', zIndex: 2000, grid: [20, 20] },
            connectionOverlays: [
                [
                    'Arrow',
                    {
                        location: 1,
                        visible: true,
                        width: 11,
                        length: 11,
                        id: 'ARROW',
                        events: {
                            click: function () {
                                alert('you clicked on the arrow overlay');
                            },
                        },
                    },
                ],
                [
                    'Label',
                    {
                        location: 0.1,
                        id: 'label',
                        cssClass: 'aLabel',
                        events: {
                            tap: function () {
                                alert('hey');
                            },
                        },
                    },
                ],
            ],
            container: container,
        });

        let connectorPaintStyle = {
                strokeWidth: 2,
                stroke: '#61B7CF',
                joinstyle: 'round',
                outlineStroke: 'white',
                outlineWidth: 2,
            },
            connectorHoverStyle = {
                strokeWidth: 3,
                stroke: '#216477',
                outlineWidth: 5,
                outlineStroke: 'white',
            },
            endpointHoverStyle = {
                fill: '#216477',
                stroke: '#216477',
            },
            sourceEndpoint = {
                endpoint: 'Dot',
                paintStyle: {
                    stroke: '#7AB02C',
                    fill: 'transparent',
                    radius: 7,
                    strokeWidth: 1,
                },
                isSource: true,
                connector: ['Flowchart', { stub: [40, 60], gap: 10, cornerRadius: 5, alwaysRespectStubs: true }],
                connectorStyle: connectorPaintStyle,
                hoverPaintStyle: endpointHoverStyle,
                connectorHoverStyle: connectorHoverStyle,
                dragOptions: {},
                overlays: [
                    [
                        'Label',
                        {
                            location: [0.5, 1.5],
                            label: 'Drag',
                            cssClass: 'endpointSourceLabel',
                            visible: true,
                        },
                    ],
                ],
            },
            targetEndpoint = {
                endpoint: 'Dot',
                paintStyle: { fill: '#7AB02C', radius: 7 },
                hoverPaintStyle: endpointHoverStyle,
                maxConnections: -1,
                dropOptions: { hoverClass: 'hover', activeClass: 'active' },
                isTarget: true,
                overlays: [
                    ['Label', { location: [0.5, -0.5], label: 'Drop', cssClass: 'endpointTargetLabel', visible: true }],
                ],
            },
            init = function (connection) {
                connection
                    .getOverlay('label')
                    .setLabel(connection.sourceId.substring(10) + '-' + connection.targetId.substring(10));
            };

        let getFlowWindow = (windowId) => {
            return root.querySelector('#' + windowId);
        };

        let _addEndpoints = function (toId, sourceAnchors, targetAnchors) {
            for (var i = 0; i < sourceAnchors.length; i++) {
                var sourceUUID = toId + sourceAnchors[i];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), sourceEndpoint, {
                    anchor: sourceAnchors[i],
                    uuid: sourceUUID,
                }, root);
            }
            for (var j = 0; j < targetAnchors.length; j++) {
                var targetUUID = toId + targetAnchors[j];
                instance.addEndpoint(getFlowWindow('flowchart' + toId), targetEndpoint, {
                    anchor: targetAnchors[j],
                    uuid: targetUUID,
                });
            }
        };

        instance.batch(function () {
            _addEndpoints('Window4', ['TopCenter', 'BottomCenter'], ['LeftMiddle', 'RightMiddle']);
            _addEndpoints('Window2', ['LeftMiddle', 'BottomCenter'], ['TopCenter', 'RightMiddle']);
            _addEndpoints('Window3', ['RightMiddle', 'BottomCenter'], ['LeftMiddle', 'TopCenter']);
            _addEndpoints('Window1', ['LeftMiddle', 'RightMiddle'], ['TopCenter', 'BottomCenter']);
    
            instance.bind('connection', function (connInfo, originalEvent) {
                init(connInfo.connection);
            });
    
            instance.connect({ uuids: ['Window2BottomCenter', 'Window3TopCenter'] });
            instance.connect({ uuids: ['Window2LeftMiddle', 'Window4LeftMiddle'] });
            instance.connect({ uuids: ['Window4TopCenter', 'Window4RightMiddle'] });
            instance.connect({ uuids: ['Window3RightMiddle', 'Window2RightMiddle'] });
            instance.connect({ uuids: ['Window4BottomCenter', 'Window1TopCenter'] });
            instance.connect({ uuids: ['Window3BottomCenter', 'Window1BottomCenter'] });
    
            instance.bind('click', function (conn, originalEvent) {
                if (confirm('Delete connection from ' + conn.sourceId + ' to ' + conn.targetId + '?')) {
                    instance.deleteConnection(conn);
                }
            });
    
            instance.bind('connectionDrag', function (connection) {
                console.log(
                    'connection ' + connection.id + ' is being dragged. suspendedElement is ',
                    connection.suspendedElement,
                    ' of type ',
                    connection.suspendedElementType
                );
            });
    
            instance.bind('connectionDragStop', function (connection) {
                console.log('connection ' + connection.id + ' was dragged');
            });
    
            instance.bind('connectionMoved', function (params) {
                console.log('connection ' + params.connection.id + ' was moved');
            });
        });`

**Comment by sporritt** [comment]
thanks. can you also share the error you see when you use `batch` ?

**Comment by MarkoHari3716** [comment]
There is no error using batch method, just wrong render. 
![image02](https://user-images.githubusercontent.com/48455134/105476979-9426e880-5ca1-11eb-8251-9084da7cae43.PNG)

I think is problem, when library tried to get element with getElementById. this.getElement return null and function _draw can't right render.
![image03](https://user-images.githubusercontent.com/48455134/105477498-35ae3a00-5ca2-11eb-8afd-9b3e25048beb.PNG)
![image04](https://user-images.githubusercontent.com/48455134/105477500-36df6700-5ca2-11eb-8662-603d6f6dba6b.PNG)

**Comment by sporritt** [comment]
Right I see there is a getElementById there - I think I got it confused with RC35, in which that has been changed. I doubt that it has any bearing on your situation here but I will publish RC35 tomorrow.

So, what is the thinking behind using the shadow dom here?

**Comment by MarkoHari3716** [comment]
I made a gif, to help solve this problem. 
![gif01](https://user-images.githubusercontent.com/48455134/105488508-04d60100-5cb2-11eb-8111-4fc5d92d2902.gif)

Work with framework that is based on web component.

**Comment by sporritt** [comment]
have you closed this because you've got it to work?

**Comment by MarkoHari3716** [comment]
Hello yes, I found a way to solve the problem. I create property "shadowRoot" that can retrieve html elements. First need to set property with method "setShadowRoot" and in method "getElement" check if "shadowRoot" is set., if this is true method use "shadowRoot" to querySelector on html elements.  "getElement" method is now abstract and can work with dom and shadow dom.

app.js
![image05](https://user-images.githubusercontent.com/48455134/105830565-f21b3f00-5fc5-11eb-81bd-6676d7fb95be.PNG)

jsplumb.community.es.js
![image06](https://user-images.githubusercontent.com/48455134/105830569-f34c6c00-5fc5-11eb-845a-9dea7d6db708.PNG)
![image07](https://user-images.githubusercontent.com/48455134/105830573-f47d9900-5fc5-11eb-9a6f-d1493d7704aa.PNG)
![image08](https://user-images.githubusercontent.com/48455134/105830576-f5aec600-5fc5-11eb-9dfe-53ad6acf97c0.PNG)

**Comment by sporritt** [comment]
thanks for the update.  So, this `getElement` method is called only twice in the code - firstly when an ID is passed as the `container`, support for which I'm actually going to remove, since its unnecessary. The second place is in the `_draw` routine, in which the code iterates a list of IDs, converting each one into an Element with `getElement`. It's here that the confusion with shadow root is occurring, and it's also something I've wanted to change for ages. So I'll make this change for the next release of 4.x, and I think you'll be able to update to that version without needing to put this shadowRoot change in. I'll update this issue when the new version is released.

**Comment by sporritt** [comment]
Can you tell me what element you are using as the `container` in your code?

**Comment by MarkoHari3716** [comment]
Thanks for you work and create new feature.

**Comment by sporritt** [comment]
Great, thanks. So this proposed change will fix the issue for you.

**Comment by sporritt** [comment]
@MarkoHari3716 4.0.0-RC39 was just published. Could you give it a try when you have a moment?

**Comment by MarkoHari3716** [comment]
@sporritt works perfectly. Thank you very much, I appreciate your work.

**Comment by sporritt** [comment]
Thanks for letting me know. Glad it's working.
