### ISSUE TITLE
Endpoint no longer drags with Anchor after Anchor ID is changed after creation 

### ISSUE THREAD

**Issue by asfand987** [jsplumb/jsplumb#1017]
I'm building an editor and when I place a shape (also requires entering ID for that shape) onto the canvas, endpoints get created and attached to the shape. The ID of the shape is used for the endpoints to anchor onto.

   `//Function which anchors endpoints onto shapes 
    
    var _addEndpoints = function (sourceAnchors, targetAnchors, id) {
    for (var i = 0; i < sourceAnchors.length; i++) {
        var sourceUUID = sourceAnchors[i];
        epp = jsPlumbInstance.addEndpoint(id, sourceEndpoint, {
            anchor: sourceAnchors[i], uuid: sourceUUID
        });
        sourcepointList.push([id , epp]);
        epp = null;
    }
    for (var j = 0; j < targetAnchors.length; j++) {
        var targetUUID = targetAnchors[j];
        epp = jsPlumbInstance.addEndpoint(id, targetEndpoint, {
            anchor: targetAnchors[j], uuid: targetUUID
        });  
        endpointList.push([id, epp]);
        epp = null;
       } 
     };
    function drawElement(element, canvasId, id) {
        $(canvasId).append(element);
        _addEndpoints(properties[0].startpoints, properties[0].endpoints, id);
        jsPlumbInstance.draggable(jsPlumbInstance.getSelector(".jtk-node"), {
             grid: [20, 20]
        });         
     }`

This works perfectly fine as the endpoints work fine and drag with the shape, however one functionality for my editor I would like is being able to change the ID after clicking on the shape. When the ID is changed, the endpoints no longer drag with the shape. They do still drag on there own however. I have attempted to the following to update the ID in the endpoints by updating the anchor and element.

` //My solution attempt
  jsPlumbInstance.selectEndpoints().each(function(endpoint) {
          endpoint.setElement(anchor); 
          endpoint.setAnchor(x, y, newID); 
  });`

However I get the following error.

`jsPlumb function failed : TypeError: Cannot read property 'el' of undefined`

Looking into the properties of the endpoints there are alot of properties which still have the old ID value, and I have no Idea how to update all of these at the same time. Can anyone please help me out?

**Comment by sporritt** [comment]
The ID is the DOM element's id? There is a `setId` and a `setIdChanged` method to assist with this. But you'd be better off switching to 4.x; it doesnt use DOM element id at all internally.

**Comment by asfand987** [comment]
Thanks for the reply, what do you mean by 4.x?

**Comment by sporritt** [comment]
Check the readme.  It's a rewrite of jsPlumb in Typescript. 2.x will be discontinued in the next few months.

**Comment by asfand987** [comment]
![image](https://user-images.githubusercontent.com/48281686/107037522-1986be80-67b3-11eb-86b4-6701fc33e21b.png)

Sorry I should have specified I am trying to change all the fields `elementID` in the endpoint, not `id`. I can change this manually for some but not for others which can not be accessed as they are private as shown below.
![image](https://user-images.githubusercontent.com/48281686/107037850-987bf700-67b3-11eb-9720-079460995633.png)

**Comment by sporritt** [comment]
But do you mean you want to tell jsPlumb that the endpoint has moved to another element? Or just that the ID of the element on which it resides has changed.

**Comment by asfand987** [comment]
The latter, The ID of the element on which the Endpoint resides has changed and I want to update the endpoint element ID to take that into account.

**Comment by asfand987** [comment]
> But do you mean you want to tell jsPlumb that the endpoint has moved to another element? Or just that the ID of the element on which it resides has changed.

The latter, the ID of the element on which the Endpoint resides has changed and I want to update the Endpoint to take that into account.

**Comment by sporritt** [comment]
With 4.x you don't have to bother with that, is my point.  Because it uses a `jtk-id` attribute to track everything internally, not the `id` attribute.

**Comment by asfand987** [comment]
Is there not a way to do this in the current version? I'm on a deadline so probably do not really have time to change to 4.x?

**Comment by sporritt** [comment]
yes, there is, which i mentioned above - `setId` or `setIdChanged` (the difference being that `setId` changes the attribute for you as well as doing the internal changes required, and `setIdChanged` only does the internal changes)

**Comment by sporritt** [comment]
oh the methods are on the jsPlumb instance, not Endpoint.  The whole of jsPlumb needs to know about the ID change, not just the Endpoint.

**Comment by asfand987** [comment]
Ah I see, thank you very much for your help. Much appreciated.
