### ISSUE TITLE
Labels are overlapping with the nearby DOM elements

### ISSUE THREAD

**Issue by chetbis** [jsplumb/jsplumb#1018]
Hi, I am having an issue with the labels, if they get too long they overlap with nearby elements. Is there a way to ellipsize those lables if there's not sufficient space and show title on hover? 

![image](https://user-images.githubusercontent.com/28381719/107909214-c0224a80-6f7d-11eb-89c5-3baa5e7e355d.png)

**Comment by sporritt** [comment]
Probably can be done with CSS. Do you know `text-overflow:ellipsis` ?

You have a rule like this

```
.myLabel {
   max-width:80px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

and `myLabel` is mapped as the `cssClass` for the overlay:

```
jsplumb.connect({
  source:"foo",
  target:"bar",
  overlays:[
    [ "Label", { cssClass:"myLabel", label:"Hello" } ]
  ]
});
```
