### ISSUE TITLE
Memory leak in community edition 2.15.5

### ISSUE THREAD

**Issue by alhuber1502** [jsplumb/jsplumb#1021]
After some time of use, I get the following error in the console (Firefox):

```
out of memory                                   jsplumb.min.js:2:8001
Uncaught out of memory                                             12
```

The error brings down the entire website and requires relaunching its browser tab.  
Any advice about what might be the issue would be appreciated!

**Comment by sporritt** [comment]
This is not something that has been reported before - I don't have any leads on what might be causing this. The 2.x branch is now effectively in maintenance. You might want to consider switching to 4.x.
