### ISSUE TITLE
Element Dragging

### ISSUE THREAD

**Issue by MarkoHari3716** [jsplumb/jsplumb#1022]
Hello, 

thank you for your effort and the knowledge you share. I want dragging my container with elements that are inside it and rendered by jsPlumb. There is example what I want to do.

![jsPlumbDragging](https://user-images.githubusercontent.com/48455134/110921813-446ab200-831f-11eb-91cb-d429e5b6faea.gif)

This is example for jsPlumbToolkit version. There is link where I found this example.
LINK: https://demo.jsplumbtoolkit.com/flowchart-builder/ 

Is there something like that for community version?

**Comment by sporritt** [comment]
The Community edition does not support panning the view in this way.

**Comment by MarkoHari3716** [comment]
Thank you for your answer. Do you maybe know js library who support that?

**Comment by MarkoHari3716** [comment]
I found a library for dragging, D3.js.
