### ISSUE TITLE
[4.x-alpha] Posses no longer an option

### ISSUE THREAD

**Issue by shurth** [jsplumb/jsplumb#1023]
I'm sure you know this, but as I was attempting to upgrade to 4.x, I found that 'addToPosses' was no longer an option on the jsplumb instance. I didn't find this change in the docs - curious if it's being retired or simply not migrated yet.

**Comment by sporritt** [comment]
i called them "drag groups" in 4.x.  i know the docs need updating, i havent had time to get to them. but take a look through the `.d.ts` files.... `addToDragGroup` etc.

**Comment by sporritt** [comment]
```
export type DragGroupSpec = string | { id:string, active:boolean }

addToDragGroup(spec: DragGroupSpec, ...els: Array<Element>): void;
    removeFromDragGroup(...els: Array<Element>): void;
    setDragGroupState(state: boolean, ...els: Array<Element>): void;
```

**Comment by shurth** [comment]
Awesome! Good thing I stashed those changes. Posses _was_ a pretty fun name though. ;)

**Comment by sporritt** [comment]
Yes I always had a little chuckle when I rounded up a posse. I dont know why I ditched that name. Must have just gone soft.
