### ISSUE TITLE
MaxConnections not respected when dragging endpoint to source

### ISSUE THREAD

**Issue by TechnoX** [jsplumb/jsplumb#1024]
Hi. 

I've set maxConnections to 1 on all sources, but I can still drag an already existing endpoint from another source. So in total I can create 2, 3 or even more endpoints connected to the very same source. 

It's not firing the onMaxConnections event either. 

I can't recreate the behavior on targets, on targets I can't move already existing endpoints to the same target.

**Comment by sporritt** [comment]
is this in 2.x or 4.x?

**Comment by TechnoX** [comment]
2.15.5  (and previous versions as well).

**Comment by sporritt** [comment]
regarding this bit:

'I can't recreate the behavior on targets, on targets I can't move already existing endpoints to the same target.'

is that also something you're not expecting?

**Comment by TechnoX** [comment]
No, I would say that targets are behaving as expected. Sorry for not being clear.

**Comment by sporritt** [comment]
I'm afraid 2.x is now unsupported.  In 5.x I believe all of the max connections stuff is working as expected.
