### ISSUE TITLE
Cannot set property 'overlays' of undefined

### ISSUE THREAD

**Issue by yaya1286249672** [jsplumb/jsplumb#1027]

**Comment by sporritt** [comment]
There is a distinct lack of information in this issue report.

**Comment by sporritt** [comment]
@yaya1286249672 Do you think it is likely you will provide some information?

**Comment by yaya1286249672** [comment]
thank you ,It is already resolved .
不用了  谢谢 已经解决了  因为我在qiankun子项目引用的jsplumb  this的指向变掉了导致的 提到父项目里 然后引用就好了

**Comment by sporritt** [comment]
好的，谢谢你让我知道
