### ISSUE TITLE
setZoom has no effect！

### ISSUE THREAD

**Issue by hbpbpl** [jsplumb/jsplumb#1030]
![1007994648](https://user-images.githubusercontent.com/42559782/112408283-7eda4300-8d52-11eb-9c39-6a7d2f91de16.jpg)

setZoom return true, and getZoom return the correct value, but sometimes there is a deviation when connect by dragging.

- jsPlumb version: 2.15.4
- CSS of div container
`transform: translate(80px, 80px) scale(.75)`
- jsplumb instance
`jsplumbInstance.setZoom(.75)`

**Comment by sporritt** [comment]
if you can reproduce - in 5.x - in jsfiddle/codepen i can look at this. but it's unlikely to get any attention if it's using 2.x.
