### ISSUE TITLE
Scrollable list children cannot be connected to twice

### ISSUE THREAD

**Issue by saivishnutammineni** [jsplumb/jsplumb#1031]
This issue can be reproduced with the Scrollable List example of demos. Connect two or more items in source list to a single item in target list that is hidden due to scroll. All connections except the first are not proxied to parent list.

Even if we delete a connection to a scrollable item using `instance.deleteConnection` and add a new connection `instance.connect` the same issue happens. Is the reason behind the issue the below code? If a connection endpoint was already proxied... it won't be proxied again even with new connections?
https://github.com/jsplumb/jsplumb/blob/dc4054558a2451d1a57b05f09bc70c1209dca90c/src/lists.js#L152

Code to reproduce: In the lists demo replace the connection part with below code
```
for (var i = 0; i < connCount; i++) {
      instance.connect({source:selectedSources[i], target:selectedTargets[i]});
      instance.connect({source:selectedSources[i], target:selectedTargets[i]}); // second connection to trigger the issue
}
```

**Comment by sporritt** [comment]
are you able to reproduce this in 4.x?

**Comment by saivishnutammineni** [comment]
Hai thanks for the quick reply. I will try to reproduce with `4.x` version as soon as possible and let you know. As i am not sure if i will be allowed to use the 4.x version i tried a workaround which seems to be working fine for now. Might help someone.
This issue doesn't happen if the endpoint of connection is visible while connecting
1. save the current scroll of source / target list 
2. scroll the source / target into view
3. call the `scrollHandler ` on list element (avalable as `_jsPlumbScrollHandler` on the parent list element)
4. connect the source and target
5. resume the scroll of list based on saved value from 1 above
6. call the `scrollHandler ` again as in 3
7. done

**Comment by sporritt** [comment]
4.x turned into 5.x.  Were you able to reproduce in 5.x?

**Comment by saivishnutammineni** [comment]
Hi i am not working on the project using js plumb so couldn't check. Closing the issue.
