### ISSUE TITLE
Wrap Connectors with a div/span 

### ISSUE THREAD

**Issue by nicoloboschi** [jsplumb/jsplumb#1032]
I'm using https://github.com/niklasvh/html2canvas library for export a jsplumb diagram
The library does not provide support for SVG absolute positioned images, as the JSplumb connectors are, but wrapping them with a absolute span (or div) it works as expected 

I was peeking in jsplumb source code and I've seen that there is a param 'useDivWrapper' for SVG elements, but it is not used for connectors rendering, there is a way (hopefully not dirty) to pass this param when creating the connector?

Alternatevely, I was thinking to manually wrap the svg elements but I would like to avoid it
Any thoughts? 
(editing source file and forcing useDivWrapper=true, the connections seems work fine and it resolves my issue)

there is an issue containing these workaround https://github.com/niklasvh/html2canvas/issues/1179 but I think it would be better to have a clean solution

**Comment by sporritt** [comment]
I think a clean solution to this would be for html2canvas to support SVG elements that are positioned absolute.

**Comment by nicoloboschi** [comment]
yes of course, using 'useDivWrapper' parameter is not possible at all for connectors?

**Comment by sporritt** [comment]
no, that functionality is only for endpoints. i can't remember at this point why it exists, in fact.
