### ISSUE TITLE
can targets be created dynamically or do they have to exist in advance?

### ISSUE THREAD

**Issue by alhuber1502** [jsplumb/jsplumb#1034]
Really just asking for clarification if this is at all possible: 

my use case is that when I start a connection drag, I want to create the target dynamically when hovering over an element (doing so in advance is forbiddingly expensive due to the number of potential targets).  I make that element a target using the .makeTarget function.

However, the target only seems to get accepted, once I stop the drag that created it and start a new one.

Is there a way to make an element a target and have it connect to that target straight away? Thanks!

**Comment by sporritt** [comment]
Recent versions of the 4.x branch have a couple of new methods to deal with the issue of calling `makeTarget` and/or `makeSource` on many elements - `addSourceSelector` and `addTargetSelector`.  For instance:

```
instance.addSourceSelector(".myDragSource", {
  // options as for makeSource
});
```

and 

```
instance.addTargetSelector(".myTargetSelector", {
  // options as for makeTarget
});
```

Currently, the selectors specified in a call to these methods are used in a `querySelectorAll` call on the instance's container. This means if you wanted to target entire elements as targets, which is the most common, you just need to use a selector that identifies entire elements.

A problem with this is that since _any_ selector can be used, it is easy to pull in elements that are not actually being managed by the instance, so in dev right now I'm working to limit the scope of these selectors to be only inside of managed nodes. Internally, for example, this:

```
.myDragSource
```

is converted to

```
[jtk-managed] .myDragSource
```

(jsPlumb writes a `jtk-managed` attribute on all managed elements).

To instruct jsPlumb to make all managed elements drag targets you'd do this:


```
instance.addTargetSelector("*", {
  // options as for makeTarget
});
```

whose selector is converted to `[jtk-managed], [jtk-managed] *` internally.

It is also possible to do this:

```
instance.addSourceSelector("*", { ... });
```

but `addSourceSelector` automatically registers a drag filter for the given selector so that elements are not dragged when a connection drag starts, so this would result in the inability to drag elements. 

These changes should be released in the next couple of days.

**Comment by alhuber1502** [comment]
That's fabulous thank you! Should I be looking out for a specific release version number for these options (.addTargetSelector etc.) to become available?

**Comment by sporritt** [comment]
These methods are already in 4.x, which is on npm as @jsplumb/browser-ui. But the scoping changes are not yet released.

I'd be interested to hear any feedback you have...

**Comment by alhuber1502** [comment]
Sorry, I'm a bit at a loss upgrading to 4.0.0. I've downloaded the latest RC which results in

`jsPlumb.ready is not a function`

I've had a look at the demos, but they reference files that don't exist, such as:

`dist/dom/js/jsplumb.dom.umd.js`

Could you point me at some up-to-date documentation or a working demo with the latest RC, so that I can at least get going. Sorry if I'm missing something obvious.

**Comment by sporritt** [comment]
How do you mean you've 'downloaded' the RC?  From npm, do you mean, or from Github?  If you've checked out the source you'd need to run the `package` npm target:

```
npm i
npm run package
```

**Comment by alhuber1502** [comment]
I've downloaded https://github.com/jsplumb/jsplumb/archive/refs/tags/4.0.0-RC84.tar.gz from Github and am doing this on my Website:
```
<script src="/js/jsplumb-4.0.0-RC84/dist/core/js/jsplumb.core.umd.js"></script>
<script src="/js/jsplumb-4.0.0-RC84/dist/browser-ui/js/jsplumb.browser-ui.umd.js"></script>
```

**Comment by sporritt** [comment]
This is the source for the flowchart demo using 4.x:

https://github.com/jsplumb-demonstrations/flowchart/blob/main/js/demo.js

There are a few syntax changes from 2.x, and `jsPlumb` is now `jsPlumbBrowserUI`....

**Comment by alhuber1502** [comment]
Ah, thanks, that is useful and should get me started. Thanks very much!

**Comment by alhuber1502** [comment]
I managed to set up the instance sucessfully, but I'm running into an error when setting an endpoint:

> Uncaught TypeError: Cannot read property 'cssClass' of undefined
>     at merge (jsplumb.core.umd.js:540)
>     at Endpoint.prepareEndpoint (jsplumb.core.umd.js:5599)
>     at Endpoint.setEndpoint (jsplumb.core.umd.js:5608)
>     at new Endpoint (jsplumb.core.umd.js:5359)
>     at BrowserJsPlumbInstance.newEndpoint (jsplumb.core.umd.js:8476)
>     at BrowserJsPlumbInstance.addEndpoint (jsplumb.core.umd.js:8669)
>     at HTMLAnchorElement.<anonymous> (text.js:382)
>     at HTMLBodyElement.dispatch (jquery-3.4.1.min.js:2)
>     at HTMLBodyElement.v.handle (jquery-3.4.1.min.js:2)

with
```
jsPlumb_instance.addEndpoint( $( jq(ids[0]) )[0], { 
        isSource:true,
        deleteEndpointsOnDetach:false,
        detachable:false,
        connectorOverlays:[ 
            [ "PlainArrow", { width:8, length:8, location:1, id:"arrow" } ],
            [ "Custom", {
                create: function(component) {
                    return $(`<div>
                    <input id="popover-rels-comment" placeholder="Choose a relation..." contenteditable="true" style="border:1px dashed #999;width:150px; height:20px;" class='jtk-overlay'
                        data-id="`+obj_id+`" data-ids="`+ids+`" data-sel="`+sel+`" data-col="`+col+`" list="relations"/><a 
                        href="#" class="check popover-rel-check"><i class="fas fa-check jtk-overlay"/></a><a 
                        href="#" class="cancel popover-rel-dismiss" data-ep="`+endpoint+`"><i class="fas fa-times jtk-overlay"/></a><!--<a 
                        href="#" class="trash popover-rel-trash"><i class="fas fa-trash-alt jtk-overlay"/></a>-->
                        <datalist id="relations">
                            <option value="is related contemporaneously to">
                            <!-- ... -->
                        </datalist></div>`);  
                },
                location:0.5,
                id:"customOverlay"
           }]
        ]
    });
```
In the README only `connector-pointer-events` and `labelStyle` are mentioned that should be replaced with cssClass, but it doesn't look like I'm using those. 

Any help gratefully received.

**Comment by sporritt** [comment]
it's the connector and endpoint declarstions - their syntax has changed. instead of:

```
connector:[ "Bezier", { curviness: 30 } ]
```

you need:

```
connector: { type:"Bezier", options:{ curviness: 30 } }
```

...and a similar change to `endpoint`.

**Comment by sporritt** [comment]
fyi, i didn't end up making the scope changes i was talking about. I realised the methods work just fine how they are, so there are no changes coming up for them.  I'm going to close this as I think it's answered but feel free to continue the discussion if you need further help.
