### ISSUE TITLE
Prevent connection reusing by dragging from source/target endpoint

### ISSUE THREAD

**Issue by nicoloboschi** [jsplumb/jsplumb#1035]
Is there any way to avoid the user to move an existing connection (by dragging from source or target endpoint)? 
My attempts were:
1) Listen to 'mousedown' event on endpoint -> no way to prevent dragging
2) Create endpoints using dragOptions: {canDrag: () => false} -> not working ('start' hook is called btw)
3) Override jsPlumb#isDragSupported in order to return false in case of dragging an anchor which is already connected -> not found a way to associate the input DOM element with them endpoint

Any thoughts?

I'm using makeTarget (for input endpoint) + addEndpoint (for output) 
```
this.instance.makeTarget(domNode, { 
   uuid,
   uniqueEndpoint: true,
   allowLoopback: false,
   dragOptions: {
      start: e => {
        console.log("start dragging", e);
        },
        canDrag: e => {
           console.log("can?", e); // not called
            return false;
          }
          },
         createEndpoint: true,
         deleteEndpointsOnDetach: false,
         anchor: ["Top", "Left", "Right"],
         ...                    
         });
}
```

```
this.instance.addEndpoint(domNode, {
   endpoint: "Dot",
   maxConnections: 1,
   allowLoopback: false,
   uuid,
   isSource: true,
  ....
                        }
```

**Comment by sporritt** [comment]
Have you tried

```
{
   ...
  connectionsDetachable:false
   ...
}
```

in the `addEndpoint` parameters?

**Comment by nicoloboschi** [comment]
thank you @sporritt, I misunderstood that option, it's so easy
