### ISSUE TITLE
jsPlumb 4.x and Angular example

### ISSUE THREAD

**Issue by davidcunningham** [jsplumb/jsplumb#1039]
Does anyone have an example using the new jsPlumb 4.x / @jsplumb/browser-ui package and Angular? All the examples that I've been able to find reference the older versions of jsPlumb.

Thank you.

**Comment by mike-niemand** [comment]
Did you figure this out? Having similar problems.

**Comment by davidcunningham** [comment]
Unfortunately no.

**Comment by mike-niemand** [comment]
Cheers. Couldn't either so had to ditch it.
