### ISSUE TITLE
Group endpoint

### ISSUE THREAD

**Issue by Arthemis97** [jsplumb/jsplumb#1042]
Hello everyone.

How to add group with endpoint?

jsPlumb.addGroup({
    el: group_el,
    id: `groupId`,
    anchor: "Left", --> THIS NOT WORKING
    endpoint: ENDPOINT, --> THIS NOT WORKING
  });

**Comment by sporritt** [comment]
You dont add endpoints to groups, you add them to the group element, in this case `group_el`

**Comment by Arthemis97** [comment]
Thank you for your quick response.
I want to add endpoint to Group Element like this.
![Untitled](https://user-images.githubusercontent.com/26436700/120894247-1bba3600-c64a-11eb-8ac0-ecad6438cc9c.png)

**Comment by Arthemis97** [comment]
Oh, I was wrong, i just use addEndpoint function. Problem solved, Thanks
