### ISSUE TITLE
Handle element drag and drop into Group.

### ISSUE THREAD

**Issue by Arthemis97** [jsplumb/jsplumb#1043]
Hi,
How to handle element drag and drop into Group.
I want to restrict elements to join group.

etc..
<div id="not_allowed_to_join_group"> 

<div id="allowed_to_join_group">

**Comment by sporritt** [comment]
there might be something on here to help

https://docs.jsplumbtoolkit.com/community/current/articles/groups-community.html

...although it may not be granular enough for what you want to do. at what point do you want to make the decision about which elements to restrict joining a given group? when the user starts dragging?  when they drop?

**Comment by Arthemis97** [comment]
I want prevent in user drop element in group.

**Comment by sporritt** [comment]
i see. did you read the docs i linked then?

**Comment by Arthemis97** [comment]
I found this event "group:addMember". But it's only fired when an element is added to a Group.

**Comment by sporritt** [comment]
on the page i linked it talks about the options for the `addGroup` method, one of which is:

```
- droppable Set to true by default. If false, the Group element will not allow elements to be dropped onto it in order to add them to the Group.
```
