### ISSUE TITLE
Multiple endpoint and multiple connections drawn wrong

### ISSUE THREAD

**Issue by ggpid** [jsplumb/jsplumb#1044]
Endpoint 'AB' should be connected with two sources but endpoint 'A' does.
It seems that the actual endpoint instances are connected correctly but drawing wrong.

`jsPlumbInstance.connect({source: jsPlumbInstance.getEndpoint('AB'), target: srcA});
  jsPlumbInstance.connect({source: jsPlumbInstance.getEndpoint('AB'), target: srcB});
  jsPlumbInstance.connect({source: jsPlumbInstance.getEndpoint('A'), target: srcB});`

![image](https://user-images.githubusercontent.com/6137599/122583627-6e591080-d094-11eb-8e06-3c95d31d6149.png)

[https://jsfiddle.net/ggpid/qfz8b5s9/186/](url)

**Comment by sporritt** [comment]
if you can reproduce this in 5.x please feel free to reopen.
