### ISSUE TITLE
document.createEvent has been marked as deprecated and may cause error

### ISSUE THREAD

**Issue by zcqno1** [jsplumb/jsplumb#1046]
https://github.com/jsplumb/jsplumb/blob/783c62141319dc40505e0e7e2a3074fea11e676a/dist/js/jsplumb.js#L1392

`document.createEvent` has been marked as deprecated, see as 
https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent

Some library(like [qiankun](https://github.com/umijs/qiankun)) would proxy the window, which would cause the `MouseEvent.initMouseEvent` broken down, because `initMouseEvent` method would check its parameter 4 to match the type 'Window'.

![image](https://user-images.githubusercontent.com/11766057/124901648-c4c2ca80-e014-11eb-9080-34eb67b1c854.png)

**Comment by sporritt** [comment]
that page does not say that document.createEvent has been deprecated, it says several methods used with it have been deprecated.

but i think that's not the error you are reporting anyway. what error are you reporting?

**Comment by zcqno1** [comment]
Yes you're right. 

The main error was not caused straightly by `document.createEvent` but the `initMouseEvent` on 'MouseEvent' which must be call after using the `document.createEvent` to create an event.

The `initMouseEvent` method strictly requests a 'Window' type `window` as the 4th parameter. In our application, `window` is proxied, not matching the `Window` type. There threw the error as shown above.

**It had better to trying to use the `MouseEvent()` constructor or the `Event()` to create an event, which is now recommended.**

I just hack it by hijacking the `initMouseEvent` method. The core is clearing its 4th parameter, making it to use the missing value(which should be the original window ?).

```js
window.MouseEvent.prototype.rawInitMouseEvent = window.MouseEvent.prototype.initMouseEvent
window.proxy.MouseEvent.prototype.initMouseEvent = function (...args) {
  args.splice(3, 1, undefined)
  this.rawInitMouseEvent(...args)
}
```

**Comment by sporritt** [comment]
ok thanks. i'll look at switching to constructors in the 5.x branch.

**Comment by sporritt** [comment]
i did look at this. i could not find a compelling reason to change the jsplumb code.

**Comment by zcqno1** [comment]
Jsplumb may go wrong in sandbox system like window proxy. or in the future when `initMouseEvent` not support any more. It could avoid it by replacing the deprecated `initMouseEvent` with event constructor.

**Comment by 13407864574** [comment]
> Jsplumb在像窗口代理这样的沙箱系统中可能会出错。或者将来`initMouseEvent`不再支持时。它可以通过将已弃用的`initMouseEvent`事件构造函数替换为事件构造函数来避免这种情况。



> https://github.com/jsplumb/jsplumb/blob/783c62141319dc40505e0e7e2a3074fea11e676a/dist/js/jsplumb.js#L1392
> 
> `document.createEvent` has been marked as deprecated, see as https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent
> 
> Some library(like [qiankun](https://github.com/umijs/qiankun)) would proxy the window, which would cause the `MouseEvent.initMouseEvent` broken down, because `initMouseEvent` method would check its parameter 4 to match the type 'Window'.
> 
> ![image](https://user-images.githubusercontent.com/11766057/124901648-c4c2ca80-e014-11eb-9080-34eb67b1c854.png)

Hello, do you have a solution to this problem

**Comment by 13407864574** [comment]
> https://github.com/jsplumb/jsplumb/blob/783c62141319dc40505e0e7e2a3074fea11e676a/dist/js/jsplumb.js#L1392
> 
> `document.createEvent` has been marked as deprecated, see as https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent
> 
> Some library(like [qiankun](https://github.com/umijs/qiankun)) would proxy the window, which would cause the `MouseEvent.initMouseEvent` broken down, because `initMouseEvent` method would check its parameter 4 to match the type 'Window'.
> 
> ![image](https://user-images.githubusercontent.com/11766057/124901648-c4c2ca80-e014-11eb-9080-34eb67b1c854.png)
Hello, have you solved this problem
