### ISSUE TITLE
Dom element removed when an inner element of a nested group is dropped into white space

### ISSUE THREAD

**Issue by frandsr** [jsplumb/jsplumb#1048]
I'm trying to implement a flowchart with the group functionality. One of my problems is that i can't figured how to avoid an element to be removed from the DOM once i have dragged it from a nested group (a group inside another group) and dropped it in the white space defined as the container. When i do this, the element disappeared and its endpoints remain somewhere.I have try setting the "orphan" property as true but it doesn't seem to work.

**Comment by sporritt** [comment]
"orphan" should be what you need for this. in 5.x a bunch of extra unit tests were added around groups. i'd suggest updating to 5.x.
