### ISSUE TITLE
Target a group nested inside another group to make a connection

### ISSUE THREAD

**Issue by frandsr** [jsplumb/jsplumb#1049]
I'm trying to implement a flowchart with the group functionality. One of my problems is that i can't figured how to target a group element inside another group set as a target connection with the `makeTarget` method. When trying to connect an element to a group element inside another group, both set as connection target with `makeTarget` method, the connection always end up being with the parent group instead of the child group. The only way i managed to connect to the inner group was by adding a target endpoint to the element. I would like tho to avoid this while remain the whole element as a target for a connection. Is there any way to do it?

**Comment by sporritt** [comment]
2.x doesnt support nested groups. Although it's not documented yet, 5.x would be a better version to use for this.

**Comment by sporritt** [comment]
I'm gonna close this. 5.x is in beta on npm now and supports nested groups.
