### ISSUE TITLE
What is the right way to animate?

### ISSUE THREAD

**Issue by nsisodiya** [jsplumb/jsplumb#1051]
https://user-images.githubusercontent.com/333455/130067410-e1284d72-12be-4a5d-b828-ad735f14e0f7.mp4

How to make this animation smooth? I am using latest jsplumb.

This is what I am doing right now.

* Step1 - Modify X/Y coordinate of Box (component). Added CSS property `transitionProperty: 'left, top',
          transitionDuration: '1s',` to animate for 1 second duration.
* When Transition is ended, Using following code to ReDraw the connections.

```js
window.setTimeout(() => {
      this.removePorts(); // This calls - this.instance.deleteEndpoint(UUID); to delete the port.
      this.createPorts(); // This calls - this.instance.addEndpoint(document.getElementById(domId), obj1, ob2);
      this.removeEdges(); // This calls - this.instance.deleteConnection(ConnectionObj); 
      this.createEdges(); // This calls - this.instance.connect(Obj)
    }, 1000);
```

Let me know, what is the right way to do things.

**Comment by sporritt** [comment]
probably

`this.instance.revalidate(document.getElementById(domId))`

will do what you want

**Comment by nsisodiya** [comment]
Thanks, I finally use this code.
```js
componentDidUpdate() {
    let start;
    var self = this;
    function step(timestamp) {
      if (start === undefined) {
        start = timestamp;
      }
      const elapsed = timestamp - start;
      if (elapsed < 1000) {
        self.instance.repaintEverything();
        window.requestAnimationFrame(step);
      }
    }
    window.requestAnimationFrame(step);
  }
```
