### ISSUE TITLE
Where is document for community

### ISSUE THREAD

**Issue by rookie-hhm** [jsplumb/jsplumb#1052]
Hi, http://jsplumb.github.io/jsplumb and https://docs.jsplumbtoolkit.com/community/current/index.html both 404, where is document for community ?

**Comment by sporritt** [comment]
https://docs.jsplumbtoolkit.com/community/

**Comment by sporritt** [comment]
those are the 5.x docs, which is now on master.

the 2.x docs are here: [https://docs.jsplumbtoolkit.com/community-2.x/current/](https://docs.jsplumbtoolkit.com/community-2.x/current/)

**Comment by rookie-hhm** [comment]
@sporritt Thanks for your quick response!
