### ISSUE TITLE
is the documentation to community version still available?

### ISSUE THREAD

**Issue by wbqtac** [jsplumb/jsplumb#1053]
It looks that the link is not working: https://docs.jsplumbtoolkit.com/community/current/index.html 
Thank you for your attention.

**Comment by sporritt** [comment]
https://docs.jsplumbtoolkit.com/community/

**Comment by sporritt** [comment]
those are the 5.x docs, which is now on master.

the 2.x docs are here: [https://docs.jsplumbtoolkit.com/community-2.x/current/](https://docs.jsplumbtoolkit.com/community-2.x/current/)

**Comment by wbqtac** [comment]
Thank you. Wonderful!
