### ISSUE TITLE
Per node/element drag stop callback.

### ISSUE THREAD

**Issue by gibonu** [jsplumb/jsplumb#1054]
Migrated from 2.15 to 5.0.0-RC21. In 2.15 i could enable dragging per element and define for them callback function using draggable method.
Is this possible with newer versions? The only thing i found was when creating new instance, but that does not solve my case where I need to access draggable component's data and keep it next to its code.
```
this.jsPlumbInstance.draggable(uuid, {
        containment: 'container',
        stop: (event) => {},
});
```

**Comment by sporritt** [comment]
The `draggable` method no longer exists in 5.x. Everything that is managed is draggable by default. You can bind to `drag:stop` on a jsPlumb instance; the event is fired whenever an element has been dragged. The callback is given a `DragStopPayload`.

```
export type DraggedElement = {el:jsPlumbDOMElement, id:string, pos:PointXY, originalPos:PointXY, originalGroup:UIGroup, redrawResult:RedrawResult, reverted:boolean, dropGroup:UIGroup}

/**
 * Payload for `drag:stop` event. In addition to the base payload, contains a redraw result object, listing all the connections and endpoints that were affected by the drag.
 */
export interface DragStopPayload {
    elements:Array<DraggedElement>
    e:Event
    el:Element
    payload?:Record<string, any>
}
```

**Comment by gibonu** [comment]
This does not solve my case unfortunately.
I use angular application in which i dynamically create components that act as nodes for JSPlumb. These elements might be one of 5 types (each type is separate angular component) and depending on type I need to fire different actions after dragging (or disable dragging at all). Previously I could define draggable for given item (using its JSPlumb UUID) to have clean drag stop handler for each type, and keep it in components class.
With current approach the only way is to have one big event handler that checks type. On top of that jsPlumb returns just a DOM element which I would need to resolve back to component's instance to get access to other data stored in the component itself.

**Comment by sporritt** [comment]
You could bind a single drag listener to act as a delegate and then register each component on it after init, by id, passing in the method you want to execute on drag stop.

**Comment by sporritt** [comment]
There isn't a method to register a listener per component, it's something you'd have to write for yourself.  This is what the Surface widget does in the Toolkit - it binds to the drag end event:

```
this.jsplumb.bind(EVENT_DRAG_STOP, (params:DragStopPayload) => {


}
```

and then inspects the payload, the interface definition for which is earlier in this thread. You could maintain a map of handlers:

```

const  handlers:Map<string, Function> = new Map()


...

class MyNg implements ngAfterViewInit {

  constructor(private el:ElementRef) { }
  
   afterDrag() { ... }

  ngAfterViewInit() {
     handlers.set(this.el.nativeElement.childNodes[0].getAttribute("data-jtk-managed"), this.afterDrag.bind(this))
  }
```

... or something.  That's the general idea. The key used on the map in this snippet will match the `id` of some `DraggedElement`.

**Comment by gibonu** [comment]
Oh i see. Thanks. This is what i implemented more or less. What I did is I registered onStop handler while creating newInstance in which, since I already know the id of dragged element I look through a list of node instances that I store in some service and from there i call component's method. 
I like your approach little more so I will take time to implement it.

Thank you for your time and explanation. Really helpful. Just out of curiosity - was there any particular reason why you/the team decided to drop ability to define draggable at node level and instead decided that all components are draggable by default?
In my case i have a flowchart with start and stop nodes which are non-draggable (luckily here i could just call setDraggable to false on component's afterInit). But then I have decision blocks and action blocks that do have actually some logic to be executed on drag and each type has different actions associated. Anyway thanks again and feel free to close the issue. This answer is sufficient to resolve my problem.

This decision seem to be weird given that i could still register click events per node:
```
this.jsPlumbInstance.on(this.element.nativeElement, EVENT_ELEMENT_CLICK, data => {
      // some code
});
```

**Comment by sporritt** [comment]
It's essentially a performance consideration. Attaching a drag handler to each element uses up a bunch of memory and takes a bit of time to do.  Hanging a single delegated event handler off the container is better from that point of view, and gets better and better as the number of elements goes up.

You can register a click handler on an element, sure, but in that case all that's happening is an event listener is added, via the browser's native api. It's not going to involve a bunch of memory usage like a single drag handler.  

`EVENT_ELEMENT_CLICK` is not an event to bind to on a DOM element in the way you have it there. It's something you use with `bind` on an instance of jsPlumb:

```javascript
this.jsPlumbInstance.bind(EVENT_ELEMENT_CLICK, data => {
      // some code
});
```

jsPlumb has a delegated click handler that listens for clicks on any "managed" elements. The difference between `on` and `bind` is that `on` is a direct conduit to `addEventListener` on some DOM element, but `bind` is an instance-wide handler, where events are fired as the result of some internal computation or whatever.

If you want to disable dragging on an element you can write an attribute on it when you write it to the DOM:

```
<div data-jtk-not-draggable="true">
  <h1>I am a non-draggable node</h1>
</div>
```

**Comment by gibonu** [comment]
> `EVENT_ELEMENT_CLICK` is not an event to bind to on a DOM element in the way you have it there. It's something you use with `bind` on an instance of jsPlumb:

You are right. I was writing out of memory, what i used was ```EVENT_CLICK``` which is just a const for 'click' IIRC.

**Comment by sporritt** [comment]
yep, `EVENT_CLICK` is `"click"`.
