### ISSUE TITLE
instance.connect() is not available

### ISSUE THREAD

**Issue by mderazon** [jsplumb/jsplumb#1055]
I am on version `5.0.0-RC23`
Looking at the latest documentation site:
https://docs.jsplumbtoolkit.com/community/lib/connectors#specifying-a-connector-by-name

```js
import { newInstance } from '@jsplumb/browser-ui';

const instance = newInstance()
// ...
instance.connect(/* ... */) // <---- Does not exist
```

Looks like the documentation is still in motion, including the api documentation section ?

**Comment by sporritt** [comment]
hmm, connect definitely exists:

https://github.com/jsplumb/jsplumb/blob/master/ts/core/core.ts#L1304

and the .d.ts files are generated from compiling the typescript, so this does seem odd.

**Comment by mderazon** [comment]
To give some more info, I have imported the following packages:
```json
    "@jsplumb/browser-ui": "5.0.0-RC23",
    "@jsplumb/core": "5.0.0-RC23",
    "@jsplumb/common": "^5.0.0-RC23",
    "@jsplumb/util": "^5.0.0-RC23",
```

You can see the import error here:
https://stackblitz.com/edit/angular-jsplumb-test-asbv39?file=app%2Fnode.service.ts

**Comment by sporritt** [comment]
...yeah so looking at this on my computer i see a console error - `el is null`:

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/262720/131919641-30b85315-25fb-4a2e-861f-56a8aab746f9.png">

**Comment by mderazon** [comment]
Thanks, you are correct. However what's weird is that yesterday the problem I was getting was an error that it couldn't find `@jsplumb/core` and also `instance.connect()` but now for some reason the compiler autocompletes correctly. Not sure what have changed

**Comment by sporritt** [comment]
who knows

that's the magical world of computers for you

**Comment by sporritt** [comment]
I'm gonna close this then.
