### ISSUE TITLE
getInstance is not found in 5.0.0-RC23

### ISSUE THREAD

**Issue by saxenarajat** [jsplumb/jsplumb#1056]
First of all thank you for this wonderful library. I am trying out `5.0.0-RC23` and discovered a couple of issues. 

First, the [documentation](https://docs.jsplumbtoolkit.com/community/#where-does-jsplumb-add-elements) says there is a `getInstance` method, but I could only manage to find `newInstance` by looking at the source code.  

Second, where can I find the the documentation for the `5.x` branch? I had a look at the `docs` folder on the `5.0.0-RC23` tag but couldn't manage to find a small workable solution for setting `5.x` up. I also had a look at the [jsPlumb demonstration](https://github.com/jsplumb-demonstrations) repo but couldn't find a `5.x` example.

Third, In `5.x` the `newInstance` method does not accept a property called `Container` but it was there in `4.x` as I was able to figure that out by exploring the examples in the jsPlumb demo repo which were using `4.x` version of jsPlumb. So how does one set up a container in `5.x`?

Thanks.

**Comment by sporritt** [comment]
Documentation for 5.x is at

https://docs.jsplumbtoolkit.com/community

**Comment by sporritt** [comment]
You pass in the container as the first arg to the render call.

```
render(container, { opts })
```

i'm on my phone right now so i cant check the demos, but i thought in fact the demos in the org you linked were setup for 5.x (despite saying 4.x). I need to go through and tidy all that up now.

**Comment by sporritt** [comment]
demonstrations are now all configured to use 5.x.
