### ISSUE TITLE
EVENT_ENDPOINT_DBL_CLICK not work

### ISSUE THREAD

**Issue by Coande** [jsplumb/jsplumb#1062]
EVENT_ENDPOINT_DBL_CLICK not work

doc: https://docs.jsplumbtoolkit.com/community/lib/events
version: 5.0.0-RC31

**Comment by sporritt** [comment]
Please provide a codepen demonstrating the issue.

**Comment by Coande** [comment]
> Please provide a codepen demonstrating the issue.

Has any codepen template?  I can't import the newest version of jsplumb on codepen.

**Comment by sporritt** [comment]
um, no. can you tell me, are you also binding EVENT_ENDPOINT_CLICK?

**Comment by Coande** [comment]
> um, no. can you tell me, are you also binding EVENT_ENDPOINT_CLICK?

Not binding EVENT_ENDPOINT_CLICK.

Only binding two event :
```
  // work
  instance.bind(jsPlumbBrowserUI.EVENT_CONNECTION_DBL_CLICK, (param) => {
    console.log(param);
  });
  
  // not work
  instance.bind(jsPlumbBrowserUI.EVENT_ENDPOINT_DBL_CLICK, (param) => {
    console.log(param);
  });
```

**Comment by sporritt** [comment]
I'd really have to see this somewhere in a test page - there's a unit test for this which works.

**Comment by Coande** [comment]
> I'd really have to see this somewhere in a test page - there's a unit test for this which works.

codepen: 
https://codepen.io/Coande/pen/WNOaVjW?editors=1010

**Comment by sporritt** [comment]
thanks. it's a z-index issue. the connector is on top of the endpoint.  if i change the endpoint's z-index:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/262720/135232646-c3652a48-7d00-4557-86a3-5661fba14dff.png">

the dblclick event fires

<img width="664" alt="image" src="https://user-images.githubusercontent.com/262720/135232700-4e518ef9-8431-48a6-9fa8-914094239106.png">
