### ISSUE TITLE
Is there a 5.x.x equivalent to 2.x.x's `beforeStart` handler on `draggable`?

### ISSUE THREAD

**Issue by liamdanger** [jsplumb/jsplumb#1067]
Howdy! I'm very excited to be migrating from 2.x.x to 5.x.x; I can already see considerable performance improvements, and the types are of course very welcome.

In the past, we used the `beforeStart` handler on the `draggable` method as a makeshift `mousedown` handler. Per [this message](https://github.com/jsplumb/jsplumb/issues/1054#issuecomment-905382497), we're now using the `dragOptions` property on `newInstance` to specify our handlers. It doesn't look like the `DragOptions` interface has a `beforeStart` equivalent; Is there a different way to listen for `mousedown` events on managed elements?

**Comment by sporritt** [comment]
Although the interface doesn't show it, I think that if you passed in an `onBeforeStart` method as shown in this interface:

https://github.com/jsplumb/jsplumb/blob/master/ts/browser-ui/drag-manager.ts#L44

as part of these drag options:

https://github.com/jsplumb/jsplumb/blob/9ccc3f172d625c05e8344b69303c1a487c5d76d7/dist/browser-ui/types/browser-jsplumb-instance.d.ts#L18

then you'd get the same functionality as before.  you'll have to do some casting to `any` to try this out of course.  If it works we can update `DragOptions` and put out a new release.

**Comment by sporritt** [comment]
..actually after looking further into the code i think probably this won't work.  i'll get it to work and do a new release.

**Comment by liamdanger** [comment]
> ..actually after looking further into the code i think probably this won't work. i'll get it to work and do a new release.

Thanks for being so responsive! I'll keep an eye out for the next release.

**Comment by sporritt** [comment]
^^^ I didn't mean to close this by referencing the issue in a commit. I think maybe the Microsoft overlords have overstepped the bounds of their authority here.

anyway - in 5.0.7, which is now published, you can supply `beforeDrag` in the `DragOptions`.

**Comment by sporritt** [comment]
(https://github.blog/2013-01-22-closing-issues-via-commit-messages/)

"This is super useful "

disagree
