### ISSUE TITLE
Unable to add Nodes or shapes in Jsplumb community edition

### ISSUE THREAD

**Issue by Aravinda93** [jsplumb/jsplumb#1068]
I am using the `@jsplumb/browser-ui` to create some `Nodes` within my `Nuxtjs/Vuejs ` application like as mentioned in their [documentation][1]. But I would like to create the Nodes at run-time. I am unable to do it.

I would like to create the `nodes/rectangle` shapes whenever the user clicks on the `Add Event` button. So rather than creating the `Nodes` static way I would like to create it dynamically/run time based on the button click. I am not understanding how to do it using `jsPlumb` [documentation][1] how to do it as they don't have a specific code sample to achieve the same.

Following is the code I have:
```
<template>
  <div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <button class="btn btn-primary btn-sm" @click="addConnector()">
            Add Connector
          </button>&nbsp;
          <button class="btn btn-primary btn-sm" @click="addNode()">
            Add Event
          </button>&nbsp;
          <button class="btn btn-success btn-sm" @click="submitEvents()">
            Submit
          </button>&nbsp;
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div id="diagram" ref="diagram" style="position: relative; width:100%; height:100%;" />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
let jsPlumb = null

export default {
  data () {
    return {
      nodeCounter: 0,
      nodeArray: [],
      connectorCounter: 0,
      connectorArray: [],
      allEventsInfoArray: []
    }
  },
  async mounted () {
    if (process.browser) {
      const jsPlumbBrowserUI = await import('@jsplumb/browser-ui')

      jsPlumb = jsPlumbBrowserUI.newInstance({
        dragOptions: {
          cursor: 'pointer',
          zIndex: 2000
        },
        container: this.$refs.diagram
      })

      console.log(jsPlumb)
    }
  },
  methods: {
    // On click of Add Node button create the draggable node into the jsPlumb canvas
    addNode () {
      // const container = "<button class='btn btn-info' id='container_" + this.nodeCounter + "'></button>"
      this.nodeCounter++
    },
    // On click of Add Connector button create the draggable node into the jsPlumb canvas
    addConnector () {
      console.log('Add Connector : ')

      jsPlumb.connect({
        anchor: 'AutoDefault',
        endpoints: ['Dot', 'Blank'],
        overlays: [
          { type: 'Arrow', options: { location: 1 } },
          {
            type: 'Label',
            options: { label: 'foo', location: 0.25, id: 'myLabel' }
          }
        ]
      })
    }
  }
}
</script>

<style scoped>
</style>

```

  [1]: https://jsplumbtoolkit.com/community/demonstration/flowchart

**Comment by sporritt** [comment]
The community edition has no provision for rendering nodes for you. You have to do that yourself, however you wish.  

The only thing you need to ensure is that the instance of jsPlumb is "managing" the elements you've created. If you call `addEndpoint` or `connect` with some DOM element then jsPlumb will add that element to its managed list. If you create an element and you want to tell jsPlumb about it yourself (if for instance you want the user to be able to drag it around before it has any endpoints or is connected to anything else) then you need to call `manage` yourself

https://docs.jsplumbtoolkit.com/community/#manually-registering-elements

**Comment by Aravinda93** [comment]
@sporritt Thanks a lot for your response and suggestion. I am still a bit confused about how to achieve this. All I want to do is create `Nodes` dynamically at runtime based on user selection and connect them together using the `Connectors` created by the users. I am not understanding how to do it. Can you please guide me with some samples to which I can refer or some documentation? I could not find any examples on the documentation page

Following is something I would like to achieve:
![CPT2111081318-1890x906](https://user-images.githubusercontent.com/29374160/140903072-486ef8c6-9b72-4535-a582-f37d06c33751.gif)

**Comment by sporritt** [comment]
The thing is, creating nodes is not something the Community edition of jsPlumb does. If you're using Nuxt/Vue then this is a question for that community. Once you have a DOM node, though, then yes you need to involve jsPlumb, by calling `manage(...)` wirh that element as argument.

**Comment by Aravinda93** [comment]
@sporritt Thanks a lot for your response. If I use plain `JavaScript/jQuery` then will it be possible to do so? Because I am willing to change my `Vutjs` to `jQuery` so I can implement this functionality. All I want to do is create `Node/Blocks` dynamically and connect them using `Connectors` based on user preference.

**Comment by sporritt** [comment]
per the comment here:

https://stackoverflow.com/questions/69896615/how-to-create-nodes-using-jsplumb-community-edition/70006467#70006467

i'm closing this
