### ISSUE TITLE
Unable to get the right connection popup message when I am connecting all the 5 nodes rightly to each other.

### ISSUE THREAD

**Issue by piyushraw** [jsplumb/jsplumb#1069]
I am unable to get the right connection message when I am connecting the nodes to each other.
for example::  LF node to LF circuit node and so on.....

Html file::

`<!DOCTYPE html>
 
 <html>

    <head>
        <title>
                 VIRTUAL_LABS
        </title>

        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

        <link rel="stylesheet" href='https://cdn.jsdelivr.net/npm/sweetalert2@7.12.15/dist/sweetalert2.min.css'></link>  

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"></link>

        <meta http-equiv="content-type" content="text/html;charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"/>
       
      

        <link rel="stylesheet" type="text/css" href="style.css">

  <script src="jsplumb-2.13.1/dist/js/jsplumb.min.js"></script>

    <meta charset="utf-8">

      <meta name="viewport" content="width=device-width, initial-scale=1">

 <script src="https://cdn.plot.ly/plotly-latest.min.js"></script> 

<meta http-equiv="content-type" content="text/html; charset=utf-8"/>

<script src="plotly.min.js"></script>

<script src=  "https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.33.1/plotly.min.js"></script>
  
    </head>

    <body>

           <div class="header">

  <img src="photos\Indian_Institute_of_Technology_Roorkee_logo.png" alt="IIT Roorkee Logo" class="logo1">

    <h2> <b> <center> <p class="para" >  Virtual Labs IIT Roorkee <br> 

              Biomedical Laboratory  </p> </center>  </b> </h2> 
        </div>

    <div class ="header2">

   <center>  <p class="para0"> <b> Study of "Monopolar" Recordings </b> </p> </center>
  
      </div>

       <div id="diagram">

          <div class="dropdown">

            <button class="dropbtn"> <b>Instructions</b> </button>

            <div class="dropdown-content">

              &nbsp;

              <p> <b> STEP 1 : Make all the Correct Connections. </b> </p> &nbsp;

                     <p> <b> 1.    Connect Left Frontal (LF) point of Frontal Lobe to the point (LF) of Monopolar circuit. </b> </p> &nbsp;

                     <p> <b>  2.    Connect Left Parietal (LP) point of Parietal Lobe to the point (LP) of Monopolar circuit. </b> </p> &nbsp;
                    
                     <p> <b>  3.    Connect Left Occipital (LO) point of Occipital Lobe to the point (LO) of Monopolar circuit. </p>  </b> &nbsp;

                     <p>  <b> 4.     Connect Left Temporal (LT) point of Temporal Lobe to the point (LT) of Monopolar circuit. </b> </p> &nbsp;

                     <p>    <b> 5.    Connect A1 point of Ear lobe to the point (A1) of Monopolar circuit.        </b></p> &nbsp;

                     <p> <b>        STEP 2 : Click on check button to check for Correct Connections. </b> </p>  &nbsp;

                     <p> <b> STEP 3 : If Connections are not correct click on reset button to reset the connections. </b> </p>  &nbsp;
                     
                     <p> <b> STEP 4 : If Connections are correct click on Graph button to plot the Graph for the particular input connection. </b> </p>  &nbsp;
                     
                     <p>  <b> STEP 5 :  you can zoom in and out the graph as per your requirement and can use other features also like show data on hover, Autoscale etc.   </b>  </p> &nbsp;
                     
                     <p> <b> STEP 6 : Click on print button to save the observations. </b> </p> &nbsp;

            </div>
            
          </div>

          <p class="para1">  <b>  Figure 1: &nbsp; &nbsp; "Monopolar" Recording </b>  </p>

            <img src="photos/left hemishere.png" alt="Brain left-hemisphere" class="center1">

            <img src="photos/circuits.jpg" alt="circuits" class="circuits">
               
        

                         <p class="Node">  <b>  LF  </b> </p>
                         <p class="Node2"> <b>  LP  </b> </p>
                         <p class="Node3"> <b>  LO  </b> </p>
                         <p class="Node4"> <b>  LT  </b> </P>   

                 </div>
                 
          <div class="jtk-demo-main">

            <div class="jtk-demo-canvas canvas wide animation-demo jtk-surface jtk-surface-nopan" id="canvas">

             <div class="littledot" id="control10">  <br style="margin-top: 0.8em;display: block;">   <a href="#" class="cmdLink detach" rel="control10"  style="font-size:18px; color: black;"> <b> LF </b> </a> 
                                   <span class="content"> <b>Left Frontal (LF) node of Frontal Lobe</b></span>
                                   
                                       </div>
            <div class="littledot" id="control11"> <br style="margin-bottom: 0.8em;display: block;"> <a href="#" class="cmdLink detach" rel="control11" style="font-size:18px;color: black;"> <b> LP </b> </a> 
            
              <span class="content"> <b>Left Parietal (LP) node of Parietal Lobe</b></span>
                                   </div>
             <div class="littledot" id="control12"> <br style="margin-bottom: 0.8em;display: block;"> <a href="#" class="cmdLink detach" rel="control12" style="font-size:18px;color: black;"> <b> LO </b> </a> 
            
              <span class="content"> <b>Left Occipital (LO) node of Occipital Lobe</b></span>
                                   </div>
            <div class="littledot" id="control13"> <br style="margin-bottom: 0.8em;display: block;"> <a href="#" class="cmdLink detach" rel="control13" style="font-size:18pX;color:black;"> <b> LT </b> </a> 
              <span class="content"><b>Left Temporal (LT) node of Temporal Lobe</b> </span>
                                                    </div>
            <div class="littledot" id="control14"> <br style="margin-bottom: 0.08em; display:block;"> <a href="#" class="cmdLink detach" rel="control14" style="font-size:18px; color: black;"> <b> A1 </b> </a> 
            
            
              <span class="content"><b> Ear Lobe (A1) </b></span>
                  </div>   

            </div>
            </div>

              <div class="jtk2-demo-main">

                <div class="jtk2-demo-canvas canvas wide animation-demo jtk-surface jtk-surface-nopan" id="canvas">
    
                <div class="littledot" id="control5">   <br style="margin-top: 0.8em;display: block;">    <a href="#" class="cmdLink detach" rel="control5"  style="font-size:15px; color:black;" >   <b>   </b> </a> </div>
                <div class="littledot" id="control6">   <br style="margin-bottom: 0.8em;display: block;"> <a href="#"  class="cmdLink detach" rel="control6" style="font-size:15px;color: black;">    <b>   </b> </a> </div>
                <div class="littledot" id="control7">   <br style="margin-bottom: 0.8em;display: block;"> <a href="#"  class="cmdLink detach" rel="control7" style="font-size:15px;color: black;">    <b>   </b> </a> </div>
                <div class="littledot" id="control8">   <br style="margin-bottom: 0.8em;display: block;"> <a href="#"  class="cmdLink detach" rel="control8" style="font-size:15pX;color: black;">    <b>   </b> </a> </div>
                <div class="littledot" id="control9">   <br style="margin-bottom: 0.08em; display:block;"><a href="#" class="cmdLink detach" rel="control9" style="font-size:15px;color:  black;">    <b>   </b> </a> </div>   
                       
                </div>
                </div>

        <a>

            <button onclick="checkk()" id="check" class=" bn54" >

              <span class="bn54span"> <b> CHECK </b> </span>

            </button>

          </a>

          <a>

            <button onclick="getData()" class ="bn54" id="graph">

                <span class="bn54span"> <b> GRAPH </b> </span>

            </button>

            </a>

            <a >
                
                <button  onclick="ResetAll()" class="bn54" id="reset">

                    <span class="bn54span"> <b> RESET </b> </span>

                </button>
                      
            </a>

            <a href="">

                  <button id ='print' class="bn54">                                                                                                                    

                      <span class="bn54span"> <b> PRINT </b> </span>

                  </button>

            </a>

                 <div class="Testing">

                 <p><center><b>Note:This Graph is for Testing purpose only.</b></center></p>

                 </div> 

            <div id="chartContainer" style="height: 400px; width: 100%;"></div>
            <div class="navbar"><span>  </span></div>
            
            <div id="chart" style="height:350px; width:35%;"> </div>

            <script>

              function getData() {

                return Math.random();

                  document.getElementById("graph")                
          
              }
          
              Plotly.plot('chart',[{
          
                  y:[getData()],

                  type:'line'

              }]) ;
          
              var cnt=0;
              setInterval (function()  {
          
                  Plotly.extendTraces('chart',{y:[[getData()]]},[0]);
                  cnt++;
                  if(cnt > 200)  {
          
                      Plotly.relayout('chart', {
                          xaxis:  {
                              range:[cnt-500,cnt]
          
                          }
                      });
                  }
              }, 15);
          
          </script>
          </div>
                               

                                
                         <script src="dist/js/jsplumb.js"></script>
                                  
    
                               
                          <script src="demo.js"></script>

                        
                       

                      <footer>

         <hr>

             <p class='copyright'> <b> © Copyright 2021 Virtual Labs,IIT Roorkee </b> </p>
  

         </footer>

                              

             </body>

           </html>`

                                                                                         Javacsript file

;
(function (ResetAll)      {
    
    var xx = document.getElementById("reset")

    xx.onclick = showAlert; // Add onclick function to element
    
    function showAlert(event) {

        window.location.reload()
    }

    var yy=document.getElementById("check")
    yy.onclick=checkk;

    function checkk()

    {
       if (connections.length<5 || connections.length>5)

       { 
              swal ({   title:"Try Again!",
                        text:"Make all the connections first!",
                        icon:"warning",
                        button: "Try Again!",
                        closeOnClickOutside: false,
                        
                  })

       return }
        
       
        if (connections.length > 0) {

            var listDiv = []

             for (var j = 0; j < connections.length; j++)   {

                listDiv.push(connections[j].sourceId)
                listDiv.push(connections[j].targetId)          
            }

            var f=0

         for (var i=0;i<6;i+=2)
         
         {

           if (Number(listDiv[i][14])%2==0 && Number(listDiv[i][14])+1 == listDiv[i+1][14])
           {
               f=1 
               break
           }

           if (Number(listDiv[i][14])%2!=0 && Number(listDiv[i][14])-1 == listDiv[i+1][14])
           {
               f=1 
               break
           }

            if (Number(listDiv[i][14])+1 ==listDiv[i+1][14] || Number(listDiv[i][14])-1 == listDiv[i+1][14] )
            {
              continue }

              else

              {
                  f=1

                  break
              }

         }

         if (f==0)

         swal   ({

                      title: "Connections Established!",
                      text:  "Right Connections!",
                      icon:  "Success",
                      button: "Aww Yiissss!",
                      closeOnClickOutside: false,

                 })

         else
         
         swal ({

             title: "Connections Error!", 
             text: "Wrong Connections!",
             icon: "error",
             button: "Oh noo!",
             closeOnClickOutside: false

             })

        }
    }

        showConnectionInfo = function (listDiv) {
           
                 console.log(listDiv)
        },
        hideConnectionInfo = function () {
            listDiv.style.display = "none";
        },
        connections = [],
        updateConnections = function (conn, remove) {
            if (!remove) connections.push(conn);
            else {
                var idx = -1;
                for (var i = 0; i < connections.length; i++) {
                    if (connections[i] == conn) {
                        idx = i;
                         break;
                    }
                }
                if (idx != -1) connections.splice(idx, 1);
            }

            if (connections.length > 0) {

                var listDiv = []

                 for (var j = 0; j < connections.length; j++) {

                    listDiv.push(connections[j].sourceId)
                    listDiv.push(connections[j].targetId)

                        
                }
                showConnectionInfo(listDiv);

            } else

                hideConnectionInfo();
        };

    jsPlumb.ready(function () {

        var instance = jsPlumb.getInstance({

            DragOptions: { cursor: 'pointer', zIndex: 2000 },
            PaintStyle: { stroke: '#666' },
            EndpointHoverStyle: { fill: "orange" },
            HoverPaintStyle: { stroke: "orange" },
            EndpointStyle: { width: 20, height: 16, stroke: '#666' },
            Endpoint: "Rectangle",
            Anchors: ["TopCenter", "TopCenter"],
            Container: "canvas"

        });

        // suspend drawing and initialise.

        instance.batch(function () {

            // bind to connection/connectionDetached events, and update the list of connections on screen.
            instance.bind("connection", function (info, originalEvent) {
                updateConnections(info.connection);
            });

            instance.bind("connectionDetached", function (info, originalEvent) {
                updateConnections(info.connection, true);
            });

            instance.bind("connectionMoved", function (info, originalEvent) {

                //  only remove here, because a 'connection' event is also fired.
                // in a future release of jsplumb this extra connection event will not
                // be fired.
                
                updateConnections(info.connection, true);
            });

            instance.bind("click", function (component, originalEvent) {

                alert("click!")
            });

            // configure some drop options for use by all endpoints.

            var exampleDropOptions = {

                tolerance: "touch",
                hoverClass: "dropHover",
                activeClass: "dragActive"

            };

            var color2 = "#316b31";

            var exampleEndpoint2 = {

                endpoint: ["Dot", { radius: 9 }],
                paintStyle: { fill: color2 },
                isSource: true,
                scope: "green",
                connectorStyle: { stroke: color2, strokeWidth: 5 },
                connector: ["Bezier", { curviness: 15 } ],
                maxConnections:1 ,
                isTarget: true,
                dropOptions: exampleDropOptions

            };

            var e1 = instance.addEndpoint('control10', { anchor: [0.75, 0, 0, -1] }, exampleEndpoint2);

            // setup some DynamicAnchors for use with the blue endpoints
            // and a function to set as the maxConnections callback.

            var anchors = [

                    [0, 0.2, 1, 0],
                    [0.8, 1, 0, 1],
                    [0, 0.8, -1, 0],
                    [0.2, 0, 0, -1]
                ],

                maxConnectionsCallback = function (info) {

                    alert("Cannot drop connection " + info.connection.id + " : maxConnections has been reached on Endpoint " + info.endpoint.id);

                };

            e1.bind("maxConnections", maxConnectionsCallback);

            instance.addEndpoint('control5', { anchor: [0.75, 0, 0, -1] }, exampleEndpoint2);

            instance.addEndpoint("control11", { anchor: [0.75, 0, 0, -1] }, exampleEndpoint2);
            instance.addEndpoint("control6", { anchor: [0.75,0 , 0, -1] }, exampleEndpoint2);
            instance.addEndpoint("control12", { anchor: [0.75, 0, 0, -1] }, exampleEndpoint2);
            instance.addEndpoint("control7", { anchor: [0.75, 0, 0, -1] }, exampleEndpoint2);
            instance.addEndpoint("control13", { anchor: [0.75, 0, 0, -1] }, exampleEndpoint2);
            instance.addEndpoint("control8", { anchor: [0.75, 0, 0, -1] }, exampleEndpoint2);
            instance.addEndpoint("control14", { anchor: [0.75, 0 ,0, -1] },exampleEndpoint2);
            instance.addEndpoint("control9", { anchor: [0.75, 0, 0, -1] },exampleEndpoint2);

            instance.draggable(jsPlumb.getSelector(".drag-drop-demo .window"));

            var hideLinks = jsPlumb.getSelector(".drag-drop-demo .hide");
            instance.on(hideLinks, "click", function (e) {

                instance.toggleVisible(this.getAttribute("rel"));
                jsPlumbUtil.consume(e);
            });

            var dragLinks = jsPlumb.getSelector(".drag-drop-demo .drag");
            instance.on(dragLinks, "click", function (e) {

                var s = instance.toggleDraggable(this.getAttribute("rel"));
                this.innerHTML = (s ? 'disable dragging' : 'enable dragging');
                jsPlumbUtil.consume(e);
            });

            var detachLinks = jsPlumb.getSelector(".drag-drop-demo .detach");
            instance.on(detachLinks, "click", function (e) {

                instance.deleteConnectionsForElement(this.getAttribute("rel"));
                jsPlumbUtil.consume(e);
            });

            instance.on(document.getElementById("clear"), "click", function (e) {

                instance.detachEveryConnection();
                showConnectionInfo("");
                jsPlumbUtil.consume(e);
            });
           
        });

        jsPlumb.fire("jsPlumbDemoLoaded", instance);      
      
     }) 
         })

    ();

**Comment by sporritt** [comment]
please provide a codepen or similar.

**Comment by sporritt** [comment]
there's really nothing actionable here. please provide a codepen or similar. otherwise this issue will be deleted.
