### ISSUE TITLE
How to make sure a connector avoids its source node?

### ISSUE THREAD

**Issue by baptisteArno** [jsplumb/jsplumb#1073]
How can I turn the green connection into the orange one? (something that is aware of the node height ideally)

I thought it was handled by the `stub` parameter, although I'm not sure what it does exactly 😭

Here is my config:

Source:
```ts
const endpointOptions: EndpointOptions = {
  endpoint: { type: DotEndpoint.type, options: { radius: 11 } },
  paintStyle: { fill: "green" },
  connectorStyle: { stroke: "green", strokeWidth: 6 },
  connector: {
    type: FlowchartConnector.type,
    options: {
      stub: [40, 60],
      gap: 10,
      cornerRadius: 15,
      alwaysRespectStubs: true,
    } as FlowchartConnectorOptions,
  },
  source: true,
};

plumbInstance.addEndpoint(
  stepRef.current,
  {
    anchor: [1, 0.5, 1, 0],
  },
  endpointOptions
);

```

Target:
```ts
const endpointOptions: EndpointOptions = {
  endpoint: { type: DotEndpoint.type, options: { radius: 11 } },
  paintStyle: { fill: "red" },
  target: true,
};
plumbInstance.addEndpoint(
  blockRef.current,
  {
    anchor: [[0, 0.2, -1, 0], "Top"],
  },
  endpointOptions
);

```

![CleanShot 2021-11-25 at 10 14 58@2x](https://user-images.githubusercontent.com/16015833/143413523-0daf77e9-2e70-4e00-889c-3724b9c41255.png)

**Comment by sporritt** [comment]
this anchor value looks fine

```
anchor: [1, 0.5, 1, 0],
```

you might need to mock this up in a codepen or something.

**Comment by baptisteArno** [comment]
[Here it is](https://codesandbox.io/s/jsplumb-1073-5on0y)

Connect the green to the red and see the issue

**Comment by sporritt** [comment]
it's very difficult to debug things on this site...why is there no console.log?

**Comment by baptisteArno** [comment]
Oh really? It looks like I can log to the console and view it into the tool or directly from browser dev tools:

![CleanShot 2021-11-26 at 09 00 33@2x](https://user-images.githubusercontent.com/16015833/143547080-74aad780-11d3-4354-9209-e5574548d18f.png)

**Comment by sporritt** [comment]
yes, i can see the console.  but try writing `console.log(..)` somewhere in the code.

**Comment by baptisteArno** [comment]
Yes that's what I do on the screenshot, I'm writing `console.log("test")` in the useEffect hook

**Comment by sporritt** [comment]
that's weird. i get a stack trace saying console.log is not defined.

**Comment by baptisteArno** [comment]
That's odd! Maybe try another browser?

**Comment by sporritt** [comment]
i feel like maybe this is a bug in the dynamic anchors in 5.x. like somehow the selected anchor's orientation is not being put into effect.  If i change the BlockNode to have a single `Top` anchor i get the effect you are expecting:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/262720/143553683-6ece6312-ee3b-4a29-ba71-bca794774c47.png">

although, along the way I am not seeing the connector snap to show its final path in the way that it does in this demonstration for example:

https://demo.jsplumbtoolkit.com/community/flowchart/

so that needs investigating too.

i'll take this offline and play around with it a bit.

**Comment by sporritt** [comment]
5.2.0 has fixes for the stuff in this issue:

- anchor orientation was lost when using a dynamic anchor
- connectors weren't snapping to show orientation on hover

**Comment by baptisteArno** [comment]
Amazing job, thank you very much! 👏

**Comment by sporritt** [comment]
no problem. i will close this and the other issue then.
