### ISSUE TITLE
❓ Questions about Community Edition

### ISSUE THREAD

**Issue by fragkakis** [jsplumb/jsplumb#1075]
I am interested to use the community version of jsPlumb for a pet project, but the following is unclear to me:

1. which can do more, the [Community Edition 2.X](https://docsjsplumbtoolkit.com/community-2.x/current/) or the [Community edition 5.X](https://docs.jsplumbtoolkit.com/community/)? Or are they equals in terms of functionality?
2. I appreciate that the project has documentation and all, but a demo is even better, where I can see an end-to-end application built with it. In my understanding, both the [demo page](https://demo.jsplumbtoolkit.com/flowchart-builder/) and the [demo repo](https://github.com/jsplumb-toolkit-demonstrations) are all about the commercial toolkit edition. Is this correct? Is there a demo of something built with the community edition?

**Comment by sporritt** [comment]
You should use 5.x and not 2.x, as 2.x is in maintenance mode now.

Home page for the Community edition is here:

https://jsplumbtoolkit.com/community

**Comment by sporritt** [comment]
closing this as i think this is answered.
