### ISSUE TITLE
Connector maxStub on `source` endpoint

### ISSUE THREAD

**Issue by baptisteArno** [jsplumb/jsplumb#1078]
Is there a way to say "the maximum length, in pixels, of the last stub that going into an Endpoint should be '50px'"?

Here is why want to do this:
<img src="https://user-images.githubusercontent.com/16015833/145236115-3c9ad7c6-dca4-44bc-906e-8f66c95d9efd.png" width="200px"/>
I just need the last stub (blue arrow) to be shorter

**Comment by sporritt** [comment]
no. the blue arrow spans two segments in this case - the stub and the segment adjoining it, which goes to the midpoint. if you changed the 'midpoint' value you might get the effect you want. but its not a very flexible approach, as its fixed to specific proportions.

**Comment by baptisteArno** [comment]
Thank you @sporritt, `midpoint` does the job for my use case 👍
