### ISSUE TITLE
`INTERCEPTOR_BEFORE_DRAG` interceptor is not triggering

### ISSUE THREAD

**Issue by baptisteArno** [jsplumb/jsplumb#1079]
It seems the command:
```ts
instance.bind("INTERCEPTOR_BEFORE_DRAG", (params:BeforeDragParams) => {
  console.log("drag fired")
});
```
Isn't printing anything to console when dragging a new connector

[Here is a reproduction](https://codesandbox.io/s/jsplumb-1079-7vyoe?file=/src/App.tsx)

**Comment by sporritt** [comment]
`"INTERCEPTOR_BEFORE_DRAG"` is not the name of an event, it's a constant, but in fact it's not that either exactly, as it's `INTERCEPT_BEFORE_DRAG`:

```
export const INTERCEPT_BEFORE_DRAG = "beforeDrag"
```

it's in `@jsplumb/core`.

it would make more semantic sense to be "INTERCEPTOR.." though, as that's a noun.  Maybe I'll put both in to the next release and deprecate `INTERCEPT_...`

**Comment by sporritt** [comment]
closing.
