### ISSUE TITLE
`stub` is applied to source AND target

### ISSUE THREAD

**Issue by baptisteArno** [jsplumb/jsplumb#1080]
It looks like when setting the `stub` property on the source endpoint, it is also applied to the target endpoint. Is this expected? I'd like to only apply a stub to the source endpoint.

[Here is a reproduction](https://codesandbox.io/s/jsplumb-1080-2hm3j?file=/src/components/StepNode.tsx)

<img width="400" alt="CleanShot 2021-12-09 at 09 39 40@2x" src="https://user-images.githubusercontent.com/16015833/145362488-792d4c9e-a988-44f3-bef4-668531969665.png">

(Also, another issue, it seems the `cornerRadius` isn't the same at the end of the connector)

**Comment by sporritt** [comment]
`stub` is defined on the connector:

```
connector: {
    type: FlowchartConnector.type,
    options: {
      cornerRadius: 15,
      stub: 50,
      alwaysRespectStubs: true
    } as FlowchartConnectorOptions
  },
```

it applies to both ends.

**Comment by baptisteArno** [comment]
Okay, thanks!
