### ISSUE TITLE
getConnections in index.d.ts has too many parameters

### ISSUE THREAD

**Issue by rbirkgit** [jsplumb/jsplumb#1081]
The file index.d.ts with jsPlumb 2.15.6 has too many parameters:

  getConnections(scope: string, options: Object, scope2?: string | string, source?: string | string | Selector, target?: string | string | Selector, flat?: boolean/* =false */): Array<any> | Record<any, any>

It should be:

  getConnections(options: Object, flat?: boolean/* =false */): Array<any> | Record<any, any>

Looking at the file jsPlumb.js you see the actual function:

  this.getConnections = function (options, flat) {

This is causing our code to not compile when using the typescript types.

**Comment by rbirkgit** [comment]
Better would be if the options parameter had an actual type.

**Comment by rbirkgit** [comment]
Looked at 5.3.1 types and there it is (in core.d.ts):

  getConnections(options?: SelectOptions<T["E"]>, flat?: boolean): Record<string, Connection> | Array<Connection>;

**Comment by rbirkgit** [comment]
It seems the PaintStyle interface is missing a few options. We get error here too.

    interface PaintStyle {
        stroke?: string;
        fill?: string;
        strokeWidth?: number;
    }

You see in 5.3.1 the full list:

export declare interface PaintStyle {
    stroke?: string;
    fill?: string;
    strokeWidth?: number;
    outlineStroke?: string;
    outlineWidth?: number;
    dashstyle?: string;
}

**Comment by rbirkgit** [comment]
Should one assume one cannot use the types in 2.15.6 as it seems rather outdated or just wrong?

**Comment by sporritt** [comment]
5.3.1 is written in typescript so the types are always accurate. The types in 2.x are cobbled together. I encourage everyone to migrate to 5.x.

**Comment by rbirkgit** [comment]
My plan was to get the typings in first and then upgrade, as the upgrade will take some time. You are right though, we should try to.

**Comment by sporritt** [comment]
I'm going to close this. I have no time to go back and update the 2.x typings. Onwards and upwards.
