### ISSUE TITLE
jtk-source-hover and jtk-target-hover styles not set on hovering (5.3.1)

### ISSUE THREAD

**Issue by rbirkgit** [jsplumb/jsplumb#1082]
I upgraded part of our code from 2.15.6 to 5.3.1. Most seems to work fine, except hovering. When hovering over our connections, the source and targets no longer gets the jtk-source-hover and jtk-target-hover css styles set. They do have the jtk-connected style set.

I can not find much info about this, if this is something that needs to be enabled with 5.x or something else changed?

**Comment by rbirkgit** [comment]
Actually, just noticed with 2.x they also had jtk-managed and jtk-endpoint-anchor styles set that no longer there with 5.x. Just the jtk-connected style.

**Comment by sporritt** [comment]
Those are not set by 5.x, because you dont setup individual elements as sources/targets. You can just do this yourself since you know what the appropriate selectors are. You dont need jsPlumb for this.

**Comment by rbirkgit** [comment]
Are you saying I should subscribe to the EVENT_CONNECTION_MOUSEOVER and EVENT_CONNECTION_MOUSEOUT events and set the css styles? Just want to make sure I understand your suggestion. Is there a mouse enter event? or I need to keep track on which one is the first mouse over until I get a mouse out one.

**Comment by rbirkgit** [comment]
Tried subscribing to the mouse over event and it seems to have the info I need, i.e. the connector in question and its source and target elements. So should be able to set/remove the css styles like it used to in 2x.

**Comment by rbirkgit** [comment]
Wanted to make sure I understood what you mean on how I should proceed with this?

**Comment by sporritt** [comment]
After seeing your code I think in fact I misunderstood what the issue was here. You mean when you hover over a connection you expect its source endpoint to get `jtk-source-hover` and its target to get `jtk-target-hover`, right, and this without you having to have explicitly configured anything?

**Comment by rbirkgit** [comment]
Yes, that how it was in v2. 

I am new to jsPlumb and trying updating our existing code to v5 and when I discovered this discrepancy.

**Comment by sporritt** [comment]
..ok so in 5.3.2 i can see that currently if you were to supply a `hoverClass` to your endpoints then hovering over the connection would see those classes get added, but not `jtk-source-hover` or `jtk-target-hover`. 

This is the first few lines of the unit test:

```
var d = _addDiv("one", 0, 0, 100, 100), 
            d2 = _addDiv("two", 250, 250, 100, 100),
            e1 = _jsPlumb.addEndpoint(d, {
                hoverClass:"sourcehovering"
            }),
            e2 = _jsPlumb.addEndpoint(d2, {
                hoverClass:"targethovering"
            }),
            c = _jsPlumb.connect({source:e1, target:e2})
```

Hovering over `c` gets those classes added to the source/target endpoints.   But I'll look into reinstating `jtk-source-hover` and `jtk-target-hover`.

**Comment by sporritt** [comment]
this is fixed in 5.3.3. you can remove that event binding code you shared in a comment above.

**Comment by rbirkgit** [comment]
Awesome news!

**Comment by rbirkgit** [comment]
I just tested 5.3.3 and not getting it to work. I don't see the styles being set on hover.

**Comment by sporritt** [comment]
i think you'll need to provide a codepen or jsfiddle or something.

**Comment by rbirkgit** [comment]
Do I need to also supply a custom hovering class?

**Comment by sporritt** [comment]
you dont _have_ to supply one, no. but if you do i'd expect them to be added to the endpoints when the connector is hovered.

**Comment by rbirkgit** [comment]
I looked a little more and see the hovering classes being set, but on the wrong element. It's on a div created by jsplumb containing a the endpoint svg (forget the name). But the little dot/circle at beginning/end of connector.

In v2 the hovering classes were set on the endpoint object itself.

**Comment by sporritt** [comment]
set on the endpoint object itself, what do you mean?

**Comment by rbirkgit** [comment]
I have a source and a target. These are the input to a new connection between them. When I hovered over the connection in v2, it added the hover classes on the source and target DOM elements.

**Comment by sporritt** [comment]
ah, right. hmm yes that is interesting. i will take a look.

**Comment by sporritt** [comment]
..yes so i should have consulted the docs before i rushed off to "fix" this:

https://docs.jsplumbtoolkit.com/community/lib/styling-via-css#interactive-css-classes

it does indeed say the classes are added to the elements, not the endpoints. and in 5.3.4 that is what happens.

**Comment by rbirkgit** [comment]
Tried it out this morning. Working great. Thanks!!

**Comment by sporritt** [comment]
No problem. This seems like a useful feature...
