### ISSUE TITLE
Connected nodes disappears while dragging from one point to another

### ISSUE THREAD

**Issue by sagarssabat** [jsplumb/jsplumb#1083]
While dragging the nodes, in higher resolution the nodes disappear and appear back when kept in a normal state.

**Comment by sporritt** [comment]
you'll need to supply a codepen or similar. there's nothing to work with here.

**Comment by sagarssabat** [comment]
https://user-images.githubusercontent.com/22165030/147533929-0f630bd3-f45d-4f67-8c99-6950dc144a46.mp4

**Comment by sporritt** [comment]
This video is not really useful. a reproducible example that can be debugged would be useful.

**Comment by sporritt** [comment]
I'm going to close this due to lack of activity.
