### ISSUE TITLE
jsPlumb: unknown connector type 'Bezier

### ISSUE THREAD

**Issue by zeusxs** [jsplumb/jsplumb#1085]
Can't create bezier connector, but straight and flowchart is ok
![image](https://user-images.githubusercontent.com/30338668/147844831-ae7680c0-a43f-4b5b-8029-5c06619ee4d6.png)

code sandbox: https://codesandbox.io/s/jsplumb-playground-fl8vj?file=/src/components/ExampleConnector.vue

**Comment by zeusxs** [comment]
package version 
![image](https://user-images.githubusercontent.com/30338668/147845421-fee6c182-eab7-44f1-a49f-f62ca3758ad6.png)

**Comment by sporritt** [comment]
you have to use the same version of everything.

**Comment by sporritt** [comment]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/262720/148851391-ac9ffc5d-cfe9-4ace-a862-e44c399b5117.png">


closing this.
