### ISSUE TITLE
Continuous anchors on different faces connecting the same elements

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1086]
**Version:** jsplumb 2.15.6 
**Summary:** When connecting the same elements a second time using connect(), choosing a different target face is being ignored.
**Description:** For example the 1st call to connect() uses the left face for the target 
`anchors: ['Continuous', ['Continuous', { faces: ['left'] }]]` 
and the 2nd call to connect() is done on the bottom face:
`anchors: ['Continuous', ['Continuous', { faces: ['bottom'] }]]`
Then both connections end up rendering on the same face (the 1st one that is connected - 'left' here). 
**Notes:** Deleting the 1st connection will render the 2nd correctly. Also if we have different source elements for the connections the rendering is correct. 
**Codepen:** https://codepen.io/panayotisk/pen/gOGejyq
Please check the codepen, the 2nd connection is expected to attach to the bottom face, unless there is something I am missing when configuring the anchors.

**Comment by panayotisk** [comment]
The same is also happening in version 5.3.1.
**Code sandbox:** https://codesandbox.io/s/epic-elbakyan-28np5?file=/src/index.js

**Comment by sporritt** [comment]
yes this looks like a bug, i can replicate this in 5.3.1 in a unit test.

**Comment by sporritt** [comment]
incidentally you can replace your longhand definitions :

```
anchors: ["Continuous", { type: "Continuous", options: { faces: ["left"] } }]
```

is the same as 

```
anchors:["Continuous", "ContinuousLeft"]
```

As well as supporting the four individual faces, there is also `ContinuousLeftRight` and `ContinuousTopBottom`.

**Comment by sporritt** [comment]
this is fixed in 5.3.2

**Comment by panayotisk** [comment]
Just one more thing. Will there be a fix for version 2.x or should we all migrate our code to 5.x as soon as possible?

**Comment by sporritt** [comment]
i dont really feel like maintaining two versions, if i'm honest.

**Comment by panayotisk** [comment]
Thank you very much for fixing the issue. It works correctly on my tests too.
