### ISSUE TITLE
Image Type is not supported for Endpoint

### ISSUE THREAD

**Issue by devmotiramani** [jsplumb/jsplumb#1089]
As described in the Endpoint documentation link (https://docs.jsplumbtoolkit.com/community/lib/endpoints), the Image type is currently not working.

![image](https://user-images.githubusercontent.com/52850656/147941622-78c72e50-af7e-40e6-ae22-2967005a69d9.png)

**Comment by sporritt** [comment]
The docs need to be updated. Image was removed in 5.x, with the expectation being you achieve the same result via the `cssClass` property and a css rule.

**Comment by devmotiramani** [comment]
> The docs need to be updated. Image was removed in 5.x, with the expectation being you achieve the same result via the `cssClass` property and a css rule.

Thank you for details.

**Comment by sporritt** [comment]
the docs have been updated and `Image` has been removed from the list.
