### ISSUE TITLE
Endpoint hover doesn't highlights associated endpoint

### ISSUE THREAD

**Issue by devmotiramani** [jsplumb/jsplumb#1090]
On Endpoint hover, the associated endpoint doesn't get highlighted.

Reference pull request - https://github.com/jsplumb/jsplumb/pull/1088

**Comment by sporritt** [comment]
this is fixed in version 5.3.2.

**Comment by rbirkgit** [comment]
Is this related to my issue? https://github.com/jsplumb/jsplumb/issues/1082

**Comment by sporritt** [comment]
...when i just read your comment on that issue this recent situation came to mind, yes. i think it's probably related but not directly in the code, if that makes sense.

**Comment by sporritt** [comment]
@devmotiramani i'm going to close this on the assumption it's fixed. feel free to reopen if you find otherwise.
