### ISSUE TITLE
Anchor always defaulting to bottom

### ISSUE THREAD

**Issue by Berkmann18** [jsplumb/jsplumb#1092]
I'm working on a tool where elements across a table are linked by arrows, one thing that keeps on happening (despite what I see on the examples), is that __the arrows always seem to be connected at the bottom__ whether or not I'm using the default *static* arrows (or when explicitly having `anchor: ['Top', ...]`) or `anchor: Continuous` (even with `anchors: { type: 'Continuous', options: { faces: [] } }` or all the `faces` enumerated).

I would have expected the arrows to be anchored at the top (of the target) when an element is connected to another one in a row below it and at the sides for elements in the same row.

Here are illustrations of what happens with the bottom anchoring:
- Same row and y-positioning:
![image](https://user-images.githubusercontent.com/8260834/148200213-7e7a514e-0287-4671-9042-e7c4199c77e5.png)

- Same row but different y-positioning:
![image](https://user-images.githubusercontent.com/8260834/148200558-d0f15cf3-be48-4ae3-a52f-010cb708596f.png)

- Different row:
![image](https://user-images.githubusercontent.com/8260834/148200704-0fbe23f4-c59a-4097-806c-c20798e4dfcc.png)

Here's the part of the code that connects elements:
```typescript
connectTickets(source: string, linkType: string, target: string) {
  //...
  const options: any = {
      connector: ['Bezier', { curviness: 50 }],
      source,
      target,
      endpoint: 'Blank',
      paintStyle: { stroke: LINK_COLOURS[linkType], strokeWidth: 2 },
      overlays: [['Arrow', { location: 1 }]],
      anchors: { type: 'Continuous', options: { faces: [] } }
    };
    
  //...
  this.jsPlumbInstance.connect(options);
}
```

**Comment by sporritt** [comment]
i don't know if this is what is causing your issue, but `anchors` should be an array of two definitions, one for the source and one for the target. The way you have it:

```
anchors: { type: 'Continuous', options: { faces: [] } }
```

will not work.  If you want both ends to have this definition, use `anchor`:

```
anchor: { type: 'Continuous', options: { faces: [] } }
```

i'm also not sure that passing in an empty `faces` array is a good idea.  i havent tested this but from memory if you give it no faces to choose from it's going to choose one anyway, as it has to, and its choice is likely indeterminate.

**Comment by Berkmann18** [comment]
I actually tried with `anchor` (instead of `anchors`) but get the following error:
![image](https://user-images.githubusercontent.com/8260834/148209764-3464f298-592a-4952-bd23-ebd59b5f44e2.png)
```
core.js:6456 ERROR TypeError: Cannot read properties of null (reading 'id')
   at push.2336.root.jsPlumbInstance.makeAnchor (jsplumb.js:6064)
...
```

**Comment by sporritt** [comment]
wait, is this not 5.x?   i just noticed your `connector` and `overlays` definitions are in the old, 2.x, format. if your're using 2.x then it should be

```
anchor: 'Continuous'
```

or

```
anchor:['Continuous', { faces:[...] }]
```

**Comment by Berkmann18** [comment]
I forgot to mention I'm using `jsplumb@2.15.6` (the latest version as of today on the NPM page).

I changed it back to `anchor: 'Continuous'` and don't seem to be getting the same errors I had before probably because it doesn't conflict as bad as what I had above with `options.anchors = ['Continuous', 'Left']` (although now, the anchors aren't _always_ set to `Bottom`).
