### ISSUE TITLE
 the click event is triggered when the node dragging stops

### ISSUE THREAD

**Issue by GeSnowBoy** [jsplumb/jsplumb#1094]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-euler-b2j9g?file=/index.html)

### Version
2.6.8 

### Description
Drag the element and you will see that the click event is triggered when the dragging stops. I would prefer not to have it triggered, what should I do? thx

**Comment by sporritt** [comment]
use the 'tap' event instead.
