### ISSUE TITLE
Event handlers for drag events and grid configuration in jsplumb 5.x 

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1098]
Configuring a draggable element in jsplumb 2.x we could define callbacks for drag events and the grid size:
```
let dragProps = {
     start: ... ,
     drag: ... ,
     stop: ..., ,
     grid: [20, 20]
};
jspInstance.draggable(el, dragProps);
```
Is there a recommended way to handle these events in jsplumb 5.x? 
Also configuring the grid is important for migrating to 5.x. Is there another way to do so?
These 2 questions are related to [https://github.com/jsplumb/jsplumb/issues/1097](https://github.com/jsplumb/jsplumb/issues/1097).

**Comment by sporritt** [comment]
You can pass `dragOptions` in to the constructor of the instance:

https://docs.jsplumbtoolkit.com/community/apidocs/browser-ui.browserjsplumbdefaults

https://docs.jsplumbtoolkit.com/community/apidocs/browser-ui.dragoptions

**Comment by panayotisk** [comment]
So, this means I cannot have different drag options on a per element basis. 
For example the filter option would be configured for all draggable elements the same way. I mean if I have different types of draggable elements (each with different child elements) I would need to somehow figure out a way to configure them all together. Or am I missing something?
Another thing: can the grid size be changed without having to create the instance again?

**Comment by sporritt** [comment]
right, you cant have different drag options for different elements. in 5.x there is no call to make individual elements draggable.

you can change the grid at runtime:

https://docs.jsplumbtoolkit.com/community/apidocs/browser-ui.browserjsplumbinstance.setdraggrid

**Comment by panayotisk** [comment]
Good to know we can set the grid at runtime! This is a quite helpful addition in v 5.x.
I will have to set up my elements in a different way to configure drag options, but it must be doable.
Thank you for the prompt response!

**Comment by sporritt** [comment]
If it gets too messy it _might_ be possible to support `filter` being a function or selector.
