### ISSUE TITLE
data-jtk-not-draggable has no effect when start is set in dragOptions

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1100]
**Version**: jsplumb 5.3.6
**Summary**: When setting an element as non draggable using setDraggable() this is being ignored if there is a dragOptions object with a start property in the call to newInstance().
**Expected behavior**: The element should not be draggable and the start event listener ignored.
**Notes**: This was working as expected in version 2.x.
**Code Sandbox**: https://codesandbox.io/s/modest-hopper-yyjzp?file=/src/index.js
On the code sandbox the red element was expected to be non-draggable.

**Comment by sporritt** [comment]
this is fixed in 5.3.7, which is now available.
