### ISSUE TITLE
DragStopEventParams.selection contains the dragged element only

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1102]
**Version**: jsplumb 5.3.7
**Summary**: After configuring dragOptions object stop property, the object passed to the listener contains a selection property with one item only in a multi-selection drag.
**Expected behavior**: Contain all items of the multi-selection.
**Notes**: The expected behavior above was the behavior in version 2.x.
We need some way to find the multi-selection and the new position of each item.

**Comment by sporritt** [comment]
bind to the `drag:stop` event on the instance. the payload has an `elements` array that contains the list of dragged elements and their new positions.

**Comment by panayotisk** [comment]
If it is possible please provide a link to the documentation or to an example for this event. I cannot find how to bind to it.

**Comment by sporritt** [comment]
https://docs.jsplumbtoolkit.com/community/lib/dragging
