### ISSUE TITLE
addTargetSelector anchor setting doesnt work

### ISSUE THREAD

**Issue by TSA0101** [jsplumb/jsplumb#1103]
version: 5.3.7

i have a simple setup in which i create a bunch of sources and targets from existing elements.

```js
instance.addSourceSelector('.ep', {
      anchor: { type: 'Continuous', options: { faces: ['right'] } },
      allowLoopback: false
});

instance.addTargetSelector('.w', {
      anchor: { type: 'Continuous', options: { faces: ['left', 'top', 'bottom'] } },
});
```

The anchor setting works perfectly fine with the addSourceSelector (the anchor is always on the right), but doesnt seem to work with addTargetSelector. No matter what setting i try, the connector always connects at the bottom of the element instead of the set anchor point(s).

**Comment by sporritt** [comment]
fixed in 5.3.8
