### ISSUE TITLE
About using of anchor

### ISSUE THREAD

**Issue by EgoistDeveloper** [jsplumb/jsplumb#1105]
Hi, I am building an entity-relation app for databases with Angular v13 and using jsPlumb v5.3.8. But I didn't understand the anchor working mechanism.

Here is my base config

```
public getJsPlumbConfigs(container: HTMLElement): BrowserJsPlumbDefaults {
  return {
    dragOptions: {
      cursor: 'pointer',
      zIndex: 2000,
      containment: ContainmentType.notNegative,
    },
    endpoint: {
      type: DotEndpoint.type,
      options: {
        radius: 5,
      },
    },
    anchor: AnchorLocations.Continuous,
    anchors: [
      AnchorLocations.ContinuousLeftRight,
      AnchorLocations.ContinuousLeftRight,
    ],
    container: container,
    connector: {
      type: FlowchartConnector.type,
      options: {
        stub: 50,
        cornerRadius: 10,
        midpoint: 20,
        alwaysRespectStubs: true,
      },
    },
  };
}
```

I use custom classes and element containers, also I am using another drag and drop library. Every table has its fields and I want dynamic left or right (_closest to linked other table field_) anchors.

![image](https://user-images.githubusercontent.com/17010054/151699799-1250d01d-e167-414e-a644-cebb37ce9077.png)

In documentation `anchor` field requires always and the default value is `AnchorLocations.Bottom`. Then I add `anchors` field,

```
...
anchor: AnchorLocations.Continuous,
anchors: [
  AnchorLocations.ContinuousLeftRight,
  AnchorLocations.ContinuousLeftRight,
],
...
```

Every connection seems drawing randomly like this
![image](https://user-images.githubusercontent.com/17010054/151700900-913ca3aa-cc99-4a24-9172-bad52111f367.png)

An another combination

```
anchor: AnchorLocations.Continuous,
anchors: [
  AnchorLocations.Right,
  AnchorLocations.Left,
],

```
![image](https://user-images.githubusercontent.com/17010054/151701081-b29def5d-8cbd-4338-8c9d-f849ff05a8bb.png)

In v2 this config is enough

```
anchor: [
  'LeftMiddle',
  'RightMiddle'
],
```

What is the best config for left middle or right middle anchors?

**Comment by sporritt** [comment]
that config is still enough. just drop the 'Middle':

```
anchor:["Left", "Right"]
```

**Comment by EgoistDeveloper** [comment]
I tested with [Stackblitz](https://stackblitz.com/edit/angular-jsplumb-example-anchor) and working perfectly. Obviously there is a bug in my project.

Thanks for your reply.

**Comment by EgoistDeveloper** [comment]
Hi again, I found the cause problem: using promise. 

When I create `newInstance` with promise, connections drawings brokes.

```typescript
private getJsplumbInstance(container: HTMLElement): Promise<BrowserJsPlumbInstance> {
  return new Promise(async (res, rej) => {
    const configs = this.builderConfigService.getJsPlumbConfigs(container),
      instance = newInstance(configs);

    if (instance) {
      res(instance);
    }

    rej(new Error('JsPlumb instance not found'));
  });
}
```

See [Stackblitz](https://stackblitz.com/edit/angular-jsplumb-example-anchor-with-bug) example.

**Comment by sporritt** [comment]
but what do you think is a jsplumb issue here?

**Comment by sporritt** [comment]
(i mean specifically regarding using a Promise vs not using a Promise)

one problem you app has is that your nodes are positioned `relative`, where they should be positioned `absolute`, as discussed here:

https://docs.jsplumbtoolkit.com/community/lib/dragging

**Comment by EgoistDeveloper** [comment]
@sporritt you are right my bad but I actually tried both ways and still same issue.

I suspect promise because in first [example](https://stackblitz.com/edit/angular-jsplumb-example-anchor) I use directly and second [example](https://stackblitz.com/edit/angular-jsplumb-example-anchor-with-bug?file=src%2Fapp%2Fapp.component.css) (_updated_) I am using in promise then connection lines brokes.

This issue can close. Just I wanted to provide feedback as this issue is so weird.

**Comment by sporritt** [comment]
obviously i know nothing about the larger context of your app, but out of interest, is there a reason you're using a promise to instantiate jsplumb? it doesn't seem to actually bring any benefit in this case.

**Comment by EgoistDeveloper** [comment]
There are many components in my app and I want to load the diagram after UI is loaded. Otherwise, If I try to load the first diagram container div is still loading and Angular says wait for UI (_with using ngAfterViewInit method_). Yes, I can load with a `setTimeout` but there is no guarantee to delay time. Some devices can be slower than my expectations.

Here is a small part of the story.

```typescript

async ngAfterViewInit(): Promise<void> {
  const boardElement = this.board.nativeElement;

  await this.getJsplumbInstance(boardElement).then(async (instance: BrowserJsPlumbInstance) => {
    this.jsPlumbInstance = instance;

    await this.installDraggieInstances().then(async () => {
      await this.drawEntityConnections().then(() => {
          this.entitiesIsLoading = false;

          this.spinner.hide('boardSpinner');

          this.installKeyBindings();
      });
    });
  });
}
```

I don't know the best practice. I am just trying.

**Comment by sporritt** [comment]
`ngAfterViewInit` is fired once the DOM is ready to use. It should suffice to instantiate jsPlumb directly inside that callback.

**Comment by EgoistDeveloper** [comment]
Yes, you are right but the app occasionally crashes with container element undefined error. Then I refresh the page and there is no error. This problem might be related to other dependencies and lifecycles. I will do what you say :)
