### ISSUE TITLE
Connection addOverlay() does not position the overlay properly

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1106]
**Version:** jsplumb 5.3.10
**Summary:** When setting a connection overlay using the addOverlay method the overlay is not positioned as expected.
**Expected behavior:** The overlay should be positioned on the connection.
**Notes:** This was working as expected in version 2.x. And it is working correctly if the overlay is declared in the connect() call (see the code sandbox). Another thing I noticed is that the connect() overlay dom element is child of the target endpoint whereas the addOverlay() dom element is child of the jtk-connector svg. 
**Code Sandbox:** https://codesandbox.io/s/connection-addoverlay-issues-gpnpz?file=/src/index.js
On the code sandbox the overlay with label bar is shown on (0, 0) of the container.

**Comment by sporritt** [comment]
in that fiddle both of the `jtk-overlay` elements are children of the container, not of an endpoint or an svg.  they have the correct parent. but the one added programmatically is yet to be positioned. calling `repaintEverything` paints the UI properly:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/262720/152703313-92e16063-1a41-4a2b-8d0c-847c0a0ba4de.png">

obviously `addOverlay` should have revalidated its source/target elements. i'll get a fix for this into 5.3.11.

**Comment by sporritt** [comment]
(it also works if you just revalidate one of the elements)

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/262720/152703346-190175d9-8f0c-4daf-9a27-711d4c90ae9b.png">

**Comment by sporritt** [comment]
in 5.4.0 you can use `addOverlay` on the jsplumb instance - not on the connection. The method still exists on connection but behaves as discussed here, ie. does not revalidate. But if you use the `addOverlay` method on the jsplumb instance the overlay will be added and the element revalidated afterwards.
