### ISSUE TITLE
Scroll listener does not detach when calling instance.destroy()

### ISSUE THREAD

**Issue by jenslind** [jsplumb/jsplumb#1107]
It seems the scroll listener added to `document` when creating a new instance is not removed when calling `instance.destroy()`.
Is it not supposed to be removed?

Also tried to disable the listener by passing `dragOptions: { trackScroll: false }` without success.

![Screenshot 2022-02-07 185744](https://user-images.githubusercontent.com/5213672/152845032-b8be6d41-2ab0-4680-809f-6cb6387ce8d4.png)

Using ` 5.3.11`

**Comment by sporritt** [comment]
fixed in 5.4.0
