### ISSUE TITLE
Support for cssClass on custom and arrow overlays

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1108]
**Version:** jsplumb 5.3.11
**Summary:** Allow setting the class of custom and arrow overlays through cssClass property.
**Notes**: This is a feature request. It was previously supported in version 2.x. It now works for label overlays only (as it is documented). 
It is quite important for us to target these overlay elements with CSS in order to style them.
**Code Sandbox:** https://codesandbox.io/s/custom-overlays-missing-support-for-cssclass-5f18v?file=/src/index.js
I would like to ask support for this functionality if it is not too much of a hassle.

**Comment by sporritt** [comment]
i've updated the code to do this for arrow overlays.  why do you need jsplumb to do it for custom overlays though, out of interest? you create the element yourself don't you?

**Comment by panayotisk** [comment]
Thank you! Yes, I just thought it is easier to have the class on the jsplumb wrapper div for my element. I would be able to target it like:
`.jtk-overlay.custom-class { ... }`
I guess I could add the custom class in my element (or introduce my own wrapper div), but I suspect having this option is more clear flexible. If you think it is not helpful addition I will do it like this.

**Comment by sporritt** [comment]
having looked at the code it's in fact a very simple change to put the cssClass onto a custom overlay, without any performance implications, so I think i'll make that change too.

**Comment by sporritt** [comment]
this is done in 5.4.0, for both custom and arrow overlays.

**Comment by panayotisk** [comment]
Thank you for this addition.
