### ISSUE TITLE
Request to add methods getClasses() or addDataProperty(), removeDataProperty() to Connection

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1111]
**Version**: Currently using jsplumb 5.4.0
**Summary:** The connection object has the extremely useful methods addClass() and removeClass() that allow us to set a class to connectors, endpoints and overlays in one go by setting the cascade parameter to true. There is a scenario where we need more dynamic data to the DOM (to style via CSS), for example if we want to set a connection's theme color. In that case:
1) We could either have multiple classes for that such as 'theme-red', 'theme-blue' e.t.c. but then we could use a function to search inside the connection classes for all classes starting with 'theme-'. In this case we could use a **getClasses()** method in the connection object so we could find what are the actual classes to remove.
2) We could store the info in data property (which we may also target via CSS) and have it in the DOM such as data-theme='red'. In that case we could use **addDataProperty()**, **removeDataProperty()** methods to set the name and value of the property along with the cascade option.
This is a feature request for extra convenience, if there is another method I don't know about, please say so.

**Comment by sporritt** [comment]
there is a `getClass()` method on `Component`, which is where the `addClass` and `removeClass` methods are defined. it returns a space separated list of classes.

**Comment by sporritt** [comment]
btw i see none of those methods actually have any apidocs at the moment, i'll update that for the next release.

**Comment by sporritt** [comment]
...in fact `addClass` and `removeClass` do have apidocs in the `Connection and Endpoint` classes. `getClass()` is on their parent - `Component`, and is now documented. Next version is 5.5.0, coming....soon, hopefully.
