### ISSUE TITLE
The connection line style is disordered when i connect the same node

### ISSUE THREAD

**Issue by NJimmi** [jsplumb/jsplumb#1113]
hello 
![image](https://user-images.githubusercontent.com/79197161/156706452-b59e18c1-07ba-4525-a132-e263ea61cc17.png)

As shown in the figure above
how can i fix the problem

**Comment by sporritt** [comment]
what connector are you using?

**Comment by NJimmi** [comment]
> what connector are you using?

FlowchartConnector

**Comment by sporritt** [comment]
this connector should theoretically render a loop if the source and target are the same.  we'd need to see a reproduction of this issue in a codepen or something.

**Comment by NJimmi** [comment]
> this connector should theoretically render a loop if the source and target are the same. we'd need to see a reproduction of this issue in a codepen or something.

hello.  this is a example for the issue

https://codesandbox.io/embed/still-moon-6krdjf?fontsize=14&hidenavigation=1&theme=dark

**Comment by NJimmi** [comment]
> this connector should theoretically render a loop if the source and target are the same. we'd need to see a reproduction of this issue in a codepen or something.

![image](https://user-images.githubusercontent.com/79197161/157018845-97a4641e-200f-4201-b234-9315c9044f05.png)

when u connect the same target,  and then drag it, the line were not move.

**Comment by sporritt** [comment]
this was fixed in 5.5.5 by merging PR #1115
