### ISSUE TITLE
jsPlumb Community edition license

### ISSUE THREAD

**Issue by dtozg** [jsplumb/jsplumb#1114]
It states
```
All 1.x.x, 2.x.x, 4.x.x, 5.x.x versions of jsPlumb Community edition are dual-licensed under both MIT and GPLv2.
```
But a bit ambiguous, e.g., should meet **BOTH** MIT **AND** GPLv2, or can choose **EITHER** MIT **OR** GPLv2 ?
From other history issues in this repo, It looks end user can choose **EITHER** MIT **OR** GPLv2.

If so, is it possible clearly add this statements into the license file?  e.g.
```
All 1.x.x, 2.x.x, 4.x.x, 5.x.x versions of jsPlumb Community edition are dual-licensed under both MIT and GPLv2. 
You can choose an appropriate one, i.e., either MIT or GPLv2.
```

**Comment by sporritt** [comment]
fixed in the repository now.
