### ISSUE TITLE
How to pass Constructable<AbstractConnector> into  Connectors.register method?

### ISSUE THREAD

**Issue by pinkcloud98** [jsplumb/jsplumb#1118]
Hi,
I tried to migrate our code from jsplumb 2.5.12 https://www.npmjs.com/package/jsplumb) to @jsplumb/browser-ui": "~5.3.4. I have a need to use **Connectors.register** method as in the following doc link:
https://docs.jsplumbtoolkit.com/community/apidocs/core.connectors#connectors-variable
https://docs.jsplumbtoolkit.com/community/apidocs/core.straightconnector

Question: How do I instantiate and pass a **Constructable<AbstractConnector>** instance into **Connectors.register** method?
Here is the code we had a long time ago with **jsplumb 2.5.12**

`let gridGraph = function(segments: any[]) {`
     `    let abstractConnector = jsPlumb.Connectors.AbstractConnector.apply(this, arguments);`
`    this.type = 'GridGraph';`
    `this._compute = (paintInfo, paintParam) => {`
       `let currentPoint = [paintInfo.sx, paintInfo.sy];`
       `let nextPoint;`
       `// draw the path according to the segments`
      `segments.forEach((segment) => {`
          `nextPoint = [segment.end[0] - segment.start[0] + currentPoint[0],`
          `segment.end[1] - segment.start[1] + currentPoint[1]`
          `];`
          `abstractConnector.addSegment(this, 'Straight', {`
              `x1: currentPoint[0],`
              `y1: currentPoint[1],`
              `x2: nextPoint[0],`
              `y2: nextPoint[1]`
         `});`
         `currentPoint = nextPoint;`
    `});`
 `};`
`};`
`// jsPlumb already initialized, so we have to set connectorsInitialized to false for the connector`
`jsPlumb.registerConnectorType(gridGraph, 'GridGraph');`
`jsPlumb.connectorsInitialized = false;`
`jsPlumb.init();`

My plan is to replace the above three lines with
jsPlumb.Connectors.register('GridGraph', some Constructable<AbstractConnector> instance);

I have
`import * as jsPlumb from '@jsplumb/core';`
`import * as jsPlumbBrowserUI from '@jsplumb/browser-ui';`

Is that the right direction?
What should I do with the old following code?
`let abstractConnector = jsPlumb.Connectors.AbstractConnector.apply(this, arguments);`
Any help on the migration would be greatly appreciated. Thanks,

**Comment by pinkcloud98** [comment]
Any help is greatly appreciated.

**Comment by sporritt** [comment]
Have you seen the Bezier connector code?

https://github.com/jsplumb/jsplumb/blob/master/ts/connector-bezier/index.ts
https://github.com/jsplumb/jsplumb/blob/master/ts/connector-bezier/bezier-connector.ts
https://github.com/jsplumb/jsplumb/blob/master/ts/connector-bezier/abstract-bezier-connector.ts

The key call is this:

```
Connectors.register(BezierConnector.type, BezierConnector)
```

and `BezierConnector` is a class that extends `AbstractBezierConnector`, which itself extends `AbstractConnector`.

**Comment by sporritt** [comment]
i'm going to assume this was sufficient to point you in the right direction. if not, let me know.
