### ISSUE TITLE
custom node

### ISSUE THREAD

**Issue by cmdares** [jsplumb/jsplumb#1127]
![image](https://user-images.githubusercontent.com/5292190/167393339-9a1d03f1-5ca4-49f0-8b6d-729d9ce8553a.png)
![image](https://user-images.githubusercontent.com/5292190/167394030-59ac8218-e049-4e77-b60f-7ada15358c16.png)
If support custom nodes

**Comment by sporritt** [comment]
I'm not really sure what the question is? You can use any arbitrary HTML as a node.

**Comment by cmdares** [comment]
thanks
