### ISSUE TITLE
Suggestions on custom overlay creation and removal

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1128]
**Version:** jsplumb 5.6.2
**Codepen:** https://codesandbox.io/s/custom-overlay-creation-and-removal-uc01vg Nothing important here, just a playground.
**Summary:** 1) I could not find `Component.addOverlay()` in the documentation. I think it should be added to the docs. 2) Moreover, `addOverlay()` has a pretty important comment in code that we should call revalidate() afterwards or, preferably, use the `JsPlumbInstance.addOverlay()` 3) Overlay removal using [removeOverlay()](https://docs.jsplumbtoolkit.com/community/apidocs/core.component.removeoverlay) is also of async nature. I had to use the (rather undocumented) parameter `dontCleanup`, since there was a race condition in the DOM element removal due to using the overlay element in Vue.js template code (and calling `removeOverlay()` on component destruction). I suggest documenting this parameter because we may need to check when/how the DOM element is removed especially since `removeOverlay()` seems to be of async nature too. Or maybe check for the DOM element existence before removing it.

**Comment by sporritt** [comment]
in 5.8.4 Component.addOverlay and Component.removeOverlay are explicitly marked internal and documented as internal methods. `removeOverlay` has been added to `JsPlumbInstance`.  users of the API should use the methods on the instance.
