### ISSUE TITLE
In Scrollable Lists state, when dragging the first node, the connection is wrong

### ISSUE THREAD

**Issue by crazy-wang** [jsplumb/jsplumb#1134]
![image](https://user-images.githubusercontent.com/24617035/172988150-5ee50ce4-a3cf-4551-95ca-c06829a84606.png)
When Figure 1 is initialized, it is normal.

![image](https://user-images.githubusercontent.com/24617035/172988187-df807403-1d96-4d1b-918e-438046befc2c.png)
Figure 2, when dragging the first node, there is a bug in the connection. But when dragging a non-first node, it can be dragged normally, and the connection is normal.

why?

**Comment by sporritt** [comment]
I'd need a codepen or similar to debug this.

**Comment by sporritt** [comment]
this is perhaps related to #1162 but without a codepen or similar i cant be sure. closing.
