### ISSUE TITLE
connection.bind not firing off events

### ISSUE THREAD

**Issue by corpulent** [jsplumb/jsplumb#1137]
I am looking at this jsfiddle and have the same issue on my end https://jsfiddle.net/priyankapothala/u7cuymzk/7/.

```javascript
jsPlumbInstance.bind("connection", function (this: BrowserJsPlumbInstance, info: any) {
  info.connection.bind("click", function (c: Connection) {
    console.log("click");
  });
});
```

I do see the click event is in the _listeners of the connection.
<img width="400" alt="Screen Shot 2022-06-15 at 12 03 12 PM" src="https://user-images.githubusercontent.com/849403/173788392-818f1341-605e-4b2e-b678-4bc217d7b699.png">

**Comment by sporritt** [comment]
you've been working with jsPlumb for years, Artem, i think probably you do know that double click events are supported on connections.

**Comment by corpulent** [comment]
@sporritt I took the time over the weekend to brush up on using jsplumb in depth instead of fast hacking it. Been a while. So for anyone who lands here in the future, there is a double click event for connections.

```
import {
  BrowserJsPlumbInstance,
  newInstance,
  EVENT_CONNECTION_DBL_CLICK } from "@jsplumb/browser-ui";

const jsPlumbInstance: BrowserJsPlumbInstance = newInstance({
  ...defaultOptions,
  container: containerRef.current
});

jsPlumbInstance.bind(EVENT_CONNECTION_DBL_CLICK, (connection: Connection) => {
  console.log(connection);
});
```

**Comment by tuku-dev** [comment]
Hi, If I need an event that should fire on a node connection, then what shall I use? 
`jsPlumbInstance.bind("connection", function` isn't working for me.
Thanks.

**Comment by agarwalsanchi** [comment]
@tuku-dev  did you get any solution.
 jsPlumbInstance.on(document.querySelectorAll(".jtk-connector"), "dblclick", function (e) {
            alert("double click");
onGroupConnectionDoubleClicked(CurrentConnection);
        });

@corpulent Please guide me
I have connectors with class name jtk-connector.
I want to read the data of current connection which is clicked and pass inside method "onGroupConnectionDoubleClicked". 
How to achieve this.

e.target is returning is the path that is the nested inside svg.

and  jsPlumbInstance.bind("click", function (component, originalEvent) {
                alert("click!")
            });

this is also not working..Please help me

**Comment by agarwalsanchi** [comment]
@corpulent i need details of current connection because i need source and target id of the clicked connector to use at some place.
