### ISSUE TITLE
mouseover event not propagated while dragging a connection

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1140]
**version:** jsplumb 5.8.3
**description:** The mouseover event does not work while dragging a connection. It looks like it is consumed by the floating endpoint.
**expected behavior:** I would expect the event to propagate so that I can style various elements while dragging. The **jtk-drag-hover** class works only for managed elements and I need to style other non-managed elements while a user pointer with a connection hovers over them.
**code sandbox:** https://codesandbox.io/s/hover-issues-while-dragging-connection-mcspoi?file=/src/index.js
**notes:** In the code sandbox you may see that when not dragging a connection both the css :hover pseudo class works and paints the elements yellow and the javascript event handler for the mouseover events work. But while dragging they do not (unless I am moving the mouse pointer too quickly). The same is true for the mouseenter events.

**Comment by sporritt** [comment]
if it's your intention to highlight the target element on hover because the connection can be dropped there, you're better off using the `jtk-drag-hover` class which jsPlumb writes onto a target element during the drag:

https://codesandbox.io/s/hover-issues-while-dragging-connection-forked-okc55b?file=/src/styles.css

**Comment by sporritt** [comment]
..i commented on this about the jtk-drag-hover and class then saw that you'd called it out, so i deleted the comment as it was pointless.  i'd need to see a specific example of something you're trying to do that you cannot do, i think. quite reluctant to change this.

**Comment by panayotisk** [comment]
I need to execute javascript code when the mouse hovers over an element (not just style it with CSS). 
This javascript code will create or remove DOM elements in my case. 
I tried using a MutationObserver for class change (to find if the change was due to setting or removing jtk-drag-hover class), but I also need the mouse coordinates in the observer handler to check if the pointer is over a specific child element. If I had the mouse event available this would have been possible.
Another (unrelated) thing that makes my task more difficult is that if you have set multiple target selectors through addTargetSelector() calls and these are set on overlapping DOM elements, only one of the elements receives the jtk-drag-hover class. For example if you set a parent and a child elements as targets then only the parent receives the jtk-drag-hover according to my tests. Maybe this could be discussed as another issue.
I understand that these may seem a bit too sophisticated, but hover handling is pretty cumbersome. If you have some tip/suggestion on any of the above please share.

**Comment by panayotisk** [comment]
Actually if you could somehow address the 2nd issue I mention above (every DOM element getting the jtk-drag-hover class), I would work around the mouse event. But I do not know if this is behavior by design or a bug.

**Comment by sporritt** [comment]
I'm not sure what's cumbersome about the hover stuff really. If you've got multiple overlapping targets jsPlumb chooses the first matching one it comes across as the drop target, and so that's the only one that gets the hover class added, since none of the others are candidates for drop.

**Comment by panayotisk** [comment]
Yes I just saw that the rank property of [BehaviouralTypeDescriptor](https://docs.jsplumbtoolkit.com/community/apidocs/core.behaviouralTypeDescriptor) seems to be the key to manage multiple overlapping targets. The thing is that during a connection drag if I dynamically add target elements it seems as if the list of target selectors is not updated. 
Can I somehow force a recalculation of target selectors during a drag?

**Comment by sporritt** [comment]
During a drag, no. The targets are identified at drag start in the current setup.

**Comment by panayotisk** [comment]
I submitted a new request  #1141 and will be closing this, since we can solve it by using the rank property.
