### ISSUE TITLE
Looking for Jump over / Crossing connectors options

### ISSUE THREAD

**Issue by vels-sonata** [jsplumb/jsplumb#1147]
Hello,

Is there any option/feature for Cross over connector ?  
![cross-over](https://user-images.githubusercontent.com/43806410/205223649-a45434e5-5fb6-4004-9775-70f36c1be36d.PNG)

**Comment by sporritt** [comment]
no, not at the moment, You can use an 'outlineWidth` like [in this demo](https://demo.jsplumbtoolkit.com/community/flowchart/)


<img width="147" alt="image" src="https://user-images.githubusercontent.com/262720/205226438-659672cd-63a5-4cfc-a367-501cde61d723.png">

to make it clearer what's happening when two connectors cross but there's no construct like you have above - the connectors don't know about each other in the current version

**Comment by vels-sonata** [comment]
After adding `outlineWidth: 2`, `outlineColor: '#ffffff'` , when we have multiple connector the outline color overlaps to the  arrows . Is there any other way?

![image](https://user-images.githubusercontent.com/43806410/205891863-0a45ce44-d6cc-4a7b-9a8a-9aaf6fe41542.png)


The data is like : 
1 --> 1.1
1.1 --> 1
1 --> 2
2 -->2.1
2.1 --> 2

**Comment by sporritt** [comment]
do you mean you have two connections on top of each other in that picture?  I can't see how the feature you originally requested would assist with this. You might want to consider using `Continuous` anchors for this so that each connection gets its own anchor point on the source and target nodes.

**Comment by vels-sonata** [comment]
Got it, What I mean here, if I have two connections with `AutoDefault`  when we use `outlineWidth: 2`, and `outlineColor: '#ffffff'` the outline color getting overlaps to the arrows. Is there any other way to achieve Cross Connection kind ?

**Comment by sporritt** [comment]
in that picture the outline from one connection is overlapping the other connection's arrow, yes. But that's because the two connections follow exactly the same path, due to the anchors you're using.

if you really want it setup like that you could [use css](https://docs.jsplumbtoolkit.com/community/lib/styling-via-css) to set a higher z-index for `.jtk-overlay`elements I guess.
