### ISSUE TITLE
Dragging on Grid seems to not be working

### ISSUE THREAD

**Issue by wernerstucky** [jsplumb/jsplumb#1153]
```
jsPlumbBrowserUI.newInstance({
    dragOptions:{
        grid:[50,50]
    }
})
```
Doesn't seem to change anything.
From the [documentation](https://docs.jsplumbtoolkit.com/community/lib/dragging#dragging-on-a-grid) I'm thinking that it would "snap to grid"?
Am I misunderstanding this functionality?

**Comment by hashmap123** [comment]
jsplumb

**Comment by tpra7** [comment]
Same here :/

**Comment by wernerstucky** [comment]
Thank you @tpra7 that works perfectly
