### ISSUE TITLE
afterLayout and afterDrag property doesn't work

### ISSUE THREAD

**Issue by Hmonat** [jsplumb/jsplumb#1154]
I was trying to use the afterLayout property referenced in https://docs.jsplumbtoolkit.com/toolkit/5.x/lib/magnetizer to avoid overlapping of nodes at the time of rendering them, but it doesn't seem to work.

**magnetize: {
      afterDrag: true,
      afterLayout: true
    },**

Also, afterDrag is working but for the first time when we move the node it allows overlapping, but once it is moved from its actual position, then it doesn't allow overlapping.

**Comment by sporritt** [comment]
This issue tracker is for the community edition. You can use support@jsplumbtoolkit.com for issues regarding the toolkit edition.
