### ISSUE TITLE
Connector over Flow the Other Element 

### ISSUE THREAD

**Issue by Boobalan-Veerappan** [jsplumb/jsplumb#1155]
![jsplumb issue with mark](https://user-images.githubusercontent.com/59165625/218382946-13dd6534-d2e2-4e0e-8510-c9c7d94ee75e.PNG)
Hi Everyone,
I have one issue, the jsplumb connectors are overflow the other Element, is any ideas to overcome this issue ? .

**Comment by sporritt** [comment]
There's no support in either the Toolkit or the Community editions to have a connector avoid a node right now. This is something that will be added to the Toolkit edition at some point in the next few months.
