### ISSUE TITLE
Equivalent of ignoreConnectionRemoval

### ISSUE THREAD

**Issue by vanessadnguyen** [jsplumb/jsplumb#1156]
Hi everybody,
In old jsplumb community version, we used to have ignoreConnectionRemoval. I wonder what would be the equivalent one in jsplumb 5.x. Thanks,
Vanessa

**Comment by sporritt** [comment]
"ignoreConnectionRemoval" doesn't ring a bell to me - what did you use it for?

**Comment by vanessadnguyen** [comment]
This is from an old code many years ago in our team's project and it appears at only one place. If it does not ring a bell to  you, it might be some custom boolean that my team came up a long time ago. Thanks.
