### ISSUE TITLE
How to build from source code?

### ISSUE THREAD

**Issue by jpech-tibco** [jsplumb/jsplumb#1157]
I have tried to build by cloning repo an running scriṕt commands from packaga.json but still throwing error. Could you please help mehere.
What node version should I be using, what are the steps for building it from code

**Comment by sporritt** [comment]
you need to run `npm create-distribution` to build everything.

**Comment by jpech-tibco** [comment]
Can you point what node & typescript version are you using please?. Because from build script I can see its using global installed `tsc` an not the one from `node_modules`

**Comment by sporritt** [comment]
i've updated `package.json` to use `npx tsc` now.

**Comment by jpech-tibco** [comment]
Thank you :D

**Comment by LiJiaXv-NCU** [comment]
Can you tell me how to run demo/draggableConnectors/index.html in the repo?  I clone the repo and run 'npm install'. when i try to run 'npm build', it throwed errors. Then i try to open demo/draggableConnectors/index.html but failed.

**Comment by sporritt** [comment]
The demonstrations are all on github individually:

https://github.com/jsplumb-demonstrations/draggable-connections

**Comment by LiJiaXv-NCU** [comment]
Thank you :D
