### ISSUE TITLE
Endpoint.setAnchor from jsplumb community version 2.15.6 to jsplumb/browser-ui version 5.13.2

### ISSUE THREAD

**Issue by vanessadnguyen** [jsplumb/jsplumb#1158]
Hi,
I tried to migrate my code from jsplumb community version 2.15.6 to jsplumb/browser-ui version 5.13.2. We have code that called Endpoint.setAnchor which used to accept an array of numbers in the old jsplumb community version 2.15.6

```
// connection is JSPlumbConnection
// startPercent is an array of numbers such as [8.206666666666667,8.761904761904763]
// endPercent is an array of numbers also.
connection.endpoints[0].setAnchor(startPercent);
connection.endpoints[1].setAnchor(endPercent);
```
How do we do the same thing in version 5?
In version 5, AnchorSpec does not accept array of numbers:
`setAnchor(anchorParams: AnchorSpec | Array<AnchorSpec>): Endpoint;`

I am having urgent deadline. Any help is greatly appreciated. Thanks.

**Comment by sporritt** [comment]
`AnchorSpec` is:

```
export declare type AnchorSpec = SingleAnchorSpec | Array<SingleAnchorSpec>;
```

`SingleAnchorSpec` is:

```
export declare type SingleAnchorSpec = AnchorId | FullAnchorSpec | ArrayAnchorSpec;
```

and `ArrayAnchorSpec` is

```
export declare type ArrayAnchorSpec = [number, number, AnchorOrientationHint, AnchorOrientationHint, number?, number?];
```

So if that's an exact example you're using (`[8.206666666666667,8.761904761904763]`) then I guess you at least need to provide values for the orientation hints.

https://docs.jsplumbtoolkit.com/community/apidocs/common.arrayanchorspec
https://docs.jsplumbtoolkit.com/community/apidocs/common.anchorspec
https://docs.jsplumbtoolkit.com/community/apidocs/common.singleanchorspec

**Comment by vanessadnguyen** [comment]
Ah. I missed the ArrayAnchorSpec. Thanks!
