### ISSUE TITLE
How to dynamically create an endpoint at a custom location on a div?

### ISSUE THREAD

**Issue by newbiemate** [jsplumb/jsplumb#1160]
Hello all, I have an interesting question if anyone could help.

I have two html divs, one is the main content div (yellow), and the other is just for *initializing* jsplumb connections (pink). From the pink div the user can drag an arrow connection out of it, however the hard part is determining how I can BEGIN the connection from the area where the user first clicked on the pink div.

An example of what I'm trying to do:

![aa](https://user-images.githubusercontent.com/34783617/229270494-35b0f5a9-e21d-4b1f-99c1-514b2d64c7ca.png)

Basically _anywhere_ the user begins dragging their mouse from the pink div, a connection will appear and originate near the point of click. The three images above shows the user dragging from different position on the pink div.

And once the user makes a full connection, the source endpoint will sit on the parent div (yellow div) and **NOT** on the pink div:

![bb](https://user-images.githubusercontent.com/34783617/229270624-09b00e68-c2bd-40f2-9768-18eb0913a125.png)

And the user can make any number of connections, resulting in many endpoints spaced out on the parent yellow div (as seen in the second image above, where there's 3 source endpoints).

-----

On my first attempt, I thought maybe instead of creating the second pink div, I could just create a `Rectangle` source endpoint that spans across the entire div:

![cc](https://user-images.githubusercontent.com/34783617/229271708-aa176377-e524-417d-9da5-c84004f87cfa.png)

However you can see the problem is that the source endpoint doesn't spawn an arrow where the user initially clicked (right side). Instead the arrows spawns in the center of the endpoint.

-----

Some sample code I've been playing with:

```
<html>
<head>
</head>
<body>
    <div class="container">
        <div id="canvas" style="position:relative">
            <div id="node1" style="position:absolute;width:100;height:100;border:1px solid black;"></div>
            <div id="node2" style="position:absolute;width:100;height:100;border:1px solid black;">                
                <div id="pink" style="position:absolute;width:10;height:90;background-color:pink;top:5;left:-10"></div>
            </div>
        </div>
    </div>


    
    <script src="jsplumb.bundle.js"></script>
    <script>

        var instance = window.j = jsPlumbBrowserUI.newInstance({
            maxConnections:-1,
            dragOptions: { cursor: 'pointer', zIndex: 2000 },
            endpointHoverStyle: { fill: "orange" },
            hoverPaintStyle: { stroke: "orange" },
            endpointStyle: { width: 20, height: 16, stroke: '#666' },
            endpoint: "Rectangle",
            anchors: ["TopCenter", "TopCenter"],
            container: canvas,
            connectionOverlays:[
                {
                    type:"Arrow",
                    options:{location:1}
                }
            ]
        });

        var exampleEndpoint = {
            endpoint: "Rectangle",
            paintStyle: { width: 10, height: 100, fill: "black" },
            source: true,
            reattach: true,
            connectorStyle: {
                strokeWidth: 5,
                stroke: "black",
            },
            target: true
        };

        var dd1 = document.getElementById('node1');
        var dd2 = document.getElementById('node2');

        instance.addEndpoint(dd1, { anchor: "Right" }, exampleEndpoint);
        instance.addEndpoint(dd2, { anchor: "Right" }, exampleEndpoint);

    </script>
</body>
</html>
```

Which will contain the following:
![image](https://user-images.githubusercontent.com/34783617/229272073-99e4677f-75d3-4f6c-934a-f6dc2ed32867.png)

I'm very new to jsplumb, and so my intuition isn't really there yet with how I can achieve this effect. 

Does anyone know how I can connect these pieces together? The part that's really causing confusing is how I can tell jsplumb to create the endpoint near where the user clicked on the pink div, and once a connection is made, disappear the original endpoint and connection, and create one on the parent (yellow) div as the final one.

**Comment by sporritt** [comment]
You might be looking for "position finders" ?

https://blog.jsplumbtoolkit.com/2022/02/10/anchor-position-finder/

**Comment by sporritt** [comment]
...hmm actually you might _not_ be looking for that. I think this is just a case of adding a source selector that identifies the pink part of your element:

```
instance.addSourceSelector("[data-jtk-managed] .pink",{})
```

So here I've said "make any element that has a class of 'pink' and is a child of a managed element into a connection source".

I don't know if you just did it for the purposes of this issue, but you should avoid using `id` for anything that you're not 100% certain is going to be unique in the DOM.:

```
<div id="node2" style="position:absolute;width:100;height:100;border:1px solid black;">                
  <div id="pink" style="position:absolute;width:10;height:90;background-color:pink;top:5;left:-10"></div>
</div>
```

If you rewrite this as :

```
<div id="node2" style="position:absolute;width:100;height:100;border:1px solid black;">                
  <div class="pink" style="position:absolute;width:10;height:90;background-color:pink;top:5;left:-10"></div>
</div>
```

it will work with the code snippet above
