### ISSUE TITLE
Community Edition demonstrations page is broken

### ISSUE THREAD

**Issue by eriknyk** [jsplumb/jsplumb#1170]
Demostration page is broken

![image](https://github.com/jsplumb/jsplumb/assets/205721/23167dfa-0ca6-4bee-bc07-27b2943ea380)

**Comment by sporritt** [comment]
fixed

<img width="1141" alt="image" src="https://github.com/jsplumb/jsplumb/assets/262720/7ad06a3a-8f68-4726-9a05-f5b20dc32326">
