### ISSUE TITLE
I am unable to install @jsplumbtoolkit/browser-ui-angular@latest in angular.

### ISSUE THREAD

**Issue by Faizi9321** [jsplumb/jsplumb#1175]
Hi, 

I hope all is good. I am try to install JsPlumb for angular but its not allowed me to do that. when i install @jsplumbtoolkit/browser-ui-angular@latest this in angular its give me this error....

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jsplumbtoolkit%2fbrowser-ui-angular - Not found
npm ERR! 404
npm ERR! 404  '@jsplumbtoolkit/browser-ui-angular@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Local\npm-cache\_logs\2023-08-19T12_02_08_716Z-debug-0.log

thanks in advanced if some one help regarding this.

**Comment by sporritt** [comment]
This repository is for the Community edition. The Toolkit is not in the public NPM repo. If you are an evaluator or licensee you can email support@jsplumbtoolkit.com. This issue will be deleted at some stage.
