### ISSUE TITLE
Avoiding shortest path between objects on same axis while using flowchart

### ISSUE THREAD

**Issue by Dwarfex** [jsplumb/jsplumb#119]
Connectors in flowcharts should clear elemtens by "stub" lenght when there is a direct connection between them and if the have the same X or Y axis.

Current behavior : dark blue
Enhanced behavior: red 

![Shortest Path](https://f.cloud.github.com/assets/721721/1406768/156e6900-3d5a-11e3-8c91-443c147979dd.JPG)

Topic was also discussed here: https://groups.google.com/forum/?fromgroups=#!topic/jsplumb/EJVdXg79nYA

**Comment by 304NotModified** [comment]
:+1:

**Comment by sporritt** [comment]
This will not be added to the Community edition.
