### ISSUE TITLE
enhancement: create endpoint at makeTarget initialization

### ISSUE THREAD

**Issue by sporritt** [jsplumb/jsplumb#122]
as discussed here:

https://groups.google.com/forum/#!topic/jsplumb/yV0_5GS8r_o

the requirement is to make an element a target (with a unique endpoint), but to show the endpoint at init time, so the user can see it's a target.

**Comment by ibitlab** [comment]
@sporritt Looks like this is already implemented with undocumented property **createEndpoint**:
`makeTarget({..., deleteEndpointsOnEmpty: false, createEndpoint: true})` 
but there is issue, steps to reproduce:
- drop connection on Target component(not Endpoint)
- then Detached it from Target Endpoint.

Result:
 Target Endpoint deletes, even if we set `deleteEndpointsOnEmpty: false` in _makeTarget_

But this I was resolved in the https://github.com/jsplumb/jsplumb/pull/870, Could you please review it? Thank you in advance.

**Comment by sporritt** [comment]
closing this, as `makeTarget` was removed from 5.x.
