### ISSUE TITLE
Rendering issues when updating large number of nested elements' positions

### ISSUE THREAD

**Issue by Greeng0** [jsplumb/jsplumb#137]
I have an app in which I have several draggable and resizeable tables, each containing fields which can be connected to fields in other tables. I've noticed that when I have a large number of connections coming out of a single table, the endpoint positions seem to not all be updated after resizing that table. This fiddle demonstrates the issue: http://jsfiddle.net/7e9Ea/

The problem can be reproduced by doing the following:
- Expand the Product Category table (near the center of the canvas) by clicking on the "+-" button on its right side.
- Resize the table with the handle on its bottom-right corner to take up the space beneath and to the right of the table.
- By this point there should be some connections whose endpoints are floating in the middle of the table, rather than the left or right sides, where the anchors are placed.
- Resize the table again, this time shrinking it, to see the endpoints floating to the right of the table as in the screenshot below.

jsPlumb still seems to know where the connections should be placed, since when you hover over them with the mouse they re-position themselves to an actual anchor.

Also I apologize for the large amount of code, most of it is just to re-position connections from a field to its table (and vice versa) when the table is collapsed, or the field is scrolled out of view.

![plumb bug](https://f.cloud.github.com/assets/1999393/1656186/ff1047a4-5b6e-11e3-998b-6521df9b7fdd.png)

**Comment by MikeSam** [comment]
@Greeng0 I know this is old issue, sorry. But did you found a solution? 
We have the same task, need some kind of visual data mapper.

**Comment by Greeng0** [comment]
@MikeSam I did not, unfortunately. Since it was a minor enough issue that didn't affect functionality, and no end-user ever complained about it, we never put any more effort into resolving it.
