### ISSUE TITLE
Bezier connector control points sometimes incorrect (may be switched source to target)

### ISSUE THREAD

**Issue by santanubasu** [jsplumb/jsplumb#318]
It looks like in some circumstances the computation of bezier control points is not done correctly.  For example, if I have a source endpoint at [0, 100] and target at [100, 0], and the orientation vector for the source is [0.5, 0.5], while that for the target is [-1.0, 0], the connector will not exit the source at 45 degrees below horizontal, nor will it enter the target at 180 degrees.  In fact, the control points appear to be reversed.  

Rewriting two functions (both part of Bezier) fixes this, but not sure if it breaks other things.:

```
    this._findControlPoint = function(point, sourceAnchorPosition, targetAnchorPosition, sourceEndpoint, targetEndpoint) {
        var cp = [];
        var so = sourceEndpoint.anchor.getOrientation(sourceEndpoint);
        var to = targetEndpoint.anchor.getOrientation(targetEndpoint);
        cp[0] = point[0]+majorAnchor*so[0];
        cp[1] = point[1]+majorAnchor*so[1];
        return cp;
    };
    this._compute = function(paintInfo, p) {
        var sp = p.sourcePos,
            tp = p.targetPos,
            _w = Math.abs(sp[0] - tp[0]),
            _h = Math.abs(sp[1] - tp[1]),
            _sx = sp[0] < tp[0] ? 0 : _w,
            _sy = sp[1] < tp[1] ? 0 : _h,
            _tx = sp[0] < tp[0] ? _w : 0,
            _ty = sp[1] < tp[1] ? _h : 0,
            _CP = this._findControlPoint([_sx, _sy], sp, tp, p.sourceEndpoint, p.targetEndpoint),
            _CP2 = this._findControlPoint([_tx, _ty], tp, sp, p.targetEndpoint, p.sourceEndpoint);

        _super.addSegment(this, "Bezier", {
            x1:_sx, y1:_sy, x2:_tx, y2:_ty,
            cp1x:_CP[0], cp1y:_CP[1], cp2x:_CP2[0], cp2y:_CP2[1]
        });
    };
```

**Comment by sporritt** [comment]
i'd need to see some example code for this.  maybe you could put together a jsfiddle.

**Comment by santanubasu** [comment]
Definitely, here you go: http://jsfiddle.net/L566hv5g/3/

This is using more recent code than when I saw this in my project, but I think the issue is the same.

Excellent library btw, I have done some pretty cool stuff with it.

**Comment by sporritt** [comment]
@santanubasu just got a moment to look at this; i'd like to get it into 1.7.5 which i am releasing soon.

there is an annoyingly cryptic comment in the the `_findControlPoint` function that seems to indicate that it _causes_ the bug you reported on purpose:

```
// determine if the two anchors are perpendicular to each other in their orientation.  we swap the control
            // points around if so (code could be tightened up)
```

"code could be tightened up", yes, good one.

i see in your rewrite you basically removed that stuff. i need to try to figure out what my reasoning for doing that was...

**Comment by sporritt** [comment]
oh and i've updated the fiddle for 1.7.4...

http://jsfiddle.net/L566hv5g/4/

**Comment by santanubasu** [comment]
@sporritt Yes I thought so too re: _findControlPoint, but I assumed there was some original reason for writing it that way.  But if it turns out that my removal of that code doesn't break anything else, then that would be great.  FWIW, I've been running the patched version locally for a few months, and didn't encounter any issues with it for what I'm doing.

**Comment by sporritt** [comment]
This - from the draggable connections demo - appears to be what i was talking about:

![image](https://cloud.githubusercontent.com/assets/262720/6883251/eba1e4e2-d5f8-11e4-9db8-a1f4b2ee5a72.png)


tha's what happens when i take out the block of code that switches the orientation. I'll take a look and see what's going on.

**Comment by sporritt** [comment]
(it should look like this)

![image](https://cloud.githubusercontent.com/assets/262720/6883263/2b2246f2-d5f9-11e4-98cb-bb43e40d363e.png)

**Comment by sporritt** [comment]
i tried your rewrites. It looks pretty good, with a few minor differences here and there from how the connectors currently paint, but probably not enough to bother people.

This situation, though, is probably not the best:

![image](https://cloud.githubusercontent.com/assets/262720/6884906/9ed61944-d652-11e4-8ba1-2b5446ad8041.png)

It only happens when the two endpoints are in close proximity. I wonder if in fact the solution to that issue would be to have only a single control point in the curve below some threshold.

**Comment by santanubasu** [comment]
The single control point I think would work, but it would mean some sort of jump discontinuity when moving elements progressively closer, if I understand what you are suggesting.  Another option might be to introduce normalized bezier points (or normalized curviness option).  By this I mean, if a certain option is set by the calling code, the curviness/control points would be recomputed based on the rectangle with opposing corners at the two endpoints being connected.  Instead of specifying curviness=150 (px), the option would be, for example, curviness=0.2.  As the elements were moved closer, this would gradually collapse the control points to coincide with the endpoints without a discontinuous jump.  But, not sure how difficult this is to implement throughout the codebase.

**Comment by sporritt** [comment]
i remembered late yesterday this PR that I have been meaning to look at for some time now:

https://github.com/sporritt/jsPlumb/pull/41

Which is perhaps the best solution of all. I havent tried it yet, and given that it is not backwards compatible it'd have to be on a switch (or at least if it became the default then the current behaviour should be switchable).

**Comment by sporritt** [comment]
...of course this is what you are talking about above.

**Comment by sporritt** [comment]
I'm going to move this to 2.0.0 and have a proper think about what solution to implement.

**Comment by santanubasu** [comment]
Sounds good, thanks
