### ISSUE TITLE
hide connections issue

### ISSUE THREAD

**Issue by hopewise** [jsplumb/jsplumb#400]
I am working on trees, a node in a tree can be collapsed, thus, connections of all sub nodes shall be hidden.

I've noticed that jsPlumb.hide works well only if target and source exist in the DOM, otherwise, for example, if source is removed from DOM ( a child of a collapsed node ) then the connection will not be hidden, but will be rendered as if the source moved to the top left corner.

Please check those two snapshots:

Node 640 has nested connected nodes:
![image](https://cloud.githubusercontent.com/assets/1061157/8477048/a4a8a68a-20cf-11e5-81fb-3cab2c6181a0.png)

If node 640 get collapsed, its sub nodes get removed from DOM, jsPlumb.hide("n640") results into:
![image](https://cloud.githubusercontent.com/assets/1061157/8477025/7f1e19a4-20cf-11e5-896b-0cd4ad56b1e2.png)

Notice that node 640's connection is hidden properly because the node was not removed from DOM, but its sub nodes connections are not properly hidden. 

Any help is greatly appreciated!

**Comment by Reviz13** [comment]
im on the same issue as you :( @sporritt  can u help us  ?

**Comment by sporritt** [comment]
i think you'd need to find the children manually and hide them. jsplumb doesn't recurse from some node into its children and apply a `hide`.  It could, right. But then when you `show` that parent do you want it also to automatically show any connections to children? Perhaps not.  So this is something you'd be best off writing a helper function for.
