### ISSUE TITLE
[Performance] Dragging becomes slower after some time (Tested in chrome)

### ISSUE THREAD

**Issue by magestican** [jsplumb/jsplumb#407]
I am currently using your library with almost the exact code from your demo with the dynamic flowchart.

What I have found is that after dragging an element linked to another, constantly for 20 or so seconds everywhere, it starts to get slower, as in there is a lag within my cursor and the movement of the element.

What I have also found is that by removing the link (clicking in the center of the connector) so that the line goes away, and re creating it, takes the performance back to the start (very fast).
 code from your demo with the dynamic flowchart.

What I have found is that after dragging an element linked to another, constantly for 30 or so seconds everywhere, it starts to get slower, as in there is a lag within my cursor and the movement of the element.

What I have also found is that by removing the link (clicking in the center of the connector) so that the line goes away, and re creating it, takes the performance back to the start (very fast).

Any ideas? Would you recommend me to re-create links by code after a while to improve performance?

Best regards, Bryan.

**Comment by magestican** [comment]
itt also happens here  

https://jsplumbtoolkit.com/demo/dynamicAnchors/dom.html

**Comment by magestican** [comment]
It is not related to calculating the borders since I commented the following code which moves the anchors' position and there are no  performance changes

if (recalc && this.anchor.isDynamic && this.connections.length > 0) {
                            console.log("paint")
                            var c = findConnectionToUseForDynamicAnchor(this, params.elementWithPrecedence),
                                oIdx = c.endpoints[0] == this ? 1 : 0,
                                oId = oIdx === 0 ? c.sourceId : c.targetId,
                                oInfo = _jsPlumb.getCachedData(oId),
                                oOffset = oInfo.o, oWH = oInfo.s;
                            anchorParams.txy = [oOffset.left, oOffset.top];
                            anchorParams.twh = oWH;
                            anchorParams.tElement = c.endpoints[oIdx];
                        }

**Comment by magestican** [comment]
Checking for cpu usage, the tab itself takes 1% cpu when idle, when I start draging the object, the more I drag it the more the cpu increases, up to about 15%, but this process is very slow the first time.

But the second time, it goes straight from 1% to 15% and stays there as long as I drag..So I am assuming there are some objects being stored which increase a for loop over the lifetime of the anchor which is cleaned when I delete the anchor.

**Comment by sporritt** [comment]
closing as this issue is not reproducible in 5.x.
