### ISSUE TITLE
jsPlumb.bind('connectionDetached') connection information .targetId inconsistency

### ISSUE THREAD

**Issue by cneuro** [jsplumb/jsplumb#443]
When cancelling a Connection a connection programmatically (e.g. in an Endpoint's `beforeDrop` or `onMaxConnections` callback), the `targetId` in the instance's `connectionDetached` callback is different than expected.

To replicate:

``` javascript
jsPlumb.instance.addEndpoint(someElement, {
  'beforeDrop': function (info) {
    return false;
  }
});

jsPlumb.instance.bind('connectionDetached', function (info) {
 console.log(info.targetId);

  // after detaching Connection manually:
  // info.targetId === the source Element's jsPlumb DOM ID

  // after programmatically cancelling a Connection:
  // info.targetId === the source Endpoint's dragid DOM attribute
});
```

This seems like a strange, arbitrary inconsistency. Or am I missing something? Also, is this linked to #440?

**Comment by sporritt** [comment]
In issue #440 you pointed out that the detach event should not be fired if beforeDrop returns false. that is fixed; how is it that you come to be reporting this issue?  you shouldn't be getting that callback if beforeDrop returns false.

**Comment by cneuro** [comment]
Sorry for not being clear. in 2.0.0, the `beforeDrop` event bubbling is indeed fixed, I shouldn't have referred to that issue.

This should be in reference to the connection info passed to other interceptors like `onMaxConnections`, and why the `connection.targetId` doesn't refer to the Element it's been attempted to connect to, but rather the source Endpoint's `dragid` attribute (not even its `elid` attribute). So this is more a clarification of that particular circumstance, and making sure it's not a potential bug.

Thanks for your time on this.

**Comment by sporritt** [comment]
Closing this - it's 6 years old and that version of the codebase is now frozen.
