### ISSUE TITLE
the attribute 'maxConnections' in makeSource do not work

### ISSUE THREAD

**Issue by daskyrk** [jsplumb/jsplumb#444]
In the demo 'statemachine',each element can have more than 5 connections

And another problem,in the doc charpter 'Connection',in the function 'makeTarget' :  

```
onMaxConnections:function(params, originalEvent) {
  console.log("user tried to drop connection", params.connection, "on element",params.endpoint.element, "with max connections", params.maxConnections);
}
```

but the object 'params.endpoint' has no attribute named 'element',

I don't understand this,is there anything i ignored?

**Comment by daskyrk** [comment]
thx for your replay,so is there any attribute can control the sourceNode's maxConnection?
And the doc also have to be updated;

**Comment by sporritt** [comment]
i missed the doc update. leaving this issue open to track that.

**Comment by sporritt** [comment]
closing as 2.x is not supported.  this does work in 5.x though.
