### ISSUE TITLE
why my  svg scroll

### ISSUE THREAD

**Issue by sdrabb** [jsplumb/jsplumb#448]
hi thank's for your library, i've got a question:

when i scroll the page my svg scroll a little why?
here an example:

![before](https://cloud.githubusercontent.com/assets/15050464/10754638/3ff32af0-7c99-11e5-85ce-7582c5742401.png)

after scroll my page all the lines scroll:
![after](https://cloud.githubusercontent.com/assets/15050464/10754699/a7b610f8-7c99-11e5-8ac9-4324c89b2912.png)

why this happen? how i can solve it?

**Comment by sporritt** [comment]
without a jsfiddle it's kind of hard to diagnose.  can you put one together to replicate the issue?

**Comment by sdrabb** [comment]
i can pass the link of my site ok? ... it's too hard put all the code in jsfiddle...

**Comment by sporritt** [comment]
if you're happy to do that, sure.

**Comment by sdrabb** [comment]
i'm uploading my code on server wait me please, thank's for now.

**Comment by sdrabb** [comment]
here the link: 
try to draw a room and scroll the page please
http://whitelight.altervista.org/serverSide/merciai/editorMuseum/editorMuseum.php

**Comment by sporritt** [comment]
...i never got around to this. that site is no longer there. closing.
