### ISSUE TITLE
JsPlumb 1.7.10 IE8 compatibility

### ISSUE THREAD

**Issue by pabloaxeitosvalino** [jsplumb/jsplumb#463]
Hi, 
Documentation specify JsPlumb 1.7.10 supports IE8, however I have a working example with this version running in IE11 and executing in IE8 I get a javascript error  (object doesn't support this property or method) calling the "connect" method to try to create a connection.

Even the demo examples includes in 1.7.10 TAG seemed to fail when I test them in IE8...Please let me know if i am missing something.

Regards,
Pablo.

**Comment by sporritt** [comment]
closing. all versions prior to 5.x are now unsupported.
