### ISSUE TITLE
Nested or inner DIVs, multiple points

### ISSUE THREAD

**Issue by Cat4D** [jsplumb/jsplumb#47]
It would be good to expand this tool with the ability to include multiple connection points, interior or nested DIVs as targets, providing the opportunity to "route" or connect to outer boundaries or specific control points as divs on a perceived container, then continue that spline into the specific local inner div or span inside the div container. An example would be "a document"/references/number3 where document's references would be a heavy connection for all references, but then continuing that onward to the div/span for the interior text, image, or reference. This would include handling situations where the DIV is a scroll box and its main connection point may be a corner, (which connects to other boxes or documents similar) which then connects to the internal div as a continuation of the spline for whatever specific internal reference pointer, hidden in the div layer of the scrool box. (which otherwise would be directly linked somewhere in its hidden buffer)

**Comment by sporritt** [comment]
I think this is what the 'groups' stuff does, more or less. Perhaps more less than more.  

https://jsplumbtoolkit.com/community/demonstration/groups
