### ISSUE TITLE
Issue with the beforeDrop event

### ISSUE THREAD

**Issue by blackshadev** [jsplumb/jsplumb#479]
I used the beforeDrop event on a jsPlumb instance to check whenever the connection can be made (to prevent loops in my graph). In earlier versions of jsPlumb I used the return value of the `beforeDrop` event. 

But in version 2.0.x I encountered the issue where if I dragged an already made connection to a invalid target endpoint (and the beforeDrop would return false), jsPlumb raises an internal error: `jsPlumb function failed : TypeError: Unable to get property isDetachAllowed' of undefined or null reference`.

I have traced the issue to jsPlumb.js:7784 `if (!jpc.isDetachAllowed(jpc) || !jpc.endpoints[idx] ||  !jpc.endpoints[idx].isDetachAllowed(jpc) || !jpc.suspendedEndpoint.isDetachAllowed(jpc) || !_jsPlumb.checkCondition("beforeDetach", jpc))` 
where idx is set to -1 after the second time it passes trough. My guess is that jsPlumb destroys the connection on the first run, and when it tries to reconnect it to the old (valid) state it fails.

Is there a new way to check whenever a newly created connection  is valid before actually connecting the 2 endpoints or is this a bug in jsPlumb?

**Comment by nickpersad** [comment]
Did you ever find a solution to this?

**Comment by blackshadev** [comment]
No I haven't. I don't have the knowledge about the JsPlumb to slove this issue. To be honest, I don't know if this issue is still present in the latest version.

**Comment by nickpersad** [comment]
It is. I am having this problem.

**Comment by lliiuu** [comment]
hello,I am having this problem. Whether to solve the problem

**Comment by sporritt** [comment]
2.x is no longer supported. closing.
