### ISSUE TITLE
Triggering click event after drag event on Nodes

### ISSUE THREAD

**Issue by ghost** [jsplumb/jsplumb#482]
I have subscribed click event for nodes example

```
$('.node').click(function(e){ 
  //this event triggering after dragging
});
```

and 

```
instance.connect({
  source: 'node1',
  target: 'node2'
});
```

HTML

```

<div class='node' id='node1'></div>
<div class='node' id='node2'></div>
```

why click event is triggering after dragging each nodes?
I want to prevent this behavior.

**Comment by pnkapadia6** [comment]
Any updates on this issue? I'm having the same problem

**Comment by aeolusheath** [comment]
I met a problem , when I click the elment, the drag event is triggered ? anyone  has met the issue?

**Comment by wangjunxin** [comment]
I think the problem is when you want to drag a node, you first should click the node and hold to drag it, so it means you click the node,  the click function will be triggered

**Comment by shuyzhou** [comment]
@aeolusheath I'm having the same problem, did you solve it?

**Comment by aeolusheath** [comment]
@shuyzhou  我是点击触发了拖动事件，你是不是设置了margin，对drag-item。。。我当时把margin去掉了就好了，因为我做了一个实验，就是没在我们项目里面去做一个demo，发现点击不会触发drag event，最后去掉项目里面drag-item的margin，就好了

**Comment by star212** [comment]
![image](https://user-images.githubusercontent.com/1164500/57926422-c7ff1780-78dd-11e9-8f26-cefad805c7e4.png)

**Comment by sporritt** [comment]
You should subscribe to the `tap` event.  As odd as it seems, the `click` event in this case is being fired by the browser, despite the fact that the element has been dragged and a certain amount of time has elapsed between mousedown and mouseup.
