### ISSUE TITLE
Drag/drop connections when endpoints covered by overlays

### ISSUE THREAD

**Issue by chipsenkbeil** [jsplumb/jsplumb#485]
Is there any recommended way to allow drag & drop of connections when overlays are covering the endpoints? I was testing out rendering an index number (1, 2, 3, ...) on top of the endpoints, but it covers up too much and causes it to be impossible for me to connect endpoints.

Is there a setting I can provide to enable drag & drop to also work on top of an endpoint's label? Is there a recommended practice of doing this?

**Comment by lconer** [comment]
You can try to use droppable option for index numbers.
Assign droppable for index and in drop event connect endpoints manually.

```
jsPlumb.droppable(index, {
  drop: funciton(){
    //code
  }
});
```

**Comment by jyywhw** [comment]
the first parameter 'index', how to set value for this?

**Comment by maxfriedmann** [comment]
I solved this issue by adding z-indexes: 
- add a css class to all endpoints that has `z-index: 100`
- add a css class to all labels that has has `z-index: 10`
