### ISSUE TITLE
revalidate is not the same as recalculateOffsets, so it does not work

### ISSUE THREAD

**Issue by Helen1987** [jsplumb/jsplumb#490]
Hello,

I updated to the latest version of **jsPlumb**. I had **jsPlumb 1.7.3** before and used `recalculateOffsets` to update children offsets.
Now it is told to use `revalidate` function instead. I tried it but it does not work correctly in 100% situations.
I checked source code and found an interesting issue. I found that in version **1.7.3** `recalculateOffsets` is the same as `updateOffsetS`:
`_currentInstance.recalculateOffsets = _currentInstance.dragManager.updateOffsets;`
For new version `revalidate` function is similar to what it was before and `_currentInstance.updateOffset` is used inside.
But `updateOffset` and `updateOffsetS` are different, so I do not expect the same behavior. Can you clarify is it a bug or do you expect the same behavior in new version?
My code does not work anymore, so I wonder, is it my fault or framework bug.

**Comment by Helen1987** [comment]
I created [jsFiddle](https://jsfiddle.net/Helen1987/Lr0ur7x3/3/) to clarify my issue.
I have a model with two collection: nodes and collection (both has at least one element by default). Issue occurs when I try to add new item into the `nodes` and add new anchor to it (if I try to add to `collection`, all is ok). 
I have three endpoints as expected, but two of them are collapsed. 
`jsPlumb.revalidate` does not help, although in old version `recalculateOffsets` worked perfectly.

**Comment by Jon-Biz** [comment]
@Helen1987 - Your jsfiddle doesn't run for me. 

I'm experiencing similar issues where DOM manipulation results in outdated offsets, that won't resolve when I call either `recalculateOffsets` or `revalidate` with the updated parent's id. 

If I move a `draggable` dom element which has it's connectors in the wrong place, during the drag the connectors paint in the correct place (with the right offsets), but they jump back to where they were when the drag is over.

**Comment by Helen1987** [comment]
Indeed, new **jsPlumb** version is available, so I updated [jsFiddle](https://jsfiddle.net/Lr0ur7x3/5/).
About your issue, yes, I have the same bug. So far I use `jsPlumb.repaintEverything` in the end of drag operation... it's a performance hit and does not look good, but at least it works

**Comment by Jon-Biz** [comment]
Why not just repaint the parent element in question? Wouldn't that reduce the performance hit?

**Comment by Helen1987** [comment]
Repaint single element will not help. But after your workaround: `jsPlumb.getDragManager().updateOffsets(id)` and then `.repaint(id)` it will.

**Comment by sporritt** [comment]
@Helen1987 i just added the `dragManager.updateOffsets(id)` call to the `revalidate` method, and pushed it to the branch `dev/2.3.3`.  Do you want to try this version (it's built into dist/js/jsplumb.js) and see if it works for you with just using `revalidate` ?

**Comment by sporritt** [comment]
actually i just went ahead and released this, as 2.3.3 and then 2.3.4.  so master has the update.
