### ISSUE TITLE
how to remove all related Elements?

### ISSUE THREAD

**Issue by vicky626** [jsplumb/jsplumb#509]
hi, 

I'm using `jsp.remove $div` to remove an element and all its related connections, but how to remove related elements at the same time? And one thing need to check is if the related element has other `source`, then not remove it. 

Thanks for your reply

**Comment by vicky626** [comment]
@sporritt Could you give me some help for this ?

**Comment by sporritt** [comment]
Closing this out as it's a few years old now.
