### ISSUE TITLE
How to change the source endpoint of a connection when the source element remains the same?

### ISSUE THREAD

**Issue by besslwalker** [jsplumb/jsplumb#513]
I'd like to be able to programmatically change the source endpoint of a connection while keeping the source element the same.

My approach has been to use the jsPlumb instance's setSource method. The call to _set() in this method correctly cleans up the old source endpoint and attaches the new endpoint to the connection. However, the subsequent call to the anchorManager's sourceChanged() method fails to complete the swap. I think this is because the anchorManager's sourceChanged() function thinks nothing needs updating; the originalId and newId it compares belong to the source _element_ rather than the source endpoint and are thus the same.

Thus, the connection gets updated, but the connectionsByElementId cache does not. Further operations relying on this cache talk to the wrong endpoint -- and moreover, it's cleaned-up endpoint that doesn't have most of the expected properties. (The resultant logged errors were quite helpful in tracking this problem down, so thank you for that!)

Is there a better way to do what I want, or am I just pushing the library to do things it isn't really meant to do?

**Comment by sporritt** [comment]
Yes it's really just a case of the API not supporting that at the moment. `sourceChanged` in the anchor manager is indeed targeted at element level, not endpoint level. i don't have any conceptual issue with adding a change endpoint call somewhere in the API.

**Comment by besslwalker** [comment]
Would you mind if I were to work on sending the endpoint IDs to sourceChanged in the situation I outlined? Or were you thinking along the lines of entirely new setSourceEndpoint and setTargetEndpoint methods?

**Comment by besslwalker** [comment]
I don't know how I managed to close this Issue. Wildly clicking about, I suppose. Sorry about that.

I notice that there is a test that looks like it applies to my situation, _jsPlumb.setSource (endpoint). It passes, because it only checks that the connection has been updated, not the connection cache.

This assertion, added to the end of the test, fails:
equal(_jsPlumb.anchorManager.getConnectionsFor(c.targetId)[0][1].original, undefined, "setSource with new endpoint honoured in connection cache");

I believe I have worked out a fix in which setSource() passes this new portion of the test and the behavior of sourceChanged() is unchanged. Would you be interested in taking a look or having me submit a pull request?

**Comment by sporritt** [comment]
ah, that's interesting.  the API seems to have grown to the point where it doesn't all fit into my head anymore.

yes a PR would be cool if you're up for it. thanks!
