### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by Nenos-Hu** [jsplumb/jsplumb#521]
Hello,

I have a page with more than 2000 links built with JsPlumb using this function :

`function createJsPlumbLink(firstEndpoint, uuidSource, anchorSource, secondEndPoint, uuidDestination, anchorDestination) {

```
jsPlumb.addEndpoint(firstEndpoint,
        {
            uuid: uuidSource,
            endpoint: "Blank",
            anchor: anchorSource
        });
jsPlumb.addEndpoint(secondEndPoint,
        {
            uuid: uuidDestination,
            endpoint: "Blank",
            anchor: anchorDestination
        });
jsPlumb.connect({ uuids: [uuidSource, uuidDestination], type: "Con", connector: "Flowchart" });
```

}`

This takes about 30s.

I would like to know if there's a faster way to create these links.
I don't need them to be manually attachable/detachable, just repaintable.

Thanks in advance.

Nenos

**Comment by sporritt** [comment]
do you wrap all of that inside a `batch` ?

```
jsPlumb.batch(function() {
  
    your code

});
```

`batch` suspends painting and only runs a single repaint at the end.

**Comment by Nenos-Hu** [comment]
I just tried it but it doesn't change the outcome.
Thanks.

**Comment by sporritt** [comment]
it would be helpful if you pasted either your code with that change or a jsfiddle. if you put the `batch` inside your `createJsPlumbLink` function then of course it will have made no difference. but i can't tell if that is what you did or not.

**Comment by sporritt** [comment]
(here are the docs about paint performance: https://jsplumbtoolkit.com/community/doc/home.html#performance)

**Comment by Nenos-Hu** [comment]
I put the batch outside my loop, but I will try to fiddle it.

**Comment by Nenos-Hu** [comment]
Here it is, sorry for the delay.
[https://jsfiddle.net/2hj2gbc9/](url)

**Comment by Nenos-Hu** [comment]
Does someone have an idea?

I was thinking about loading the links on the scroll to avoid loading 2000 or more links at the same time but maybe there is an easier way.

**Comment by Helen1987** [comment]
I have the same issue with performance. I add more than 2000 endpoints in a loop, I use `batch` to improve performance but it takes 7-9s to add endpoints, half of the second to add connections and half of the second to repaint. It's too much. Adding one endpoint takes ~4ms, sometimes even more than 10ms.
I thought about adding new method to add several endpoints at once. Can it improve performance somehow? Is there any way to improve addEndpoint method?

**Comment by ssivanatarajan** [comment]
@Nenos-Hu , Found any solution? I am also facing the same issue.

**Comment by sporritt** [comment]
i have a branch i'm working on at the moment which has a few performance enhancements. it isn't ready, i don't know when it will be ready, it'd be great if this issue didn't turn into an "any updates?" fest. it will get released when it's done and then there'll be an update.

for reference i am using a test page that adds 1500 nodes and creates 1500 connections. the current version runs around 8 seconds to render. the branch is at about 2.3 seconds at the moment.

it will be a new major version of jsplumb - 3.0.0. There are several breaking changes (but no loss of functionality).

**Comment by Nenos-Hu** [comment]
Hello,

I replaced this by some less fun but a lot quicker css. I still use jsPlumb where I need some links between draggable items but I have only a few at a time.

Thanks for the good work sporritt :)

**Comment by sporritt** [comment]
i didnt mean to close this.

**Comment by sporritt** [comment]
3.0.0 was skipped, in favour of 4.x, which includes the changes mentioned here. closing this.
