### ISSUE TITLE
dbclick on overlay

### ISSUE THREAD

**Issue by lconer** [jsplumb/jsplumb#525]
Hi

I've got problem with catch dblclick event on custom overlay.
I've added events to overlay constructor, but dblclick doesn't work.

example:
[https://jsfiddle.net/wcnfyy10/5/#&togetherjs=eC2DCi9czS](https://jsfiddle.net/wcnfyy10/5/#&togetherjs=eC2DCi9czS)

In example everything looks ok, in my case, with this same approach it's not working.
Thats only one place in my code where I wanted to catch dblclick

Any advice why it is not working i my code?

**Comment by sporritt** [comment]
closing. old.
