### ISSUE TITLE
Regression in Connection gradients - based on X Axis rather than length of connection

### ISSUE THREAD

**Issue by lhfiedler** [jsplumb/jsplumb#527]
My painter style:

```
this.connectorPaintStyle = {
    lineWidth: 5,
    gradient: { stops: [[0.8, "#225588"], [1, "#558822"]] },
    ConnectionOverlays: [["Arrow", { location: 0.9 }]],
    strokeStyle: "#225588",
    joinstyle: "round"
};
```

The style flips between almost entirely green and then entirly blue depending on the x axis distance between the start and end of the connection.

![image](https://cloud.githubusercontent.com/assets/18379804/15620330/a3dd69b4-2427-11e6-91e4-1dbc3b6a88ac.png)

![image](https://cloud.githubusercontent.com/assets/18379804/15620340/b0fdf2e4-2427-11e6-9e8f-8331eb8e42c3.png)

**Comment by sporritt** [comment]
closing this as gradients were removed in 5.x.
