### ISSUE TITLE
Source Endpoint Click occasionally not firing - thinks it's a drag start and end event

### ISSUE THREAD

**Issue by lhfiedler** [jsplumb/jsplumb#529]
Here's a jsfiddle:
https://jsfiddle.net/larsf/avhzssyo/13/

Below is the log when I start clicking on the source endpoint.  It recognizes the clicks as drag start and end, and sometimes it misses the click events.  Is there a drag threshold?  It seems to be finicky across machines and browsers.

connectionDrag
VM105:144 connectionDragStop
VM105:147 click
VM105:140 connectionDrag
VM105:144 connectionDragStop
VM105:147 click
VM105:140 connectionDrag
VM105:144 connectionDragStop
VM105:140 connectionDrag
VM105:144 connectionDragStop
VM105:147 click
VM105:140 connectionDrag
VM105:144 connectionDragStop
VM105:147 click
VM105:140 connectionDrag
VM105:144 connectionDragStop
VM105:140 connectionDrag
VM105:144 connectionDragStop
VM105:147 click
VM105:140 connectionDrag
VM105:144 connectionDragStop
VM105:140 connectionDrag
VM105:144 connectionDragStop
VM105:147 click
VM105:140 connectionDrag
VM105:144 connectionDragStop

**Comment by lhfiedler** [comment]
When trying to reproduce, connect the source endpoint to the destination endpoint, and then click on the source endpoint.  As see in the my console.logs below, the click never even fired.

(index):140 connectionDrag
(index):144 connectionDragStop
(index):140 connectionDrag
(index):144 connectionDragStop
(index):140 connectionDrag
(index):144 connectionDragStop
(index):140 connectionDrag
(index):144 connectionDragStop
(index):140 connectionDrag
(index):144 connectionDragStop
(index):140 connectionDrag
(index):144 connectionDragStop
(index):140 connectionDrag
(index):144 connectionDragStop
(index):140 connectionDrag
(index):144 connectionDragStop
(index):140 connectionDrag
(index):144 connectionDragStop

**Comment by sporritt** [comment]
this was fixed in 5.x. 2.x no longer supported, closing.
