### ISSUE TITLE
jsPlumb.getConnections({ source, target }); does not returned scoped connections

### ISSUE THREAD

**Issue by yvesgoeleven** [jsplumb/jsPlumb#532]
According to the documentation at https://jsplumbtoolkit.com/community/doc/querying.html

`jsPlumb.getConnections({ source:"mySourceElement", target:["target1", "target2"] });`

is supposed to return `all connections for the given source and targets (return value is a map of scope names to connection lists)`

but this isn't the case, it returns an empty array unless I explicitly specify the scope as well, then it returns the right connection

**Comment by sporritt** [comment]
do you have a jsFiddle demonstrating the issue?

**Comment by chj-damon** [comment]
I encounter the same issue. instance.getConnections({target: targetId}) returns all the exist connections in the scene, but it should just return the connections for the given target.
And I want to ask another question: what's the difference between instance.select() and instance.getConnections() ? the api is almost the same.

**Comment by sporritt** [comment]
`select` returns an object that you can performa bunch of operations on. `getConnections` just returns a JS object.

**Comment by sporritt** [comment]
@chj-damon your issue does not sound the same as the OP's issue.  We will not address more than one thing in a single issue. If you wish, open a separate issue. And please provide a jsFiddle.

@yvesgoeleven the docs should read like this:

```
- Get all connections for the given source and targets (return value is a list if only connections for the default scope exist, otherwise its a map of scope names to connection lists):

jsPlumb.getConnections({
        source:"mySourceElement", 
        target:["target1", "target2"]
});
```

i've updated this for the next release, 2.4.3

**Comment by chj-damon** [comment]
@sporritt sorry for that. I think I've solved my problem. Thank you very much.
