### ISSUE TITLE
Testing jsPlumb using mocha with babel compiler

### ISSUE THREAD

**Issue by ajainarayanan** [jsplumb/jsplumb#543]
Running `import jsPlumb from 'jsPlumb'` through mocha seems to be having issues.

In a normal application,
- `import jsPlumb from 'jsPlumb'` returns proper `jsPlumb` object.
- when run through mocha (with babel) `import jsPlumb from jsPlumb` returns

```
  {
    jsPlumb: {...},
    jsPlumbUtil: {...}
  }
```

Not sure if its an issue with mocha or babel or jsPlumb. Since I am facing the issue only with jsPlumb I am reporting an issue here. If its not a valid jsPlumb issue please feel free to close the issue. Right now as an alternative I am using the require syntax.
##### Note:
- The mocha command I am using is,
  `mocha --require ignore-styles --compilers js:babel-core/register test/.setup.js test/react-dag-test.js` (.setup.js sets up navigator and document objects using `js-dom` node module)
- I am right now using `2.2.0` branch of jsPlumb that supports webpack.

**Comment by sporritt** [comment]
The concatenated jsPlumb exports both `jsPlumb` and `jsPlumbUtil`, yep. Both of those things are available in the browser as static objects. So `import jsPlumb from 'jsPlumb'` should indeed be fine, as you've seen. I havent seen this issue with Mocha. I guess it is caused by jsPlumb exporting a couple of things but I'm reluctant to call it a bug.

**Comment by ajainarayanan** [comment]
@sporritt Thank you for the reply. Is there any workaround for using `import jsPlumb from 'jsPlumb` for mocha? I am not sure if want to change code just for testing.

**Comment by sporritt** [comment]
not that i know of; this is the first I have heard of this. i don't know what causes it...

**Comment by ajainarayanan** [comment]
@sporritt Just to provide an update, this is what I am seeing right now,

```
1. In console mode (mocha running on console)
  import {jsPlumb} from 'jsPlumb'; // === requiring only jsPlumb
works fine.
2. In window mode (running in a browser)
  import jsPlumb from 'jsPlumb'; // === requiring the default as jsPlumb
works fine.
```

Using one in the other environment fails. Possible causes could be that,
-  `jsPlumb` is exporting a default if window object if present and exporting both `jsPlumb` and `jsPlumbUtil` otherwise. I see an occurrence of adding a static `jsPlumb` instance to window object if present. Not sure if that is what is causing the issue. 

Hope this helps a little bit.

**Comment by sporritt** [comment]
i suspect that in 5.x this will not be an issue. Feel free to reopen if that is incorrect.
