### ISSUE TITLE
How to get the old position while dragging?

### ISSUE THREAD

**Issue by takaobaltazar** [jsplumb/jsplumb#545]
Hi everyone,

I am planning to upgrade my jsPlumb version which I am currently using is 1.7.2. But I have an issue with the parameter of jsPlumb draggable.

For my current version (1.7.2) of jsPlumb draggable, It has two(2) parameters which are **event** and **ui** , which I can get the ui.oldPosition.

But for the version of jsPlumb 1.7.6 and up, It has now only 1 parameter and it does not have an oldPosition.

Is there a way on how to get the old Position of drag elements?

**Comment by sporritt** [comment]
closing, very old.
