### ISSUE TITLE
Outline path not being drawn anymore?

### ISSUE THREAD

**Issue by lbssousa** [jsplumb/jsPlumb#555]
I'm trying to set up a connection with outline (with proper outlineStyle/outlineWidth parameters) using jsPlumb 2.1.6, but nothing happens. Inspecting the generated HTML code, I can only see a single SVG path for the connection, not two paths as before (one for the connection itself, and another one for its outline). Investigating jsPlumb code itself, I can't find any statement about drawing the outline path.

How are outline paths handled in this version of jsPlumb?

**Comment by no1youknowz** [comment]
Same for me too.  I've had to revert back to an older release (2.1.0).  

Would be nice if someone can do a jsfiddle for 2.2.6+ thanks.

**Comment by no1youknowz** [comment]
@sporritt any chance you can look at this?

**Comment by sporritt** [comment]
@no1youknowz the changelog tracks breaking changes

https://github.com/jsplumb/jsPlumb/blob/master/doc/wiki/changelog.md

see the entries for 2.2.0.

@lbssousa `outlineStyle` was never supported.  it's `outlineStoke` in 2.2.x+

**Comment by no1youknowz** [comment]
Thank you!  I did go through the code and see one of the changes, however the doc lead me to all of them.

Now it works fantastically!  

Thank you for the library, I was previously using vis.js, which is an excellent library itself, however for the needs that I had.  Your library is unparalleled!

Cheers!

**Comment by sporritt** [comment]
no problem. i will close this out then.
