### ISSUE TITLE
Bug: JsPlumb.removeFromGroup(someElement) completely removing the element from DOM

### ISSUE THREAD

**Issue by soniabhishek** [jsplumb/jsplumb#562]
I was working with groups and created a small working example but as soon as i tried programatically removing the element from group it gets completely removed from the DOM.
I think there is some problems regarding its implementation i am attaching just the glimpse of my code my complete code is on Codepen

```
jsPlumb.draggable(c1_1,{
      stop: function(params){
        console.log("dropped", params)
      }

    });
    jsPlumb.addGroup({
        el:container1,
        id:"one",
        constrain:true,
        anchor:"Continuous",
        endpoint:"Blank",
        droppable:true,
        dragOptions:{
          stop: function(params){
        console.log("dropped", params)
      }
        }
    });
  jsPlumb.addToGroup("one", c1_1)

...

//This is completely removing the element, even if i provide other element suppose c1_2 its also getting deleted from dom
jsPlumb.removeFromGroup(c1_1)
```

Here is my complete code on codepen

[http://codepen.io/myCompleteCode](http://codepen.io/soniabhishek/pen/ozkjry?editors=1010)

I require urgent help as i am stuck with this please help me what am i doing wrong or is there some problem with function implementation in JsPlumb

In the above link remove last line functioncall of removefromgroup to see complete implementation.

**Comment by markhus-aurelius** [comment]
Just incase anyone else stumbles into this issue. It seems the documentation is incorrect as it currently states..

jsPlumb.removeFromGroup(someElement);  _with one param._

Where as, the actual codebase reads as follows.
/**
     * Remove an element from a group.
     * @method removeFromGroup
     * @param {String} group Group, or ID of the group, to remove the element from.
     * @param {Element} el Element to add to the group.
     */
    _jpi.prototype.removeFromGroup = function(group, el, doNotFireEvent) {
        this.getGroupManager().removeFromGroup(group, el, doNotFireEvent);
    };

So yea, you need to pass the group as the first param to get this working correctly.
