### ISSUE TITLE
Impossible to connect a node to a node nested in a group

### ISSUE THREAD

**Issue by joccd** [jsplumb/jsPlumb#568]
Hi,

On this fiddle : https://jsfiddle.net/joccd/z9fgu86w/
- I have a container (target)
- I create 2 nodes : n1 (target) and n2 (source)
- I put n1 in a container
- I want to connect n2 to n1 with my mouse.

As you can see when you release the click the connection is between n2 and the container instead of n2 with n1

In my code I have 

```
j.makeTarget($('#container3'), {
    dropOptions: {
      hoverClass: "dragHover"
    },
    endpoint: ["Dot", {
      radius: 11,
      cssClass: "large-green"
    }]
  })
  j.makeTarget($('#n1'), {
    dropOptions: {
      hoverClass: "dragHover"
    },
    endpoint: ["Dot", {
      radius: 11,
      cssClass: "large-green"
    }]
  })
```

If I switch them it works, any idea ?

Regards,
Joccd

**Comment by sporritt** [comment]
does "if i switch them" mean if you switch the source and target?

**Comment by joccd** [comment]
If I call makeTarget on #n1 first and then makeTarget on #container3 it works.

**Comment by sporritt** [comment]
i can see why this occurs - drop targets are matched by their bounding rectangle to the mouseup event, and in this case of course both the Node and the Group match. In Katavorio, the drag manager, multiple drop is supported but can be circumvented by one drop listener returning true, and that is what the jsPlumb code does. The problem is that if the container is configured as a droppable first then of course it is checked first, and it responds in the affirmative and the connection is made to it.

it seems that the most appropriate solution to this would be for Katavorio to support 'sorting' of droppables. a Group droppable would be given a lower sort index than a Node. i'll take a look in Katavorio and see what can be done.

**Comment by sporritt** [comment]
https://github.com/jsplumb/katavorio/issues/32

**Comment by sporritt** [comment]
an update on this - here's a version of the fiddle that uses the active class and hover class concepts to show what jsplumb is doing

https://jsfiddle.net/z9fgu86w/8/

you can see that both the node and the group are possible drop targets but that as soon as the mouse hovers over the group it becomes active and the node never does. the katavorio issue linked above is done and 0.18.0 has been pushed, and jsplumb 2.2.1 is on a branch with this included.  right now if you were to set a 'rank' on either the group or the node makeTarget calls you could get this to work with 2.2.1, eg

```
j.makeTarget($('#container3'), {
    dropOptions: {
      hoverClass: "dragHover",
      activeClass:"foo",
      rank:-10
    }
  })
```

the default `rank` is zero, which is therefore what the node gets. Higher values take precedence.

I am going to explore ways in which rank could be automatically applied.  on the `makeTarget` call, for instance, does jsPlumb know that this is a group element? i need to check the code to see what it knows or what can be done.

**Comment by sporritt** [comment]
2.2.1 is released now. it sets a rank of `-1` for Groups if the user does not provide one. This will cause them to be ranked after Nodes. Your example fiddle should work with 2.2.1 with the `makeTarget` operations in any order.

**Comment by Cyw1104** [comment]
@sporritt  There is an error in your previous code example. You can not put **rank** in the **dropOptions** object, **rank** must placed in the second param of the **setTarget** method, like this:

```javascript

j.makeTarget($('#container3'), {
    dropOptions: {
      hoverClass: "dragHover",
      activeClass:"foo"
    },
    rank:-10
  });

```

Am i correct?

**Comment by Cyw1104** [comment]
By the way,  this error occurs in version **2.7.15**  when i add a node to a group with the **addToGroup**
method. I don't know why....

**Comment by sporritt** [comment]
what error occurs?

**Comment by sporritt** [comment]
oh and `rank` goes in the `dropOptions`, as i showed it.

**Comment by Cyw1104** [comment]
Let's look into the **makeTarget** method:

```javascript

this.makeTarget = function (el, params, referenceParams) {
            var p = root.jsPlumb.extend({_jsPlumb: this}, referenceParams);
            root.jsPlumb.extend(p, params);
            // p has merged params and referenceParams

          _doOne = function (el) {
                    //.......
                    _makeElementDropHandler(elInfo, p, dropOptions, p.isSource === true, true);
                   //.......
                }.bind(this);
    
};

```

then the **_makeElementDropHandler** method:

```javascript

        var _makeElementDropHandler = function (elInfo, p, dropOptions, isSource, isTarget) {
           //.........
            dropOptions.rank = p.rank || 0;  //HERE IS THE KEY
          //...........
        };

```

**dropOptions.rank = p.rank || 0; **  

This statement can see **p.rank** override **dropOptions.rank**, so if we place **rank** in **dropOptions**, it do nothing.

I hope that I show the code clearly.
