### ISSUE TITLE
consumeStartEvent cannot be set for `_newEndpoint` method.

### ISSUE THREAD

**Issue by cam-stitt** [jsplumb/jsplumb#572]
When i start to drag a connection, it calls _newEndpoint to create a temporary endpoint, however this does not use either the default or inherit params from the original endpoint i selected. This means that I cannot modify the `consumeStartEvent` option, which in turn means that it calls `_consume` every time.

**Comment by cam-stitt** [comment]
This could be partly related to https://github.com/jsplumb/jsPlumb/issues/376 in the sense that all mouse events are being consumed.

**Comment by sporritt** [comment]
Closing as this is very old now. If it's still an issue in 5.x, feel free to reopen, but a little more context on your requirement to modify the `consumeStartEvent` would be helpful.
