### ISSUE TITLE
Remove version number on library file name

### ISSUE THREAD

**Issue by guimaluf** [jsplumb/jsPlumb#573]
Everytime jsPlumb is update I've to change the importation filename, e.g.
`app.import('bower_components/jsPlumb/dist/js/jsPlumb-2.2.3.js')`

Would be good if the specific file was named only `jsPlumb.js`

**Comment by michelboaventura** [comment]
:+1:

**Comment by sporritt** [comment]
this has been discussed a bunch of times on here. it's ok for you to have to be a little bit involved when you change the version of a library on which your application depends.

**Comment by michelboaventura** [comment]
The main idea behind semantic versioning is that you should not worry about changes at the last version's digit. If I need to, for every minor update, change my includes or lock the library version on bower.json it lost its purpose.

Besides, if a new dev clones my repository and there is a new jsplumb version, the project will simply just not work. It adds a new layer of frustration to the newbie (which already needs to grasp a lot of new code) and implies that someone will need to stop his work just to find out the new version, push a change and let everybody else to know. Jsplumb is the only import (out off 30) on my bower.json which does it, and every time a new dev joins the project I need to give my default speech: Welcome to the project and be careful with jsplumb, it will probably break your repo when you 'bower install'.

**Comment by guimaluf** [comment]
Seriously, if it was discussed so many times why do you insist in keep this way? Many issues have been raised upon this subject(#462 #331 #436 #426 #432) and you seem to be the only one that push  this versioning scheme.

Maybe you should consider what your users are saying.

**Comment by sporritt** [comment]
https://github.com/jsplumb/bower-jsplumb

**Comment by sporritt** [comment]
@michelboaventura what is the project you use jsPlumb in.
