### ISSUE TITLE
jsPlumb 2.2.5 KO - Where is Mottle?

### ISSUE THREAD

**Issue by sguiheux** [jsplumb/jsPlumb#575]
Hi,

Seems that all Mottle code have disappeared from jsPlumb.js in the 2.2.5 release
https://github.com/jsplumb/jsPlumb/commit/fab212ccce5acbed5e9091a1aaffbc6616ce06cc

**Comment by sporritt** [comment]
try 2.2.6

**Comment by sguiheux** [comment]
That works. :+1: 
Thanks
