### ISSUE TITLE
Wrong file name in bower.json v1.7.10 and v1.7.9

### ISSUE THREAD

**Issue by n2iw** [jsplumb/jsPlumb#576]
In v 1.7.10 bower.json file, main file is "dist/js/dom.jsPlumb-1.7.10.js", however the correct file should be "dist/js/jsPlumb-1.7.10.js". This cause wiredep inject wrong file name in my html file. Same issue with in v 1.7.9.

**Comment by cperreault** [comment]
Why is this issue is closed if no fix have been deployed for it? I don't see v1.7.11. I can confirm that this issue affects our project also. I had to put a < 1.7.9 constraint. Is it a "won't fix" closing? Thanks.
