### ISSUE TITLE
Add cssClass attribute to overlays

### ISSUE THREAD

**Issue by iansoper** [jsplumb/jsPlumb#581]
I would like to see overlays (arrows) to have a class (like endpoints and connections) to be able to style them with CSS.

**Comment by sporritt** [comment]
you can do this already. 

```
[ "Arrow", { cssClass:"foo" } ]
```

**Comment by vishalbiradar** [comment]
@sporritt 
Please help me in this issue https://github.com/jsplumb/jsplumb/issues/714
I have added **cssClass** attribute but the **css is not working**.

```
overlays: [
      ['Label', {label: 'foo', location:0.5, cssClass: 'connectorLabel'}]
 ],
```
style.css
---------

```
.connectorLabel {
    height: 20px;
    width: 110px;
    border-radius: 13px;
    background-color: #B8C5D6;
    color: #FFFFFF;
    text-align: center;
}

```
