### ISSUE TITLE
Putting objects inside bootstrap modal cause line drawing to fail

### ISSUE THREAD

**Issue by carmenbranje** [jsplumb/jsPlumb#584]
If I put my objects inside a bootstrap modal the line drawing fails.

If I do the line drawing, then add the bootstrap modal and fade class, the line drawing work. Seems like the objects need to be visible for the drawing to work? Would be nice if this wasn't the case.

**Comment by sporritt** [comment]
yes they use the offset of the container, which is not set if the container is not visible. this will not change. you can use `repaintEverything` after the dialog opens to do a redraw.

**Comment by Teclogen** [comment]
Created a new instance while opening a Popup and Repainted everything event though points are  not able to plot in Bootstrap Modal Popup

**Comment by sporritt** [comment]
can you provide a codepen or fiddle?

**Comment by Teclogen** [comment]
@sporritt After opening Bootstrap Model Popup EndPoints are creating on back of the popup, not on the popup.
Hope will get a solution
Jsfiddle Link: https://jsfiddle.net/xpvt214o/851858/
Attaching my example code, please Look into that.

[Jsplumb_Popup.html.pdf](https://github.com/jsplumb/jsplumb/files/2424048/Jsplumb_Popup.html.pdf)
