### ISSUE TITLE
animate documentation + implementation 

### ISSUE THREAD

**Issue by Domiii** [jsplumb/jsplumb#585]
**Documentation Issues**

First of all, the documentation for [jsPlumb.animate](https://jsplumbtoolkit.com/community/doc/animation.html) incomplete, ending a list of possible options  with `etc` in three different places, even though there is no other place where you can look up those options. I initially assumed, this is just a wrapper for jQuery's [animate](http://api.jquery.com/animate/) function.

**Implementation Issue: Silent failures**

One particular issue cost me quite a few minutes of debugging time:
The `duration` option requires a numerical argument. You cannot use `slow` or `fast`, even though jQuery supports string-type arguments.

The biggest problem here though is that it fails silently, and I had no idea what went wrong until I actually stepped through the jsPlumb code. A basic sanity check for arguments would be great! :)

**Comment by sporritt** [comment]
closing this. `animate` is not in the API any longer.

I have for a long time had the intention of adding a `sprout` method to jsPlumb though, which would be the same as `connect` but the process of establishing the connection would be animated.
