### ISSUE TITLE
bower registry points to source repo instead of distribution repo

### ISSUE THREAD

**Issue by Toilal** [jsplumb/jsPlumb#589]
Bower registry points to https://github.com/sporritt/jsPlumb.git instead of https://github.com/jsplumb/bower-jsplumb. 

Am I missing something ?

**Comment by Toilal** [comment]
And `2.2.7` tag is missing in the distribution repo.

**Comment by sporritt** [comment]
i dont know if you are missing something or not. that is where it points, yep. that is where jsplumb is. the bower repo exists purely because a whole bunch of people were complaining about having to manually change version numbers. they should have to do that of course, but they dont want to.

**Comment by Toilal** [comment]
Is see. Problem is that the package downloaded by bower doesn't contain bower.json, so tools like wiredep are not able to automatically inject the main js file into the app project.

**Comment by sporritt** [comment]
i see.  how many "tools like wiredep" are there?

**Comment by Toilal** [comment]
In my case I use wiredep.

But I think webpack also rely on the bower.json main properties to create the app package when declaring package from bower (even if npm is prefered over bower for webpack).

Short answer : If you still support bower as a packaging format for jsplumb, `bower.json` file should be present in this repository, and according to [bower.json spec](https://github.com/bower/spec/blob/master/json.md#main), `main` property should have a single entry per file type pointing to a single js source file (concatenated, but not minified).
