### ISSUE TITLE
Question: how do I know which endpoint was picked up?

### ISSUE THREAD

**Issue by OlsonDev** [jsplumb/jsPlumb#592]
Apologies if this is documented but I'm not seeing it anywhere.

### Simplified situation:
I have two kinds of endpoints. They're both sources and targets. One kind has `cssClass` A, the other B. When I drag a connection from an A endpoint, all other A endpoints should hide. Vice versa for B. When I drag an existing endpoint off of a B endpoint, all A endpoints should hide (as A is already "set"). Vice versa if I pick up an A endpoint.

### Problem:
I tried looking at the connection's `floatingEndpoint` to determine which endpoint was picked up (in the `connectionDrag` event). What I think I'm seeing though is floatingEndpoint is always constructed using the connection's source endpoint, not the one being dragged.

### Question:
How do I know which endpoint was picked up? Is there a better way to go about this?

**Comment by DedicatedManager** [comment]
I'm kind of new myself, just happened to see this question.  I may not be fully understanding what you want but...

Can't you use the Uuid of the endpoint to determine which endpoint was picked up?  You can set the Uuid when you create the endpoint.  Something like (possible syntax errors):

jsPlumb.addEndpoint("Your-DOM-ElementId", {
    anchor:"Top",
    uuid: "myIdentifier"
});


jsPlumbInstance.bind("beforeDrag", function(params) {
 params.endpoint.getUuid(); // should return myIdentifier
});

**Comment by DedicatedManager** [comment]
Also, I haven't done it yet, but if you need more of a generic tag for the endpoint to label it as a "type_of_source" it may be helpful to look into using parameters:
https://jsplumbtoolkit.com/community/doc/parameters.html

(but I could be wrong.  Again, I haven't used them yet.)

**Comment by OlsonDev** [comment]
@DedicatedManager Thanks for the suggestions. However, unfortunately, they don't solve my problem. In the `connectionDrag`, `arg0.floatingEndpoint.getUuid()` throws an exception that it cannot read property uuid of null. `beforeDrag` appears to only get called when I'm creating a connection, not modifying one...? Unless I need to bind it to something else.

I'm successfully using `parameters` already; they still won't solve my issue... same thing happens there: Cannot read property 'parameters' of null when I call `arg0.floatingEndpoint.getParameters()`. If I call `arg0.getParameters()`, it's the mixed parameters of `arg0.endpoints[0]` and `arg0.endpoints[1]` (which is expected/desired, but doesn't help figure out which endpoint was picked up by the user).

**Comment by DedicatedManager** [comment]
Ok... sorry I wasn't more help.  You are beyond me with the arg0.floatingEndpoint as I don't know what that is.  Is that a jsPlumb thing?  Or is it part of your code?   Where are you getting arg0 from?  

And I don't see any documentation on floatingEndpoint?  Is that (what would be in another language) a private class variable?   Are you dumping the "params" variable to the console.log and viewing the properties?  Like this:
jsPlumbInstance.bind("beforeDrag", function(params) {
   arg0 = params;
    console.log(arg0)
});

Maybe a jsfiddle may help.

**Comment by DedicatedManager** [comment]
beforeDrag seems to get called only when creating a new connection.  beforeDetach is called instead on a new connection.  (At least that's what I recall).

**Comment by OlsonDev** [comment]
@DedicatedManager By arg0, I just meant the first argument passed to whichever event you're binding to. In `connectionDrag`, it's a connection. In `beforeDrag`, it's more like an event object.

I don't know that `floatingEndpoint` is meant to be private; you can certainly make "real" private variables in JS by using closures effectively. Either way, yeah, it's not documented but it has shown up in a few issues before. When I was inspecting "arg0" in the debugger on several events, it was the only property that looked to have the data I need. Unfortunately, it only does half the time (when the source is picked up, not the target).

![image](https://cloud.githubusercontent.com/assets/308072/21409848/359f02cc-c7a2-11e6-9b07-0f6a3eea4121.png)

In the picture above, I created the connection by click-dragging from "A1" to "B1". Thus, A1 is the source and B1 is the target. Keep in mind A1 and B1 are both capable of being sources or targets; I want the UX to be that you can start from either. However, if you go to reconfigure the connection A1->B2, I have no means to identify you picked up B1 to do that. Thus I can't hide A2 & A3 to signal to the user "these aren't valid drop locations".

So, I can't really put together a jsfiddle to show you what's broken; I more so need someone to give me a jsfiddle to show me how to accomplish this. Or, maybe this is a bug/use-case not currently supported?

**Comment by DedicatedManager** [comment]
Make a jsFiddle that does what your diagram above shows.  

I must be misunderstanding something.  You can get that fairly easy using beforeDetach.  Remember, the interceptor is before the detach, so your picture is above is still the current state.  The beforeDetach function is passed the "params" object, which includes the "sourceId" -  the ID of the DOM element the Endpoint belongs to.  Give that endpoint a html <div id="B1"></div> and you know endpint B1 was picked up.  its "params.sourceId". No?

If you have more than one endpoint on each object you'd have to do a little more work to know which endpoint on that Id was picked up.

Maybe make a jsFiddle of your diagram and I'll see if I can make happen what you need to happen.

**Comment by OlsonDev** [comment]
The problem with `beforeDetach` is it happens when you let the mouse up. I want to hide nodes while you're still dragging. [Here's a codepen](https://codepen.io/OlsonDev/pen/eBoybm) demonstrating the issue.

Fortunately I only have 1 endpoint on each.

**Comment by DedicatedManager** [comment]
Yeah.. I forgot beforeDetach doesn't fire until you let the mouse up.  What you need is to add a "mousedown" event on each of your endpoints right after you create each of them.  And within that "mousedown" event you could hide all the elements for the same class except for the element clicked on.  Then unhide all the endpoints on the "mouseup" event.

Unfortunately, I'm in a similar boat in that "mousedown" does not fire if the endpoint is a source.  
See my issue here: https://github.com/jsplumb/jsPlumb/issues/594

Finally, this is a work-around, but the only other way I can currently think of detecting which endpoint is being moved is to get the position of the endpoints upon entering connectionDrag and do some math to calculate which is closer to the cursor, which will be the endpoint that is being moved.

**Comment by DedicatedManager** [comment]
Take a look at this demo:
https://jsplumbtoolkit.com/community/demo/flowchart/index.html

When you pick up an endpoint, the endpoint that remains gets a pink square around it.  I'd think something is happening there that would allow you to detect the endpoint that was picked up.

**Comment by OlsonDev** [comment]
@DedicatedManager I checked out that demo - it uses the same premise as [this other demo](https://jsplumbtoolkit.com/community/demo/draggableConnectors/index.html): things with the same `scope` enable the `activeClass`. And, of course, I don't think I can get `scope` to work for my purposes...

I could certainly use that workaround as a last resort... :-\

**Comment by OlsonDev** [comment]
I managed to figure it out... in the `connectionDrag` event, I inspected `conn.source` and `conn.target`. Both of them had the `jtk-connected` class so that was useless, and why I looked into `floatingEndpoint`. However, if I inspect `conn.endpoints[0]` and `conn.endpoints[1]`, only one of them has the `jtk-endpoint-connected` class - useful!

Here's my [working codepen demo](https://codepen.io/OlsonDev/pen/BQeyRm).

@DedicatedManager Thanks again for all your suggestions.

**Comment by DedicatedManager** [comment]
Great work!  Glad to see you got your problem solved.

Unfortunately, though, you still don't know which endpoint was picked up, correct?  (which was your original question title)

Also, I've got a few unanswered questions on the google group.  Any help over there would be appreciated.  

Specifically I think you could easily answer this one:
https://groups.google.com/forum/?fromgroups#!topic/jsplumb/p8ziTm9nGf0

This is similar to your "which endpoint" title and the "click" issue above:
https://groups.google.com/forum/?fromgroups#!topic/jsplumb/ehgjbA1LxyI

This one is about updating overlays when a connection is moved:
https://groups.google.com/forum/?fromgroups#!topic/jsplumb/Pdswrdn4ZMU

**Comment by OlsonDev** [comment]
I believe I do know which endpoint was picked up by a simple process of elimination. The connection has at max 2 endpoints, one of them is marked as `jtk-connected` and the other isn't. So, I can say with certainty the non-`jtk-connected` endpoint was picked up.
