### ISSUE TITLE
Which files need to be host

### ISSUE THREAD

**Issue by kennynaoh** [jsplumb/jsPlumb#593]
Hello @sporritt , I am the member of cdnjs project. We want to update this library. There is a question want to ask. I think the main files are under `dist/js/` excluded `demo` and also the `jsplumb.css`. Am I right? Any other dependencies file do we need? Please help me confirm this. Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/10030

**Comment by sporritt** [comment]
hello

you only really need jsplumb.js / jsplumb.min.js. You can get those from the bower jsplumb project as discussed here

https://github.com/jsplumb/jsPlumb/issues/596#issuecomment-268766147

there is a css file that provides some defaults but it is mostly for the Toolkit edition.

**Comment by kennynaoh** [comment]
Thanks @sporritt
