### ISSUE TITLE
Build a file without version pattern

### ISSUE THREAD

**Issue by kennynaoh** [jsplumb/jsPlumb#596]
Hello @sporritt, I am the member of cdnjs project. We want to add the auto-update config to automatically add the file if there is latest release of this library. Would it possible to build the file name without version pattern? Like `jsPlumb-2.2.8.js` -> `jsPlumb.js` and `jsPlumb-2.2.8-min.js` -> `jsPlumb.min.js`. This will be better to automatically add new release file on CDNJS in the future. Thank you!

https://github.com/cdnjs/cdnjs/issues/10030
https://github.com/cdnjs/cdnjs/pull/10039

**Comment by sporritt** [comment]
hello

You can get released files with names that do not have version numbers from the [bower-jsplumb](https://github.com/jsplumb/bower-jsplumb) project.

**Comment by kennynaoh** [comment]
Thanks @sporritt
