### ISSUE TITLE
怎么实现两个步骤属性之间垂直居中对齐

### ISSUE THREAD

**Issue by wwqking** [jsplumb/jsPlumb#598]
我使用改变步骤面板的left，top属性去实现对齐，对齐之后在连线，连线起点还在原来的位置

**Comment by sporritt** [comment]
not speaking Chinese the best I can do with this is use google translate, which says:

```
I used to change the steps panel left, top attributes to achieve alignment, after alignment in the connection, the starting point is still in the original location
```

er, so...not entirely sure.  perhaps you want to call `jsPlumb.revalidate(someElement)` after you have moved it?
