### ISSUE TITLE
How does the "clone" option works?

### ISSUE THREAD

**Issue by joao678** [jsplumb/jsplumb#600]
I'm trying to make some sort of toolbox with elements to be dragged to a jsPlumb container, but the cloned object simply disappears.
Is this a bug? Or do I have to set up a "jsPlumb.droppable" option in the container itself? If so, how do I set it up?
```javascript
jsPlumb.draggable(elem,{
    grid:[5,5],
    clone: true
  });
```

**Comment by WalkerJG** [comment]
Same problem met here. Can anyone help us?

**Comment by WalkerJG** [comment]
I think I have solved this problem. This is not a bug.The reason cloned objects disappear is that you haven't handle the drop event in the container.To set a handler, you may try something like below:

```js

jsPlumb.droppable(workingArea,{
    drop: function(p){
    ///Handle the drop event here. Just a sample.
      var dl = target.offsetLeft - source.offsetLeft,
      dt = target.offsetTop - source.offsetTop;
      p.drag.el.style.left = (p.drag.el.offsetLeft - dl) + "px";
      p.drag.el.top = (p.drag.el.offsetTop - dt) + "px";
      target.appendChild(p.drag.el);
      }
})

```

**Comment by regiszanandrea** [comment]
Same problem here, any news?

**Comment by sporritt** [comment]
@regiszanandrea you saw WalkerJG's last comment?

**Comment by regiszanandrea** [comment]
Hi @sporritt, I'm using Flowchat from https://jsplumbtoolkit.com/community/demo/flowchart/index.html, so where I can use the method droppable from WalkerJG's last comment?

**Comment by sporritt** [comment]
'workingArea' should probably be the div used as the container in that demo.
