### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by wuyannan538** [jsplumb/jsPlumb#603]
If i have two same pictures in a html, the first picture is be connected, but the second picture is not be connected.
`jsPlumbInstance.connect({uuids: value});`
`jsPlumbInstance.connect({ source: $source,target: $target,anchors: ['RightMiddle', 'LeftMiddle']})`
these two methods is not work.

**Comment by sporritt** [comment]
if those two methods really didnt work i think we'd have a lot more than just one issue reported, right? so perhaps you could supply a plunkr or jsfiddle demonstrating your problem.

**Comment by wuyannan538** [comment]
![1](https://cloud.githubusercontent.com/assets/17284634/21759087/770beba6-d67c-11e6-96a1-7bf8b08bba22.png)

this is your demo/chart/dom.html
i add a same container in HTML ,but the second container is not work. And now, i have a same business scene. Maybe the problem is these two container has the same id. how to solve ?

**Comment by sporritt** [comment]
yes, maybe.  give it a different ID?

**Comment by sporritt** [comment]
closing - no updates since a month ago.
