### ISSUE TITLE
How to change svg style after drag?

### ISSUE THREAD

**Issue by jyywhw** [jsplumb/jsplumb#604]
I found that after drag one endpoint, svg style will change to original style 'return "position:absolute;left:" + d[0] + "px;top:" + d[1] + "px";'
The connect line will be cover some dome. 
but I want to add some additional style, like 'z-index: 999'.

How can I do it?

**Comment by sporritt** [comment]
you should just use CSS.

**Comment by jyywhw** [comment]
I have use cssClass with z-index:999, but when drag the endpoint, it can't work.
Could you show how to set css when drag endpoint.

**Comment by sporritt** [comment]
closing this as it's very old now.

for anyone doing a drive-by, docs about CSS classes can be found here:

https://docs.jsplumbtoolkit.com/community/lib/styling-via-css
