### ISSUE TITLE
How can I get the whole data of the all connections and use the returned data to re-render page?

### ISSUE THREAD

**Issue by bq-hentai** [jsplumb/jsPlumb#612]
I want to save the whole data and use the whole data to re-render page, like snapshot.
I looked through the apis but I can't found a good way to achieve this.

Now, the solution I can do is to use jsPlumb.getAllConnections() and save connection info. Then try to deal with info to re-render. 

I am new to jsPlumb now. Does there're an easier method to achieve this? Thx

**Comment by sporritt** [comment]
This is what you have to do with the Community edition. You get the connection info and save the elements yourself, and then recreate the state with those two datasets.
