### ISSUE TITLE
drag the line

### ISSUE THREAD

**Issue by wwqking** [jsplumb/jsPlumb#613]
I want to drag the line, you can provide a way to do it

**Comment by sporritt** [comment]
This is not supported in the Community edition.  We intend to provide this functionality in the Toolkit edition later this year.

**Comment by wwqking** [comment]
What time can we use to provide

**Comment by sporritt** [comment]
We havent got it definitely scheduled yet.  This is not a forum for the Toolkit edition. Are you a licensee? You can email us directly.

**Comment by wwqking** [comment]
I want to buy a licensee,but we need drag the line functionality

**Comment by sporritt** [comment]
unfortunately we do not yet have a release date scheduled for this functionality.

**Comment by wwqking** [comment]
We need this function, can identify a specific date

**Comment by sporritt** [comment]
I'm sorry, no, we really do not have a firm idea right now. Was that you who emailed us a couple of pictures of what you are trying to do?

**Comment by wwqking** [comment]
I want this line can turn

**Comment by sporritt** [comment]
yep. i know!

**Comment by wwqking** [comment]
Can you finish line turning function？







------------------ 原始邮件 ------------------
发件人: "Simon Porritt";<notifications@github.com>;
发送时间: 2017年2月24日(星期五) 上午10:52
收件人: "jsplumb/jsPlumb"<jsPlumb@noreply.github.com>; 
抄送: "拉勾勾"<2223505639@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jsplumb/jsPlumb] drag the line (#613)




yep. i know!

**Comment by sporritt** [comment]
unfortunately we do not yet have a release date scheduled for this functionality.

**Comment by sporritt** [comment]
We're going to put this into version 2.0.0, which we're scheduling for sometime in Q2 2017.

**Comment by BobLuo** [comment]
@sporritt 
you have offical release this functionality? Any demo or ducoment show online?
Thanks
