### ISSUE TITLE
The effect of API in where?

### ISSUE THREAD

**Issue by wwqking** [jsplumb/jsPlumb#614]
![n h zmd2q7 i1pc dygik](https://cloud.githubusercontent.com/assets/20062330/23193382/b2af3814-f8e3-11e6-9ccc-a4d797de7f2c.png)

**Comment by sporritt** [comment]
not _entirely_ sure of the question, but...

https://github.com/jsplumb/jsPlumb/tree/master/demo/flowchart

?
