### ISSUE TITLE
connection bug with group

### ISSUE THREAD

**Issue by SergDi** [jsplumb/jsPlumb#615]
I have an issue with the coordinates of a connection when moving group.
This bug can be seen [demo/groups](https://jsplumbtoolkit.com/community/demo/groups/index.html)
![jsplumb_group_bug](https://cloud.githubusercontent.com/assets/10080433/23354243/e07a62c0-fcd8-11e6-83cb-00ca38537d2d.gif)

**Comment by sporritt** [comment]
this seems to have been fixed as a side effect of the change made for #490 - in which the `revalidate` method also updates the drag manager's offsets.  2.3.3 is on a branch right now but probably will be released in the next day or so.

**Comment by sporritt** [comment]
fixed.
