### ISSUE TITLE
Encountered a big problem when using jsplumb, I really need to turn the line, if you can help me

### ISSUE THREAD

**Issue by wwqking** [jsplumb/jsPlumb#616]
Encountered a big problem when using jsplumb, I really need to turn the line, if you can help me

**Comment by sporritt** [comment]
https://github.com/jsplumb/jsPlumb/issues/613

unless i am mistaken, we already know you want this.

**Comment by wwqking** [comment]
We are very anxious to use this demand, thank you for your help

**Comment by sporritt** [comment]
yes, i can tell. however, i do not seem to be communicating our position clearly enough, so i will try once more. 

we are not doing this right now. there is nothing that can be done to induce us to do this right now.  and when we do this, we do not intend to put it into the community edition anyway.

there is nothing stopping you from having a go at this yourselves. you have all the source for the community edition right here.

**Comment by wwqking** [comment]
If you can provide this function, we are willing to spend money to buy your products

**Comment by sporritt** [comment]
We're going to put this into version 2.0.0, which we're scheduling for sometime in Q2 2017.
