### ISSUE TITLE
Lower case CSS file in npm module

### ISSUE THREAD

**Issue by aurbano** [jsplumb/jsPlumb#617]
The current npm module has the dist css in `/node_modules/jsplumb/dist/css/jsPlumbToolkit-defaults.css`

The fact that it's not lower cased is an issue with some build systems on certain operating systems (usually webpack + linux), and it seems like making it lowercase would be an easy fix that probably wouldn't affect most people.

At the moment we've had to add a post install task to rename it.

**Comment by sporritt** [comment]
@aurbano  really?  I just installed from npm and it's lower case for me. version 2.3.0.

**Comment by aurbano** [comment]
@sporritt well, I don't know what to say - just try again installing with npm and yarn and it's lowercased in both cases...
I can't think of any reason why it may have happened the previous time, so closing this.

Thanks!

**Comment by sporritt** [comment]
thanks for the update. it is possible an earlier version of it had the upper case filename; if you are on a mac sometimes its default of a case insensitive filesystem makes odd things happen.
