### ISSUE TITLE
draggable "grid" option let place elements everywhere, except for [10,10]

### ISSUE THREAD

**Issue by Tilogorn** [jsplumb/jsPlumb#618]
## Example A:

```
myInstanceOfJsPlumb.draggable("elementId", { 
    grid:[10,10] 
});
```

**What works**: The element will snap near multiples of 10. The element can only be dropped on "valid" positions (means multiples of 10)
**What does not work:** -

## Example B:

```
myInstanceOfJsPlumb.draggable("elementId", { 
    grid:[50,50] 
});
```
**What works**: The element will snap near multiples of 50
**What does not work:** The element is repainted at any position and can be dropped at any position

Working example (jsPlumb v1.7.5, but same behaviour in 2.3.0): [jsPlumb Snap to Grid Example](http://www.freedevelopertutorials.com/jsplumb-tutorial/examples/jsplumb-snap-to-grid-example/)
Try it out with `10`, then change it to `20` and use the `update` button

## Assumption

There is a katavorio argument with default "10" which is not overwritten when setting `grid` in `draggable()`.

**Comment by flogo1982** [comment]
+1
I have the same problem.

**Comment by rikvdlooi** [comment]
I had the same problem. I created a pull-request on the jsplumb/katavorio package here: https://github.com/jsplumb/katavorio/pull/33

**Comment by carolqian** [comment]
Same problem here. If you change the grid to 20 in the example. Dragging the items does not snap to grids anymore

**Comment by rikvdlooi** [comment]
I've got no reaction on my PR so far (more than 3 months later). I don't think they are very actively maintaining it. You can use my fork of the katavorio repository with the fix (https://github.com/rikvdlooi/katavorio).

**Comment by sporritt** [comment]
@rikvdlooi I dont think the PR addresses the specific issue the OP was talking about.

**Comment by sporritt** [comment]
fixed in release 2.5.2

**Comment by carolqian** [comment]
Thanks @sporritt for addressing this issue promptly . Now grid size other than 10 is respected!

But it seem to work only for the first time the draggable is initialized.  Let's say, if I want to have the ability to turn on / off the "snap to grid" option.  I initially have the grid size set to 20 and have the following line when the canvas is first loaded -
jsPlumb.draggable("someElement", {grid: [20, 20]} );

And later, user want to drag and drop the items freely anywhere, so they turn off this "snap to grid" option, which trigger the following code I put in the handler, I suppose this will remove the grid constrain.  
jsPlumb.draggable("someElement", {grid: null} );

But somehow, the old grid size is still being used. So it looks like the "grid" value for the draggable cannot be updated. Is this something you can also take a look?

**Comment by sporritt** [comment]
sure

**Comment by sporritt** [comment]
wait...you mean that's the same element each time? no that won't work like that.

**Comment by carolqian** [comment]
Understand. 
Yes, it would be good if we can have the ability to set the dom drag option.

**Comment by sporritt** [comment]
we'll need to start in [katavorio](https://github.com/jsplumb/katavorio/issues/38) with this

**Comment by sporritt** [comment]
and then do https://github.com/jsplumb/jsPlumb/issues/674

**Comment by carolqian** [comment]
Great. Thank you

**Comment by panayotisk** [comment]
Has any progress been made in the latest katavorio releases regarding this issue? Allowing the user to toggle the grid on or off would be very convenient indeed.

**Comment by sporritt** [comment]
I'm working on a replacement for Katavorio which uses delegates for events and is a lot quicker with a smaller memory footprint. in that project it is possible to change the size of the grid at runtime.

i'll be releasing a new version of jsplumb - 3.0.0 - at some point in the near future, which uses this katavorio replacement.
