### ISSUE TITLE
.each iteration failed : TypeError: Cannot read property 'force' of undefined

### ISSUE THREAD

**Issue by aeolusheath** [jsplumb/jsPlumb#619]
when the data  input , the draw connection's method is invoked , it's the second time. then console raise the error.

drag function not work.

what is the best way re-render the connections and draggle.

or how to remove the instance of jsPlumb

**Comment by aeolusheath** [comment]
and this info:    jsPlumb function failed : TypeError: Cannot read property 'el' of undefined

the element is draggable but **the connections is not dragged any more**

**Comment by sporritt** [comment]
might need to provide a jsfiddle or something for this. it's a little hard to diagnose on this information alone.

**Comment by sporritt** [comment]
closing, no updates.

**Comment by DarshanTeerth** [comment]
I have the same issue. Here I'm loading chart using JSON. Here's the cede - 
$.each(nodes, function( index, elem ) {
		if(elem.nodetype === 'startpoint'){
			self.repositionElement('startpoint', elem.positionX, elem.positionY);
		}else if(elem.nodetype === 'endpoint'){
			self.repositionElement('endpoint', elem.positionX, elem.positionY);
		}else if(elem.nodetype === 'source'){
			var id = self.addSource(elem.blockId)
			self.repositionElement(id, elem.positionX, elem.positionY);
		}
		}else{
			console.log("nothing")
		}
	});
and for this I'm getting error like this: 
.each iteration failed : TypeError: Cannot read property 'force' of undefined

**Comment by sporritt** [comment]
this issue was closed due to a paucity of information. your update suffers the same affliction. nothing can be done. no progress can be made. all is lost.
