### ISSUE TITLE
我需要线条拖动的功能

### ISSUE THREAD

**Issue by vivayue** [jsplumb/jsplumb#620]
我需要线条拖动的功能，你们能提供吗？

**Comment by sporritt** [comment]
is this the same question as in #616 and #613  ?

**Comment by vivayue** [comment]
yes it is

**Comment by vivayue** [comment]
i need that it can drag line to each direction of function. could you provide it? we will pay

**Comment by sporritt** [comment]
the answer is the same here as on the other issues. it will be added to the Toolkit edition at some stage but there is no chance it can be added right now.

**Comment by vivayue** [comment]
All right. thanks

**Comment by sporritt** [comment]
We're going to put this into version 2.0.0, which we're scheduling for sometime in Q2 2017.
