### ISSUE TITLE
"container"params doesn't work

### ISSUE THREAD

**Issue by song-forever** [jsplumb/jsPlumb#621]
I want to set container for my endpoint ,but "container:id"or "container:$('#id')" doesn't work in my pages.
for some reason I can't use setContainer method (It's work)  
![image](https://cloud.githubusercontent.com/assets/4048406/24130017/2e5f556e-0e21-11e7-88ea-7f6c5fa7304f.png)

**Comment by sporritt** [comment]
you cant set a Container on a per-endpoint basis. the Container is where jsPlumb adds _all_ of the things it adds.

https://jsplumbtoolkit.com/community/doc/home.html#container

**Comment by song-forever** [comment]
so..it means you cant use this in a tab component because of the Container..

**Comment by sporritt** [comment]
why?

**Comment by song-forever** [comment]
if I setContainer in first tab , endpoints in other tab also will be added to first tab ,if i dont setContainer, endpoints will show in all tabs..

**Comment by sporritt** [comment]
given that you cannot connect endpoints in different tabs you just need to use a separate instance of jsplumb in each tab.

**Comment by song-forever** [comment]
ah...........when I use jsPlumb it works,but when i use instance it throws error:{msg: "jsPlumb: unknown connector type 'Bezier'"}

**Comment by sporritt** [comment]
you're definitely wrapping your code in a ready function?

https://jsplumbtoolkit.com/community/doc/home.html#initializing

```
You should not start making calls to jsPlumb until the DOM has been initialized - perhaps no surprises there. To handle this, you should bind to the ready event on jsPlumb (or the instance of jsPlumb you are working with):
```
