### ISSUE TITLE
Connectors drawn offset from actual elements

### ISSUE THREAD

**Issue by urbanhusky** [jsplumb/jsPlumb#627]
I've got a scrollable container. Everything is laid out via flexboxes.
I use `jsPlumb.getInstance({ Container: "containerdiv"});` to get an instance for that container and have set up scroll and resize event handlers to `repaintEverything()`.

The connectors are drawn quite offset to the actual elements. Sometimes connectors are drawn at random to some element outside (I use UUIDs for element IDs).

![jsplumb offset](https://cloud.githubusercontent.com/assets/2065748/24761852/e6a13660-1aec-11e7-9967-30809f1e0803.jpg)

**Comment by FlowerBirds** [comment]
I think you can fix the container size and wrap with a scrollable element like div,

**Comment by urbanhusky** [comment]
I've given up and rolled my own library.

**Comment by sporritt** [comment]
a page demonstrating the issue would have been useful.
