### ISSUE TITLE
Is that possible to undo dragging and revert it to original position in some condition?

### ISSUE THREAD

**Issue by wangzi6147** [jsplumb/jsPlumb#628]
In my case, when I drag a element to a group, I have to send a ajax request to server to confirm if it can be dropped in certain group. If not, how can I revert this dragging event?

**Comment by sporritt** [comment]
are you asking about the Toolkit edition? are you a licensee?  we dont track the toolkit edition on github.

**Comment by wangzi6147** [comment]
@sporritt No, just community edition.

**Comment by sporritt** [comment]
ok. the short answer is you'd have to do this manually right now. but a "can drop in group" callback is something we could think about adding if you were interested.

**Comment by wangzi6147** [comment]
OK Thanks a lot.

**Comment by HopperGithub** [comment]
You can do the job that using esc to revert the dragging element to original position with the drag api, setRevert, and revert event callback.

**Comment by wangyu142857** [comment]
how I can catch the drop event on the group?
