### ISSUE TITLE
Is there swimlanes feature?

### ISSUE THREAD

**Issue by besley** [jsplumb/jsPlumb#629]
When drawing a BPM process diagram, it's popular to use a swimlanes feature. I am not sure where we can find this feature in jsPlumb library. If someone has the same requirement or a nice resolve solution, please give me a suggrestion. Thanks.

**Comment by sporritt** [comment]
the community edition doesnt have layouts or decorators, so you'd have to do this all yourself (probably using Groups). in the toolkit edition we've been thinking about doing a bpmn process editor demo for a while, just need to find some time.

**Comment by besley** [comment]
It's a good news that we can see a bpmn process editor in future. Thanks.

**Comment by sporritt** [comment]
...in the toolkit edition.

**Comment by besley** [comment]
By the way, we just only need the bpmn feature in jsPlumb library, is there a development plan for a seperated product of bpmn process editor? Or we have to purchase the toolkit edtion to get this feature? Thanks.

**Comment by sporritt** [comment]
it doesnt exist yet. but when it does it will be one of the examples in the toolkit edition.
