### ISSUE TITLE
how many   'jsPlumb.getInstance' I  could make in a page

### ISSUE THREAD

**Issue by FlownChao** [jsplumb/jsPlumb#638]
I have two 'jsPlumb Instance'  in a page ,dose the options in second instance overwrite the options in first instance ?https://fiddle.jshell.net/FlownChao/jzmdpaox/

**Comment by sporritt** [comment]
as many as you like.

that fiddle doesnt work for a couple of reasons, one of which is a show stopper:

```
        // 'anchors' is expected to have 2 args. use 'Anchor'
    //etlcontainer.addEndpoint($(".items")[0],{anchors:["Right"]},etlpoint);
    etlcontainer.addEndpoint($(".items")[0],{anchor:"Right"},etlpoint);
    etlcontainer.addEndpoint($(".items")[1], {anchor:"Right"},etlpoint);
```

the commented out code is how you had it setup.  

also, you didn't have the elements positioned absolute, which is required:

```
.items{
        background-color: #fff;
        border-radius: 8px;
        width: 60px;
        height: 35px;
        /* elements must be positioned absolute */
        position:absolute;
        /* dont use margins on absolute positioned elements
        margin: 0 auto;
        margin-top: 20px;
        */                
    }
```

![image](https://user-images.githubusercontent.com/262720/27310170-b7ea09e8-559b-11e7-9702-31e99cc3df5b.png)

https://fiddle.jshell.net/jzmdpaox/2/

**Comment by sporritt** [comment]
closing this to keep the issue list clear but let me know if your problem is not resolved.

**Comment by typingduck** [comment]
@sporritt I have experienced this when trying to create two instances from `jsPlumb.getInstance`.

It would be my expectation than two instances would be independent objects, but looking at the code here https://github.com/jsplumb/jsplumb/blob/master/src/jsPlumb.js#L470 it looks like they are modifying but not replacing the prototype 'Defaults' which is shared between all instances.
