### ISSUE TITLE
can a Source connect to a Source

### ISSUE THREAD

**Issue by xmdda** [jsplumb/jsplumb#640]
l can't use a source to connect another Source ,how can i do this

**Comment by FlowerBirds** [comment]
you can add one or more endpoint in one element, both has source and target endpoint, and you can use one element's source endpoint to connect the other element's target endpoint. eg:

`var sourceEndpointOpts = { isSource:true, anchor: 'right' };`
`var endpoint1 = jsPlumb.addEndpoint('elementOneId', sourceEndpointOpts );`
`var targetEndpointOpts = { isTarget:true , anchor: 'left'};`
`var endpoint2 = jsPlumb.addEndpoint('elementOneId', targetEndpointOpts );`
`// add other one like this`

i think it can help you !
