### ISSUE TITLE
Error cause stack is missing in listener error handling

### ISSUE THREAD

**Issue by Toilal** [jsplumb/jsPlumb#641]
Please display the stack of the error cause [here](https://github.com/jsplumb/jsPlumb/blob/2.4.2/src/util.js#L400). 

Stacktrace of the error is not displayed, there's only the message and it's a mess to find out what's failing in my app. I found the stack by placing a breakpoint [here](https://github.com/jsplumb/jsPlumb/blob/2.4.2/src/util.js#L400) and running `console.log(e.stack)` in the interactive debug of my browser.

**Comment by sporritt** [comment]
yes that's how you can do it. i am not keen to always dump a stack trace to the console.

**Comment by Toilal** [comment]
I'm so sorry to hear that, browser console is a developer tool, it's not UI
element, that's why it's hidden from user since a long time in every
browser.

Error stack should just appear to help developpers fix errors ...

**Comment by sporritt** [comment]
yeah i'm not going to make that decision on behalf of all the people who use jsplumb.
