### ISSUE TITLE
_unmanage not used, should be used by remove?

### ISSUE THREAD

**Issue by JYouren** [jsplumb/jsplumb#642]
I remove and add DOM elements with the same id, and use the features in jsPlumb to add/remove connections as appropriate. The framework seems to cache some data in managedElements, but doesn't remove it when the element is removed from jsPlumb.

I think _unmanage should be used when elements are removed from the jsPlumb framework.

**Comment by sporritt** [comment]
yes.  it is now, since...some time ago. closing this.
