### ISSUE TITLE
How to use Vanilla

### ISSUE THREAD

**Issue by DedicatedManager** [jsplumb/jsPlumb#643]
I don't get how to know if I'm using the jQuery version or Vanilla version?  Are they two separate js files?  Or is it one js file that is configured in a certain way to be one or the other?  I don't see anything in the docs on how to run a given version.  

There is only one version on the download page (currently 2.4.2):
https://jsplumbtoolkit.com/download
Is this jQuery or Vanilla?

**Comment by sporritt** [comment]
there is no jquery version anymore.

**Comment by DedicatedManager** [comment]
Got it.  Might be helpful to update the documentation to say what version no longer uses jQuery.  Thanks again for making such a great tool!

Thanks again!
Terry

https://jsplumbtoolkit.com/community/doc/home.html

> Selectors/NodeLists

> In jQuery there is the concept of a "selector" - a list of elements conforming to some CSS path spec, for instance $(".myClass"). Both the jQuery flavour, and also vanilla, jsPlumb support these selectors as arguments for elements (vanilla jsPlumb can do this because jQuery's selector object is list-like, ie. it has a length property).

> When using vanilla jsPlumb, you can use a NodeList - it is, effectively, the native equivalent of the selectors we just discussed. There are several ways of getting a NodeList from the DOM; perhaps the most useful (supported in IE8+) is document.querySelectorAll("some selector").
> 
> You will see selector referred to in many places in the jsPlumb documentation. Just think of it as a list of elements that match some CSS spec.
>

**Comment by sporritt** [comment]
yes good idea, thanks.

**Comment by sporritt** [comment]
docs are updated in 2.4.3
