### ISSUE TITLE
源于Connections在firefox和ie上连线错位的问题

### ISSUE THREAD

**Issue by caoruonan** [jsplumb/jsPlumb#644]
![1496914068 1](https://user-images.githubusercontent.com/23349013/26921916-1a5c61d2-4c70-11e7-8418-fcac7ae3559a.jpg)
你好！

当前我们使用的版本是2.1.4

在谷歌下能够完美运行，但是在firefox和ie上就会出现图示的问题。不知道jsplumb能否提供类似refresh（滚动时刷新位置信息）的方法。

当然，我们尝试过jsplumb.repaintEverything()的方法，但是在火狐和ie上并没有任何效果。

火狐给出的提示信息 “此网站似乎使用 scroll-linked 定位效果。这可能不适合异步平移；参见 https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects 可深入了解，也可加入相关的工具和功能的讨论。”

请问jsplumb是否存在一个解决办法？

谢谢(*≧▽≦*)~~

**Comment by caoruonan** [comment]
I have solved this problem, this may be because jquery-ui automatically added the window scrollTop reasons. I put the scroll bar on the other elements, just fine. Thank you very much (* ^ __ ^ *) ...

**Comment by sporritt** [comment]
thanks for the update.
