### ISSUE TITLE
Containment on scrollable containers is wrong

### ISSUE THREAD

**Issue by Knochenmark** [jsplumb/jsPlumb#646]
The containment rectangle is calculated by the parents offset height/width properties, which results in wrong results as soon as the container is scrollable. When scrolling down the element can't be dragged further than the original height of the parent element.

The getSize function that is used should take this into account and use scrollHeight/scrollWidth properties instead.

This seems to fix the issue:
`getContainmentSize: function (el) { return [ el.scrollWidth, el.scrollHeight ]; },`

**Comment by Knochenmark** [comment]
Hey guys, this is such a trivial fix and the issue is open for months. Is this project even maintained anymore?

**Comment by sporritt** [comment]
sure it's maintained, there was a release today and one yesterday.

**Comment by Knochenmark** [comment]
@sporritt Really? So why it took you almost 5 months to respond without taking the actual issue into account? The issue was neither assigned or labeled. Even though it is such a trivial fix. I wonder if you even test for this scenario. Your build setup is quite painful by the way and you might want to consider adding a contribution.md with some sort of guide for this.

**Comment by sporritt** [comment]
i can do without the abuse thanks.
