### ISSUE TITLE
Disable Anchonr Dragging

### ISSUE THREAD

**Issue by besingamkb** [jsplumb/jsPlumb#649]
Is there an option to disable an anchor from dragging?

**Comment by sporritt** [comment]
anchors cant be dragged. do you mean an endpoint? you want to disable dragging a connection from an endpoint?

**Comment by besingamkb** [comment]
yes. I only want to have a connection on-load and will not be changed by dragging.

**Comment by sporritt** [comment]
you can use `detachable` in the connect call:

https://jsplumbtoolkit.com/community/doc/connections.html#disconnectreconnect

or you can set `ConnectionsDetachable:false` in the defaults:

https://jsplumbtoolkit.com/community/doc/defaults.html


or you can set `connectionsDetachable` on some `addEndpoint` call.
