### ISSUE TITLE
Typescript definition file for Community Edition?

### ISSUE THREAD

**Issue by RonNewcomb** [jsplumb/jsplumb#652]
Is there a .d.ts file for Community Edition?  Normally I'd use `@types/jsplumb` in my packages.json file, but that is pulling down something that looks like it's a major version number out of date and/or wildly incomplete.

**Comment by sporritt** [comment]
yeah, we didn't have anything to do with the definition file that's on npm for the community edition. we ship one, at least one that exposes enough for the toolkit demos to compile, with the toolkit edition. i'll look into getting it into npm and this repo.

**Comment by RonNewcomb** [comment]
Thank you!!  I tried making one for jsplumbInstance from the online docs, but it went poorly for me. The docs lack detail beyond Object and Array<any>... almost like the site docs were autogenerated from typeless JavaScript.

A good .d.ts file could be useful for autogenerating better site docs as well.

**Comment by Schlesiger** [comment]
@sporritt Is a definition for the community edition still planned? I am currently using the `@types/jsplumb` definitions but as @RonNewcomb mentioned, it's quite out of date.

**Comment by sporritt** [comment]
@RonNewcomb actually contributed one

https://github.com/jsplumb/jsplumb/blob/master/index.d.ts

**Comment by sporritt** [comment]
so i will close this

**Comment by Schlesiger** [comment]
Thanks! It was my fault to not check the source, but it appears the definition isn't included in the distribution. Could you please try PR #676 and republish?

**Comment by RonNewcomb** [comment]
i made another PR that has a few more updates on this file in cause you find it useful, @Schlesiger

**Comment by matthiasscudlik** [comment]
i get this error with AoT:

ERROR in /home/travis/build/xyz/node_modules/jsplumb/index.d.ts (12,6): Duplicate identifier 'Endpoint'.
ERROR in /home/travis/build/xyz/node_modules/jsplumb/index.d.ts (235,11): Duplicate identifier 'Endpoint'.

does anybody else have the issue?
