### ISSUE TITLE
How can I recalculate the anchor position after I changed the width/height of one element?

### ISSUE THREAD

**Issue by chj-damon** [jsplumb/jsPlumb#653]
I realize that anchor's left/top positions of the anchor are settled after instance initialized. after I changed the width/height of the element, it looks like the anchor position didn't change synchronously. Is there any method I can use to recalculate the anchor position in this situation? I already tried repaint() and recalulateOffset() but none of them works.
my jsplumb version is v2.3.2 btw.

**Comment by sporritt** [comment]
try `jsPlumb.revalidate(theElement)`

**Comment by chj-damon** [comment]
@sporritt Thanks for you reply. It works great now. I'm sorry I didn't read all the apis.

**Comment by sporritt** [comment]
no problem. closing this out.
