### ISSUE TITLE
High CPU usage on Chrome 59

### ISSUE THREAD

**Issue by rbx** [jsplumb/jsPlumb#658]
I experience very high CPU usage on Chrome 59.0.3071.115 (Official Build) (64-bit) on both Linux/MacOS.

It occurs after a short time (several seconds to several minutes) when a page with jsPlumb has been interacted with. I could not yet determine what exactly triggers the high CPU usage to start, but here are some details:

- the CPU core is used 100% even when there is no interaction with the page.
- the performance monitor in Chrome Developer Tools does not show anything having such high usage.
- refreshing the page does not stop the issue.
- changing the page to one without SVG (for example a jsPlumb docs page) does not stop the high usage.
- changing to an unrelated page (e.g. google) stops the high CPU usage.
- closing the page and reopening it again stops the issue (but it reoccurs again shortly thereafter).
- on Firefox there is no problem.

It does seem a little bit like problem in the browser (but triggered by something in jsPlumb), but you probably know better.

Here is just a screenshot with two jsPlumb tabs open, one with a demo, and another with a docs page open.
![screenshot_2017-07-10_09-35-42](https://user-images.githubusercontent.com/1915061/28007746-f04b3ee2-6554-11e7-8564-450d99433535.png)

Another screenshot of the developer tools profiling:
![screenshot_2017-07-10_09-58-35](https://user-images.githubusercontent.com/1915061/28008131-851fe03a-6556-11e7-911b-6299bac06cb6.png)

**Comment by sporritt** [comment]
this was reported by email to us recently. in chrome 60 beta the issue is apparently no longer present.

**Comment by rbx** [comment]
I tried the 60 beta - indeed, there is no problem there. Thanks!

**Comment by sporritt** [comment]
oh cool, thanks for the update.

**Comment by tianjianchn** [comment]
Thanks for this report. I made gif for problem reproduction. 
![jsplumb-cpu-100](https://user-images.githubusercontent.com/7612199/28055830-395488ac-664d-11e7-8527-904e245d5a31.gif)

**Comment by sporritt** [comment]
@tianjianchn but you see that it's not an issue in beta 60, right?
