### ISSUE TITLE
connectorOverlays parameter doesn't work with makeSource?

### ISSUE THREAD

**Issue by tonybach** [jsplumb/jsplumb#659]
So I want to apply a Custom Overlay like this:

    var customOverlays = [
      [ 'Custom', {
        create: function (label) {
          ...
          return angular.element('<div><span class="metric-label-text"></span> / <span class="metric-error-label"></span></div>');
        },
        location: [4.3, 0],
        id: 'metricLabel',
      }]
    ];

However, for some reason when I pass it to `makeSource` in this format:

        jsPlumbInstance.makeSource(node.name, {
          ...
          endpoint: {
            connectorOverlays: customOverlays
          }
        });

It just didn't work. It worked when I set `jsPlumb.Defaults.ConnectionOverlays = customOverlays`, and it also worked I did

    jsPlumb.addEndpoint("someDiv", {
      connectorOverlays: customOverlays
    });

However, I would prefer to make it work with `makeSource` if possible.

Please let me know if I'm using the wrong syntax here. I'm using version 2.0.6, but it doesn't seem like there were changes related to this between 2.0.6 and the latest version.

**Comment by sporritt** [comment]
there was no support for this in the code. it's been added to version 2.6.4 which is in development and to be released soon.
