### ISSUE TITLE
Memory leak and high cpu usage with angular 1.x intergration

### ISSUE THREAD

**Issue by ErlendSB** [jsplumb/jsPlumb#660]
This might be releated to: https://github.com/jsplumb/jsPlumb/issues/658  (I'll test again after version 60 is released)
I'm currently testing with Chrome 59 (64-bit) on Windows.  

Steps to reproduce:

- https://jsplumbtoolkit.com/demos/toolkit/angular-1.x/index.html
- Drag three questions onto the canvas
- Connect them to some of the existing questions
- Move them around a bit

With the page idle at this point, open up Task manager within Chrome, and witness the CPU usage above 10%, and the memory gradually increasing. 

I'm unable to reproduce this with the demo on the start page, so I'm assuming this has something to do with your implementation of the angular 1.x integration.

**Comment by raygig** [comment]
I am also seeing this behavior both on the Angular demo as well as the standard https://jsplumbtoolkit.com/ demo site.

![capture](https://user-images.githubusercontent.com/1569098/28524186-6d9979ec-704d-11e7-8b91-b61adff04e9a.gif)

This has been confirmed on 
- Chrome 59.0.3071.115 (Official Build) (64-bit) Windows 10
- Chrome 59.0.3071.115 macOS Sierra 10.12.5

When debugging with Chrome's Performance tools there doesnt seem to be any JS processing which is really strange.

Any insights here would be greatly appreciated.

**Comment by sporritt** [comment]
as you said, please test again with chome 60.

**Comment by raygig** [comment]
Chrome 60 worked! 

Just curious do you know what was happening in Chrome 59 that was triggering the high CPU spikes?

**Comment by sporritt** [comment]
I wish I had any kind of clue. I guess the bits and bytes were being manipulated in such a way that unexpected realms of interdependent busy activity were being instigated. I mean like something was combobulated in a manner that was causing an excess of push and mult and pop. Do you know what I mean?  I once read there's more entropy in 6 integers than there are atoms in the universe. I can't exactly boil that down to any concrete suggestions, but I do suspect that in the fullness of time our current approach to computing will be considered laughable at best.

**Comment by ErlendSB** [comment]
:) I can also confirm that Chrome 60 (beta) fixes the issue.
