### ISSUE TITLE
Is there a "render complete" event?

### ISSUE THREAD

**Issue by DinkDonk** [jsplumb/jsPlumb#661]
Is there anything like a "render complete" event, for knowing when jsPlumb has completed drawing the flowchart?

FYI: I'm running the toolkit and the angular 1.x plugin.

I'm looking for an event to subscribe to that fires when the toolkit has finished it's initial render, and everything is visible on screen.

The `dataLoadEnd` does not wait for a complete draw cycle (probably as intended)

**Comment by sporritt** [comment]
if you are a licensee please contact us via email.
