### ISSUE TITLE
Drawing lines offset

### ISSUE THREAD

**Issue by gmunumel** [jsplumb/jsplumb#665]
Hello there. 

Im working in a simple project where I drag and drop some images. Every image has the possibility to be a source and target, so that I can connect them with lines, but the lines looks odd. 

Please take a look a my example: [here](https://jsfiddle.net/n0dix/rLx61s5e/)

**Comment by sporritt** [comment]
If by odd you mean they're offset, it's because you didn't set a Container.  Wrap all the dom elements in a single element and tell jsPlumb that's the root of its tree:

```
<div id="container">
<div id="panel">
  <br>
  <div class="dude_outside" id="dude_outside">
    <img class="dude_image" id="dude_outside2" src="http://lasolanadigital.com/wp-content/uploads/2014/12/monigote.jpg" alt="dude" />
  </div>
</div>
<div id="canvas">
</div>
</div>
```

```
jsPlumb.ready(function() {
  jsPlumb.setContainer("container");

    $('.dude_image').draggable(
            ...

```

https://jsfiddle.net/rLx61s5e/2/

![image](https://user-images.githubusercontent.com/262720/29095045-ea08af7a-7cd2-11e7-81c5-74c3eb57d506.png)

**Comment by gmunumel** [comment]
Can I not use `canvas` as a container?

Thanks for the quick answer :)

**Comment by gmunumel** [comment]
There are two issues: 

Both are related to rezised object the connection looks offset. 

**Issue A**
![issue a](https://user-images.githubusercontent.com/276168/29275092-406cbbfa-810a-11e7-99ea-3f31b4e2dbea.gif)

**Issue B**
![issue b](https://user-images.githubusercontent.com/276168/29275105-480533b0-810a-11e7-9d9e-489cdd698cf2.gif)

The jsfidle [link](https://jsfiddle.net/n0dix/rLx61s5e/12/)

**Comment by JackHanLinWei** [comment]
@gmunumel 
I'm experiencing similar issues where DOM manipulation results in outdated offsets. Have you solved issue B?

**Comment by gmunumel** [comment]
@JackHanLinWei , not mate. I haven't the time to find a workaround.

**Comment by sporritt** [comment]
the method `revalidate(someElement)` is what you need to call whenever you've manipulated the DOM. this applies to both the resize stuff from the OP and @JackHanLinWei 's comment
