### ISSUE TITLE
connectionDetached bug - originalEvent always undefined

### ISSUE THREAD

**Issue by TobyEalden** [jsplumb/jsPlumb#666]
I can't see how to distinguish between a connection detach as a result of a drag/drop action as opposed to programmatically.

The originalEvent parameter is always 'undefined'

Looks like this could be a result of https://github.com/jsplumb/jsPlumb/commit/c321a7b6ab7adb9772715bd20a7877cb39b62928#diff-6d5425628b7b8e7b29bdb7492aa04464R758

**Comment by wulucxy** [comment]
@TobyEalden have you done with it? I encouter the same problem

**Comment by TobyEalden** [comment]
@wulucxy I patched it with this - https://github.com/nqminds/nqm-jsplumb/commit/cf8ae0b4d029e36b195c6873ab96746f73955ef9
