### ISSUE TITLE
Add jsplumb source and LICENSE.txt to npm package

### ISSUE THREAD

**Issue by leipert** [jsplumb/jsplumb#667]
First of all, thanks for the great project.

It would be really great to add the jsplumb sources (src folder) to the npm package, so one could require the code directly within a build system like webpack. There are currently two use cases for us:

1. We do not need everything of jsplumb.
2. We do want to use a modified katavario library.

EDIT: If you want, we could help you extend jsPlumb to be more webpack compatible.

**Comment by leipert** [comment]
I saw \[[1]], that in recent releases the LICENSE files are also missing. Would also be nice to add them as well :)

[1]: https://unpkg.com/jsplumb@2.5.0/

**Comment by PeterDaveHello** [comment]
Looks like npm is dated on npm now?

**Comment by sporritt** [comment]
i think 5.x probably covers this, as it is split into a bunch of packages and delivered as modules.
