### ISSUE TITLE
Anchor points not updated when 'transform: translate()' is used.

### ISSUE THREAD

**Issue by pavitrakumar78** [jsplumb/jsPlumb#669]
Hi,

I found a (bug?) problem where the anchor points are not updated properly if I style a div using 'transform: translate()' property.

Example: [jsFiddle here](https://jsfiddle.net/pavitrakumar/7v8gcnhL/5/)

To replicate the problem:
Both the blocks (divs) - green and yellow are draggable. The text ('Hello') is the filter for the yellow block, to replicate the problem I faced, drag a connection from the filter of yellow block to the target (lightgreen block) inside the bigger green div. The anchor is supposed to form only on the edges of the lightgreen block but instead, it forms anchor on the previous position of the lightgreen block (i.e the original position of the lightgreen block before transform is applied).
GIF: 

![GIF explaining my problem](https://user-images.githubusercontent.com/5354407/30048331-5458f37e-9233-11e7-9b11-65238492adaa.gif)

This is a problem that could be fixed by other jsPlumb functions or is this a bug?

**Comment by sporritt** [comment]
jsPlumb doesn't take transforms into account when computing anchor points. It is highly unlikely we'd add support for this, due to the extra computation required.

**Comment by pavitrakumar78** [comment]
@sporritt ok, thanks for the information!
