### ISSUE TITLE
Why do you have 'jquery' reference in 'index.d.ts'?

### ISSUE THREAD

**Issue by mb1986** [jsplumb/jsplumb#679]
https://github.com/jsplumb/jsplumb/blob/90ddebbd91db5fb50be6d70bab34115aa6d09de1/index.d.ts#L4

**Comment by RonNewcomb** [comment]
That was from my previous pr, and I had removed it prior to seeing this comment, but it hasn't been accepted yet.

**Comment by sporritt** [comment]
@RonNewcomb do you use Typescript as part of using Angular 4?

**Comment by RonNewcomb** [comment]
Yep. And AngularJS.

**Comment by sporritt** [comment]
did you start using it because of angular?  if angular ceased to exist would you continue using typescript?

**Comment by RonNewcomb** [comment]
No, I have a c/c# background.

**Comment by RonNewcomb** [comment]
So I will continue to use it regardless of framework

**Comment by sporritt** [comment]
right, yeah. it's nice having types.  i'm converting jsplumb to typescript.

**Comment by sporritt** [comment]
jquery reference is gone.
