### ISSUE TITLE
How can I listen group drag event

### ISSUE THREAD

**Issue by p0pfan** [jsplumb/jsplumb#685]
I made a demo , and set draggable in line 28. But it did not work. I hope someone can help me to solve this issue
![image](https://user-images.githubusercontent.com/11961909/32936817-c6538172-cbb0-11e7-9c30-d9c9b08ace81.png)

I hope when I drag a group container, I can get do something else.

the link is : https://jsfiddle.net/2f6Lrm9c/

**Comment by sporritt** [comment]
use `dragOptions`, not `draggable`:

```
dragOptions: {
          start:function(params) {
            console.log("start");

          },
          drag:function(params) {
            console.log("drag");

          },
          stop:function(params) {
            console.log("stop");


          }

        }
```


updated fiddle:

https://jsfiddle.net/2f6Lrm9c/1/
