### ISSUE TITLE
.draggable() affects the focus state of DOM？

### ISSUE THREAD

**Issue by shuyzhou** [jsplumb/jsplumb#688]
I want to change the CSS style of a node when I select it. So I use the :focus CSS pseudo-class to change it.But it doesn't work on nodes with jsPlumb.draggable() .

**Comment by sporritt** [comment]
you'll need to provide a jsfiddle or a codepen or something here.

**Comment by shuyzhou** [comment]
JsFiddle : https://jsfiddle.net/shuyzhou/1cmrvfvk/2/
please take a look at it

**Comment by sporritt** [comment]
yes i see what you mean. i guess katavorio is consuming the mouse event. you can workaround it, like in this version of your fiddle

https://jsfiddle.net/1cmrvfvk/8/

the key piece being listening for click events on nodes:

```
  jsPlumb.on(".list-item", "click", function() {
    this.focus();
  });
```
