### ISSUE TITLE
Deleting requires user to click 2 times

### ISSUE THREAD

**Issue by raksit31667** [jsplumb/jsplumb#693]
I found that when user tries to click arrow for deleting connection, it requires 2 clicks instead of 1.

I also found that connection is gone but arrow still exists.

Here is some parts of source code:

`
instance.bind('click', function (conn, event) {
    // some logic
    instance.deleteConnection(conn);
}
`

and it always come with this following exception:

`
jsPlumb: fire failed for event click : TypeError: Cannot read property '0' of null
`

**Comment by sporritt** [comment]
in this demo

https://jsplumbtoolkit.com/community/demo/statemachine/index.html

we do this

```
instance.bind("click", function (c) {
        instance.deleteConnection(c);
    });
```

and it doesnt report an error.

**Comment by raksit31667** [comment]
Actually it works when graph has been created. However, if I add new node to the container, then problem occurs.

Eventually I solved it by using `instance.repaintEverything()` and arrow disappeared. I guess that the connection has been already deleted, but svg element (arrow) still exists, thus it cannot find any references so it throws an error.

**Comment by sporritt** [comment]
so is there a bug in jsplumb?
