### ISSUE TITLE
The sample code missing "node_modules" folder.

### ISSUE THREAD

**Issue by spsh68** [jsplumb/jsplumb#698]
The sample code missing "node_modules" folder. 
        <script src="../../node_modules/jsbezier/js/jsbezier.js"></script>
       <script src="../../node_modules/mottle/js/mottle.js"></script>		 
        <script src="../../node_modules/biltong/src/biltong.js"></script>
        <script src="../../node_modules/katavorio/src/katavorio.js"></script>

**Comment by sporritt** [comment]
you have to run `npm install`.
