### ISSUE TITLE
document for event missing some content

### ISSUE THREAD

**Issue by cwtuan** [jsplumb/jsplumb#700]
https://jsplumbtoolkit.com/community/doc/events.html

![image](https://user-images.githubusercontent.com/3455798/34560503-edff9256-f180-11e7-9c0c-b643fd94f618.png)

**Comment by Anemy** [comment]
@cwtuan My page shows the content, try a refresh?

![screen shot 2018-01-04 at 1 05 47 pm](https://user-images.githubusercontent.com/1791149/34577686-09a63b94-f150-11e7-819e-1324ae5dcac3.png)
