### ISSUE TITLE
Any demo community version with jquery.panzoom

### ISSUE THREAD

**Issue by alanhg** [jsplumb/jsplumb#703]
as we know, Community has not  panzoom feature

**Comment by sporritt** [comment]
I don't know of any Community edition demo using jquery.panzoom.

**Comment by YuriGor** [comment]
http://yurigor.com/pan-zoom-jsplumb-dagrejs-jqueryui-draggable/

**Comment by alanhg** [comment]
@YuriGor The solution that I ended up using was solved. It's my demo 
https://github.com/alanhg/angular-demo/issues/22
