### ISSUE TITLE
connection path could be draggable?

### ISSUE THREAD

**Issue by alanhg** [jsplumb/jsplumb#704]

**Comment by sporritt** [comment]
we will be adding this to the toolkit edition, but not the community edition.

**Comment by alanhg** [comment]
Pity, I had to seek third-party js or to do it myself.

**Comment by sporritt** [comment]
or buy a license!

**Comment by wulucxy** [comment]
hi @alanhg，do you have any progress？I'm seeking for this solution too。

**Comment by sporritt** [comment]
we will be adding this to the toolkit edition, but not the community edition.

**Comment by alanhg** [comment]
@wulucxy I did not solve this feature.
