### ISSUE TITLE
Jsplumb recalculateOffsets issue

### ISSUE THREAD

**Issue by Tobjoern** [jsplumb/jsplumb#705]
I have a problem with the recalculateOffsets function, which is located in the jsPLumb object. The problem is, it doesn´t seem to work. 
I am building an application, which consists of multiple draggable Boxen, which can be connected and have  content within each of them (like https://jsplumbtoolkit.com/community/demo/flowchart/index.html). Connecting them in their default position works very well, however when I add some additional content the Endpoints of this draggable box keeps stuck at its original position (when no additional content was added).
But as its listed in jsPlumb´s documentation, this is expected as it would take too much performance to check for changes in the markup every second. It is also listed that one should use the recalculateOffsets function, whenever there are changes in the markup. So that is what I did but recalculateOffsets simply does not seem to work. I have an example of the problem here: https://jsfiddle.net/vpj99sny/.

So my questions are:
  1. Am I doing something wrong?
  2. Is there a similar method like recalculateOffsets that works?
  3. I there a workaround (like writing a recalculation method by yourself)
  4. Is this a bug in JsPlumb?

Thanks in advance!

**Comment by sporritt** [comment]
you could try the `revalidate` method instead of `recalculateOffsets`

**Comment by Tobjoern** [comment]
Thank you for trying to help me with my issue! @sporritt  
I replaced the recalculateOffsets method with the revalidate method, but it still doesn't do anything. Am I doing something wrong? (https://jsfiddle.net/ykm2xut3/)

**Comment by Tobjoern** [comment]
Looking back I dont really now what the problem was but this function gets the job done for me:

```
 //Fixes endpoints for specified target
    function fixEndpoints(parentnode) {

        //get list of current endpoints
        var endpoints = instance.getEndpoints(parentnode);
        
        //there are 2 types - input and output

        var inputAr = $.grep(endpoints, function (elementOfArray, indexInArray) {
            return elementOfArray.isSource; //input
        });

        var outputAr = $.grep(endpoints, function (elementOfArray, indexInArray) {
            return elementOfArray.isTarget; //output
        });

        calculateEndpoint(inputAr, true);
        calculateEndpoint(outputAr, false);

        instance.repaintEverything();
    }

    //recalculate endpoint anchor position manually
    function calculateEndpoint(endpointArray, isInput) {

        //multiplyer
        var mult = 1 / (endpointArray.length+1);

        for (var i = 0; i < endpointArray.length; i++) {

            if (isInput) {

                //position
                endpointArray[i].anchor.x = 1;
                endpointArray[i].anchor.y = mult * (i + 1);
            } 
            else {

                //position
                endpointArray[i].anchor.x = 0;
                endpointArray[i].anchor.y = mult * (i + 1);
            }
        }
    }
```
