### ISSUE TITLE
In-group scroll bar

### ISSUE THREAD

**Issue by caoruonan** [jsplumb/jsplumb#706]
Here I try jsplumb open source document, we need to achieve the needs of the figure:
![image](https://user-images.githubusercontent.com/23349013/35132386-ea844820-fd05-11e7-827b-530868168e37.png)
Elements within the group can do as source or target.
If there are too many elements in the group, we will see a scroll bar on the group.
In this case, when the group uses the scroll bar, the elements in the group start to move upward or downward, but the connection point does not move. How to make a point follow the DOM?

**Comment by sporritt** [comment]
perhaps add a scroll listener to the group element and call `revalidate` on that group whenever it scrolls?
