### ISSUE TITLE
cloudy selection

### ISSUE THREAD

**Issue by cdaniel** [jsplumb/jsplumb#708]
Selecting a couple of nodes and adding some sort of cloudy group would be a nice, visual feature:

An example:
![image](https://user-images.githubusercontent.com/1265262/35672955-5a52a63a-0740-11e8-827c-7cb56f24e3ff.png)

**Comment by sporritt** [comment]
Do you mean in the Toolkit edition?

**Comment by cdaniel** [comment]
Nope. The community one. Unfortunately, I'm required to keep everything open source, so the toolkit does not exist for me.

The point is that I sometimes need to show that a group of nodes constitutes something together.

**Comment by sporritt** [comment]
I see. Unfortunately this isn't the sort of the thing that would get added to the Community edition.
