### ISSUE TITLE
css is not getting applied using cssClass

### ISSUE THREAD

**Issue by vishalbiradar** [jsplumb/jsplumb#714]
I am using jsplumb to connect two elements in my angular 4 project.
Below is my code:

createLine.component.ts
--------------------------

```
jsPlumb.connect({
      connector: ['Flowchart', { stub: [220, 67], cornerRadius: 1 }],
      source: this.sourceIds[i],
      target: this.targetId,
      anchor: ['Right', 'Left'],
      endpoint: 'Blank',
      paintStyle: {stroke: '#10D8A1', strokeWidth: 4},
      overlays: [
         [ 'Label', { label: this.sourceIds[i], location: labelLocation, cssClass: 'connectorLabel' } ]
      ],
});
```

Then I have tried to apply custom css to those elemnts as below, but nothing is working.

style.css
----------

```
.jtk-connector {
    z-index:2 !important;
}
.connectorLabel {
    height: 26px;
    width: 140px;
    border-radius: 13px;
    background-color: #B8C5D6;
    color: #FFFFFF;
    text-align: center;
}

```

Please help me.

**Comment by sporritt** [comment]
@vishalbiradar have you confirmed that the required class is not actually present on the overlay element?

**Comment by vishalbiradar** [comment]
@sporritt 
Please refer the screen-shot image.
The added class **_connectorLabel_** is present in the below image.

<img width="735" alt="screen shot 2018-02-21 at 2 51 15 pm" src="https://user-images.githubusercontent.com/29951629/36472252-49c578d8-1717-11e8-9596-8a1613d0104e.png">

**Comment by sporritt** [comment]
in that case jsPlumb has done what you asked it to. there must be some other reason you're not seeing the results you want.

**Comment by vishalbiradar** [comment]
@sporritt 
But what may be the cause ??
I have written the respective class css also, but jsplumb is not taking that css.
Note: I am using Angular 4
Will you please help me.
Only this thing is causing the problem.
Waiting for the solution from your side.

**Comment by vishalbiradar** [comment]
Finally, I got the solution.
I have created a css file in the assets/css folder and then added that file link in the index.html file.
Then its working fine.
Thanks a lot for such a great plugin.
