### ISSUE TITLE
Extra corner exist when use `Flowchart` type

### ISSUE THREAD

**Issue by bq-hentai** [jsplumb/jsplumb#718]
Shown in [demopage](https://jsplumbtoolkit.com/demos/wrapped/flowchart/index.html).

![image](https://user-images.githubusercontent.com/19964297/36767156-3f7d04d8-1c74-11e8-999e-3b5342128bbf.png)

How can i optimize the connector?

**Comment by sporritt** [comment]
the connector will paint itself according to its own algorithm.  you cant make this do anything other than that which it automatically does.  in the Toolkit edition soon you'll be able to drag connector paths. but the Toolkit edition is of course not free.

**Comment by bq-hentai** [comment]
@sporritt Thx for ur reply.

But it is not very good in following situation.
![image](https://user-images.githubusercontent.com/19964297/36768070-3701913a-1c78-11e8-9ad4-c7d1a2fe3ef4.png)

I just noticed that it is OK in this [eg](https://jsplumbtoolkit.com/demos/wrapped/flowchart/index.html).

I update my jsplumb and current version is `2.6.8`. The version in the [eg](https://jsplumbtoolkit.com/demos/wrapped/flowchart/index.html) is `2.6.7`. Do I need some special configurations ?

P.s. The [eg](https://jsplumbtoolkit.com/demos/wrapped/flowchart/index.html) uses the community version.

**Comment by bq-hentai** [comment]
@sporritt Sry, I just checked again and the jsplumb in that example is toolkit version.

**Comment by sporritt** [comment]
No, that's not the Toolkit edition. That's the Community edition. Unless that's one of the "wrapped" Community edition demos....the Toolkit edition does currently exhibit the same behaviour, as it uses the same connectors.

**Comment by bq-hentai** [comment]
@sporritt Thx again :)

Yeah, u r right. It is the wrapped demos.

But Please check this. [Toolkit version](https://jsplumbtoolkit.com/demos/toolkit/flowchart-builder/index.html) & [Pure Comunity version](https://jsplumbtoolkit.com/community/demo/flowchart/index.html).

Although the styles are not same, yet they  don't exhibit the same behaviour.
![1519789237 1](https://user-images.githubusercontent.com/19964297/36768989-a2e2afca-1c7c-11e8-876e-c777ed76fcbb.jpg)

![image](https://user-images.githubusercontent.com/19964297/36768720-740bafd6-1c7b-11e8-8fd7-b4427b9ca646.png)

The wrapped one is Ok although it is not so somooth when interacting.

**Comment by bq-hentai** [comment]
@sporritt If they should present consistently, then how can I optimize the connector style if use Community version.

**Comment by sporritt** [comment]
the difference is in the value of the stub parameter on the connector.

you will not be able to drag connector paths in the community edition.

**Comment by bq-hentai** [comment]
@sporritt Oh silly me......

I ignored the `stub` param. Thx very very much:):)

Thanks for ur great work on `jsPlumb`.
