### ISSUE TITLE
bug found in jsPlumb.repaint( ) 

### ISSUE THREAD

**Issue by totola147** [jsplumb/jsplumb#720]
![image](https://user-images.githubusercontent.com/3626320/37453489-c63a9210-2872-11e8-95eb-62477eb1cddf.png)

**Comment by sporritt** [comment]
that doesnt necessarily illustrate a bug. do you have a situation in which you have seen a bug manifest itself?

you may be expecting `repaint` to do what `revalidate` does.

**Comment by totola147** [comment]
in my code , i  have moved an element programmatically , 
![image](https://user-images.githubusercontent.com/3626320/37456306-fd6f49c2-2879-11e8-947a-65b77dc1bca5.png)
![image](https://user-images.githubusercontent.com/3626320/37456375-2370bfb6-287a-11e8-8a4d-31bd57b68363.png)
in my circumstances , after i moved the element , i try to repaint the element , but failed , unless i use the repaintEverything( ) , so i compare these two function , and find that .

just as the documentation says , the repaint  should be used when "you have moved an element programmatically" ;   so i think this is a bug , but anyway , my problem has been solved : )

**Comment by totola147** [comment]
@sporritt   you are right  , revalidate( ) does  work !

thank you

**Comment by sporritt** [comment]
i will update the documentation to reference `revalidate` instead.

**Comment by bq-hentai** [comment]
Oh `revalidate`!

**Comment by sporritt** [comment]
docs updated in 2.6.10 to reference `revalidate` rather than `repaint`
