### ISSUE TITLE
Prevent the node out of the top & left boundary

### ISSUE THREAD

**Issue by bq-hentai** [jsplumb/jsplumb#721]
If we set the `container`, the node can't be dragged out of the boundary,
yet if not set and drag node to leave the top or left boundary, then we can't *find* them.

It's not very good. So I tried to catch some events and then reset the `position` when moving / dropped. But jsPlumb doesn't emit any events like `nodeMoving/nodeDropped`.

Are there any other methods to prevent this?

Thanks for ur great work on jsPlumb.

**Comment by bq-hentai** [comment]
sorry for typo `container`: `containment: true`

**Comment by sporritt** [comment]
jsplumb _does_ have events you can bind to when dragging.  it uses katavorio:

https://github.com/jsplumb/katavorio/wiki

**Comment by bq-hentai** [comment]
@sporritt sorry for late reply. I replied but I just found it had not been sent.

I read the docs and found how to do this. And my code now is like this.

```javascript
    stop ({ el, pos: [ x, y ] }) {
        let needRepaint = false
        if (x < 0) {
          el.style.left = '0px'
          needRepaint = true
        }
        if (y < 0) {
          el.style.top = '0px'
          needRepaint = true
        }
        if (needRepaint) {
          // must update before repaint
          // if not, won't reclac. in repaint fn, default value of recalc is false
          jsPlumbInstance.updateOffset({ recalc: true, elId: el.id })
          jsPlumbInstance.repaint(el)
        }
      }
```

I have read jsplumb docs in homepage serveral times, but I ignored wiki :(.

Thanks sincerely :) :+1:

**Comment by bq-hentai** [comment]
my code `updateOffset` may be replaced and use `revalidate`.[see this](https://github.com/jsplumb/jsplumb/issues/720#issuecomment-373319096)

and [doc](https://jsplumbtoolkit.com/community/apidocs/classes/jsPlumbInstance.html)
