### ISSUE TITLE
Cannot create endpoint with .addEndpoint(target, ...) and .addEndpoints(target, [...])

### ISSUE THREAD

**Issue by mbao01** [jsplumb/jsplumb#722]
I tried to add an endpoint to an element using the **addEndpoint()** method and I got the error below.
![jsplumb](https://user-images.githubusercontent.com/10655408/37851865-c85ee9c8-2ee0-11e8-9f3b-5ce4b1ad86ab.png)
This was the parameter I used (also tried other values for _endpoint_ property, same result):

> jsPlumbInstance.addEndpoint('targetId', {
            endpoint: ['Dot', { radius: 10 }],
            hoverPaintStyle: {
                stroke: 'rgb(200,200,200)',
                fill: 'rgb(200,200,200)',
                strokeWidth: 5
            },
            . . .
  })
>
I traced the error and found the culprit.
![jsplumb2](https://user-images.githubusercontent.com/10655408/37852544-562147ea-2ee3-11e8-8f44-8f8ef2ae08e1.png)

I think Line **10901** should be **`this.resetBounds.call(this)`**. That way it points to _bounds_ property on the _this_ object _AbstractComponent_ is bound to. I confirm that this works perfectly.
Please confirm the solution is correct. Thank you.
I can create a PR for this too.

**Comment by mbao01** [comment]
I have figured out the issue here. Turns out to be a configuration in UglifyJSPlugin, Webpack.

I changed **`pure_getters`** from **`true`** to **`false`** according to webpack doc..

![jsplumb3](https://user-images.githubusercontent.com/10655408/37936740-7e1d76ac-314e-11e8-8889-cb58b40c1726.png)

**Comment by sporritt** [comment]
thanks for providing the update.
