### ISSUE TITLE
Cannot establish connection - source does not exist

### ISSUE THREAD

**Issue by vishalbiradar** [jsplumb/jsplumb#724]
I am trying to connect source1, source2,source3 to target1 in my Angular 4 project.
So I am iterating over the loop containing all those source ids.

Step 1) I will connect source1 to target1
With the below code, it will create a line between source1 and target1

```typescript
jsPlumbInstance: any;
ngAfterViewInit() {
        this.jsPlumbInstance = jsPlumb.getInstance();
}
connectSourceToTargetUsingJSPlumb(sourceIds) {
        this.jsPlumbInstance.reset();
        this.jsPlumbInstance = jsPlumb.getInstance();
            this.jsPlumbInstance.connect({
                source: 'source' + sourceIds[i],
                target: 'target1',
            });
        }
    }
```
Step 2) I will go to next page and add some more info about the connection between them
Step 3) come back to the step1 page and call connectSourceToTargetUsingJSPlumb() function
AT this time am getting this error
**Cannot establish connection - source does not exist**

Please help me.

**Comment by vishalbiradar** [comment]
I have resolved it on my end.
I know it's not the proper solution, but with that its working fine.
I am calling this method two times, so a result for the first time it will fail and throw the error
`Cannot establish connection - source does not exist ` but for next time it will work fine.
Maybe as I am returning from one component to the second component in my angular app, there may be some delay to load the content.

```typescript
connectSourceToTargetUsingJSPlumb(sourceIds) {
        this.jsPlumbInstance.reset();
        this.jsPlumbInstance = jsPlumb.getInstance();
            this.jsPlumbInstance.connect({
                source: 'source' + sourceIds[i],
                target: 'target1',
            });
        }
    }
```

**Comment by bq-hentai** [comment]
It's ok if it is revolved.

P.s. Maybe codes of `connectSourceToTargetUsingJsPlumb` function is not complete.
You lost the loop line in the code block.
