### ISSUE TITLE
Connection losing reference when add new connection

### ISSUE THREAD

**Issue by williamespindola** [jsplumb/jsplumb#729]
I'm using version 2.6.9
I have two elements connected, an when I create some other the fist connection lose reference with other elements.
![screen shot 2018-04-09 at 08 36 18](https://user-images.githubusercontent.com/794521/38495877-b2942c4a-3bd1-11e8-8195-a280473f9217.png)
I'm connecting elements with this code:
```js
...
 this.settings = {
      Connector: "Flowchart",
      Endpoint: ["Dot", { radius: 5 }],
      ConnectionOverlays: [
        ["Arrow", { location: 0.5, cssClass: "arrow-connection" }]
      ],
      Anchor: ["Top", "Bottom"]
    }; 

    this.plumbInstance = jsPlumb.getInstance(this.settings);
...
this.plumbInstance.connect({source: "node-1",  target: "node-11"});
this.plumbInstance.connect({source: "node-11",  target: "node-111"});
```
I already tried to reset all connections and reconnect but reset not work keeping old and new connections.
![screen shot 2018-04-09 at 08 47 43](https://user-images.githubusercontent.com/794521/38496121-b54eeba4-3bd2-11e8-8a8c-5b84308e4534.png)
maybe this reset problem is the same of #719 

The expect behaviour are the 1 node and 11 is connected and 11 and 111 node are connected too.

**Comment by sporritt** [comment]
are you able to reproduce this in a jsfiddle?

**Comment by williamespindola** [comment]
I think so, I need to remove some proprietary code.
Let me ask a question about this. 
This nodes (white boxes) are created dynamically exist some routine that I need to care about when creating elements and connect dynamically? My be sobre code example can help me on this.

**Comment by williamespindola** [comment]
Other question is I need to `addEndpoint ` for every element before `.connect` it?

**Comment by sporritt** [comment]
you dont need to call `addEndpoint` before you connect elements, no. jsPlumb will create an endpoint for each end of the connection in the `connect` call.

**Comment by williamespindola** [comment]
@sporritt here a jsfiddle https://jsfiddle.net/xop6svbt/22/
Today I'm running this pice of code to remove this extra connections lost on the way:
```js
clean() {
    let elements = document.getElementsByClassName('jtk-connector');
    Array.from(elements).forEach(element => {
      element.remove();
    });
    let foo = document.getElementsByClassName('jtk-endpoint');
    Array.from(foo).forEach(element => {
      element.remove();
    });
  }
```
But of course I'm doing something wrong

**Comment by sporritt** [comment]
thanks. you cant add new nodes to the DOM like this

```
let newNode = '<div id="node-' + id + '" class="node"><p>' + id + '</p><button class="add-node" value="' + id + '">add node</button></div>';
	document.getElementById('canvas').innerHTML += newNode;
```

you blow away all the nodes that are there when you do this. jsPlumb loses its references.

**Comment by williamespindola** [comment]
Thanks for reply @sporritt. How can I add new nodes? May be using createElement like [this](https://github.com/jsplumb/jsplumb/blob/master/demo/animation/demo.js#L69-L79)?
