### ISSUE TITLE
How to get the sequential connections from start to end

### ISSUE THREAD

**Issue by arisweb101** [jsplumb/jsplumb#730]
I have 3 draggable boxes and I'd like to know how the jsplumb would know that the last element were connected to the first two elements.  

The layout is like this:  1stbox is the source of 2ndbox  and 2nd box is the source of 3rd box.

[  1  ] ----------------> [   2    ] ------------------>[  3  ]

For now I have this code:

plumb.bind("connection", function(info){
    
    source = info.sourceId
    target = info.targetId

      if(source('1stbox') !== -1 ) {  // Defined

        alert("connected to 1st")   // Working

          if(source('2ndbox') && target('3rdbox') !== -1) {

            alert("Should recognize that 3rdbox are connected from 1st to 2nd boxes") // NOT WORKING
          }
        }

      })

})

Thanks in advance. I'd really appreciate it.

**Comment by sporritt** [comment]
you'd need to start with the `select()` call on the jsplumb instance. it gets you all of the connections.  from that list you would then need to extract the list of unique nodes managed by that instance of jsplumb. from there you could identify all the nodes that are not the target of any connections, and all the nodes that are not the source of any connections. etc.

the Toolkit edition can do this, but the Toolkit edition is not free.

**Comment by arisweb101** [comment]
Awesome, I also found this solution on the document and it works. Thank You :)

**Comment by sporritt** [comment]
ok cool, closing this out.
