### ISSUE TITLE
Transform Matrix vs Transform Scale

### ISSUE THREAD

**Issue by arisweb101** [jsplumb/jsplumb#731]
How to use zoom in/out in JSplumb with transform SCALE? I tried the available source using transform matrix but it doesn't fit on what I'm working on. It has an issue when dragging elements which there was a gap from the cursor and a delay on movements. Perhaps using transform scale will solve the issue I have.

Thanks in Advance :)

**Comment by sporritt** [comment]
the recommended approach _is_ to use scale:


https://jsplumbtoolkit.com/community/doc/zooming.html

**Comment by arisweb101** [comment]
I got it. :D The right answer is to get the value of the transform div (scale or matrix) then set the setZoom.
Booommm. Thank yah!
