### ISSUE TITLE
addOverlay throws error on new connections

### ISSUE THREAD

**Issue by olegmedoed** [jsplumb/jsplumb#732]
plumber.bind("connection", conn => {
      conn.addOverlay({
        location: 0.5,
        id: "LABEL",
        cssClass: "label"
     })
    })

as result I receive error:

----------

> TypeError: o.isVisible is not a function
>     at ./node_modules/jsplumb/dist/js/jsplumb.js._jp.Connection.paint (jsplumb.js:9090)
>     at ./node_modules/jsplumb/dist/js/jsplumb.js._jp.Connection.paint (jsplumb.js:2817)
>     at ./node_modules/jsplumb/dist/js/jsplumb.js._jp.Connection.repaint
> (jsplumb.js:9125)
>     at ./node_modules/jsplumb/dist/js/jsplumb.js._jp.Connection.repaint
> (jsplumb.js:2817)
>     at ./node_modules/jsplumb/dist/js/jsplumb.js._jp.Connection.addOverlay
> (jsplumb.js:7151)
>     at ./node_modules/jsplumb/dist/js/jsplumb.js._jp.Connection.addOverlay
> (jsplumb.js:2817)
>     at ./node_modules/jsplumb/dist/js/jsplumb.js.root.jsPlumbInstance.<anonymous>
> (addHooks.ts:74)
>     at ./node_modules/jsplumb/dist/js/jsplumb.js.root.jsPlumbInstance.fire
> (jsplumb.js:2929)
>     at ./node_modules/jsplumb/dist/js/jsplumb.js.root.jsPlumbInstance._currentInstance.finaliseConnection
> (jsplumb.js:4122)
>     at Object.<anonymous> (jsplumb.js:8524)

**Comment by sporritt** [comment]
for anyone who comes across this, it was probably closed due to the fact that the `addOverlay` call didn't specify an overlay type. it should have been like this:

```
plumber.bind("connection", conn => {
  conn.addOverlay(["Label", {
    location: 0.5,
    id: "LABEL",
    cssClass: "label"
 }])
})
```
