### ISSUE TITLE
How to get beforeStartConnect() return data in beforeConnect()?

### ISSUE THREAD

**Issue by Jimmy880** [jsplumb/jsplumb#735]
beforeStartConnect(source, edgeType) method can not pass return data in to the beforeConnect(source, target, edgeData) method interceptor as the edgeData parameter.
I have tried `return { lang:node.data.l };` that is showed in the HelloWorld demo. however, demo get the data in render by `overlays:[ [ "Label", { label:"${lang}"}]]` but not in beforeConnect() method that is wrote in the toolkit document.(as shown in the picture).
![tim 20180424221046](https://user-images.githubusercontent.com/34367740/39192696-5c26001c-480c-11e8-8a10-d9f60b042f32.png)
Therefore, I wonder how can i get beforeStartConnect return data in beforeConnect method

**Comment by sporritt** [comment]
please contact us at support@jsplumbtoolkit.com. this issie tracker is for the community edition.

**Comment by sporritt** [comment]
@Jimmy880 after receiving your support request we advised you we'd need to know your licensee details for the Toolkit. having received no reply to multiple emails we have sent you, it's difficult not to reach the conclusion that you are using the Toolkit edition without a license.
