### ISSUE TITLE
createTouch Deprecation Notice

### ISSUE THREAD

**Issue by wallzero** [jsplumb/jsplumb#738]
I am receiving the following warnings on Chrome 66 and `jsplumb@^2.6.9`:

`[Deprecation] document.createTouch is deprecated and will be removed in M68, around July 2018. Please use TouchEvent constructor instead. See https://www.chromestatus.com/features/5668612064935936 for more details.   jsplumb.js:1175`
`[Deprecation] document.createTouchList is deprecated and will be removed in M68, around July 2018. Please use TouchEvent constructor instead. See https://www.chromestatus.com/features/5668612064935936 for more details.   jsplumb.js:1180`

**Comment by sporritt** [comment]
this code is in Mottle, the event manager. created an issue there to track this.
