### ISSUE TITLE
How to show a broken connection

### ISSUE THREAD

**Issue by jwerre** [jsplumb/jsplumb#740]
What would be the best way to render a Connection If the source or target does not exist? Is it possible to have a connection that starts at a target or source and doesn't connect to anything?

**Comment by sporritt** [comment]
that would be nice but isnt yet supported. it is an open feature request somewhere around this repo.

**Comment by sporritt** [comment]
for instance #726

**Comment by sporritt** [comment]
closing this.  #726 will probably get the updates.
