### ISSUE TITLE
jsPlumb not updating data in its template

### ISSUE THREAD

**Issue by apmeena** [jsplumb/jsplumb#741]
I am working on a project in which I need to implement [jsPlumb][1]. I am going to use vanilla JS for this. The problem is I am not able to update the data in its template engine [Rotors][2]. 

Here is my template code:

    <script type="jtk" id="tmplSplit">
        <div>
          <r-each in="ports">
              <li class="bp-endpoint">${source}</li>
           </r-each>
        </div>    
    </script>

JS

```
<script type="text/javascript">

      var rotor = Rotors.newInstance();

      rotor.template('#tmplSplit', { data });

</script>
```

Here I am able to change `${text}` and `${ports.length}` property but the `r-each` loop is not updating the data.

Thanks.

  [1]: https://jsplumbtoolkit.com/
  [2]: https://github.com/jsplumb/rotors

@sporritt  Please Help me 😞 😢

**Comment by apmeena** [comment]
@pvmsikrsna need expert help 😄

**Comment by sporritt** [comment]
Rotors is part of the Toolkit edition. Are you asking about the Toolkit edition?

**Comment by apmeena** [comment]
@sporritt, Yes I am talking about the template engine which is given here `https://jsplumbtoolkit.com/docs/toolkit/templating.html`

**Comment by sporritt** [comment]
Yes. That's part of the Toolkit edition. Are you using the Toolkit edition?

**Comment by apmeena** [comment]
@sporritt yes

**Comment by sporritt** [comment]
@apmeena support requests for the Toolkit edition can be sent to support@jsplumbtoolkit.com.
