### ISSUE TITLE
Is bower.json still necessary?

### ISSUE THREAD

**Issue by sporritt** [jsplumb/jsplumb#745]
I have never really used bower, nor been a fan of the way it conflates source repo with package manager, but there's been a bower.json in jsPlumb for a while now because for a time there it was reasonably popular.

We now package everything of note up via package.json. Is there any point in retaining support for bower?

**Comment by sporritt** [comment]
i'm going with no.

**Comment by koppor** [comment]
I would also remove it. I think, it's maintained via pull requests and the last one touching it is one year old (https://github.com/jsplumb/jsplumb/pull/558).

Even the bower guys recommend to switch to something else:

![grafik](https://user-images.githubusercontent.com/1366654/40584503-35eb127a-61a2-11e8-88c5-01402c41e6e0.png)

Regarding building older software: That software depends on an older version of jsPlumb with a bower.json. When updating that software, it is very likely that they also will migrate away from bower.

Historical note: Initial PR adding `bower.json`: https://github.com/jsplumb/jsplumb/pull/70

**Comment by sporritt** [comment]
thanks for your input. i canned it, starting version 2.7.3.

**Comment by olivbd** [comment]
Even if bower is deprecated, many projects still use bower.json for compatibility issues and I think it's better to keed this file.
Because of the lack of this file, I'm unable to build my app using Grunt/Bower... Could you re-put this file please?
