### ISSUE TITLE
How to make connection that half dashed half straight

### ISSUE THREAD

**Issue by eserdinyo** [jsplumb/jsplumb#746]
Is this possible to make jsPlumb connection half with dashed another half straight?
Like this example.

https://jsfiddle.net/eser3424/et2z8dfv/

**Comment by sporritt** [comment]
no, you can't do this at the moment. the svg element is continually rewritten by jsplumb so even if you were to set this stroke dasharray manually it would be replaced continually.

**Comment by eserdinyo** [comment]
I understand. Is there another solition for this? I mean maybe we can do it something with custom overlays. I just want one side to look like straight.

**Comment by sporritt** [comment]
there isnt really, no. other than continually overwriting the connection's dash array when the path is redrawn, but there is not a discrete "this connection was repainted" event that you could hook into anyway.

**Comment by breakintheweb** [comment]
You can always write a custom jsplumb style. Not sure if this is the best way to do this but it works.
I added a new style called straightdashstyle which takes 3 values
` paintStyle: {strokeWidth: 2,  straightdashstyle: '100 10 5', stroke: '#445566'},`

And in the jsplumb code i added:
`          // Function for straight line plus dashed line
          // takes 3 values straightLine,dashLine,dashSpace
          if (style[STRAIGHTDASHSTYLE] && style[LINE_WIDTH] && !style[STROKE_DASHARRAY]) {

            var dashArray = [];
            var svgWidth= dimensions[2] // svg path length
            var  parts = style[STRAIGHTDASHSTYLE].split(' '),
             straightLine = parseInt(parts[0]),
             dashLine= parseInt(parts[1]),
             dashSpace = parseInt(parts[2]);
            var remainingLen = 0;
            remainingLen = svgWidth-straightLine-dashSpace;
            dashArray.push(straightLine);
            dashArray.push(dashSpace);
            var loop=remainingLen/(dashLine+dashSpace);

            for (i = 0; i < loop; i++) {
              dashArray.push(dashLine);
              dashArray.push(dashSpace);
            }
            node.setAttribute(STROKE_DASHARRAY, dashArray);
          }`

**Comment by eserdinyo** [comment]
@breakintheweb thank you for answer. But i'm so newbie in jsPlumb. Where should i add this function in jsPlumb instance. I'm getting an error like this: `Uncaught ReferenceError: style is not defined`

**Comment by breakintheweb** [comment]
No worries, I'm new as well. Here's the change for jsplumb.
https://github.com/breakintheweb/jsplumb/pull/1/commits/7f06177c0f18b74e6a2658c2100ffae274da91e0

**Comment by eserdinyo** [comment]
@breakintheweb I'm sorry for disturbing you but I add the code in jsPlumb.js file. Now I'm getting an error like this: `Uncaught ReferenceError: STRAIGHTDASHSTYLE is not defined`

**Comment by breakintheweb** [comment]
Looks like I had two mistakes. Can you try again? I updated the link above with the new changes.

**Comment by eserdinyo** [comment]
It's worked. Is this result normal?
[https://imgur.com/a/0d7hTGf](url)

**Comment by breakintheweb** [comment]
Looks like i messed up the dimensions. It seems to be working now. For FlowChart connection types, it appears to duplicate the line style 3 times thus doesn't work properly. For straight, bezier and StateMachine, it works.

Here is a working jsfiddle:
http://jsfiddle.net/1d8mmxo9/
