### ISSUE TITLE
import jsPlumb wrong

### ISSUE THREAD

**Issue by dryqiao** [jsplumb/jsplumb#747]
`import jsPlumb from 'jsplumb'`

got this error:

Uncaught TypeError: Cannot set property 'matchesSelector' of undefined
    at eval (jsplumb.js)

**Comment by sporritt** [comment]
which version of jsplumb is this?

**Comment by dryqiao** [comment]
@sporritt 2.7.1

**Comment by sporritt** [comment]
try 2.7.3, released yesterday

**Comment by dryqiao** [comment]
@sporritt thanks,I have tried 2.7.3,but jsPlumb.default object is empty now,
`TypeError: __WEBPACK_IMPORTED_MODULE_2_jsPlumb___default.a.ready is not a function`

**Comment by sporritt** [comment]
you should try some pre 2.7.0 version and see if you get the same error. in what context are you doing this?

**Comment by dryqiao** [comment]
I use `<script src="static/jsplumb.js"></script>`   It works!

**Comment by sporritt** [comment]
yes.  that's not really related to the original question, but anyway. i will close this i guess.
