### ISSUE TITLE
My page gets slower and slower when I append more objects

### ISSUE THREAD

**Issue by arisweb101** [jsplumb/jsplumb#754]
Hi Guys, I have 10 dynamic endpoint in every object. The problem is when I append like 3 to 5 object, the page gets slow. Does anyone have an idea why the page become slow and how to prevent it? Thank You in Advance :)

**Comment by arisweb101** [comment]
Does setSuspendDrawing(true); can help?

**Comment by sporritt** [comment]
what does "the page gets slow" mean?  slow to draw everything for the first time?
