### ISSUE TITLE
JSPlumb Resize also causes drag

### ISSUE THREAD

**Issue by websitewill** [jsplumb/jsplumb#756]
Posted this as a comment on an old issue that has already been closed. Creating a new issue for it. 

I recently stumbled upon this issue with the latest versions of jsPlumb and jquery-ui. Anyone know the fix?
I tried handling the drag stuff with JQuery-ui instead of jsPlumb, but when I do that, all my connections don't move with the thing being dragged.

I agree that this is a relatively "new" bug in jsPlumb. Also, sorry to drag up an old post, but it's the most relevant place I have found to ask about this.

Here is a jsfiddle for it: https://jsfiddle.net/sfzdb7k3/116/

Thanks,
Will

**Comment by mcottonra** [comment]
I'm having this exact same issue/behavior.

**Comment by sporritt** [comment]
this has been asked and answered several times. it isnt a bug.  you need to filter out the resize handle from the drag:

```
   instance.draggable($(".window"), {filter:".ui-resizable-handle"});
```

https://jsfiddle.net/sfzdb7k3/130/
