### ISSUE TITLE
detachAllConnections no longer exists?

### ISSUE THREAD

**Issue by Lambik** [jsplumb/jsplumb#757]
Hi,

The demo and the manual suggest that there is such a thing as "detachAllConnections" and "detachEveryConnection" (demo says it's on instance, manual on jsPlumb).

However, these functions no longer exist in the codebase...

Why is that, and could they be added in again?

**Comment by sporritt** [comment]
can you link me to the docs that discuss this? it was renamed to deleteEveryConnection or something (on my phone...cant find the actual method right now)

**Comment by Lambik** [comment]
Sure, I found it on https://jsplumbtoolkit.com/community/doc/removing.html#connections
And the demo that uses it is on https://jsplumbtoolkit.com/community/demo/draggableConnectors/index.html

**Comment by sporritt** [comment]
ok found it...it was renamed to `deleteConnectionsForElement` in 2.4.0.  the docs and the demo had stale references. fixed in 2.7.6, which was just released.

**Comment by Lambik** [comment]
Thanks!
