### ISSUE TITLE
Correct way of importing in a typescript environment?

### ISSUE THREAD

**Issue by Lambik** [jsplumb/jsplumb#758]
Hi,

I'm trying to use the library in a typescript setup. However, I'm probably too inexperienced, because I can't figure out how to import it.

```
import * as jsPlumb from 'jsplumb';

jsPlumb.ready(function () {
    alert('hoho');
});
```
Results in `Property 'ready' does not exist on type 'typeof jsPlumb'`. The same happens when I use `import {jsPlumb} from 'jsplumb';`

The construction `import 'jsplumb';` just says `Cannot find name jsPlumb`.

What's the correct way? (I already have the typings file, and the pathing is set up correctly)

**Comment by sporritt** [comment]
i've not actually used the community edition typings file in a typescript setup, but its structure is the same as the toolkit's typings file, and this is an example import statement from one of the toolkit's angular demos:

```
import { Dialogs, jsPlumbToolkit, jsPlumb, jsPlumbUtil  } from "jsplumbtoolkit";
```

so i'd be inclined to try

```
import { jsPlumb } from "jsplumb";
```

**Comment by Lambik** [comment]
I decided to let my (aurelia) framework handle the .ready part, because most likely the import is correct, but the definitions file is not fully compatible with the examples of non-ts code. I've opened another issue specifically for that question.

So yes, pretty sure your suggestion of import { } from '' is correct, thanks!
