### ISSUE TITLE
Typescript definitions file incomplete?

### ISSUE THREAD

**Issue by Lambik** [jsplumb/jsplumb#759]
Hi,

The index.d.ts file seems to be missing at least the jsPlumbUtil information, to use .uuid() for example.

Other details too, like when you do jsPlumb.getInstance() you cannot use 'EndpointHoverStyle', or 'EndpointStyle', and DragOptions does not support { cursor: 'pointer', zIndex: 2000 } (copied from an example not using typescript).

It's probably a manual labour to get the definitions file updated, but currently it's a bit hard to use the code in a typescript environment :-/

**Comment by sporritt** [comment]
these few things made it into a release recently. i'm sure more things will crop up one day.
