### ISSUE TITLE
Zoom doesn't zoom to current position in modals or in something position fixed and when page got scrollY

### ISSUE THREAD

**Issue by ElectronicaGitHub** [jsplumb/jsplumb#764]
You can simple reproduce it on main page https://jsplumbtoolkit.com/
adding to .jtk-demo-canvas
```
position:fixed;
top:0;
left: 0;
right: 0;
```
or just init in modal on window.scrollY about 500px

**Comment by sporritt** [comment]
if you are a toolkit licensee please email us.  this tracker is for the community edition.

jacking with the styles as you've done on that page doesn't indicate there's a problem.

closing - and clearing - the issue.
