### ISSUE TITLE
demo lists fall flat

### ISSUE THREAD

**Issue by liuyun1014** [jsplumb/jsplumb#765]
demo lists fall flat

**Comment by sporritt** [comment]
do you think you could perhaps provide more information?

**Comment by liuyun1014** [comment]
demo/lists/dom.html   can't the attachment 
Has this example passed the test?

**Comment by sporritt** [comment]
oh right. that isnt one of the demos yet. its just a bit of a prototype.

**Comment by liuyun1014** [comment]
My requirements are similar. The source and target are both  lists, and the connection does not move with the scroll bar.Is there any good solution

**Comment by sporritt** [comment]
there are various issues that have been created over time related to this but noone's ever provided a proper spec. right now there is no out of the box solution for this.

**Comment by liuyun1014** [comment]
Can the wire be positioned relative to the source and target
