### ISSUE TITLE
Is it possible to cancel draggable on child elements?

### ISSUE THREAD

**Issue by Zane-zetaris** [jsplumb/jsplumb#767]
Hi jsPlumb team,

Thanks for the amazing work first.

I am using draggable but I need to cancel the draggable on the child element, is there any to achieve this?

Thanks

**Comment by sporritt** [comment]
you mean you have some child of a node that you do not wish to cause the node to start dragging?  you can do that with the `filter` option on the `draggable` method call.

```
jsPlumb.draggable({
  ...
  filter:"button, .another-thing"
});
```

Here we instruct jsPlumb to ignore and drag that starts on an element matching `button` or `.another-thing`.

**Comment by Zane-zetaris** [comment]
Thanks a lot!
