### ISSUE TITLE
connections between nodes not being created sometimes

### ISSUE THREAD

**Issue by MohammedAbdulMateen** [jsplumb/jsplumb#768]
I'm using the following function to create a connection between two nodes (two HTML DOM elements not jQuery objects) on page load by getting the data from a database, note that the nodes are also created dynamically.

I'm running this code in an Angular 5 app to create a workflow (workflow designer page).

The connection is not created when I first go back from the designer page using the browser back button and then I navigate again to the designer, but when I hit refresh it works properly again. Please suggest a solution, I've attached a .gif demonstrating the issue.

expected behavior is it should work no matter how I navigate with in the application and the connections between the node should get created.

I've written a log to the console even when the issue occurs, the log is being written and the code is being called every time without any console errors.

```
            function createConnection(source, target, label) {
                console.log('create connection invoked');
                var conn = jsPlumb.connect({
                    source: source,
                    target: target,
                    label: label,
                    anchors: ['Bottom', 'Top'],
                    endpoint: 'Dot',
                    endpointStyle: { fill: 'black', radius: 5 },
                    paintStyle: { stroke: '#E6E6E6', strokeWidth: 5 },
                    connector: ['Straight'],
                    overlays: [
                        ['PlainArrow', { direction: 1, location: -1 }]
                    ],
                });

                $(conn.canvas).attr('id', conn.id);
                connections[conn.id] = { source: source, target: target, conn: conn };
                if (label !== undefined && label !== null && label.length) {
                    $(conn.canvas).data('faqdata', label);
                    connections[conn.id].label = conn.getLabelOverlay();
                    var labelCount = $(source).data('labelcount') || 0;
                    $(source).data('labelcount', ++labelCount);
                } else {
                    $(conn.canvas).data('faqdata', undefined);
                }

                var outwardConnCount = $(source).data('outwardconncount') || 0;
                $(source).data('outwardconncount', ++outwardConnCount);
                var inwardConnCount = $(target).data('inwardconncount') || 0;
                $(target).data('inwardconncount', ++inwardConnCount);

                validateNode(source);
                validateNode(target);

                return conn;
            }
```

![gif](https://user-images.githubusercontent.com/17563774/42747613-d531a1ee-88fa-11e8-8a71-8040753327b2.gif)

**Comment by MohammedAbdulMateen** [comment]
In order to fix this issue, I tried to destroy jsPlumb when user nagivates away from this designer page
```
function ngOnDestroy() {
    jsPlumb.clear();
}
```

I wasn't able to successfully try it out because the next time I'm going back to the page and when jsPlumb.connect({ ... }) is called I'm getting the following error in console - jQuery.Deferred exception: Cannot read property '0' of null TypeError: Cannot read property '0' of null

**Comment by abhirocks550** [comment]
@MohammedAbdulMateen see #611 looks similar. I hope that can help.

**Comment by sporritt** [comment]
closing. if this is still an issue in 5.x, feel free to reopen but please provide a codepen or jsfiddle.
