### ISSUE TITLE
document.getElementById requires that DOM nodes are already available in the document.

### ISSUE THREAD

**Issue by viswesh** [jsplumb/jsplumb#770]
Why is it that the [internal method 'getElement'](https://github.com/jsplumb/jsplumb/blob/master/dist/js/jsplumb.js#L14534) which returns an element have to be document.getElementById? Can the element be filtered from the registered container instead. For ex.) _currentInstance.getContainer()

I'm generating nodes/divs on the fly and they are not available in the DOM yet. But since getElement requires that the element is in the DOM, I have hit a wall. The alternative is I do jsPlumb related tasks after generating the DOM elements on the document but it would be nice if thats not a mandate.

**Comment by sporritt** [comment]
`getElement` is used to resolve an element from some specifier, which may be a string or it may already be a DOM element. The contract has always been that if it's a string then we assume it's the ID of some element and we use `document.getElementById`.

In your case, if you are generating elements on the fly, without the benefit of seeing the code I can't really see what the problem is. Surely you can just pass the element in to whatever you're calling?

**Comment by viswesh** [comment]
Thanks for the quick reply. I put together a [jsFiddle](https://codepen.io/viswesh/pen/OwvEOr) to explain better. 

In the fiddle (line 3), $container is overwritten to $('.visual') which is not available in the dom yet. Since nodes are not available in the DOM, jsPlumb would error out with 'Cannot establish connection - source does not exist'. But, if nodes are appended to $container (comment out line 3), jsPlumb will work because getElement method finds the node in the DOM.

Please clarify usage if I'm missing something.

**Comment by sporritt** [comment]
`$container` is not overwritten to `.visual` in that fiddle, it is actually overwritten to `visual`, which results in an empty reference:

```
$container = $container.find('visual');
```

you don't want `.visual` anyway, as you set the id on that element, you want `#visual`

```
$container = $container.find('#visual');
```

you also need to ensure the container element has position:relative or absolute.  

https://codepen.io/anon/pen/qyYMxW

**Comment by viswesh** [comment]
Thanks for the correction. That was my bad. 

What I was originally referring to was creating a div which is not appended to the DOM yet, running jsPlumb on the div and finally attaching it to the DOM. This is working. In the fiddle, I'm creating `'<div class="visual"></div>'`, adding child elements to it, transforming it through jsPlumb and finally appending to the DOM.

https://codepen.io/viswesh/pen/ejrLPx

**Comment by sporritt** [comment]
yep i know, and i still don't think all is necessarily lost for you if that's what you really need/want to do.

what you need to do is to use the elements as the reference to the connect call, not their ids:

https://codepen.io/anon/pen/VBxVLd

Here I've stripped back your original pen.  

`.visual` is created but not appended to anything:

```
var $container = $('<div class="visual"></div>'); 
```

the nodes are added with some positioning:

```
for (var node of nodes) {
    $container.append('<div id=' + node.id + '  class="item" style="left:' + node.l + 'px;top:' + node.t + 'px;">' + node.name + '</div>');   
}
```

an instance of jsPlumb is created and drawing is suspended (not necessary, strictly, but it prevents a  bunch of console errors from svg elements that are not visible):

```
jsPlumb.ready(function() {
  plumb = jsPlumb.getInstance({
    PaintStyle: { strokeWidth: 1 },
    Anchors: [["Left", "Right", "Bottom"], ["Top", "Bottom"]],
    Container: $container

  });
  var $nodes = $container.find(".item");
  plumb.draggable($nodes);

  plumb.setSuspendDrawing(true);
  
  _.each(links, function(link) {
    plumb.connect({
      source: $container.find("#" + link.from)[0],
      target: $container.find("#" + link.to)[0],
       connector: ["Bezier"],
      endpoints: ["Blank", "Blank"]
    });
  });
  
});
```

source and target are specified as elements, found from the container.

finally there's a click listener on the button that will append the container to the dom and repaint jsPlumb:

```
jsPlumb.on(document.getElementById("button"), "click", function() {
  $('.container').append($container)
  
    plumb.setSuspendDrawing(false, true);
});
```

note the 2nd argument to `setSuspendDrawing` instructs jsPlumb to `repaintEverything`.

incidentally in this second fiddle your own code has a bug in it that expects elements to already be in the DOM:

```
dg.nodes().forEach(function(n) {
    var node = dg.node(n);
    var top = Math.round(node.y - node.height / 2) + "px";
    var left = Math.round(node.x - node.width / 2) + "px";
    $("#" + n).css({ left: left, top: top });    <---------------

});
```


you should use the `$container.find(..)` approach here too; $("#something") expects `#something` to be in the page.

**Comment by viswesh** [comment]
@sporritt Thanks for your time and efforts. Loving jsplumb!
