### ISSUE TITLE
Flowchart connector is overlapping with node

### ISSUE THREAD

**Issue by wulucxy** [jsplumb/jsplumb#771]
![image](https://user-images.githubusercontent.com/5326403/43759003-8105327c-9a50-11e8-8ebd-e1e9ec8d50f6.png)

Hi, @sporritt I have a problem like this,  the connector is overlapping with the node。

the full settings is:

```
import { extend, clone } from 'lodash'

// globalTextColor
const globalGrayColor = '#90949c'
const whiteColor = '#fff'

// 基础设置
export const defaultSettings = {
  Connector: ['Flowchart', {
    alwaysRespectStubs: true,
    gap: 4,
    cornerRadius: 10,
    midpoint: 0.2,
    stub: 40
  }],
  ConnectionsDetachable: true
}

// 是否可 drop
export const dropNotAllowedStyle = {
  stroke: 'red',
  fill: 'red'
}

// 连接线样式
export const connectorStyle = {
  stroke: globalGrayColor,
  strokeWidth: 2
}

export const connectorOverlays = {
  connectorOverlays: [
    ['Arrow', { location: 1, length: 6, width: 12, height: 10, foldback: 1 }],
    ['Label', {
      location: 0.5,
      id: 'label',
      cssClass: 'aLabel',
      events: {
        click: (info) => console.log(info.label)
      }
    }]
  ]
}

export const disabledConnectorOverlays = {
  connectorOverlays: [
    [ 'Arrow', { location: 1, length: 6, width: 12, height: 10, foldback: 1 } ]
  ]
}

export const commonSettings = {
  endpoint: 'Dot',
  maxConnections: -1, // -1 means unlimited connections
  allowLoopback: false,
  paintStyle: {
    stroke: globalGrayColor,
    fill: whiteColor,
    radius: 4,
    lineWidth: 1
  },
  anchors: ['Static']
}

export const sourceSettings = extend({
  isSource: true,
  connectorStyle: connectorStyle,
  anchor: [1, 0.5, 0, 0, 0, 0]
}, commonSettings, {maxConnections: -1})

export const sinkSettings = extend({
  isTarget: true,
  anchor: [0, 0.5, 0, 0, 0, 0],
  connectorStyle: connectorStyle,
  onMaxConnections: function (info, e) {
    console.error('Maximum connections (' + info.maxConnections + ') reached') // eslint-disable-line
  },
  dropOptions: {
    // todo: dynamic检测
    // hoverClass: 'drop-hover',
    activeClass: 'drag-active'
  }
}, commonSettings, {maxConnections: -1})

export function getSettings (isDisabled = false) {
  let settings = {
    transformSource: {},
    transformSink: {}
  }
  if (isDisabled) {
    settings = {
      default: defaultSettings,
      commonSettings: extend(commonSettings, disabledConnectorOverlays),
      source: extend(sourceSettings, disabledConnectorOverlays),
      sink: extend(sinkSettings, disabledConnectorOverlays),
      transformSource: {},
      transformSink: {}
    }
  } else {
    settings = {
      default: defaultSettings,
      commonSettings: extend(commonSettings, connectorOverlays),
      source: extend(sourceSettings, connectorOverlays),
      sink: extend(sinkSettings, connectorOverlays),
      transformSource: {},
      transformSink: {}
    }
  }

  settings.transformSource = clone(settings.source)
  settings.transformSink = clone(settings.sink)

  return settings
}

```

do you have any advice on this?

**Comment by sporritt** [comment]
it's probably due to their being no orientation set on the anchor definitions in `sinkSettings` and `sourceSettings`:

```
export const sourceSettings = extend({
  isSource: true,
  connectorStyle: connectorStyle,
  anchor: [1, 0.5, 0, 0, 0, 0]
}, commonSettings, {maxConnections: -1})

export const sinkSettings = extend({
  isTarget: true,
  anchor: [0, 0.5, 0, 0, 0, 0],
  connectorStyle: connectorStyle,
```

I would try

```
anchor:[1,0.5,1,0]
```

for source

and

```
anchor:[0,0.5,01,0]
```

for sink.

**Comment by wulucxy** [comment]
@sporritt this don't work，what I want is like below：

![image](https://user-images.githubusercontent.com/5326403/43770890-30847bc6-9a70-11e8-86c7-8f58225ac19c.png)

and [flowchart demo ](https://jsplumbtoolkit.com/community/demo/flowchart/index.html) is great，I don‘t know what’s going wrong here。

may be I can send my source code to you，if you have time

**Comment by wulucxy** [comment]
@sporritt thanks you you reply，and this solved my problem。

but the orientation is hard to understand，why the source anchor need set dx to 1，and the target anchor is -1？

do you have any picture to show the reason?

thanks your your answer again。

**Comment by sporritt** [comment]
the orientation of an anchor indicates the general direction that edges from that anchor should travel in.  It's an [x,y] array, each of whose values can be -1, 0, or 1. 

your source anchor:

```
anchor:[1,0.5,1,0]
```
is positioned at x=1, y-0.5, and connections from it should travel to the right in the x axis (x orientation = 1). 

your sink anchor:
```
anchor:[0,0.5,-1,0]
```

is positioned at x=0, y=0.5, and connections from it should travel to the left in the x axis (x orientation = -1).  note that in my first response i had a typo:

```
anchor:[0,0.5,01,0]
```

it said "01" when it should have said "-1".

The flowchart connector needs these orientation values set in order to figure out the path it should follow. When you had your orientations all set to 0, the Flowchart connector couldn't draw something sensible.

Incidentally these two anchors are aliased as "Right" and "Left" in jsPlumb, as they are common use cases.


https://jsplumbtoolkit.com/community/doc/anchors.html
