### ISSUE TITLE
Typescript module and Endpoints selection API

### ISSUE THREAD

**Issue by rathish** [jsplumb/jsplumb#772]
Hi Team,

We are trying to build a automation editor using JsPlumb in Typescript but in recent version the Typescript module has been introduced which is good but it is not exposing all the APIs, for example we need to select the EndPoints using getEndPoints API but which is not exposed via Typescript module.  Can you please add this function so that we dont need to rework on downgrading the JsPlumb version.

Thanks,
Rathish

**Comment by sporritt** [comment]
oh right i thought you would do a PR

**Comment by antonverhoeven32** [comment]
Is there any example for Typescript?

**Comment by sporritt** [comment]
5.x is written in typescript. demos available at https://github.com/jsplumb-demonstrations
