### ISSUE TITLE
Connections Drawn only when dragging

### ISSUE THREAD

**Issue by tterpell** [jsplumb/jsplumb#773]
Hello,
I am new to jsPlumb and I think I have found a Problem:
The connections I add to my elements will not show up until i drag the elements around. See the Video for details: https://drive.google.com/file/d/1hgswkCjVh_fSQibLCsVwfkPiMsQeEJ_h/view?usp=sharing
Also, the connections will always start at the top left corner, even though i have configured them to be continuous. 

I Build my javascript via Java-Code, so this is what i execute:
`"<script>" +
                               "jsPlumb.setContainer(document.getElementById(\"diagramContainer\"));\n" +
                               "jsPlumb.Defaults.Anchor = \"Continuous\";\n" +
                               "jsPlumb.Defaults.Connector = \"Bezier\";\n" +
                               "jsPlumb.Defaults.Endpoint = \"Blank\";\n" +
                               "jsPlumb.Defaults.Overlays = [ [\"Arrow\" , { width:12, length:12, location:0.67 }] ];" +
                               "jsPlumb.ready(function() {" +
                               connectionJavascript[0] +
                               "});" +
                               "</script>");`
With connectionJavaScript being (for each of my needed connections):
`"jsPlumb.connect({" +
                                       "source:\"" + (lastEvent[0] != null ? lastEvent[0] : "START-EVENT") + "\"," +
                                       "target:\"" + map.get("eventname") + "\"" +
                                       "});";`

**Comment by sporritt** [comment]
This typically happens when the element you're drawing into is not visible when you draw into it. jsPlumb cannot compute the size/position of anything.  Closing this, you've probably fixed it by now given that I am commenting about six months after you opened the ticket...
