### ISSUE TITLE
Changing doNotRepaint in jsPlumb.remove() causes regression

### ISSUE THREAD

**Issue by Tilogorn** [jsplumb/jsplumb#780]
After updating from v2.6.9 to v2.8.0 I got some weird rendering errors. jsPlumb-Elements changing position which they didn't do before. I can try to fiddle it, I can send some screenshots, but maybe the following description is enough:

I installed the complete jsplumb build environment, checked out every commit since 2.6.9 and built the dist/js/jsplumb.js until I found out, which commit was causing the error.

It was commit b2bef7cb9944bc8a3701a8ba449a2bad7cf1b6c9 on May 7th. You changed `doNotRepaint` from `false` to `true` in `this.remove()`, see the [line 6253 of dist/js/jsplumb.js](https://github.com/jsplumb/jsplumb/blob/master/dist/js/jsplumb.js#L6253).

Then I browsed my callstack to see which method calls `this.remove()` and found out it is `this.stop()` with `_jsPlumb.remove(placeholderInfo.element, false, false);` in [line 8286 of dist/js/jsplumb.js](https://github.com/jsplumb/jsplumb/blob/master/dist/js/jsplumb.js#L8286).

As the function call is clearly wrong (`this.remove()` has only two parameters) I guess you forgot to adapt this function call to the new function signature and function of `this.remove()`. Am I right?

If I change line 8286 to `_jsPlumb.remove(placeholderInfo.element, true);` everything works fine.

**Comment by sporritt** [comment]
thanks for the detailed description. i will take a look.

**Comment by Tilogorn** [comment]
Any progress on this?

Meanwhile the wrong function call is here: https://github.com/jsplumb/jsplumb/blob/master/dist/js/jsplumb.js#L7734

```
if (placeholderInfo && placeholderInfo.element) {
     _jsPlumb.remove(placeholderInfo.element, false, false);
}
```
while the function signature stays
```

**Comment by Tilogorn** [comment]
Silly bug on my side, not worth explaining.
