### ISSUE TITLE
"loop" connection not acts normal 

### ISSUE THREAD

**Issue by linkun199011** [jsplumb/jsplumb#782]
How can I achieve "loop" connection as below.

![](https://wx2.sinaimg.cn/mw690/8926cc65gy1fvfrgokcc0j20ph0amwel.jpg)

**Comment by sporritt** [comment]
did you try using a Top anchor on the target and a Bottom anchor on the source?

**Comment by sporritt** [comment]
right, i see. it does this on the flowchart demo in the project too:

![image](https://user-images.githubusercontent.com/262720/45853879-2f82b880-bd8b-11e8-9540-e1c201517219.png)


whereas one from the side looks neater

![image](https://user-images.githubusercontent.com/262720/45853882-37425d00-bd8b-11e8-80ea-4d8a9e8ce4ac.png)

when you move them slightly out of alignment it paints more clearly

![image](https://user-images.githubusercontent.com/262720/45853895-4aedc380-bd8b-11e8-804a-0284c3f29e74.png)


but not what you want, i know.  the thing is what you are asking for, in a general sense, is for the path of the connector to avoid obstructions. i do not think this is something that would be added to the community edition of jsplumb.

**Comment by linkun199011** [comment]
Thank you for your reply, Much appreciated!

**Comment by linkun199011** [comment]
BTW, is there any chance that this feature will be added to the ToolKit-Edition of jsPlumb.

**Comment by sporritt** [comment]
yes it's quite likely that object avoidance will be added to the Toolkit edition. in an upcoming release we'll be adding support for users to drag the paths that the connections follow, and then once we have the ability for a user to do that then we can combine that with some object avoidance algorithm to route the connector paths automatically.

**Comment by linkun199011** [comment]
Wow, that would be great, looking forward to it !
