### ISSUE TITLE
Palette functionality

### ISSUE THREAD

**Issue by adamthomason** [jsplumb/jsplumb#783]
Excuse my ignorance here if I've missed an obvious piece of documentation somewhere. Does the community edition have any functionality around node palettes (dragging from a sidebar such as here: https://jsplumbtoolkit.com/demos/toolkit/groups/index.html)?

I appreciate this demo is highlighting the toolkit edition, although I wondered whether this might exist, albeit in a less-advanced way perhaps, in the community edition?

**Comment by sporritt** [comment]
No, there's no such thing in the community edition. you'll need to do that yourself.
