### ISSUE TITLE
How can I get all connections for selected block in jsplumb and marked all connection to be red.

### ISSUE THREAD

**Issue by krishna567** [jsplumb/jsplumb#784]
How can I get all connections when i select particular block from group and make all connections to be red?

I am using jsplumb to make flow chart and my requirement is that when i will click on any block so all the to and from connections needs to be turn red.

**Comment by sporritt** [comment]
use the `select` method to get some connections

https://jsplumbtoolkit.com/community/doc/querying.html

use "types" or just add a css class to make them go red

https://jsplumbtoolkit.com/community/doc/types.html

**Comment by krishna567** [comment]
Thanks.

By using get Connections method I am able to get only one connection but I have requirement that when i am selecting one block that all to and from line of selected block needs to  get red.

please see attached image suppose if i am clicking on block B then all to and from lines be turned red.

<img width="576" alt="flowchart" src="https://user-images.githubusercontent.com/31684094/45863477-f6027b00-bd93-11e8-9dc8-de548123ca6b.png">
