### ISSUE TITLE
Resizable window with text in it does not work 

### ISSUE THREAD

**Issue by jinglegit** [jsplumb/jsplumb#789]
Using jquery-ui.min.js, we can achieve resizable window feature. But once there are some content in the window, it is not resizable any more. For example, after setting innerHTML or innerText in a window, it is not resizable. Can we have a general resizable feature just similar to draggable? It is very important to have this feature because sometimes we have a lot of content in a window and need to enlarge it in UI to read it. Thanks!

**Comment by sporritt** [comment]
i've never really thought jsplumb needs to support element resizing. it tries to be as agnostic as possible about the html it is working with.

**Comment by sporritt** [comment]
closing this.
