### ISSUE TITLE
index.d.ts problem

### ISSUE THREAD

**Issue by niconico49** [jsplumb/jsplumb#790]
In the index.d.ts there are some problems:
1) some method get<> has void as return value type (it doesn't have any sense)
for example getSelector()
2) in the EndpointOptions there isn't the radius declaration (on the other hand in the StateMachine example
there is this kind of configuration: Endpoint: ["Dot", { radius: 2 }]

Could you please correct this kind of problem and give some typescript example in the demo too?

Thanks and Bye

**Comment by sporritt** [comment]
you should totally feel free to open a PR if you've got some good ideas about updates to that file.

**Comment by sporritt** [comment]
5.x is written in Typescript. .d.ts files are now up to date automatically.
