### ISSUE TITLE
Configure loopback connection to go around and not through div

### ISSUE THREAD

**Issue by attkk** [jsplumb/jsplumb#791]
Hey! I have parent div with child div as endpoint which I can drag and drop on parent div -> which will create loopback connection. 

parent div is configured like this:
```javascript
jsPlumb.makeTarget(document.querySelector('#div_id'), {
      endpoint: 'Rectangle',
      maxConnections: -1,
      anchor: [ 'Continuous', { faces: ['top'] } ],
      allowLoopback: true
    });`
```
and endpoint:
```javascript
jsPlumb.makeSource(document.querySelector('#div_id .endpoint_name_class'), {
        anchor: [0,1, 0, 0, 1],
        endpoint: 'Rectangle',
        maxConnections: 1,
        isSource: true,
      });
```

![image](https://user-images.githubusercontent.com/7917722/47166384-bda77b80-d304-11e8-9870-7feb284bbd43.png)

Everything works fine both manually and programmatically but loopback connection goes through div. Is there a way to configure this kind of connection to go from bottom around the div and hit the top? Thanks!

**Comment by attkk** [comment]
@sporritt

**Comment by attkk** [comment]
@sporritt can you help with this issue?

**Comment by attkk** [comment]
@sporritt

**Comment by sporritt** [comment]
hello, @attkk 

i hope you are doing well @attkk 

@attkk i think you need to use endpoints that are on adjacent faces in order to get the loopback to not cross through the div

@attkk

**Comment by attkk** [comment]
@sporritt sorry for pinging. Can you add more details what do you mean adjacent faces? The idea here is that endpoint which you can drag are at the bottom but div is a place where you can drop them and it will hit the top. Not sure I understand what you are trying to say :(

**Comment by attkk** [comment]
the idea is to make connection go from bottom endpoint to the top like this 
![image](https://user-images.githubusercontent.com/7917722/50658813-38e30a00-0fa3-11e9-859a-14633be8743c.png)

**Comment by sporritt** [comment]
i mean that for the flowchart connector if the source anchor is Bottom and the target is Right, i think you will get a loop. but i dont think it will draw a loop between Bottom and Top, since they are not adjacent. You could check the source in the connectors-flowchart.js file to verify this.

**Comment by attkk** [comment]
maybe you have any suggestion or recommendation how to achieve something like example on a picture above?

**Comment by sporritt** [comment]
this is essentially the same question as in this issue https://github.com/jsplumb/jsplumb/issues/782

you have to use adjacent faces, not opposite faces.
