### ISSUE TITLE
how to increase the clickable area for an onClick event on connector?

### ISSUE THREAD

**Issue by wulucxy** [jsplumb/jsplumb#792]
@sporritt 
![image](https://user-images.githubusercontent.com/5326403/47205709-47188580-d3b9-11e8-9948-a28843d2e529.png)

It's hard to choose the connector path，the question is how to increase the clickable area?

**Comment by sporritt** [comment]
use the `outlineWidth` and `outlineStroke` properties to create a border around the connector, like in this demo

https://jsplumbtoolkit.com/community/demo/flowchart/index.html

```
var connectorPaintStyle = {
            strokeWidth: 2,
            stroke: "#61B7CF",
            joinstyle: "round",
            outlineStroke: "white",
            outlineWidth: 2
        }
```
we use white and 2 pixels in this example. You could use `transparent` and something larger.

**Comment by sporritt** [comment]
i'm going to close this now.
