### ISSUE TITLE
Regression in connection rendering in 2.7.17

### ISSUE THREAD

**Issue by aurbano** [jsplumb/jsplumb#793]
I initially posted this as a reply on #780 but then realised it was a different bug.

When upgrading from [2.7.16 to 2.7.17](https://github.com/jsplumb/jsplumb/compare/2.7.16...2.7.17) (including all subsequent versions) a bug appears when rendering, incorrectly drawing angled connections.

<img width="533" alt="screenshot 2018-10-24 at 13 28 21" src="https://user-images.githubusercontent.com/2827818/47431890-d4caeb00-d794-11e8-89e9-e9c619ca9b1c.png">

#### jsPlumb Instance

```js
const jsPlumbInstance = jsPlumb.getInstance({
      Container: $containerRef, // defined somewhere else
      ConnectionsDetachable: false,
      ConnectionOverlays: [
        ['Arrow', {
          location: 1,
          width: 8,
          length: 6,
          foldback: 1,
        }],
        ['Label', {
          location: 0.1,
          id: 'label',
          cssClass: 'aLabel',
        }],
      ],
    });
```

#### Endpoints

```js
const dropOptions = {
  tolerance: 'touch',
  hoverClass: 'dropHover',
  activeClass: 'dropActive',
};

const sourceConfig = {
  filter: '.handle, .handle .icon',
  anchor: 'Continuous',
  endpoint: 'Blank',
  isSource: true,
  connector: ['Flowchart', {
    stub: [10, 10],
    gap: 5,
    cornerRadius: 3,
    alwaysRespectStubs: false,
  }],
  maxConnections: 1000,
  isTarget: false,
  dropOptions,
};

const targetConfig = {
  dropOptions: {
    hoverClass: 'dropHover',
  },
  endpoint: 'Blank',
  anchor: 'Continuous',
  isTarget: true,
};

jsPlumbInstance.makeSource(itemRef, sourceConfig);
jsPlumbInstance.makeTarget(itemRef, targetConfig);
```

#### Connections

```js
const connection = jsPlumbInstance.connect({
  source: sourceId,
  target: targetId,
  paintStyle: {
    strokeWidth: 2,
    outlineStroke: 'transparent',
    outlineWidth: 10,
  },
  label: null,
});
```

**Comment by aurbano** [comment]
@sporritt yes, up until 2.7.16 they were rendering like normal arrows, here is how the exact same chart looks using 2.7.16

<img width="509" alt="screenshot 2018-10-25 at 16 01 36" src="https://user-images.githubusercontent.com/2827818/47510095-52fbc000-d86f-11e8-9231-6bbac9001c4d.png">

I'm not sure if I can set up a simple jsFiddle or similar to reproduce this, as there is quite a lot of code involved in the system that generates it.

Do you have any ideas as to what could cause something like this? Maybe I can try some things or look into different parts of our codebase to try to figure out what the problem is.

**Comment by sporritt** [comment]
its a css thing. somehow the segments are getting a 'fill' applied to them. i would check the styles and try to see where that is coming from.

**Comment by aurbano** [comment]
@sporritt sorry for the late reply - you are correct :smile:

For some reason the `path` in our css had a `fill: inherit` property that must have been ported over...

Thanks!

**Comment by sporritt** [comment]
ok cool - thanks for the update.
