### ISSUE TITLE
Issue with elements with both static and makeTarget endpoint anchors

### ISSUE THREAD

**Issue by JomppeTuominen** [jsplumb/jsplumb#795]
- jsPlumb version: 2.8.3

- Link to jsFiddle: http://jsfiddle.net/xpvt214o/920350/

Hello,

I am trying to achieve a scenario where I could have elements inside a containing element. Every element has four endpoints (Left, Top, Right, Bottom). Every element also acts as a connection target.
I have encountered a problem, which the linked fiddle demonstrates.

**Steps to reproduce:**

1. Drag a connection from the red rectangle's endpoint to the blue rectangle's endpoint, connection is created normally, there should be no problems, this is the desired behaviour.

2. Create a third rectangle from the button in the top left. Now drop a connection on the new rectangle's endpoint. 

3. I would assume the connection would be created to the green rectangle's endpoint, but it is in fact created to the center endpoint of the pink rectangle, which is not desired. 

How to prevent this from happening?

**Comment by JomppeTuominen** [comment]
Forked master and fixed this particular issue, pull request: https://github.com/jsplumb/jsplumb/pull/796

**Comment by sporritt** [comment]
makeTarget no longer exists in 5.x. Closing.
