### ISSUE TITLE
How to Redraw Lines by Changing the Position of Endpoints through CSS

### ISSUE THREAD

**Issue by leavesdog** [jsplumb/jsplumb#800]

**Comment by sporritt** [comment]
i dont think it is possible to do this. anchor positions are specified in code.

**Comment by leavesdog** [comment]
> i dont think it is possible to do this. anchor positions are specified in code.

okay,Thank you very much for your reply.
I need this effect,Is there any other way to solve it? QAQ

**Comment by sporritt** [comment]
you could try something with endpoint types:

https://jsplumbtoolkit.com/community/doc/types.html#endpoint-type

to take the code snippet on there and make it something more like you need:

```
jsPlumb.registerEndpointTypes({
  "basic":{         
    paintStyle:{fill:"green"}
  },
  "hidden":{          
    paintStyle:{fill:"transparent"}
  }
});

var e = jsPlumb.addEndpoint("someElement", {
  anchor:"Right",
  type:"basic"
});

e.bind("click", function() {
  e.toggleType("hidden");
});
```

something like that might work for you here.
