### ISSUE TITLE
Ability to edit/load Bezier/StateMachine connector paths

### ISSUE THREAD

**Issue by aurbano** [jsplumb/jsplumb#801]
I've searched around but haven't been able to find anything relevant.

From the [roadmap](https://jsplumbtoolkit.com/roadmap.html) I can see there are plans to add this feature to the community edition. Do you have any estimates on this?

This feature would be very useful for us so I'd love to discuss it 👍

**Comment by sporritt** [comment]
There are no plans to add this to the community edition - the page you linked lists it as a possible addition to the Toolkit edition. We have done a lot of the work for this already. Something else just keeps popping up to prevent us from getting it over the line.

**Comment by sporritt** [comment]
closing this.
