### ISSUE TITLE
Running multiple versions of jsPlumb in the same application

### ISSUE THREAD

**Issue by pilifs** [jsplumb/jsplumb#802]
Hey,

I'm trying to run multiple jsPlumb versions in the same SPA using Webpack to manage the build. One version is 2.5.x (npm) and the other is 1.6.x (static file via script-loader). They are lazy loaded by their respective pages. When the user navigates from a page with old version to one with new and then back, or the other way around, we get an error.

The problem seems to be that both versions depend on conflicting variables in global namespace, regardless of how they are imported in application code. I tried hacking the source without much success. The only thing I can think of at this point is to force a page reload.

I found some discussion about the use of window from a couple of years ago (https://github.com/jsplumb/jsplumb/issues/314), but could not find anything newer than that. I'm wondering if anything has changed since then, or if I'm missing something here. Any advice or insight would be appreciated.

Thanks!

**Comment by sporritt** [comment]
i dont think you'll have much joy with this.  there are a few things declared on the global namespace and running two versions at once is bound to cause confusion.
