### ISSUE TITLE
How to draw Mutilple Edges with more nodes and groups in React?

### ISSUE THREAD

**Issue by Rain120** [jsplumb/jsplumb#803]
![image](https://user-images.githubusercontent.com/20939839/49932053-18bfae00-ff03-11e8-80e9-f7f3c594e7a8.png)
![image](https://user-images.githubusercontent.com/20939839/49932108-32f98c00-ff03-11e8-8743-74020a3a252b.png)

Environment：React + jsPlumb

Q: How to separate the above lines and dynamically set the color and Label values for the line？

**Comment by sporritt** [comment]
you can't reliably separate those lines to run alongside each other with the connectors that ship with jsplumb when they share endpoint locations. something like this would need a custom connector.

**Comment by Rain120** [comment]
Thx for your reply, I had finished the demo used echarts, bcs, I don't know how to separate those lines with jsplumb, but I will try to do that with your suggestion, thx very much!!!

**Comment by sporritt** [comment]
a custom connector is a reasonably complex undertaking. you might want to try separate endpoints first, if your design can support it.

**Comment by Rain120** [comment]
Yes, this work is more complicated, when I looked at the documentation and found that jsplumb could not meet my needs.

**Comment by sporritt** [comment]
i think i will close this then.

**Comment by Rain120** [comment]
OK, thx for your time.
