### ISSUE TITLE
How to stop overlapping node inside group ?

### ISSUE THREAD

**Issue by krishna567** [jsplumb/jsplumb#804]
I don't want to overlap one node to another node in Group, how can I achieve using jsplumb?
When we drag node inside group on any other node , after dropping it should not overlap with other node,  instead it should move on either side of  that node.
See this jsplumb in this one group is not overlapping each other whe you are dragging I want same behavior for node inside group.

https://jsplumbtoolkit.com/demos/toolkit/groups/index.html

**Comment by sporritt** [comment]
that's a toolkit edition demo. are you using the toolkit edition?

**Comment by krishna567** [comment]
How to know whether we are using toolkit edition or not?
May be I am using Jquery version.

**Comment by sporritt** [comment]
there is no jquery version anymore. if you dont know, then you are most likely using the community edition, which does not support layouts. so you'd need to achieve the separation of nodes yourself.

**Comment by krishna567** [comment]
How to achieve the separation of nodes? Can you give some idea?
