### ISSUE TITLE
How to make node as transparent when we drag node inside group or on any other node?

### ISSUE THREAD

**Issue by krishna567** [jsplumb/jsplumb#806]
In my project I have one requirement that If i drag node on any other node then it should show as transparent so  i can see the content of other node if its overlap to other node.

please check below link which shows , i want same behavior.

https://jsplumbtoolkit.com/community/demo/flowchart/index.html

**Comment by sporritt** [comment]
whenever a node is being dragged it gets a class of `jtk-drag` assigned.  that demo has a rule something like

```
.jtk-drag {
  opacity:0.8;
}
```

i dont know if that's the exact number. you can experiment.

**Comment by krishna567** [comment]
But I am not using toolkit version , so how can I achieve this?

**Comment by sporritt** [comment]
closing this. i think it's answered.
