### ISSUE TITLE
detachable: false does not work after 2.8.6 release

### ISSUE THREAD

**Issue by semanticfire** [jsplumb/jsplumb#809]
The update from 2.8.5 to 2.8.6 introduces a bug which causes the 'detachable:false' setting on connections and endpoints to not work at all.

Problem introduced with this commit:
https://github.com/jsplumb/jsplumb/commit/d6e7e0c40e52e216a7f336dd121359a66a029a21

**Comment by sporritt** [comment]
i can't reproduce this for endpoints. in the flowchart demo i changed the endpoint add code to this, for example:

```
var _addEndpoints = function (toId, sourceAnchors, targetAnchors) {
        for (var i = 0; i < sourceAnchors.length; i++) {
            var sourceUUID = toId + sourceAnchors[i];
            instance.addEndpoint("flowchart" + toId, sourceEndpoint, {
                anchor: sourceAnchors[i], uuid: sourceUUID, connectionsDetachable:false
            });
        }
        for (var j = 0; j < targetAnchors.length; j++) {
            var targetUUID = toId + targetAnchors[j];
            instance.addEndpoint("flowchart" + toId, targetEndpoint, { anchor: targetAnchors[j], uuid: targetUUID, connectionsDetachable:false });
        }
    };
```

and neither the connections made programmatically nor any new ones dragged with the mouse are detachable.

looks like i can reproduce the `detachable` flag being ignored on a `connect` call though.

**Comment by semanticfire** [comment]
Yes, it ignores the detachable flag on connect, should have mentioned that.

**Comment by sporritt** [comment]
functioning correctly in 5.x. previous versions now unsupported,
