### ISSUE TITLE
connector params is missing in ConnectParams object

### ISSUE THREAD

**Issue by abhirocks550** [jsplumb/jsplumb#812]
While I was trying to change default connector which Bezier to Straight. 

I used following piece of code 

``` j.connect({
      source: source1,
      target: destination1,
      endpoint: [
        'Blank',
        {
          // Mandatory parameters
          type: 'Dot',
          maxConnections: 10,
          parameters: {},
          connector: 'Straight',
          id: source1,
          scope: source1,
          reattachConnections: true,
        },
      ],
      anchors:["RightMiddle","LeftMiddle"],      
      overlays: [['Arrow', { width: 10, length: 10, location: 1 }]],
    }); 
```

this is not working.

When I debugged code I found out that function is looking for **params.connector** which is not available in current TypeScript definition.

Adding connector params solves the issue.

Raising #811 PR for the same.

**Comment by sporritt** [comment]
fixed by the supplied PR.
