### ISSUE TITLE
Error position calculation of draggable method

### ISSUE THREAD

**Issue by lx544690189** [jsplumb/jsplumb#814]
For example, when an element has a margin-left attribute, dragging the element adds an additional margin-left value to the final position of the element.

**Comment by lx544690189** [comment]
I use margin-left because it's easier to compute node locations in complex situations

here is the [demo](https://codesandbox.io/s/21m622785y) 
`
#flowchartWindow1 {
  top: 50px;
  left: 50px;
  margin-left: 50px;
}
`

**Comment by sporritt** [comment]
can you elaborate on what you said about margins making it easier to compute node locations?

**Comment by lx544690189** [comment]
> can you elaborate on what you said about margins making it easier to compute node locations?

I use left: 50% with margin-left and margin-right to symmetrically display nodes, which may not be a good way, but should not the margin value be taken into account when dragging elements?

**Comment by sporritt** [comment]
no, because a margin on an absolute positioned element doesn't make sense.  plus it's another property to read, and it's a property read that would cause a reflow too.

**Comment by sporritt** [comment]
i'm going to close this - margins on draggable elements will not be supported.
