### ISSUE TITLE
Problem with deleteConnection and delete element then ReConnect

### ISSUE THREAD

**Issue by Eniwder** [jsplumb/jsplumb#815]
I connect div elements and delete target element.
Next, I create deleted element and reconnect one.
Then, target's endpoint is fixed position(left:0, top:0).

In this case, I used only this method.
`instance.deleteConnection`

However, I append this code, so It works that I wanted.
`delete instance.getManagedElements()['TRG']`

This behavior is strange for me.

The problem can check this fiddle.
https://jsfiddle.net/93e6uwdf/1/

Is there any other solution?

Info
`instance.deleteEveryEndpoint` is worked because this method also delete managed element.
https://github.com/jsplumb/jsplumb/blob/3078d1f790944bc689c1a96fbb5f5b5f34c31a34/src/jsplumb.js#L1401

**Comment by mwaa** [comment]
Thank you @Eniwder  The appended code worked for me. 
This should be added in the deleteConnection, deleteConnectionsForElement and remove functions to ensure proper clean up once node is deleted

**Comment by sporritt** [comment]
@Eniwder when you say "delete target element" what do you mean, exactly, in terms of the code?

**Comment by Eniwder** [comment]
@sporritt 
First, I create connection by below code.
```
jsPlumbInstance.connect({
  source:'elem1',
  target:'elem2',
});
```
*elem1 and elem2 are defined as div in HTML
*some arguments are omitted

Then, elem2 no longer need and I delete it.
`$('#elem2').remove();`
This code means "delete target element".

At the time, I espect the connection is deleted together but  the code does not work as you know.
So I append below code to delete the connection and managed info.
```
jsPlumbInstance.deleteConnection(jsPlumbInstance.getConnections({source:'elem1'})[0]);
jsPlumbInstance.getManagedElements()['elem2'];
```

**Comment by sporritt** [comment]
you should use jsplumb's `remove` method to remove the element. there is no way for jsplumb to know it should have done anything if you use jquery to remove the element.

**Comment by Eniwder** [comment]
I use `jsPlumb.remove` but the broblem may not be solved.
https://jsfiddle.net/bpL6ozv7/1/

**Comment by sporritt** [comment]
may not be?

**Comment by jpruiz114** [comment]
@Eniwder, your solution seems to work as expected for me. Perhaps this ticket could be closed @sporritt?

**Comment by sporritt** [comment]
Yes I think I will close this issue then.  In the linked fiddle the method that removes the element does not actually use the correct instance of jsPlumb to do so, which is why it doesn't appear to work:

```javascript
function deleteElem1(id){
	$('#reborn').prop('disabled',false)
  jsPlumb.remove("e02");	
}
```

the fiddle creates an instance of jsPlumb - `firstInstance` - which is the instance on which the `remove` method should be called:

```javascript
function deleteElem1(id){
	$('#reborn').prop('disabled',false)
  firstInstance.remove("e02");	
}
```

The other delete method also references the global jsPlumb, and includes an unnecessary `deleteConnection` call (necessary here because the element was not removed by the correct instance):

```javascript
function deleteElem2(id){
	$('#reborn').prop('disabled',false);
	jsPlumb.remove("e02");
    firstInstance.deleteConnection(firstInstance.getConnections({source:'e01'})[0]);
  // need below code
  //delete firstInstance.getManagedElements()['e02']
}
```

This method should be:

```

```javascript
function deleteElem2(id){
	$('#reborn').prop('disabled',false);
	firstInstance.remove("e02");
}
```

I know the global `jsPlumb` instance confuses things from time to time. In 5.x there is no global instance anymore.
