### ISSUE TITLE
Typescript Example

### ISSUE THREAD

**Issue by jalutin** [jsplumb/jsplumb#817]
Hello,

I was impressed with this library and wanted to use in Typescript project.
I found one js example code in CodePen.
https://codepen.io/heyouxian/pen/GQddZX?page=1
However when I am going to use this code in typescript project.
It causes several errors.
For example, at below code, it blames to me that several params are missing for EndPoint options.
```instance.addEndpoint('dragDropWindow2', { anchor: "LeftMiddle" }, exampleEndpoint2)```

I tried to find the typescript sample in jsplumb doc however I am not sure what would be good example usage.
I would really appreciate if you can provide me a sample code of typescript for jsPlumb Community Edition.

**Comment by sporritt** [comment]
5.x is written in typescript. there are examples in the demo repo.
