### ISSUE TITLE
Where is document for community on website?

### ISSUE THREAD

**Issue by Tan90Qian** [jsplumb/jsplumb#818]
https://jsplumbtoolkit.com/community/doc/home.html
Yesterday I read documents on this page，and it is 404 now.
I found the document for toolkit has been reconstructed, then community version?

**Comment by sporritt** [comment]
you'll have to look at it in github for the time being

https://github.com/jsplumb/jsplumb/tree/master/doc/wiki

this is not permanent. just trying to figure out the best thing to do for the community edition.

**Comment by sporritt** [comment]
docs are here:


http://jsplumb.github.io/jsplumb/

**Comment by rookie-hhm** [comment]
Hi, [http://jsplumb.github.io/jsplumb](http://jsplumb.github.io/jsplumb/) and [https://docs.jsplumbtoolkit.com/community/current/index.html](https://docs.jsplumbtoolkit.com/community/current/index.html) both 404, where is document for community ?

**Comment by sporritt** [comment]
https://docs.jsplumbtoolkit.com/community/

**Comment by sporritt** [comment]
those are the 5.x docs, which is now on master.

the 2.x docs are here: [https://docs.jsplumbtoolkit.com/community-2.x/current/](https://docs.jsplumbtoolkit.com/community-2.x/current/)
