### ISSUE TITLE
ctx.querySelectorAll is not a function

### ISSUE THREAD

**Issue by czuroski** [jsplumb/jsplumb#820]
I'm trying to call addToGroup in order to add an element to a group that I have defined, but I keep getting the error mentioned above. 

```

j.addGroup({
            el: $('#' + id),
            id: groupid,
            droppable: true,
            dragOptions: {                
                filter: '.group-canvas'
            }
        });
j.addToGroup(groupid, $('#group-canvas"));

```

**Comment by sporritt** [comment]
are those jquery selectors? you should be using straight DOM elements.

**Comment by czuroski** [comment]
I've tried numerous approaches, including this - 

```
var canvas = $.parseHTML('<div id="' + id + '-canvas" </div>');
j.addToGroup(groupid, canvas);
```
using $.parseHTML should provide me with a valid dom element,  but I'm still getting the same error.

**Comment by sporritt** [comment]
https://api.jquery.com/jquery.parsehtml/

`$.parseHTML` returns an Array of nodes, not a single node.

**Comment by czuroski** [comment]
I've tried numerous variations on the approach - 

var canvas = $.parseHTML('<div id="' + id + '-canvas" </div>')[0];
j.addToGroup(groupid, canvas);

var canvas = $($.parseHTML('<div id="' + id + '-canvas" </div>'))[0];
j.addToGroup(groupid, canvas);

each of these should just return a single element of the array, but still throw the error.  Can you suggest another way of getting and passing the element?

**Comment by sporritt** [comment]
i dont mean to sound abrupt, but have you tried debugging through from this to see what the code does?

**Comment by czuroski** [comment]
Unfortunately, I haven't yet had an opportunity to debug the jsplumb code at all - that is next.  I am currently prototyping a UI and was hoping this was a recognizable issue that I would be able to quickly resolve.  I'll circle back on it when I get a chance to debug.

**Comment by sporritt** [comment]
i would try adding the element to the container before trying to add it to the group before you get out the debugger. i cant replicate this in the groups demo, although i can get a different error if i havent first added the new element to the dom.

**Comment by czuroski** [comment]
Thanks - I'll give that a shot.

**Comment by alhuber1502** [comment]
I'm encountering the exact same issue, have you found a solution for this?

**Comment by alhuber1502** [comment]
in my browser console I type:```jsPlumb_instance.getGroups()```
I get: 
`(3) [A, A, A]`
`0: A {id: "carthusian-group", connections: {…}, getEl: ƒ, getDragArea: ƒ, getAnchor: ƒ, …}`
`1: A {id: "deamico-group", connections: {…}, getEl: ƒ, getDragArea: ƒ, getAnchor: ƒ, …}`
`2: A {id: "dta-32407-group", connections: {…}, getEl: ƒ, getDragArea: ƒ, getAnchor: ƒ, …}`
`length: 3`

Then, I try to add an elemnt by its ID:
`jsPlumb_instance.addToGroup( "deamico-group", document.getElementById( "deamico-03920") )`

I get:
`Uncaught TypeError: a.querySelectorAll is not a function`
    `at a.jsPlumbInstance.getSelector (jsplumb.min.js:7)`
    `at A.v.getDragArea (jsplumb.min.js:6)`
    `at z.addToGroup (jsplumb.min.js:6)`
    `at a.jsPlumbInstance.<anonymous> (jsplumb.min.js:6)`
    `at a.jsPlumbInstance.c.addToGroup (jsplumb.min.js:6)`
    `at <anonymous>:1:18`

Any help appreciated!

**Comment by collabsoft** [comment]
I am having the same issue.  And I am afraid I am not seeing a solution to this anywhere including in this thread, so I am not sure why it would be closed.

**Comment by collabsoft** [comment]
//instance.addToGroup("group_one", $("#control1"));// throws **Uncaught TypeError: ctx.querySelectorAll** is not a function
        var control1 = document.getElementById("control1");
        instance.addToGroup("group_one", control1 );// throws **Uncaught TypeError: ctx.querySelectorAll** is not a function

**Comment by sporritt** [comment]
its unlikely this will get any attention at this point: i couldnt replicate it, and 2.x is now in maintenance mode.

**Comment by collabsoft** [comment]
Thanks.
I wouldn't mind using the newer version but documentation seems lacking.
And although I have followed links into the abyss (where most of them lead)
I cannot seem to find where the community edition is different now.
Any suggestions for a new jsplumb user?

**Comment by collabsoft** [comment]
I am trying to debug it BTX, and the function that is the problem is below.  As you can see i have added some debug items to see what is happening, and the weird thing is the jtk-scrollable-list that is the spec.  That is nowhere to be found in what I am building and I cannot see where it is getting set (in case anyone has any ideas).  The stack trace info is below...


 getSelector: function (ctx, spec) {
            var sel = null;
            console.log( ctx +" = ctx" );// [object HTMLDivElement] = ctx
            console.log( spec +" = spec" );// [jtk-scrollable-list] = spec
            console.log( arguments.length +" = arguments.length" );// **2 = arguments.length**
            console.log( ctx.nodeType +" = ctx.nodeType" );// 1 = ctx.nodeType
            
            if (arguments.length === 1) {
                sel = ctx.nodeType != null ? ctx : document.querySelectorAll(ctx);
            }
            else {
                sel = ctx.querySelectorAll(spec);
            }

            return sel;
        }




stack trace continued:

jquery-3.5.1.min.js:2 Uncaught TypeError: ctx.querySelectorAll is not a function
    at root.jsPlumbInstance.getSelector (jsplumb.2.14.3.js:15543)
    at Group.getDragArea.getDragArea (jsplumb.2.14.3.js:13066)
    at GroupManager.addToGroup (jsplumb.2.14.3.js:12770)
    at root.jsPlumbInstance.<anonymous> (jsplumb.2.14.3.js:13388)
    at root.jsPlumbInstance._jpi.addToGroup (jsplumb.2.14.3.js:13398)

As you can see the getDragArea is called right before the getSelector, and when it is called it sends "[jtk-group-content]" but the getSelector is called 6 times before that.  Just before the 7th run there is a failure.  An unidentified object with an undefined node type has slipped in somewhere.  On the subsequent run the proper GROUP_CONTAINER_SELECTOR is passed in, but by that time the failure has occurred.  

[object Object] = ctx
jsplumb.2.14.3.js:15532 [jtk-scrollable-list] = spec
jsplumb.2.14.3.js:15533 2 = arguments.length
jsplumb.2.14.3.js:15534 undefined = ctx.nodeType
jsplumb.2.14.3.js:3422 jsPlumb: fire failed for event manageElement : TypeError: ctx.querySelectorAll is not a function


var getDragArea = this.getDragArea = function() {
            //console.log( GROUP_CONTAINER_SELECTOR + " = GROUP_CONTAINER_SELECTOR");//[jtk-group-content] = GROUP_CONTAINER_SELECTOR
            var da = _jsPlumb.getSelector(el, GROUP_CONTAINER_SELECTOR);
            return da && da.length > 0 ? da[0] : el;
        };

**Comment by sporritt** [comment]
The project page contains a link to the 5.x documentation

https://docs.jsplumbtoolkit.com/community/

all of the demonstrations here are configured to work with 5.x:

https://github.com/jsplumb-demonstrations

**Comment by collabsoft** [comment]
Thanks sporritt.  I will give it a whirl.  I just want to be sure I am not messing up with licenses or anything, and want to be able to use the tool to do something great... or at least better than what I have done so far.  :)
