### ISSUE TITLE
How do I make the Bezier curve perpendicular to the target

### ISSUE THREAD

**Issue by wzqiang1332** [jsplumb/jsplumb#821]
![GIF](https://user-images.githubusercontent.com/20432873/54418218-34736400-473f-11e9-8a49-0808e21f12d4.gif)
I want the source and target of the line to be perpendicular to the node, regardless of its relative position. 
Is there a way to do that now?

**Comment by sporritt** [comment]
make use of the "orientation" of the anchors.  

http://jsplumb.github.io/jsplumb/anchors.html

in this case the anchor on `aa` could be like `[ 0.33, 1, 0, 1 ]` and the anchor on `bb` could be `[ 0.33, 0, 0, -1 ]`
