### ISSUE TITLE
Change cursor for crosshair when selected area.

### ISSUE THREAD

**Issue by leandrojo** [jsplumb/jsplumb#822]
When chosen "select mode" should be cursor for "crosshair" type.

**Comment by sporritt** [comment]
You're talking about one of the Toolkit demos?

**Comment by leandrojo** [comment]
yep
![image](https://user-images.githubusercontent.com/674449/54729108-6120e480-4b60-11e9-8f9c-a0a1e81508ab.png)

**Comment by leandrojo** [comment]
![image](https://user-images.githubusercontent.com/674449/54729166-bbba4080-4b60-11e9-82df-87e9d0388461.png)

**Comment by sporritt** [comment]
yeah idk, maybe. that's just an implementation detail of a demo though, not an issue with jsplumb itself, and its the Toolkit edition, which this tracker is not for. closing this.
