### ISSUE TITLE
Programmatically change connection targetid

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#826]
Is there a simple way to modify the targetid or the sourceid of a jsplumb connection (i.e to move a connection programmatically)? Or do we have to delete the current connection and create a new one? I've seen that we can assign the connection id programmatically, but I cannot manage to change these other properties.

**Comment by sporritt** [comment]
You'd use the [setTarget](https://docs.jsplumbtoolkit.com/community/apidocs/core.jsplumbinstance.settarget) method on `JsPlumbInstance` for this.
