### ISSUE TITLE
Endpoint-anchor located incorrect when drag the scrolling container or sort container

### ISSUE THREAD

**Issue by iGarym** [jsplumb/jsplumb#827]
Sorry if it's duplicate issue.

Version: 2.9.0
Demo: [jsfiddle](https://jsfiddle.net/ybp653e1/)

Reproduce step:
1. Scroll the list, make sure `scrollTop !== 0`
2. Drag the dragable item
3. Then the endpoint-anchor position is incorrect.

To resolve the question, i must set `scrollTop = 0` for scrolling container.
Is there a better solution?

**Another problem that may be similar**
Demo: [jsfiddle](https://jsfiddle.net/ybp653e1/3/)

Step:
1. Sort the list
2. Drag the dragable item
3. Then the endpoint-anchor position is incorrect.

In my understanding, the dom element is already cached in `managedElements`, the `updateOffset` method will reset the cache.

**Comment by sporritt** [comment]
@iGarym  you might be interested in this demo, which was added in 2.10.0:

https://jsplumbtoolkit.com/community/demo/lists/index.html

**Comment by iGarym** [comment]
> @iGarym you might be interested in this demo, which was added in 2.10.0:
> 
> https://jsplumbtoolkit.com/community/demo/lists/index.html

Well done!
