### ISSUE TITLE
Why don't connectorOverlays provide hiding and display methods?

### ISSUE THREAD

**Issue by helpceo** [jsplumb/jsplumb#830]
Viewing the documentation does not reveal the method's hidden and displayed methods!

**Comment by helpceo** [comment]
// jsPlumb.select({source:"potentiometer-bottom-left"}).hideOverlays();
  // jsPlumb.select({source:"potentiometer-bottom-left"}).showOverlays();

**Comment by sporritt** [comment]
this is not an issue in 5.x since the code is written in typescript
