### ISSUE TITLE
How to branch multiple different endpoints from one endpoint

### ISSUE THREAD

**Issue by Zhaolight** [jsplumb/jsplumb#831]
like A to A1 and  A to A2
![image](https://user-images.githubusercontent.com/17547899/56630028-53d8a780-6682-11e9-939b-ea46ce22b128.png)

**Comment by sporritt** [comment]
one endpoint can have multiple connections. you can set `maxConnections:-1` on it.

**Comment by sporritt** [comment]
i'm going to close this on the assumption that your question is answered.
