### ISSUE TITLE
connect by uuid, paintStyle not take effect

### ISSUE THREAD

**Issue by werbug** [jsplumb/jsplumb#836]
instance.connect({
                    uuids: uuids,
                    paintStyle: { stroke: 'green', strokeWidth: 10 },
                    hoverPaintStyle: { stroke: "red" },
})

**Comment by werbug** [comment]
hoverPaintStyle take effect，but paintStyle not

**Comment by sporritt** [comment]
that seems unusual. perhaps you can provide a codepen or jsfiddle demonstrating the issue?

**Comment by werbug** [comment]
> that seems unusual. perhaps you can provide a codepen or jsfiddle demonstrating the issue?

now i know why, because connector's config lower priority than endpoint's config.My connector's config was rewritten
