### ISSUE TITLE
How  to set color of jsplumb connections dynamically?

### ISSUE THREAD

**Issue by krishna567** [jsplumb/jsplumb#840]
In my project I have one requirement that to change the connection color when you click on block.
I have one block , I am able to get all in and out connections from that block using getConnections() method and it returns jsPlumb.Connection object but i am not able to set all the connections color dynamically.

Here is my code 
              newItem.click(function(e) {
                	var elementId = $(this).attr('id');
                	var inOutConnections=[];
                	var outConnections;              
                	var inConnections = jsPlumb.getConnections({ target: elementId });
                	for(var j=0;j<inConnections.length;j++){
                	inOutConnections.push(inConnections[j]);
                	}
                              	if(elementId.indexOf("-CONDITIONAL") != -1){
                		var div = $(this).find('.decisionDivs.adjustColumns')[0].childNodes;
                		for(var i=0;i<div.length;i++){
                			 outConnections = jsPlumb.getConnections({ source: div[i].id });
                			if(outConnections.length>=1){
                				inOutConnections.push(outConnections[0]);
                			}
                		}
                	}
                	else{
                		 outConnections = jsPlumb.getConnections({ source: elementId });
                		 for(var k=0;k<outConnections.length;k++){
                         	inOutConnections.push(outConnections[k]);
                         	}
                	}
                	for(var con=0; con<inOutConnections.length;con++){
                		console.log(inOutConnections[con]);

                });

Here  I have array inOutConnections which contains list of all connection of newItem division but i want to set all the connection color to red when i click on that division.

**Comment by sporritt** [comment]
connection "types" are probably the best way to approach a problem like this.

You can register types on an instance:

https://docs.jsplumbtoolkit.com/community/apidocs/core.jsplumbinstance.registerconnectiontype

and then activate them on connections:

https://docs.jsplumbtoolkit.com/community/apidocs/core.component.settype
