### ISSUE TITLE
addType() for connections results in "abandon" Overlays

### ISSUE THREAD

**Issue by exodus4d** [jsplumb/jsplumb#841]
jsPlumb: **v2.9.3**

#### Issue:
If a new connection **type** is added to an existing connection with `connection.addType()`, previous set connection **overlays** set by `connection.addOverlay()` get _ignored_ and stay _sticky_ on the map.

#### Reproduce:
1. Create a new connection between elements (I prepared them with `makeTarget()`/`makeSource()`)
2. Use `addType()` to apply a new connection type to it (for demonstration I used a type previously registered with `registerConnectionTypes()` ) that has an **overlay** definition. (the red "save mass" label)
3. Now add a 2nd **overlay** to  it. This one is **not** part of a type definition `con.addOverlay()` (the green Arrow overlay)
4. Until here its all fine! -> Dragging the source/target updates its connections and overlay positions...
5. Now add another type to it with `addType()` (for demonstration I used a type previously registered with `registerConnectionTypes()` ) that has **not** an overlay definition. (the yellow glow type for "active" connections on click)
6. Now, moving the source/target will **not** update the previously overlay set by `con.addOverlay()` 

Hint: You can see that the red label overlay (that belongs to a type definition) updated correctly on move. `con.getOverlays()` no longer lists the Arrow overlay.
![addtype_bug](https://user-images.githubusercontent.com/9299033/57980067-6eeecb00-7a26-11e9-9db5-a179fc8baf3f.gif)

#### Problem
- `addType()` calls `_applyTypes()`. Here we have a loop over the existing types, that merges the options for all types [#L3621](https://github.com/jsplumb/jsplumb/blob/master/dist/js/jsplumb.js#L3621). This seems to "ignore" overlays that set to it and **not** part of a type definition.

#### Workaround:
  **A:** Do not use `con.addOverlay()` for adding overlays. -> Register a new type with an overlay and add it `addType()`
  **B:** After `addType()` is called, and the _standalone_ overlay is "floating around". -> Reapply it from the cache (yes it is still there?!): `con.addOverlay(con.getCachedTypeItem('overlay', 'myOverlayId'))`

**Comment by sporritt** [comment]
it would be great to get this as a PR with a qunit test, i don't know if that appeals to you or not.

**Comment by sporritt** [comment]
i mean i know this was 2 years ago, after all....
