### ISSUE TITLE
Flowchart demo: cannot detach via drag from source

### ISSUE THREAD

**Issue by sporritt** [jsplumb/jsplumb#846]
this applies to connections made with the mouse only. connections made programmatically on page load can be detached via drag from source.

the current flowchart demo allows detach via drag from source for connections made with the mouse.

**Comment by sporritt** [comment]
the original issue here is fixed. now, though, for both source and target, if you detach a connection but put it back, after that detaching it and dropping it in whitespace will cause the connection to be reattached. this is not how the current production version works - it allows the connection to be detached after it has been put back one or more times.

**Comment by CristiCor** [comment]
I can't find a jsPlumb comunity with Angular 8 project implementation Drag & Drop connection
I can't simplify this to work:
https://stackblitz.com/edit/angular-jsplumb-test-rx8hdy

**Comment by sporritt** [comment]
this is an issue related to the upcoming 3.x release of jsplumb.

**Comment by sporritt** [comment]
all of the 3.x issues are locked now, so as to keep them focused.  

there are no angular integration examples for the community edition.
