### ISSUE TITLE
Cannot read property 'baseVal' of undefined

### ISSUE THREAD

**Issue by Fiv5** [jsplumb/jsplumb#854]
I use community edition in my react app. When I use jsPlumb.ready(() => { ..  }) in "useEffect" hooks , it throw error "Cannot read property 'baseVal' of undefined" because "document" has not the property "className".

**Comment by Fiv5** [comment]
I resolve this problem through manually assgined 'className' to document like: 
```jsx
 useEffect(() => {
    const { jsPlumb } = jsPlumbJS
    document.className = ''
    ....
}, [])
```

**Comment by sporritt** [comment]
although it's good your problem has gone away, I'm not entirely sure about what this fix has done.
