### ISSUE TITLE
Dynamically created elements not draggable

### ISSUE THREAD

**Issue by throne1986** [jsplumb/jsplumb#855]
I have a simple block its element is dynamically added to DOM, I want the user to be able to create a block and it should be draggable using jsplumb library.

Unfortunately, now I can create element but their not draggable but if I add them manually to the dom, it's draggable.

Here is what I have so far

    function addMovieButton() {
    
        var newMovieBlockButton = $("<div class='movie-button w'>Button New<div class='ep' action='begin'></div><div>");
    
    }

Here is plumb.js 

    jsPlumb.ready(function () {
    
        // setup some defaults for jsPlumb.
        var instance = jsPlumb.getInstance({
            Endpoint: ["Dot", {radius: 5}],
            Connector:"StateMachine",
            HoverPaintStyle: {stroke: "#1e8151", strokeWidth: 2 },
            ConnectionOverlays: [
                [ "Arrow", {
                    location: 1,
                    id: "arrow",
                    length: 14,
                    foldback: 0.8
                } ],
                [ "Label", { label: "FOO", id: "label", cssClass: "aLabel" }]
            ],
            Container: "canvas"
        });
    
        instance.registerConnectionType("basic", { anchor:"Continuous", connector:"StateMachine" });
    
        window.jsp = instance;
    
        var canvas = document.getElementById("canvas");
        var windows = jsPlumb.getSelector(".statemachine-demo .w");
        var windows_movie = jsPlumb.getSelector(".statemachine-demo .movie-block ");
    
        // bind a click listener to each connection; the connection is deleted. you could of course
        // just do this: jsPlumb.bind("click", jsPlumb.detach), but I wanted to make it clear what was
        // happening.
        instance.bind("click", function (c) {
            instance.deleteConnection(c);
        });
    
        // bind a connection listener. note that the parameter passed to this function contains more than
        // just the new connection - see the documentation for a full list of what is included in 'info'.
        // this listener sets the connection's internal
        // id as the label overlay's text.
        instance.bind("connection", function (info) {
            info.connection.getOverlay("label").setLabel(info.connection.id);
        });
    
        // bind a double click listener to "canvas"; add new node when this occurs.
        jsPlumb.on(canvas, "dblclick", function(e) {
          //  newNode(e.offsetX, e.offsetY);
        });
    
        //
        // initialise element as connection targets and source.
        //
        var initNode = function(el) {
    
            // initialise draggable elements.
            instance.draggable(el);
    
            instance.makeSource(el, {
                filter: ".ep",
                anchor: "Continuous",
                connectorStyle: { stroke: "#5c96bc", strokeWidth: 2, outlineStroke: "transparent", outlineWidth: 4 },
                connectionType:"basic",
                extract:{
                    "action":"the-action"
                },
                maxConnections: 6,
                onMaxConnections: function (info, e) {
                    alert("Maximum connections (" + info.maxConnections + ") reached");
                }
            });
    
            instance.makeTarget(el, {
                dropOptions: { hoverClass: "dragHover" },
                anchor: "Continuous",
                allowLoopback: true
            });
    
            // this is not part of the core demo functionality; it is a means for the Toolkit edition's wrapped
            // version of this demo to find out about new nodes being added.
            //
            instance.fire("jsPlumbDemoNodeAdded", el);
        };
    
        // suspend drawing and initialise.
        instance.batch(function () {
            for (var i = 0; i < windows.length; i++) {
                initNode(windows[i], true);
                console.log(windows[i]);
            }
            for (var j = 0; j < windows_movie.length; j++) {
                initNode(windows_movie[j], true);
                console.log(windows_movie[j]);
            }
    
       
        });
    
        jsPlumb.fire("jsPlumbDemoLoaded", instance);
    
    });

Here is live demo [live demo][1]

Here is plunker [full source code][2]

On the demo above just right click to add movie block for testing

Why does draggable not working for dynamically created elements?

  [1]: https://videomill-bot.audiencevideo.com/editor/
  [2]: https://plnkr.co/edit/mjCxW2g0k5jHRfUT

**Comment by sporritt** [comment]
draggable works for any element, either there on page load or added afterwards.

**Comment by sporritt** [comment]
that plunker is not loading jsplumb:

![image](https://user-images.githubusercontent.com/262720/59505972-e9ccc980-8e9e-11e9-8123-71f4000e6cae.png)


and the other app has a JS error:

![image](https://user-images.githubusercontent.com/262720/59506004-0963f200-8e9f-11e9-9ecd-22f6775c59b4.png)


closing this

**Comment by throne1986** [comment]
Hi sporrit , I added plunker to show source code , you can check it in live demo link,  just right click to create a new element and check it, it's not draggable for new2 created an element, please help :(

**Comment by throne1986** [comment]
Can you please tell me what am I doing wrong with my codes?? I

**Comment by sporritt** [comment]
after a right click and then add a movie block the code never actually calls `draggable(..)` on the new element.

**Comment by throne1986** [comment]
Ok, thanks for help bro, here is my function to create new movie block ;

function addMovieButton() {

    var newMovieBlockButton = $("<div class='movie-button w'>Button New<div class='ep' action='begin'></div><div>");

}

How do I call draggable function for new created elements?

**Comment by throne1986** [comment]
My bad the demo link for now works on incognito, so if you want to test  Just open the live demo in incognito right click and add new block u can see it not draggable. Thanks alot for this awesome library ,  am learning it, hope to get there soon.

**Comment by throne1986** [comment]
I solved the problem , thanks for this awesome plugin my brother, God bless your work

**Comment by aawajjoshi** [comment]
@throne1986, I am currently facing a similar issue. How did you solve it?
