### ISSUE TITLE
Problems with elelement created dynamically

### ISSUE THREAD

**Issue by throne1986** [jsplumb/jsplumb#856]
I asked a similar question before but someone closed it without even giving me the option to explain my problem :( 

I have a simple block its element is dynamically added to DOM, I want the user to be able to create a block and it should be draggable using jsplumb library.

Unfortunately, now I can create element but their not draggable but if I add them manually to the dom, it's draggable.

Here is what I have so far

    function addMovieButton() {
    
        var newMovieBlockButton = $("<div class='movie-button w'>Button New<div class='ep' action='begin'></div><div>");
    
    }

Here is plumb.js 

    jsPlumb.ready(function () {
    
        // setup some defaults for jsPlumb.
        var instance = jsPlumb.getInstance({
            Endpoint: ["Dot", {radius: 5}],
            Connector:"StateMachine",
            HoverPaintStyle: {stroke: "#1e8151", strokeWidth: 2 },
            ConnectionOverlays: [
                [ "Arrow", {
                    location: 1,
                    id: "arrow",
                    length: 14,
                    foldback: 0.8
                } ],
                [ "Label", { label: "FOO", id: "label", cssClass: "aLabel" }]
            ],
            Container: "canvas"
        });
    
        instance.registerConnectionType("basic", { anchor:"Continuous", connector:"StateMachine" });
    
        window.jsp = instance;
    
        var canvas = document.getElementById("canvas");
        var windows = jsPlumb.getSelector(".statemachine-demo .w");
        var windows_movie = jsPlumb.getSelector(".statemachine-demo .movie-block ");
    
        // bind a click listener to each connection; the connection is deleted. you could of course
        // just do this: jsPlumb.bind("click", jsPlumb.detach), but I wanted to make it clear what was
        // happening.
        instance.bind("click", function (c) {
            instance.deleteConnection(c);
        });
    
        // bind a connection listener. note that the parameter passed to this function contains more than
        // just the new connection - see the documentation for a full list of what is included in 'info'.
        // this listener sets the connection's internal
        // id as the label overlay's text.
        instance.bind("connection", function (info) {
            info.connection.getOverlay("label").setLabel(info.connection.id);
        });
    
        // bind a double click listener to "canvas"; add new node when this occurs.
        jsPlumb.on(canvas, "dblclick", function(e) {
          //  newNode(e.offsetX, e.offsetY);
        });
    
        //
        // initialise element as connection targets and source.
        //
        var initNode = function(el) {
    
            // initialise draggable elements.
            instance.draggable(el);
    
            instance.makeSource(el, {
                filter: ".ep",
                anchor: "Continuous",
                connectorStyle: { stroke: "#5c96bc", strokeWidth: 2, outlineStroke: "transparent", outlineWidth: 4 },
                connectionType:"basic",
                extract:{
                    "action":"the-action"
                },
                maxConnections: 6,
                onMaxConnections: function (info, e) {
                    alert("Maximum connections (" + info.maxConnections + ") reached");
                }
            });
    
            instance.makeTarget(el, {
                dropOptions: { hoverClass: "dragHover" },
                anchor: "Continuous",
                allowLoopback: true
            });
    
            // this is not part of the core demo functionality; it is a means for the Toolkit edition's wrapped
            // version of this demo to find out about new nodes being added.
            //
            instance.fire("jsPlumbDemoNodeAdded", el);
        };
    
        // suspend drawing and initialise.
        instance.batch(function () {
            for (var i = 0; i < windows.length; i++) {
                initNode(windows[i], true);
                console.log(windows[i]);
            }
            for (var j = 0; j < windows_movie.length; j++) {
                initNode(windows_movie[j], true);
                console.log(windows_movie[j]);
            }
    
       
        });
    
        jsPlumb.fire("jsPlumbDemoLoaded", instance);
    
    });

Here is plunker [full source code][2]

Please check my  live demo [live demo][1] On the demo above just right click to add movie block for testing and right click on the block you create, then check it if it's draggable 

Why does draggable not working for dynamically created elements?  can some one please tel what am I doing wrong?

  [1]: https://videomill-bot.audiencevideo.com/editor/
  [2]: https://plnkr.co/edit/mjCxW2g0k5jHRfUT

**Comment by sporritt** [comment]
it was me who closed the other issue, because neither the plunker nor the live demo actually worked.  i am closing this one too as it is a duplicate and i have added another comment on the original.
