### ISSUE TITLE
endpoints not connecting

### ISSUE THREAD

**Issue by greenta** [jsplumb/jsplumb#858]
Hi guys, first thank you for such a rich library, I'm trying to learn how to use it efficiently with angular (which also is kinda new to me), I'm trying to give to the user the ability to create, drag and connect multiple nodes, I'm to trying to achieve what I already achieved in [**this simple HTML page**](https://jsfiddle.net/greenwa/tLyuszfh/10/), but this time [**here**](https://stackblitz.com/edit/angular-jsplumb-test) with Angular.
First I was struggling with making the new divs draggable, I managed to do that but now I can't get my divs to connect, I can drag the line from the source but it doesn't connect when dropped on the target.
Not sure if the problem is with jsplumb or angular so thanks for any help or explanation

**Comment by CristiCor** [comment]
I'm struggling with the same situation .. i think here is the answer .. 
https://github.com/jsplumb/jsplumb/wiki/dragging
but.. we must digg..

**Comment by greenta** [comment]
@CristiCor I fixed it, it has something to do with the instances used in your page, I posted my answer [here](https://stackoverflow.com/questions/56849220/dynamically-dragging-and-connecting-created-nodes-in-angular6-with-jsplumb/56950453#56950453). I hope it helped.
