### ISSUE TITLE
Dragging Multiple Elements got error: "Uncaught TypeError: Cannot read property '0' of null"

### ISSUE THREAD

**Issue by chbin12** [jsplumb/jsplumb#859]
ver:jsplumb-2.10.2
I had try out both instance.addToPosse() and instance.addToDragSelection() method, when draging node got the error log below. help:( thanks!
jsplumb.js:2191 Uncaught TypeError: Cannot read property '0' of null
    at Drag.moveBy (jsplumb.js:2191)
    at jsplumb.js:2594
    at _foreach (jsplumb.js:1651)
    at root.Katavorio.updateSelection (jsplumb.js:2594)
    at Drag.<anonymous> (jsplumb.js:2013)

**Comment by sporritt** [comment]
if you could provide a jsfiddle or something it would be helpful.

**Comment by chbin12** [comment]
I case is when press Shift key and drag root node, all low level nodes which connected by root node move together.
I think my mouse event logical conflict with jsplumb event.
code:
node.on('mousedown', function (ev) {
        node.focus();
        node.on("keydown", function (e) {
            if (e.which == 16) {
                //shift
                var list = flowChartKit.getAllLowerNodes(node.id);
                instance.addToPosse(list);
                node.off("keydown");
            }
        });
    });

**Comment by sporritt** [comment]
you will need to provide a jsfiddle or something.

**Comment by chbin12** [comment]
[myflowchart.zip](https://github.com/jsplumb/jsplumb/files/3364553/myflowchart.zip)
Please unzip the  myflowchart.zip and place it into the jsplumb's demo folder, open index.html then press shift key and drag node, console error log will appeared.
I add some codes at the end of  demo.js. Thanks!

**Comment by sporritt** [comment]
closing since it's a couple of years old now and we're moving to 4.x. if still an issue in 4.x feel free to reopen.
