### ISSUE TITLE
Cannot establish connection - source does not exist

### ISSUE THREAD

**Issue by throne1986** [jsplumb/jsplumb#860]
I have a simple section in which users can connect from one element to another element as they wish. after connection can be like this. am using jsPlumb for connections

[![enter image description here][1]][1]

After connections, if the user is satisfied he/she can save it,

everything is saved correctly as I want, now when user reload the page connections eg (con_6, con_18) are not displayed   

Here is live demo :[live demo][2]

Here is js plumb connect function documentation: [js plumb connect][3]

  [1]: https://i.stack.imgur.com/nDmxZ.png
  [2]: https://videomill-bot.audiencevideo.com/editor/?settings2
  [3]: https://community.jsplumbtoolkit.com/doc/connect-examples.html

Here is json where the data are saved 

    {
        "movies": [
            {
                "left": 237,
                "top": 99,
                "movieid": "51"
            },
            {
                "left": 241,
                "top": 263,
                "movieid": "10"
            },
            {
                "left": 746,
                "top": 184,
                "movieid": "12"
            }
        ],
        "connections": [
            {
                "buttonid": "0",
                "movieid": "12"
            },
            {
                "buttonid": "4",
                "movieid": "12"
            }
        ]
    }

Here is my function to load my connections
    

    $.getJSON('datasaved/settings2.json', function (data) {
        
            var flowchartconnection =data.connections;
    
            for( var j = 0; j < flowchartconnection.length; j++ ) {
                
                console.log(flowchartconnection[j].buttonid);
    
                jsPlumb.connect({ source: flowchartconnection[j].buttonid, target: flowchartconnection[j].movieid });
                console.log(jsPlumb.connect);
    
    
            }
    
    
        });

Unfortunately, I am getting the following error:

> Cannot establish a connection - source does not exist

What is wrong with my code?

**Comment by sporritt** [comment]
the obvious first question is whether or not the dom elements do exist before you try to connect them.

**Comment by throne1986** [comment]
Hii, Here is my console.log  from my live demo : https://videomill-bot.audiencevideo.com/editor/


[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/9HJRV.png

As you can see on the console the source and target id is available on the  DOM before the connections happen,

Can you please tell me what am I doing wrong? 

Thank you for this great library

**Comment by sporritt** [comment]
the elements ids in the dom are like `moviebutton0` `moviebutton1` etc, but you are just trying to connect `0` and `1`. you need to add that "moviebutton" prefix to the buttonid field when you make the connect call.

**Comment by throne1986** [comment]
Your right bro, now it displays like this 

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/8FANA.png

Here is a function to save the flow to json

`
function saveFlowchart(){
    var connections = [];
    $.each(instance.getConnections(), function (idx, connection) {
        console.log(instance.getConnections());
        connections.push({
            connectionId: connection.id,
            buttonid: connection.sourceId,
            movieid: connection.targetId,
        });
    });
    return connections;
}    `


Here is a function to load the flow from json

`     
            var flowchartconnection =data.connections;

            $.each(flowchartconnection, function( index, elem ) {
                 var connection1 = jsPlumb.connect({
                    source: elem.buttonid,
                    target: elem.movieid,
                    anchor: "Continuous",
                    
                });
            });`

Here is live demo: https://videomill-bot.audiencevideo.com/editor/?settings2

why my connection after save and refresh the page goes beyond the target element?

**Comment by sporritt** [comment]
have you set the container correctly?

http://jsplumb.github.io/jsplumb/home.html#container

**Comment by throne1986** [comment]
Thanks a lot, brother, God bless ya hand, it works like charm now, a wonderful library, I love it, you can close the issue
