### ISSUE TITLE
Prevent movement of anchors during drag and drop

### ISSUE THREAD

**Issue by Jon-Murray** [jsplumb/jsplumb#862]
Hi,

   We are trying to prevent a default behaviour in jsplumb. This can be seen in the sample workflow element https://jsplumbtoolkit.com/demos/toolkit/flowchart-builder/index.html

when you load this page, if you drag the "do something" node to the left, the connector anchors to the top. It starts like this:

![image](https://user-images.githubusercontent.com/2168795/61482895-9238e680-a993-11e9-9864-cf6dfc3211c2.png)

And then ends up like this:

![image](https://user-images.githubusercontent.com/2168795/61482933-a54bb680-a993-11e9-9512-79bd12f8ddcb.png)

We have a situation whereby users can drop connections to the top, left, bottom, or right of nodes. However, once these are drawn once (via drag and drop) we don't want them to automatically move when the node's position is moved around. ie. if they draw a connection from the bottom of node A to the top of node B, then node B is moved above node A, the connection should still remain from bottom of A -> top of B. 

We have had some luck by setting the "anchor": "Continuous" and "Anchors":['Bottom', 'Continuous'] but as soon as we add more in (ie. "Anchors":['Bottom', 'Top', 'Right', 'Left' 'Continuous']) it just anchors to the bottom, and will never go to another node regardless of the position (even if it *should* draw to the left or right for example).

Is there any way to disable the automatic recalculation of anchor positions when the parent node is moved about?

Thanks

**Comment by sporritt** [comment]
this is not a tracker for the toolkit edition.  please contact us via email instead.
