### ISSUE TITLE
连线时，滚动条问题

### ISSUE THREAD

**Issue by ranxiaoli** [jsplumb/jsplumb#863]
页面上有滚动条且两个节点距离比较大，并且节点不能移动，当我从源节点开始连连时，就必须要用鼠标滑轮将滚动条下拉到目标节点才能连线，但是一旦我用到了鼠标滑轮，线条与我的鼠标就对不齐了，相差一个滚轮距离的高度了

**Comment by sporritt** [comment]
如果在4.x中这仍然是您的问题，我可以看一下。

**Comment by Choi-Keith** [comment]
我在用2.14.6版本的时候也遇到这个问题，请问4.x版本解决了吗？怎么解决？

**Comment by sporritt** [comment]
我认为没有将任何特定的代码添加到4.x来处理此问题。 我的意思是，在2.x中不会对此进行修复，因此，如果在4.x中存在问题，那么我们可以考虑对此做一些事情。

**Comment by Choi-Keith** [comment]
好的，谢谢您的回复，希望能修复这个问题，因为滚动条滚动问题在应用程序中是比较常见的

**Comment by sporritt** [comment]
4.x中有问题吗？ 我的意思是似乎是这样。 但还没有人尝试过。 我希望有人会尝试。

**Comment by sporritt** [comment]
![jsplumb-drag-scroll](https://user-images.githubusercontent.com/262720/112589092-9dc0fe00-8e54-11eb-8d93-0c7b94a8e697.gif)

This is how 4.x currently behaves - when you scroll, the element moves away from the cursor. When you move the cursor again, the element follows the cursor.

这就是4.x当前的行为-滚动时，元素从光标移开。 当您再次移动光标时，该元素将跟随光标。

**Comment by sporritt** [comment]
![jsplumb-drag-scroll](https://user-images.githubusercontent.com/262720/112589275-f09ab580-8e54-11eb-8090-4d616dfa3859.gif)

**Comment by sporritt** [comment]
This is how 4.x currently behaves - when you scroll, the element moves away from the cursor. When you move the cursor again, the element follows the cursor.

这就是4.x当前的行为-滚动时，元素从光标移开。 当您再次移动光标时，该元素将跟随光标。

**Comment by sporritt** [comment]
In development it now behaves like this (this is not yet released):

在开发中，它现在的行为如下（尚未发布）：

![jsplumb-drag-scroll-new](https://user-images.githubusercontent.com/262720/112691550-9a1f8c80-8ed1-11eb-8717-686f21105383.gif)

**Comment by sporritt** [comment]
this has been published in version 4.0.0-RC79 this afternoon
