### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by tarik-ayoub** [jsplumb/jsplumb#867]
I am somewhat confused about the licensing rules for this project. I've read [this issue](https://github.com/jsplumb/jsplumb/issues/398) and I'm aware that it is up to me to choose which version to use.

As I understand it, I can choose to use it as MIT license and by doing so I can use it in my commercial application (even closed source).

I got confused though with this phrase on the [website](https://jsplumbtoolkit.com/demos.html) that says: The Community edition is a **view** technology **only**.

Can I still use the library to build and display my own diagrams?

**Comment by sporritt** [comment]
that just means its not backed with a graph like the toolkit edition is. with the toolkit edition most of the operations occur directly on the dataset and the rendering, and dom, is abstracted away.

**Comment by sporritt** [comment]
so - yes, you can.
