### ISSUE TITLE
makeSource click event isn't functional before connect

### ISSUE THREAD

**Issue by JerryX** [jsplumb/jsplumb#871]
when I use makeSource function like this
`
jsPlumb.makeSource('left0', config);
jsPlumb.makeTarget('right0', config);
`
the  <i id='left0' onclick='show()'></i>  element's click function can't be trigger untill I drag a line from this element. How can I trigger the show() function just after jsPlumb.makeSource('left0', config);

**Comment by sporritt** [comment]
if the whole element is a drag source it doesnt surprise me that the click event is consumed. is that what you mean is happening? you have bound a listener to a click event on the element and it is never called?

**Comment by JerryX** [comment]
![QQ图片20190821100928](https://user-images.githubusercontent.com/3296784/63397066-e81e0580-c3fb-11e9-8cc8-61b02a078328.png)
here is the init code
`
jsPlumb.ready(function () {
    jsPlumb.makeSource('left0', config);
    jsPlumb.makeTarget('right0', config);

    jsPlumb.makeSource('left1', config);
    jsPlumb.makeTarget('right1', config);

    jsPlumb.makeSource('left2', config);
    jsPlumb.makeTarget('right2', config);

    jsPlumb.makeSource('left3', config);
    jsPlumb.makeTarget('right3', config);
});
`

**Comment by sporritt** [comment]
Closing. 5.x doesn;' have `makeSource`/`makeTarget`. This issue would not occur.
