### ISSUE TITLE
Endpoints jump to top left 

### ISSUE THREAD

**Issue by obaid** [jsplumb/jsplumb#872]
I am using this within react and whenever I delete the node from react and remove all connections, the endpoints on all nodes that were connected with the deleted node jump to the top left of the container.

I am going to try to get a JSFiddle to reproduce this error but just wondering if there is anything that I am missing in my setup.

**Comment by mwaa** [comment]
@obaid am facing the same challenge. When deleting the node add the piece of below. Ref #815 
`delete instance.getManagedElements()['id_of_node']`

**Comment by liyuchuan86** [comment]
not work in vue

**Comment by bereziuk** [comment]
Unfortunately, this problem still occurs.

**Comment by sporritt** [comment]
if this can be reproduced with 5.x feel free to reopen.
