### ISSUE TITLE
Is it possible to show a visual indicator at the edge crossing point to tell "not connected"? 

### ISSUE THREAD

**Issue by ilovepumpkin** [jsplumb/jsplumb#873]
Currently, if two edges are crossing, we can not tell they are connected or not. 

![image](https://user-images.githubusercontent.com/11310645/65216945-2a169600-dae5-11e9-836a-d70b09ed2e87.png)

It is possible to show a visual indicator at the crossing point so the two states "connected" and "not connected" can be recognized? 
![image](https://user-images.githubusercontent.com/11310645/65216993-4ca8af00-dae5-11e9-884f-f2c6a88c906d.png)

**Comment by sporritt** [comment]
This isn't something that's on the roadmap for the Community edition. I'm sure it possible...anything is possible with a computer. But I think it is unlikely to go into the Community edition.

**Comment by ilovepumpkin** [comment]
@sporritt okay, I got it. Thanks for your prompt response!

**Comment by sporritt** [comment]
you can use an outline style to mimic this, like in the flowchart demo:

https://jsplumbtoolkit.com/community/demo/flowchart/index.html

![image](https://user-images.githubusercontent.com/262720/65370092-20a83d80-dc4d-11e9-8c88-4ef6c6e66b21.png)

**Comment by sporritt** [comment]
```
connectorPaintStyle = {
            strokeWidth: 2,
            stroke: "#61B7CF",
            joinstyle: "round",
            outlineStroke: "white",
            outlineWidth: 2
        }
```
