### ISSUE TITLE
Adding Endpoint with ContinuousBottom

### ISSUE THREAD

**Issue by sikemullivan** [jsplumb/jsplumb#875]
Adding a new endpoint when using ContinuousBottom, results in the dot rendering at the top left of the page. In the following screenshot, "newroute" is showing at the top left of the parent container. The red arrow shows where it should be located. 

FYI, if I drag the card, the endpoint will then snap to the correct position. 

![image](https://user-images.githubusercontent.com/23320600/66728161-df005200-ee08-11e9-8485-44c672f6ee2b.png)

**Comment by sporritt** [comment]
are you able to reproduce in a code pen? is it definitely only ContinuousBottom that does this in your app?

**Comment by sikemullivan** [comment]
https://stackblitz.com/edit/angular-jsplumb-test-vneeof

**Comment by sporritt** [comment]
oh it's angular?  you probably need to revalidate the node at some point when it has been painted.

**Comment by sikemullivan** [comment]
jsplumb.repaint("elementId") solves the issue. Thanks
