### ISSUE TITLE
Exporting the graph visible on the surface to PNG (Vue2 Integration)

### ISSUE THREAD

**Issue by rhaicode** [jsplumb/jsplumb#877]
I have tried using a third-party library, html2canvas, that captures a 'screenshot' based on DOM elements being rendered. More details can be seen from this issue: 

https://github.com/niklasvh/html2canvas/issues/2040

What I am thinking now is instead of doing a DOM screenshot, I want to get the data of the graph of surface, most likely an `exportData()` function as referenced from the docs (link below) then just programmatically generate an image.

https://docs.jsplumbtoolkit.com/toolkit/current/articles/loading-and-saving-data

On the 'Exporting' part, instead of  `jsPlumbToolkit.newInstance()`, I want to use the current Instance that I am using for rendering. I have looked at the docs for Vue2 Integration but can't seem to find a support for that one.

Support for this matter is highly appreciated. thisrhaidzsalali@gmail.com

**Comment by sporritt** [comment]
Locking this pending further communication.  This repository is not for the Toolkit edition.

**Comment by sporritt** [comment]
Closing this out. After some discussion it was decided export to PNG was not what was actually required in this case.
