### ISSUE TITLE
JSPlumb connectorStyle can't be applied after using lastest version

### ISSUE THREAD

**Issue by danieljd** [jsplumb/jsplumb#878]
Before ,I use jsplumb 1.3.16 version, and everything is ok like this . But when I switch version to the lastest version 2.12.3. The connector style can't be applied.

var connectorPaintStyle = {
      lineWidth: 3,
      strokeStyle: "#229900",
    },
    connectorHoverStyle = {
      lineWidth: 3,
      strokeStyle: "#2e2aF8"
    },
    sourceEndpoint = {
      endpoint: "Dot",
      paintStyle: {
        fillStyle: "#225588",
        radius: 1
      },
      isSource: true,
      maxConnections: -1,
      connector: ['Bezier', {curviness : 20}],
      connectorStyle: connectorPaintStyle,
      hoverPaintStyle: connectorHoverStyle,
      connectorHoverStyle: connectorHoverStyle,
      dragOptions: {}
    },
    bottomSource = jsPlumb.extend(
        {
          anchor: 'BottomCenter'
        },
        sourceEndpoint
      ),
   targetEndpoint = {
        endpoint: 'Dot',
        paintStyle: {
          fillStyle: '#558822',
          radius: 1
        },
        hoverPaintStyle: connectorHoverStyle,
        maxConnections: -1,
        dropOptions: {
          hoverClass: 'hover',
          activeClass: 'active'
        },
        isTarget: true,
        anchor: ['TopCenter']
      };

var sourceEndpoints = jsPlumb.addEndpoint(windows, bottomSource),
      targetEndpoints = jsPlumb.addEndpoint(windows, targetEndpoint);
 
  jsPlumb.bind('jsPlumbConnection', function(connInfo) {
      init(connInfo.connection);
  });

 $edges.each(function() {
      var c = $(this).attr('xxx');
      jsPlumb.connect({
        source: sourceEndpoints[antiWindows[c[0]]],
        target: targetEndpoints[antiWindows[c[1]]],
        deleteEndpointsOnDetach: false
      });
    });
Before 
![image](https://user-images.githubusercontent.com/26050414/67742337-c0c86200-fa56-11e9-979e-87df804f5410.png)
After:
![image](https://user-images.githubusercontent.com/26050414/67742367-d3db3200-fa56-11e9-9789-61f68b7c5903.png)

**Comment by sporritt** [comment]
please migrate to 4.x

https://www.npmjs.com/package/@jsplumb/community
