### ISSUE TITLE
Cannot clear the offset position cache when dynamically moving a node.

### ISSUE THREAD

**Issue by AdamJessop** [jsplumb/jsplumb#880]
See the codepen for an example and demo:
https://codepen.io/AdamJessop/pen/qBBYxEK

If I re-position a node and it's endpoints programatically, when I drag the containing element, the endpoint re-positions at it's old cached offset position.

trying repaint(), revalidate() and recalculateOffsets(), none of them have the desired effect.

**Comment by daiduongbian44** [comment]
Have you tried the method like unmanage?
`jsPlumb.unmanage(elementId);`
