### ISSUE TITLE
Plural version of default parameters not taken into account

### ISSUE THREAD

**Issue by Jashtoyunda** [jsplumb/jsplumb#882]
When setting default parameters with "importDefaults", settings can either be set with singular parameter (like "Anchor"), or plural ("Anchors"), to differentiate start and end values, for anchors, endpoints, etc.

In recent versions, plural version of these parameters are not taken into account.
Eg : `Endpoints : [ [ "Dot", { radius:7 } ], [ "Dot", { radius:11 } ] ]`

**Comment by megeek** [comment]
+1

**Comment by sporritt** [comment]
please migrate to 4.x

https://www.npmjs.com/package/@jsplumb/community
