### ISSUE TITLE
addEndpoint not working as expected

### ISSUE THREAD

**Issue by 562533246** [jsplumb/jsplumb#885]
When I first use addEndpoint, the result is valid, but after deleting the endpoint, the second time I use addEndpoint to add the endpoint location in the same location is wrong.
it's my addEndpoint api
`
                const endPoint = this.jsPlumb.addEndpoint(filed.id, {
                    anchors: ['Left'],
                    uuid: filed.id + "_in"
                }, config.jsplumbLeftConnectCommon);
                // 设置源点，可以拖出线连接其他节点
                const sourcePoint = this.jsPlumb.addEndpoint(filed.id, {
                    anchors: ['Right'],
                    uuid: filed.id + "_out"
                }, config.jsplumbRightConnectCommon);
`
it's my deleteEndpoint api
`
            deleteEndpoint(id) {
                console.log(id);
                this.jsPlumb.deleteEndpoint(id)
                // this.jsPlumb.deleteEveryEndpoint();
            },
`

**Comment by sporritt** [comment]
do you have a picture?

**Comment by 562533246** [comment]
yes.
first step: addEndpoint
![1](https://user-images.githubusercontent.com/17511658/69526951-45e75e00-0fa6-11ea-945c-0b27401ffa81.png)
it's useful
second step: deleteEndpoint
![2](https://user-images.githubusercontent.com/17511658/69526994-5566a700-0fa6-11ea-812f-20424e1087ae.png)
three step: addEndpoint
![3](https://user-images.githubusercontent.com/17511658/69527028-6a433a80-0fa6-11ea-90fd-8fb6dac26956.png)

**Comment by 562533246** [comment]
My general scenario is that there is an array in VUE to indicate whether or not to allow connection.
my code:
`
// addEndpoint
fileds.forEach(function (filed) {
                    if (filed.id === filedId) {
                        filed.isConnected = true;
                        filed.isCheck = true;
                        _this.$nextTick(() => {
                            _this.addPoint(filed);
                            _this.jsPlumb.repaintEverything();
                        })
                    }
                })
// deletePoint
fileds.forEach(function (filed) {
                    if (filed.id === filedId) {
                        filed.isConnected = false;
                        filed.isCheck = false;
                        _this.$nextTick(() => {
                            const endPoint = filed.id + "_in";
                            const sourcePoint = filed.id + "_out";
                            _this.deleteEndpoint(endPoint);
                            _this.deleteEndpoint(sourcePoint);
                            _this.jsPlumb.repaintEverything();
                        })
                    }
                })
`

**Comment by sporritt** [comment]
please migrate to 4.x

https://www.npmjs.com/package/@jsplumb/community

**Comment by Yanzengyong** [comment]
I have the same problem, but how use 4.x 
import { jsPlumb } from '@jsplumb/community'
not working

**Comment by Yanzengyong** [comment]
where is the doc of 4.x

**Comment by sporritt** [comment]
its actually 5.x you should migrate to now:

https://docs.jsplumbtoolkit.com/community/
