### ISSUE TITLE
A large number of nodes

### ISSUE THREAD

**Issue by web-css** [jsplumb/jsplumb#886]
Article 400 the data need to load for 7 seconds

**Comment by sporritt** [comment]
what does "article 400" mean exactly?

**Comment by web-css** [comment]
> what does "article 400" mean exactly?

for(var i = 0; i< 400; i++) {
 plumb.connect({ source: 'sourceId', target: 'targetId' }) 
}

It takes 7 seconds.

**Comment by sporritt** [comment]
have you suspended rendering while you do this?

**Comment by web-css** [comment]
> have you suspended rendering while you do this?

How to suspended rendering?

**Comment by sporritt** [comment]
you can call `setSuspendRendering(true)` before you connect everything and then `false` afterwards. Or you can wrap the whole thing in a batch:

```
jsPlumbInstance.batch(function() {

  ...connections

});
```

**Comment by web-css** [comment]
Yes,I had used batch,but it still runs slowly.You can run an demo to test it.




| |
css
|
|
邮箱：cssbook@163.com
|

Signature is customized by Netease Mail Master

On 11/30/2019 18:58, Simon Porritt wrote:

you can call setSuspendRendering(true) before you connect everything and then false afterwards. Or you can wrap the whole thing in a batch:

jsPlumbInstance.batch(function() {

  ...connections

});

**Comment by sporritt** [comment]
there is a test page in the project that creates 1500 connections in about 400ms.

**Comment by web-css** [comment]
My god,can you send me the file or link?Thank you.




| |
css
|
|
邮箱：cssbook@163.com
|

Signature is customized by Netease Mail Master

On 11/30/2019 19:21, Simon Porritt wrote:

there is a test page in the project that creates 1500 connections in about 400ms.

**Comment by sporritt** [comment]
its in the project, a file called loadtest-dom.html or something. i cant easily check the name right now.

**Comment by web-css** [comment]
Thank you,I try.




| |
css
|
|
邮箱：cssbook@163.com
|

Signature is customized by Netease Mail Master

On 11/30/2019 19:35, Simon Porritt wrote:

its in the project, a file called loadtest-dom.html or something. i cant easily check the name right now.

**Comment by sporritt** [comment]
closing this. no updates for a couple of months.
