### ISSUE TITLE
Connections using wrong anchors on non-Firefox browsers

### ISSUE THREAD

**Issue by dominikonysz** [jsplumb/jsplumb#890]
Following happens in most of all browsers (tested in IE11, Edge, Edge Beta and Chrome):
If two nodes with opposite connections are placed underneath each other the connections don't use the nearest anchor on the other node, but the one farthest away from the source anchor.
![jsPlumb_error](https://user-images.githubusercontent.com/28198753/70331278-726d6680-183f-11ea-92e5-d0f28e34d1d6.PNG)

My expected behaviour would be (and is the behaviour in Firefox):
![jsPlumb_expected](https://user-images.githubusercontent.com/28198753/70331365-9af56080-183f-11ea-997d-675f1fd6d78c.png)

Seems like some calculations get handled differently on different browsers.

Anchor Type: Continuous
Connector Type: Flowchart

**Comment by sporritt** [comment]
i think this also is related to #893, #892 and #891.

**Comment by sporritt** [comment]
2.12.8 was released today. marking this fixed. if you could verify for your use case it'd be helpful.

**Comment by dominikonysz** [comment]
For me it also works perfectly, thank you.

**Comment by sporritt** [comment]
thanks for the update.
