### ISSUE TITLE
Hovering over connections makes them "disappear"

### ISSUE THREAD

**Issue by dominikonysz** [jsplumb/jsplumb#891]
Initial state:
![jsPlumb_disappearedConnections_before](https://user-images.githubusercontent.com/28198753/70335545-c3815880-1847-11ea-8258-8161f2d9db8b.png)

If I hover over a connection now, I can see the hover-styling for a part of a second and then the connection disappears.
Now this is the state:
![jsPlumb_disappearedConnections](https://user-images.githubusercontent.com/28198753/70335837-5ae6ab80-1848-11ea-854e-32e0de20c589.png)

As you can see the endpoints of the connections still remain on the previous locations.
Hovering over one of the endpoints (marked yellow) shows where the disappeared connection is placed:
![jsPlumb_disappearedConnectionsHovered](https://user-images.githubusercontent.com/28198753/70335998-b5800780-1848-11ea-9b27-f40be3e08be7.png)

The recalculation of the connection seems to use different anchors to connect to, what is weird as the endpoints don't move at all.

This bug happens on many browsers (tested on IE11, Edge, Edge Beta, Chrome), but not on Firefox.

Anchor Type: Continuous
Connection Type: Flowchart

**Comment by sporritt** [comment]
assuming this is not reproducible in any of the demos can you please provide an example.

**Comment by dominikonysz** [comment]
Cannot get it to work for straight connections, but in this [fiddle](https://jsfiddle.net/Lc09e426/90/) the left or right loopback on 'div2' is always disappearing for me.
Hovering the other one makes the first one appear again, but hovering the endpoint shows that the connection is not located where its endpoint is.

**Comment by sporritt** [comment]
i think this is related to issues #892 and #893 that were created yesterday.

**Comment by sporritt** [comment]
2.12.8 was released today. marking this fixed. if you could verify for your use case it'd be helpful.
