### ISSUE TITLE
Flickering issue in continuous anchors

### ISSUE THREAD

**Issue by Zanzavar** [jsplumb/jsplumb#892]
![jsplumb_bug](https://user-images.githubusercontent.com/900831/70527973-cc2ea300-1b55-11ea-9487-350907f9062a.gif)

When moving con_19 to the same face as con_52 and con_3 the other two connections flicker and constantly switch target endpoints.

This gif was reproduced in the official state machine with continuous anchors demo page on jsplumb website: https://jsplumbtoolkit.com/community/demo/statemachine/index.html

The bug appears on Chrome 78 but not on Firefox 71

**Comment by sporritt** [comment]
the curious thing here is that dragging `Begin` or `Phone Interview 1` does not result in the same behaviour.

**Comment by Zanzavar** [comment]
Indeed. It also seems to appear when there are at least two other endpoints on the same face with the endpoint of the dragged element.

**Comment by sporritt** [comment]
2.12.8 was released today. marking this fixed. if you could verify for your use case it'd be helpful.

**Comment by Zanzavar** [comment]
Works great, thanks!
