### ISSUE TITLE
Disappearing endpoint in continuous anchors

### ISSUE THREAD

**Issue by Zanzavar** [jsplumb/jsplumb#893]
![jsplumb_bug_2](https://user-images.githubusercontent.com/900831/70530319-4c0b3c00-1b5b-11ea-9dc8-e9b5afd703d6.gif)

When creating new connection from makeSource/makeTarget element the endpoint from one of the targeted connections (con_52) moves on top of the other connection endpoint (con_3).

This gif was reproduced in the official state machine with continuous anchors demo page on jsplumb website: https://jsplumbtoolkit.com/community/demo/statemachine/index.html

The bug appears on Chrome 78 but not on Firefox 71

**Comment by sporritt** [comment]
i would imagine this is related to #892

**Comment by sporritt** [comment]
2.12.8 was released today. marking this fixed. if you could verify for your use case it'd be helpful.

**Comment by Zanzavar** [comment]
Yes, works perfectly. Thanks for the quick fix!

**Comment by sporritt** [comment]
ok cool, thanks for letting me know.
