### ISSUE TITLE
How to avoid line overlap

### ISSUE THREAD

**Issue by CerryXu** [jsplumb/jsplumb#894]
The lines are the same height, the lines have words on them, the words overlap

**Comment by sporritt** [comment]
i dont think the community edition has any means to avoid this. if you have a picture i could probably confirn that.

**Comment by CerryXu** [comment]
> i dont think the community edition has any means to avoid this. if you have a picture i could probably confirn that.

![1VSWUI)KK8QKD7T} QWQVT](https://user-images.githubusercontent.com/45084662/71707615-dd519380-2e25-11ea-8a71-7faed3569e99.png)
I want to avoid the occurrence of this situation, the words on the line are stacked up, may I ask how to avoid it

**Comment by CerryXu** [comment]
![1VSWUI)KK8QKD7T} QWQVT](https://user-images.githubusercontent.com/45084662/71707643-10942280-2e26-11ea-814c-ecdb7403abec.png)

**Comment by CerryXu** [comment]
![1VSWUI)KK8QKD7T} QWQVT](https://user-images.githubusercontent.com/45084662/71707673-505b0a00-2e26-11ea-8bd7-a53e7fe70d5e.jpg)

**Comment by CerryXu** [comment]
> i dont think the community edition has any means to avoid this. if you have a picture i could probably confirn that.

I want to avoid the occurrence of this situation, the words on the line are stacked up, may I ask how to avoid it
![1VSWUI)KK8QKD7T} QWQVT](https://user-images.githubusercontent.com/45084662/71707690-77194080-2e26-11ea-9749-35ac325357c9.jpg)

**Comment by sporritt** [comment]
The community edition does not currently have any way of avoiding this.

**Comment by sporritt** [comment]
closing.
