### ISSUE TITLE
【license】 May I select one of the [GPLV2, MIT] licenses?

### ISSUE THREAD

**Issue by kxcc** [jsplumb/jsplumb#899]
If anybody can select one or can select one on certain conditions or can not select one, Pls write here.

I guess there's gonna be a lot of people are confused about it.

![image](https://user-images.githubusercontent.com/24751083/72673966-38cd8380-3aac-11ea-8968-7a002db03a38.png)

**Comment by sporritt** [comment]
you just select the one that suits you.
