### ISSUE TITLE
resizable group 

### ISSUE THREAD

**Issue by soe-htike** [jsplumb/jsplumb#900]
how can I make resizable for group container? I want to make the group to be resizable just like normal item. Thanks

http://embed.plnkr.co/5FVney1yEqgz293aVwV5/

**Comment by sporritt** [comment]
there's no API in jsPlumb to do this - you can just use the code in your plunker and have that element be the element used for the group. Probably need to call `jsPlumbInstance.revalidate(groupEl)` whenever a resize occurs.
