### ISSUE TITLE
Move a connection programmatically?

### ISSUE THREAD

**Issue by Zanzavar** [jsplumb/jsplumb#901]
Is there currently a way in jsplumb to programmatically change a connection sourceid or targetid and rerender the connection? So far i have only managed to trigger a programmatic "move" by removing and creating new connection but it is quite sub-optimal :/

**Comment by sporritt** [comment]
in 4.x you can use the `setSource` on `JsPlumbInstance` method for this

```
setSource (connection:Connection, el:Element | Endpoint, doNotRepaint?:boolean):void {
```
