### ISSUE TITLE
deleteConnection in bind('connection') throws error: Cannot read property '0' of null

### ISSUE THREAD

**Issue by Tilogorn** [jsplumb/jsplumb#906]
See demo [here](https://jsfiddle.net/ahd9pe3f/). Just drag a connection from the left endpoint to the right one and have a look on the console.

When creating a connection by mouse and listening to the `connection`-Event, you can not delete the connection in the callback without getting the error `jsPlumb function failed : TypeError: Cannot read property '0' of null`.

Use case: You let the user connect two elements and check in the `connection` event, if the connection meets your validation criteria. If it doesn't, you delete the connection and show a warning to the user.

**Comment by sporritt** [comment]
you should use a `beforeDrop` interceptor for this instead

http://jsplumb.github.io/jsplumb/interceptors.html

**Comment by Tilogorn** [comment]
Thanks for the hint, @sporritt. Works perfectly, I updated the [fiddle](https://jsfiddle.net/5knxcgw2/1/).
