### ISSUE TITLE
How to Important JSPlumb from Typescript?

### ISSUE THREAD

**Issue by radiantone** [jsplumb/jsplumb#907]
Hi,
  Sorry to post new on this ticket, but I'm having the same issue. There is no clear documentation on how to import jsplumb into typescript (not using any intergrations, just vanilla javascript).

My project uses webpack too. I placed all the jsplumb ts directories where my other project .ts files are. How can I import jsplumb so it works like this?

import { jsPlumb } from "jsplumb";

------
`
 src/
    ts/
      myapp.ts
      jsplumb/
          index.d.ts
          package.json
      jsplumbtoolkit/
          index.d.ts
          package.json
 
 etc
`

**Comment by rohya8** [comment]
try importing like:
import * as jsplumb from 'jsplumb';
