### ISSUE TITLE
Cannot read property 'scrollWidth' of null

### ISSUE THREAD

**Issue by joselrio** [jsplumb/jsplumb#910]
**"Cannot read property 'scrollWidth' of null"** is the message that I'm receiving on start drag the only element at canvas. According the debug info that I was able to retrieve it seams that the **el** received on the **getConstrainingRectangle** method receives an element that doesn't exist in DOM, and the **scrollWidth** is assigned to an element that doesn't exist...
If I've more than one element in canvas, this issue doesn't happen...

Do you have any fix to this? Thanks in advance...

**Comment by joselrio** [comment]
This is the quick fix that I've added directly to the library file, **this is not a good approach and it's not OK**!
Can you please take a look at this in order to remove this from the library?

<img width="730" alt="Screenshot 2020-02-12 at 18 26 55" src="https://user-images.githubusercontent.com/5339917/74365420-f6a31380-4dc5-11ea-8a98-98cc9c3547e7.png">

Once again, thanks in advance.

**Comment by sporritt** [comment]
i think reproducing this in a jsfiddle might be best.  i've never seen an error occur when there's only one node in the canvas.

**Comment by joselrio** [comment]
Hi... Just to give more feedback about this issue:
It happens that I'm using the library inside an React15 application, and this was happening because I was using the **startDrag** and **stopDrag** node event in order to add a **.class** to the nodes parent, and since I'm adding that class to the parent the **dragEl** "looses" your father element. 
**Basically, if you add a class to the parent nodes while we are dragging an element this issue will happen**.
