### ISSUE TITLE
setId() does not update jsPlumb definitions like makeSource/makeTarget

### ISSUE THREAD

**Issue by dominikonysz** [jsplumb/jsplumb#912]
After changing the elements id with setId the element definitions as source or target get lost.

[Example](https://jsfiddle.net/mzvLbtxk/29/)

Changing the id manually with jQuery and calling setIdChanged results in the same behaviour.

`TypeError: this.sourceEndpointDefinitions[e] is undefined` gets thrown when trying to interact with the changed element.

**Comment by sporritt** [comment]
this is fixed and published in 2.12.12
