### ISSUE TITLE
Programmatically changing connection type makes arrow overlay disappear

### ISSUE THREAD

**Issue by dominikonysz** [jsplumb/jsplumb#913]
When changing the connection type of a connection after is has been created with a different type, then any existing arrow overlay on the connection disappears.

[Example](https://jsfiddle.net/y6ad7ctm/8/)

While the examples uses Flowchart and StateMachine as connection types, it also happens with other connection types.

**Comment by sporritt** [comment]
right, yeah. but why should that not be the case?

**Comment by dominikonysz** [comment]
I dont think so.

In my case the default connector is Flowchart, but for loopbacks i want to use the StateMachine connector. To achieve this i check the source and the target id in a beforeDrop listener and change the type to loopback if they are equal. After doing this if have the better looking loopback but no arrow overlay anymore.

See div3 in this [Fiddle](https://jsfiddle.net/rpox489y/6/)

**Comment by sporritt** [comment]
I saw what happened, yes, but i'm not sure that your expectation is "correct". i don't mean it conflicts with my own: I don't really have an opinion and could go either way. I can see how an overlay set on the instance defaults should probably be present on all types.

there is other odd behaviour around this that has convinced me to fix this - in this fiddle

https://jsfiddle.net/yntz2qw4/

there are no instance defaults, and each of the types has the arrow overlay defined. but when you press the button, the connection on div2 actually _loses_ its arrow, which is definitely not correct.

in this one, though, the default type does not have an arrow overlay:

https://jsfiddle.net/r8sjbeuw/1/

and when you press the button the div2 connection _does_ get an arrow overlay.

**Comment by sporritt** [comment]
...this should be fixed (and published) in 2.12.13

**Comment by dominikonysz** [comment]
Thank you very much, i will try it in my project tomorrow and let you know if it works for me

**Comment by dominikonysz** [comment]
Great, the arrow overlay remains.

But it seems like there is a problem when trying to delete the previously changed connection. Try doubleclicking the connections in this [fiddle](https://jsfiddle.net/3aLj6md8/10/).

**Comment by sporritt** [comment]
..and in this one, the unminified code?

**Comment by dominikonysz** [comment]
https://jsfiddle.net/mqpncybh/1/

**Comment by sporritt** [comment]
ok try 2.12.14, just published

**Comment by sporritt** [comment]
tagged with alpha 4.x to ensure it gets checked

**Comment by dominikonysz** [comment]
Yes, this works now, thanks
