### ISSUE TITLE
erROR in node_modules/jsplumb/index.d.ts(309,9): error TS2300: Duplicate identifier 'sourceId'.

### ISSUE THREAD

**Issue by Aravinth-AK** [jsplumb/jsplumb#915]
the last patch (2.12.10) fix throwing this error when creating the packages, please look into this and resolve ASAP

**Comment by sporritt** [comment]
you know,  when it's open source, and you have the source, etc, telling someone to look into something "asap" is not really the done thing.

**Comment by sporritt** [comment]
you could have instead been like @antishov and submitted [a PR](https://github.com/jsplumb/jsplumb/pull/916)

**Comment by Aravinth-AK** [comment]
> you know, when it's open source, and you have the source, etc, telling someone to look into something "asap" is not really the done thing.

**Comment by Aravinth-AK** [comment]
@sporritt 

Hi sporrit,
thanks for the input, i'm unaware of this package flow and its been in my project. noticed this issue while the package build so just reported.

**Comment by sporritt** [comment]
you are welcome for the input.

**Comment by sporritt** [comment]
btw you do know that setting up your imports to automatically pull in a new release is a bad idea, right? a terrible idea.  it would be remiss of me to pass up an opportunity to comment on this in a public forum.
