### ISSUE TITLE
Node endpoints keeps shifting

### ISSUE THREAD

**Issue by SupriyaSudhindra** [jsplumb/jsplumb#917]
I am using jsplumb in my application for the flowchart kind of functionality. I am able to create node/div dynamically even endpoints also.But, I am facing this issue of endpoints keeps moving from the node/div randomly and if we move the div a bit manually endpoints comes back to its position.. as shown below.

![image](https://user-images.githubusercontent.com/32768262/75524271-9651da00-5a33-11ea-9549-a62085c1a456.png)

Please suggest...it's urgent...

**Comment by sporritt** [comment]
have you set the Container correctly?

http://jsplumb.github.io/jsplumb/home.html#container

**Comment by SupriyaSudhindra** [comment]
@sporritt thanks for the quick reply...the container is set as per the documentation only...but still the issue exists

Please suggest

**Comment by SupriyaSudhindra** [comment]
@sporritt any updates on this?...please i am working on this issue from past 3 weeks...itz urgent...

Please suggest.

**Comment by sporritt** [comment]
nothing comes to mind from that description except for my question about the container. perhaps you can reproduce in a jsfiddle or something?
