### ISSUE TITLE
setId not picked up by makeTarget

### ISSUE THREAD

**Issue by dominikonysz** [jsplumb/jsplumb#918]
The fix for #912 resolves the problem for source definitions, but there is still a problem with target definitions after changing the id of an element.

https://jsfiddle.net/k801su24/3/

**Comment by sporritt** [comment]
could you link the unminified code?  it would be easier to debug.

**Comment by dominikonysz** [comment]
https://jsfiddle.net/aktbojcg/

**Comment by sporritt** [comment]
try 2.12.14

**Comment by sporritt** [comment]
tagging this with alpha 4.x, as a reminder to ensure this is not an issue there

**Comment by dominikonysz** [comment]
This also works perfectly, thank you for the quick fix
