### ISSUE TITLE
Connect function not accepting some params

### ISSUE THREAD

**Issue by AkarshanDehal** [jsplumb/jsplumb#920]
instance.connect({ source : "src", target : "tar", endpoint: ["Dot", {radius: 5, cssClass:"hasInfluencedEndpointStrong"}], anchor: "Center", paintStyle: { width: 25, height: 21, fill:"transparent"}, scope: "hasInfluencedStrong", isSource: true, reattach: true, maxConnections: -1, connectorStyle: { stroke: "#708088", strokeWidth: 2.6, outlineStroke: "transparent", outlineWidth: 4 }, connectorOverlays:[ [ "Arrow", { location: -15.5, id: "arrow", length: 14, width:14, foldback: 1, direction:1 } ] ], isTarget: true, })

**I have passed this object in jsplumb connect function its not behaving the way it is expected to i want to adjust the width of line and arrow type is there any alternative for this ?**

![image](https://user-images.githubusercontent.com/62586930/77400047-9b0a7380-6dd0-11ea-8c4f-156215c25da1.png)

i have tried to connect using uuid of endpoints also firstly the uuid of endpoints are added after that trying to connect them and consoled both uuid and the endpoint its same uuid but still getting source does not exist error.

**Comment by sporritt** [comment]
```
instance.connect({ 
  source : "src", 
  target : "tar", 
  endpoint: ["Dot", { radius: 5,  cssClass:"hasInfluencedEndpointStrong" }], 
  anchor: "Center", 
  paintStyle: { 
    width: 25, 
    height: 21, 
    fill:"transparent"
  }, 
  scope: "hasInfluencedStrong", 
  isSource: true, 
  reattach: true,
  maxConnections: -1, 
  connectorStyle: { 
    stroke: "#708088", 
    strokeWidth: 2.6, 
    outlineStroke: "transparent", 
    outlineWidth: 4 
  }, 
  connectorOverlays:[ 
    [ "Arrow", { location: -15.5, id: "arrow", length: 14, width:14, foldback: 1, direction:1 } ] 
  ], 
  isTarget: true, 
})

**Comment by sporritt** [comment]
it looks to me like everything after "endpoint" was supposed to be part of the endpoint definition, but its in the scope of the `connect` call, and would be treated as parameters for the connection. The only of those that would be applied is `paintStyle`, and it doesnt have any values in it that apply to connections (but of course i dont think you are trying to apply it to a connection).

i guess you probably first want to use `addEndpoint` somehow:

```
let e1 = instance.addEndpoint("src", {
  endpoint: ["Dot", { radius: 5,  cssClass:"hasInfluencedEndpointStrong" }], 
  anchor: "Center", 
  paintStyle: { 
    width: 25, 
    height: 21, 
    fill:"transparent"
  }, 
  scope: "hasInfluencedStrong", 
  isSource: true, 
  reattach: true,
  maxConnections: -1, 
  connectorStyle: { 
    stroke: "#708088", 
    strokeWidth: 2.6, 
    outlineStroke: "transparent", 
    outlineWidth: 4 
  }, 
  connectorOverlays:[ 
    [ "Arrow", { location: -15.5, id: "arrow", length: 14, width:14, foldback: 1, direction:1 } ] 
  ]
});

let e2 = instance.addEndpoint("target", {
  endpoint: ["Dot", { radius: 5,  cssClass:"hasInfluencedEndpointStrong" }], 
  anchor: "Center", 
  paintStyle: { 
    width: 25, 
    height: 21, 
    fill:"transparent"
  }, 
  scope: "hasInfluencedStrong", 
  isTarget: true, 
  reattach: true,
  maxConnections: -1, 
  connectorStyle: { 
    stroke: "#708088", 
    strokeWidth: 2.6, 
    outlineStroke: "transparent", 
    outlineWidth: 4 
  }, 
  connectorOverlays:[ 
    [ "Arrow", { location: -15.5, id: "arrow", length: 14, width:14, foldback: 1, direction:1 } ] 
  ]
});
```

and then connect those endpoints:

```
instance.connect({
  source:e1,
  target:e2
});
```

btw `width` and `height` are not valid values for an endpoint's paint style.

**Comment by AkarshanDehal** [comment]
@sporritt it worked fine, thank you so much for the response 👍

**Comment by sumit-sharma7** [comment]
> it looks to me like everything after "endpoint" was supposed to be part of the endpoint definition, but its in the scope of the `connect` call, and would be treated as parameters for the connection. The only of those that would be applied is `paintStyle`, and it doesnt have any values in it that apply to connections (but of course i dont think you are trying to apply it to a connection).
> 
> i guess you probably first want to use `addEndpoint` somehow:
> 
> ```
> let e1 = instance.addEndpoint("src", {
>   endpoint: ["Dot", { radius: 5,  cssClass:"hasInfluencedEndpointStrong" }], 
>   anchor: "Center", 
>   paintStyle: { 
>     width: 25, 
>     height: 21, 
>     fill:"transparent"
>   }, 
>   scope: "hasInfluencedStrong", 
>   isSource: true, 
>   reattach: true,
>   maxConnections: -1, 
>   connectorStyle: { 
>     stroke: "#708088", 
>     strokeWidth: 2.6, 
>     outlineStroke: "transparent", 
>     outlineWidth: 4 
>   }, 
>   connectorOverlays:[ 
>     [ "Arrow", { location: -15.5, id: "arrow", length: 14, width:14, foldback: 1, direction:1 } ] 
>   ]
> });
> 
> let e2 = instance.addEndpoint("target", {
>   endpoint: ["Dot", { radius: 5,  cssClass:"hasInfluencedEndpointStrong" }], 
>   anchor: "Center", 
>   paintStyle: { 
>     width: 25, 
>     height: 21, 
>     fill:"transparent"
>   }, 
>   scope: "hasInfluencedStrong", 
>   isTarget: true, 
>   reattach: true,
>   maxConnections: -1, 
>   connectorStyle: { 
>     stroke: "#708088", 
>     strokeWidth: 2.6, 
>     outlineStroke: "transparent", 
>     outlineWidth: 4 
>   }, 
>   connectorOverlays:[ 
>     [ "Arrow", { location: -15.5, id: "arrow", length: 14, width:14, foldback: 1, direction:1 } ] 
>   ]
> });
> ```
> 
> and then connect those endpoints:
> 
> ```
> instance.connect({
>   source:e1,
>   target:e2
> });
> ```
> 
> btw `width` and `height` are not valid values for an endpoint's paint style.

Thanks @sporritt Worked fine for me!
