### ISSUE TITLE
JSDoc types can only be used inside documentation comments.

### ISSUE THREAD

**Issue by samyakbhalerao** [jsplumb/jsplumb#922]
type AnchorArraySpec = [ number, number, number, number, number?, number?, string? ];
![Screenshot from 2020-04-06 12-52-04](https://user-images.githubusercontent.com/10878623/78533007-d14ee680-7805-11ea-81fe-f46399418d4d.png)

**Comment by sporritt** [comment]
i dont think there's anything wrong with that type declaration.

**Comment by JamesXia23** [comment]
how do you fix it？

**Comment by sporritt** [comment]
I have since run into this while working on the 4.x release of the Toolkit edition. I think it might be related to the version of Typescript in use. What version are you using, @JamesXia23 ?
