### ISSUE TITLE
opacity and strokeOpacity does not take effect in paintStyle

### ISSUE THREAD

**Issue by ilovepumpkin** [jsplumb/jsplumb#925]
I tried to set "opacity" or "strokeOpacity" in paintStyle, but they do not take any effect - look like they are filtered out during the rendering. They do work when I set them using css.  Is this a limitation of JsPlumb? 

```
 this.graphInstance.registerConnectionTypes({
      basic: {
        paintStyle: {
          strokeWidth: 1,
          stroke: '#152935',
          joinstyle: 'round',
          outline: 'white',
          outlineWidth: 2,
          fill: 'red',
          opacity: 0.3,
          strokeOpacity: 0.3,
        },
        hoverPaintStyle: { strokeWidth: 2, stroke: '#0062ff' },
      })
```

![image](https://user-images.githubusercontent.com/11310645/79179678-c36b1800-7e3a-11ea-9a2e-dedb7950ac63.png)

![image](https://user-images.githubusercontent.com/11310645/79179921-4be9b880-7e3b-11ea-8387-005fc7e85841.png)

**Comment by sporritt** [comment]
`opacity` and `strokeOpacity` are not supported keys in a paint style.

**Comment by ilovepumpkin** [comment]
okay, got it, thanks for confirming this.
