### ISSUE TITLE
Could child nodes be collapsed and expanded?

### ISSUE THREAD

**Issue by greenTea2Codes** [jsplumb/jsplumb#926]
Hi, 

I am looking for a library which supports creating interactive mind map. The user could create nodes and connect nodes with edges; in addition, the child nodes could be expanded or collapsed by clicking on the parent node.

I checked the documentation but I am not sure whether there is api for expanding and collapsing child nodes. Could someone advice?

**Comment by sporritt** [comment]
this sounds a bit like the concept of "groups"

https://community.jsplumbtoolkit.com/groups/dom.html

**Comment by greenTea2Codes** [comment]
Thank you for showing the documentation.

I wonder if the library has api supporting the behaviors in the screenshots below:
![Screenshot from 2020-04-17 16-41-32](https://user-images.githubusercontent.com/13864960/79575386-5ff71980-80ca-11ea-93e8-741abdd1beb2.png)
![Screenshot from 2020-04-17 16-41-49](https://user-images.githubusercontent.com/13864960/79575404-69808180-80ca-11ea-81df-20fcf4f0c496.png)
Instead of clicking the group box, is there way to have the click on the vertex of the parent and child nodes?

**Comment by sporritt** [comment]
there's nothing that specific, but it's all just html.

**Comment by greenTea2Codes** [comment]
Thank you for the reply. I would try the library later.
