### ISSUE TITLE
How do I get two endpoint names to connect in beforeDrop events？

### ISSUE THREAD

**Issue by linshuzhen** [jsplumb/jsplumb#930]
instance.bind('beforeDrop', params => {
   
    var sourceUuid = params.connection.endpoints[0].getUuid()
    var targetUuid = params.connection.endpoints[1].getUuid()
    console.log('params', params, sourceUuid, targetUuid)
}）

The sourceUuid value is correct,But targetUuid value is undeifined ?why?How do I get two endpoint names to connect in beforeDrop events？

**Comment by sporritt** [comment]
`uuid` is something you set when you call `addEndpoint`:

```
instance.addEndpoint(someElement, {
  uuid:"foo"
});
```

If you haven't set this when you configure the endpoint then the endpoint won't have one.
