### ISSUE TITLE
Create multiple connections between same endpoints

### ISSUE THREAD

**Issue by vishalbiradar** [jsplumb/jsplumb#931]
I have been using jsplumb with Angular.
I am not finding any reference that will give details about, creating multiple connections between the same endpoints.

For ex:
```
import { jsPlumb } from 'jsplumb';
export class AppComponent implements AfterViewInit {
jsPlumbInstance;

ngAfterViewInit() {
    this.jsPlumbInstance = jsPlumb.getInstance();
    this.connectSourceToTargetUsingJSPlumb();
}

connectSourceToTargetUsingJSPlumb() {
    for (let i = 0; i < 10; i++) {
      this.jsPlumbInstance.connect({
       connector: ['Flowchart'],
        source: 'Source',
        target: 'Target1',
        anchor: ['Right', 'Left'],
        paintStyle: {stroke: '#456', strokeWidth: 4},
        overlays: [
          ['Label', {label: 'con-' + i}]
        ],
      });
    }
  }
```

But with the above approach, it is overriding the connection lines and the overlay text.
How can we show all those connections differently?

Please refer below screenshot, this is what I am expecting.
There will be multiple connections between Source(NA56) and Target(XY27 )

![image](https://user-images.githubusercontent.com/29951629/82425696-81ba3680-9aa4-11ea-8134-d92cc789dbab.png)

**Comment by sporritt** [comment]
if its connections between the same endpoint then the connectors will overlap, yes. there is no support for any different behaviour currently.

**Comment by vishalbiradar** [comment]
@sporritt Can we customize CSS so that we can avoid the overlapping?
Or can we add the style attribute to overlay directly?

**Comment by sporritt** [comment]
no. you can't manipulate the paths with css.
