### ISSUE TITLE
Connection wrong connect to each node when Tree uncollapse

### ISSUE THREAD

**Issue by Reviz13** [jsplumb/jsplumb#934]
![1cc55006-f609-4473-a425-e0907d01c244_P4CV75oE_GS5w](https://user-images.githubusercontent.com/66105642/83228400-78ba1b00-a1b0-11ea-9b5a-9d2a2ea68333.gif)

why my connection not connected to node when tree is uncollapse ? like gif above any solution  ?

**Comment by sporritt** [comment]
it might have something to do with the anchor you're using. a jsfiddle/codepen would be useful.

**Comment by Reviz13** [comment]
@sporritt my mapper theres too many js and css to include inside jsfiddle/ codepen  i could share my folder to you , is okay ?

**Comment by ChooseyLife** [comment]
i have same issuses. This should be a problem of not judging whether the connection node is hidden.
https://jsbin.com/xukocicavu/edit?html

**Comment by sporritt** [comment]
It doesn't look to me like @Reviz13 's problem was due to jsplumb not knowing the node was hidden. it looks like it is related to the choice of anchor.

as for your code, @ChooseyLife , without a jsfiddle i don't know either what the issue is or how you could remedy it.

**Comment by ChooseyLife** [comment]
https://codepen.io/goahead/pen/dyGBJBx

the right box is uncollapse, left item can't connect nodes of uncollapse

**Comment by sporritt** [comment]
I cant see any problem with this...everything scrolls and connects as far as I can tell. What's supposed to happen/not happen?

**Comment by ChooseyLife** [comment]
https://codepen.io/goahead/pen/dyGBJBx

I've connected r subitem one, but it's hidden, causing the line to break. you can click item one in right box

**Comment by sporritt** [comment]
oh i see, right.  Well that's easily explained - the list code is not written to support nested lists like this.

**Comment by ChooseyLife** [comment]
So what should I do to solve the current problem, i need to do that

**Comment by sporritt** [comment]
You could look into the `hide(elementId)` and `show(elementId)` methods on jsPlumb - use these when you collapse/expand a node on its affected children. Although how well that will play with the proxied connection stuff from the list is not something I can predict.

**Comment by ChooseyLife** [comment]
thinks, When I scroll, I judge whether the node is hidden.
