### ISSUE TITLE
Misleading jsDoc for deleteConnection(), 2nd parameter

### ISSUE THREAD

**Issue by exodus4d** [jsplumb/jsplumb#936]
The 2nd parameter `params` for method `deleteConnection()` has a misleading _jsDoc_ information:
```js
{Boolean} [params.doNotFireEvent=false]
```
...The parameter  should be renamed to:
```js
{Boolean} [params.fireEvent=false]
```
... or the method body should be fixed in order to reName the property name:
```js
fireDetachEvent(connection, !connection.pending && params.doNotFireEvent!== false, params.originalEvent);
```

https://github.com/jsplumb/jsplumb/blob/5dff8ff81a2443a6badca1b2ede630c474d8e054/src/jsplumb.js#L1485-L1494

**Comment by sporritt** [comment]
fixed in 2.14.0
