### ISSUE TITLE
Touch events for connectors

### ISSUE THREAD

**Issue by pavitrakumar78** [jsplumb/jsplumb#937]
Hi,

I'm trying to get touch events to work for connectors, but I can't seem to get it working on any of the chrome dev tool's mobile devices. I am using the latest release and according to the docs, I don't see any other option than to just do `connection.bind("click", function(conn) {})` - this does work for all mouse events, but not for touch events - say, tapping the screen once - like a click.

Does mottle (https://github.com/jsplumb/mottle) not take care of mapping events bound to connectors? or am I missing something here?

**Comment by sporritt** [comment]
events on connectors do work on touchscreen devices. for instance on this demo

https://community.jsplumbtoolkit.com/flowchart/dom.html

you can tap a connector and the type of the connector changes. the code that does that is

```
instance.bind("click", function (conn, originalEvent) {
           conn.toggleType("basic");
});
```

when you say "chrome dev tool's mobile devices" i suppose you mean the emulator on a machine that actually does not have a touchscreen?

**Comment by pavitrakumar78** [comment]
Thanks for the quick reply. Yes, I do mean exactly those emulators. 

I used code from this answer: https://stackoverflow.com/a/4819886/359287 to test detection for touch screen. The `is_touch_device4` function returns `false` when I run it on dev console in normal desktop mode, but `true` when I use the emulator, so I assumed testing on the emulator was good enough since I'm in the early dev stage. Is this way to check for touchscreen not reliable?

**Comment by sporritt** [comment]
is it written exactly like that:

```
instance.bind('connection'), function ()... {}) 
```

?

I ask because you've got a closing parentheses after `'connection'`, which would cause that to not actually bind.

**Comment by pavitrakumar78** [comment]
Sorry for that mistake, I mistyped the code in my previous comment. The actual code is like this:
    instance.bind('connection', function(info, originalEvent) {
        ...
        info.connection.bind('click', function(component, e) {
            ...
        });
    });

**Comment by sporritt** [comment]
The difference here is that your code is binding to `click` on a Connection:

```
info.connection.bind('click', function(component, e) {
            ...
        });
```

but the sample above is binding to `click` on the instance:

```
instance.bind("click", function(conn, evt) { ... });
```

I don't know, though, if this is what's causing the problem for you.

**Comment by pavitrakumar78** [comment]
Thank you for the suggestion, but that was not it, I'm not sure why, but for some reason, I'm able to use the touch events also now. I had not changed code - the thing that changed was my environment and possibly some of my other packages versions.  

I'll close this for now. I will report back if I have the same issue with some reproducible code.
