### ISSUE TITLE
How to get  bothe source and target for a node?

### ISSUE THREAD

**Issue by shrutis0896** [jsplumb/jsplumb#938]

**Comment by sporritt** [comment]
How do you mean? You want to find all the connections for some given element?

**Comment by shrutis0896** [comment]
For example there are three nodes as A node is connected to B node as 'B' being the target and B node is connected to node 'C' as C being the target. Is there any pre-defined function to check both source and target for B? (To check whether a node has both source and a target as using getAllConnections() all provides pair of source and target)

**Comment by shrutis0896** [comment]
> For example there are three nodes as A node is connected to B node as 'B' being the target and B node is connected to node 'C' as C being the target. Is there any pre-defined function to check both source and target for B? (To check whether a node has both source and a target as using getAllConnections() all provides pair of source and target)

**Comment by shrutis0896** [comment]
@sporritt 
For example there are three nodes as A node is connected to B node as 'B' being the target and B node is connected to node 'C' as C being the target. Is there any pre-defined function to check both source and target for B? (To check whether a node has both source and a target as using getAllConnections() all provides pair of source and target)

**Comment by sporritt** [comment]
I think you'd just have concat the result of running `getConnection` on `B` as source and then target:

https://docs.jsplumbtoolkit.com/community/current/articles/querying.html#getConnections

```
instance.getConnections({ source:"B" })
    .concat(instance.getConnections({ target:"B" }));
```

**Comment by shrutis0896** [comment]
Thank you for the help!
