### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by Tyrant-sixsixsix** [jsplumb/jsplumb#940]
Using jsplumb causes JSON conversion to fail

     --> starting at object with constructor 'root.jsPlumbInstance'
     |     property 'listManager' -> object with constructor 'ListManager'
     --- property 'instance' closes the circle
     at Object.stringify (<anonymous>)
     at stringify (stringify.js?aa42:4)
     at fnAddDynamicMenuRoutes (index.js?61a1:149)
     at fnAddDynamicMenuRoutes (index.js?61a1:140)
     at eval (index.js?61a1:68)

--------------------------------------------------router -- index.js  ----------------------------------------
function fnAddDynamicMenuRoutes (menuList = [], routes = []) {
  var temp = []
  for (var i = 0; i < menuList.length; i++) {
    if (menuList[i].list && menuList[i].list.length >= 1) {
      temp = temp.concat(menuList[i].list)
    } else if (menuList[i].url && /\S/.test(menuList[i].url)) {
      menuList[i].url = menuList[i].url.replace(/^\//, '')
      var route = {
        path: menuList[i].url.replace('/', '-'),
        component: null,
        // name: menuList[i].url.replace('/', '-'),
        name: '',
        meta: {
          menuId: menuList[i].menuId,
          title: menuList[i].name,
          enTitle: menuList[i].enName,
          isDynamic: true,
          isTab: true,
          iframeUrl: ''
        }
      }
      // url以http[s]: // iframe show
      if (isURL(menuList[i].url)) {
        route['path'] = `i-${menuList[i].menuId}`
        route['name'] = `i-${menuList[i].menuId}`
        route['meta']['iframeUrl'] = menuList[i].url
      } else {
        try {
          route['component'] = _import(`modules/${menuList[i].url}`) || null
        } catch (e) {
        }
      }
      routes.push(route)
    }
  }
  if (temp.length >= 1) {
    fnAddDynamicMenuRoutes(temp, routes)
  } else {
    mainRoutes.name = 'main-dynamic'
    mainRoutes.children = routes
    router.addRoutes([
      mainRoutes,
      {path: '*', redirect: {name: '404'}}
    ])

    // TODO   JSON conversion 
    sessionStorage.setItem('dynamicMenuRoutes', JSON.stringify(mainRoutes.children || '[]'))
  }
}

**Comment by sporritt** [comment]
I cant see how this is a jsplumb issue.

**Comment by sporritt** [comment]
closing this in the absence of any evidence to the contrary.
