### ISSUE TITLE
请教jspump的两个小问题

### ISSUE THREAD

**Issue by diaomina** [jsplumb/jsplumb#941]
①这个连线弯折的功能是不是开源版没有的呀，jsplumbtoolkit里面才有嘛

②还有这个自定义选择锚点连接，在默认自动选择最近的锚点的情况下，应该怎么配置才可以不强制自动选择最近锚点，而是可以自己手动调整连接到哪个锚点

**Comment by sporritt** [comment]
两者仅在工具包版本中可用。

**Comment by sporritt** [comment]
closing this.
