### ISSUE TITLE
How to drop in 4.0-rc1

### ISSUE THREAD

**Issue by xrei** [jsplumb/jsplumb#942]
before it was el.droppable({...})

how can i do same thing in current version?

**Comment by sporritt** [comment]
Can you tell me more about your use case with some code? `droppable` doesn't exist in 4.x currently.

**Comment by sporritt** [comment]
@xrei i'm interested in following up on this. any detail you can provide would be great.

**Comment by xrei** [comment]
@sporritt I have done this by html5 drag&drog api, made my own light implementation of droppable :)

**Comment by sporritt** [comment]
ok. So you don't think jsPlumb 4.x needs to support it?

**Comment by sporritt** [comment]
https://github.com/jsplumb/jsplumb/issues/943

**Comment by xrei** [comment]
Sadly, i don't know how droppable worked in 2.x version, i thought it's jquery's stuff for area where you can drop draggable element. If you had similar api in older version i think it's good to have but it should be abstracted over html5 drag&drop api, but as it turned out for me it wasn't hard implement such feature by myself.

**Comment by sporritt** [comment]
nothing internal to jsplumb used it and there were no tests. without seeing anyone's use case i've no real idea what people used it for, so it seems likely it wont get ported.
