### ISSUE TITLE
Dropping underneath lists

### ISSUE THREAD

**Issue by jfrkennedy** [jsplumb/jsplumb#944]
This can be seen in the demo page

https://jsplumbtoolkit.com/community/demonstration/lists

Drag an item from the left list and drop it an inch or so underneath, outside, the list on the right, the connection will still be drawn. This becomes an issue if there's happen to be a 3rd list in that area, as depending which list was added first will lead to unexpected behavior (which can happen in systems where the user can drag the lists around)

Drop here:
![image](https://user-images.githubusercontent.com/46765344/86165005-b1ffe680-bae0-11ea-9276-a3d9aed26275.png)

After drop:
![image](https://user-images.githubusercontent.com/46765344/86165034-bc21e500-bae0-11ea-82ff-a9f791d2b046.png)

**Comment by sporritt** [comment]
this is interesting; it's probably not just lists where this happens. the code that computes the drop targets does not test if some element is within the scroll viewport of its parent.

**Comment by sporritt** [comment]
I'm adding this to 4.x, and if the fix is simple I might backport it to 2.x, although I'm trying to discourage people from using 2.x now.

**Comment by sporritt** [comment]
fixed in 4.0.0-RC41, released today.
