### ISSUE TITLE
How to choose the specified endpoint when establishing a connection

### ISSUE THREAD

**Issue by diaomina** [jsplumb/jsplumb#947]
建立连接的时候如何选择连接指定的端点

或者说可以选择指定源锚点和目标锚点进行连接嘛，不会自动选择最近的锚点，我看社区版的demo内有一个flowchart的demo是可以实现的

**Comment by sporritt** [comment]
您是指使用“连接”方法以编程方式表示吗？

**Comment by diaomina** [comment]
> 您是指使用“连接”方法以编程方式表示吗？

你好，我是拖动连接，需要指定两个锚点之间的连接

**Comment by diaomina** [comment]
已解决

**Comment by sporritt** [comment]
优秀的
