### ISSUE TITLE
Connection dots radius is broken (?) in RC4

### ISSUE THREAD

**Issue by xrei** [jsplumb/jsplumb#948]
Updated to newer version and it fixes connecting output to other output but the dots have become small and it seems config to make them bigger not working.
![image](https://user-images.githubusercontent.com/9521710/86385473-02ba3f80-bc99-11ea-9c8d-8b3e1e84d443.png)

**Comment by sporritt** [comment]
could you paste the code you're using?

**Comment by sporritt** [comment]
if its a default you might want to make sure you've read everything listed in the changelog:

https://jsplumbtoolkit.com/blog/community-edition-4.x

**Comment by xrei** [comment]
Well it's strange.
```js
const targetEndpoint = {
  endpoint: 'Dot',
  paintStyle: {
    radius: 10,
    fill: 'transparent',
    strokeWidth: 1,
    stroke: '#D0D3FA',
  },
  hoverPaintStyle: endpointHoverStyle,
  maxConnections: -1,
  dropOptions: { hoverClass: 'hover', activeClass: 'active' },
  isTarget: true,
}```

this is my config for source dot for example. maybe you tell me which property changes the width and height of the dot? i want make it bigger.

**Comment by xrei** [comment]
I downgraded to previous version and here its fine with exactly the same config as above
![image](https://user-images.githubusercontent.com/9521710/86406695-45414380-bcbc-11ea-8e64-537b49421770.png)

**Comment by xrei** [comment]
Well i see you've changed the default radius of dot endpoint
https://github.com/jsplumb/jsplumb/commit/a9e159944ee642d5df7e1aaa6c8b81a2837c23c4

also i don't see `radius` here https://github.com/jsplumb/jsplumb/blob/4.0.0-RC4/ts/styles.ts

**Comment by xrei** [comment]
Finally i found where it should be!

`endpoint: ['Dot', { radius: 10 }]`

If you need some help with documentation of such things i think i could help :) Because currently i had to go inside sources to understand how it should be.

**Comment by sporritt** [comment]
This issue _is_ you helping with the documentation of things, so thanks!

**Comment by sporritt** [comment]
This is the type definition for `PaintStyle` now:

```
export interface PaintStyle {
    stroke?: string;
    fill?: string;
    strokeWidth?: number;
    outlineStroke?:string;
    outlineWidth?:number;
}
```

I'll update the changelog to reflect the fact that `radius` is not supported.
