### ISSUE TITLE
Endpoint/connection events not firing in 4.x alpha

### ISSUE THREAD

**Issue by BellangerK** [jsplumb/jsplumb#949]
Hi,
Moving my code to 4.x alpha, I realized listeners are not working anymore for endpoints (and probably connections too). I had :

```typescript
    endpoint.bind("mouseover", (endpoint) => {
      //stuffs
      console.log("over", etape.isShowingNoLink);
    }, true);
    endpoint.bind("mouseout", (endpoint) => {
      //stuffs
      console.log("out", etape.isShowingNoLink);
    });
    console.log(endpoint);
```

When creating endpoints, I can see the listeners i just bound in console bu they are never firing.

![image](https://user-images.githubusercontent.com/32840014/86458636-dac4ed80-bd25-11ea-921d-58d3401abf1d.png)

 Are they still available in alpha or am I doing it wrong ?

**Comment by sporritt** [comment]
they weren't available, no.  one of the main changes in 4.x, aside from the port to Typescript, is moving to delegated event handlers instead of binding to each endpoint/connection. so i've just released RC5, in which you can bind (on a jsplumb instance) to

```
connectionMouseOver
connectionMouseOut
endpointMouseOver
endpointMouseOut
```

the callback is given the connection/endpoint and the original event.  there are no tests for this yet so i'd be interested in hearing how it goes for you.

**Comment by sporritt** [comment]
...I've added some tests for these now, they appear to be working.

**Comment by BellangerK** [comment]
It's working like a charm. I thought it was broken since I used npm install with the RC5 but the changes were not in the package (maybe it's not what you should do to get last version). I had to get the js file from GitHub directly. Good idea to move to delegated event handlers. :)

**Comment by sporritt** [comment]
hmm no sounds like I messed something up if the changes aren't in the package. i'll take a look. thanks for the feedback.

**Comment by sporritt** [comment]
it doesnt look to me like there was a problem with the packaging in RC5, but I've just released RC6 in case.

**Comment by BellangerK** [comment]
I deleted my node-modules folder and runned "npm install" again. And changes to jsPlumb.js are here now. Though I do not see the change you've made concerning typings in AnchorSpec (where anchor can be an array of numeric values). Thanks.

**Comment by sporritt** [comment]
right, yes - that _was_ an issue, I'd been running the wrong build target for packaging! try 4.0.0-RC7, just released like 30 seconds ago.

**Comment by BellangerK** [comment]
Everything seems alirght now :) Thanks a lot. I will let you know if I run into some other issues but right now my app seems to fully work with alpha version 4.

**Comment by BellangerK** [comment]
Ah. There is still an import issue with AnchorSpec modification

![image](https://user-images.githubusercontent.com/32840014/86601018-1cad9800-bfa1-11ea-8874-4ce84aed15e3.png)

Anchor manager seems not to have exported member for AnchorPlacement

**Comment by BellangerK** [comment]
Ah wait... my bad, the problem was on my side. ;)

**Comment by sporritt** [comment]
It's very useful getting some feedback on 4.x, much appreciated.

**Comment by sporritt** [comment]
I'll close this one out then.
