### ISSUE TITLE
Crossing connectors jumps

### ISSUE THREAD

**Issue by xversus** [jsplumb/jsplumb#950]
Hello,

I'm trying to figure out the way to add Visio-like jumps on crossing connectors but have trouble finding such an option in the docs.
https://support.content.office.net/en-us/media/f59f134d-11dc-4068-85c7-7977c9a8850e.png

Is it possible at all? If not, is there a possibility to implement it in the future?

**Comment by sporritt** [comment]
no, this is not possible currently.  there's nothing on the roadmap for the community edition for this.
