### ISSUE TITLE
关于连线单击选中的问题

### ISSUE THREAD

**Issue by diaomina** [jsplumb/jsplumb#951]
您好，请问在连线的单击事件里面添加什么可以实现：单击连线后，可以把这条线从前后两个端点移开，而不是拉出了新线呀
`jsplumb.bind('click', function (connection) {
  // 将连线标记为选中状态，可以对其进行重新连接
}`

现在的情况是：元素添加了4个端点，每个端点的isSource、isTarget都是true。就是两个元素相连后，想重新把一个元素连接其他地方去。现在是当你去拉动线的时候，线不会移开元素，而是新拉出了一条线。

**Comment by sporritt** [comment]
听起来好像这些端点的“ maxConnections”设置为-1。 如果您设置“ maxConnections：1”，则每个端点仅支持单个连接，并且在拖动时应拖动现有连接。

**Comment by sdfcbs91** [comment]
> 您好，请问在连线的单击事件里面添加什么可以实现：单击连线后，可以把这条线从前后两个端点移开，而不是拉出了新线呀
> `jsplumb.bind('click', function (connection) { // 将连线标记为选中状态，可以对其进行重新连接 }`
> 
> 现在的情况是：元素添加了4个端点，每个端点的isSource、isTarget都是true。就是两个元素相连后，想重新把一个元素连接其他地方去。现在是当你去拉动线的时候，线不会移开元素，而是新拉出了一条线。

需要在connect线条上加上点击事件，获取到connect对象后，进行删除  比如:
//connect 为连线的对象 
//jsPlumb.getAllConnections() 可以获取所有连线
window.jsPlumb.deleteConnection(connect);
