### ISSUE TITLE
HTML classes not updating well in alpha 4.*

### ISSUE THREAD

**Issue by BellangerK** [jsplumb/jsplumb#952]
Hi Simon,
I noticed some problems involving endpoints manipulation :

1) I'm setting endpoints on my elements (left source, left target, right source, right target for each element). I'm able to do most manipulations as in previous versions of jsPlumb but when I detach an element the classes are not updating.
![image](https://user-images.githubusercontent.com/32840014/86787866-d40be280-c065-11ea-8eb8-b8b064f3a5cf.png)
Here is an example where is detach my element by dragging my connection from target endpoint and droping in empty area but as you can see there are still classes such as "jtk-enpoint-connected" and others. I made a workaroud by removing classes on each event (detach, abort and even connection). But I don't feel well about it.

2) Now, here is another weird behavior. Following this is the structure of endpoints for one element in the DOM :
![image](https://user-images.githubusercontent.com/32840014/86788731-c73bbe80-c066-11ea-8598-66d79269fd11.png)
But if i click on the endpoint without dragging it creates one element by click (i dont what kind of elements they are). In the following example I clicked three times on same endpoint : 
![image](https://user-images.githubusercontent.com/32840014/86789051-28fc2880-c067-11ea-8a12-c21e27f6ee96.png)

3) Last, when detaching a connection the same way i did in first issue above I have log in my console telling : 

> REGRESSION: getDragScope will not work now that individual elements are not configured as draggables

But i don't know the meaning.

Hope it's useful and it's not just about misunderstanding on my part. ;)

**Comment by sporritt** [comment]
The first two of these are fixed in RC8, released this morning. The third is just a warning about something that may or may not turn out to be a problem.

**Comment by BellangerK** [comment]
Fixes are working. Great. Thanks. You can close that issue.

**Comment by sporritt** [comment]
Thanks again for your help getting this released polished up.

**Comment by BellangerK** [comment]
Hello @sporritt, 
It seems that [this commit](https://github.com/jsplumb/jsplumb/commit/c13f2c85f4a8a1bc0ce8b1954b6943c7014ed657) breaks the fix you've made concerning drag classes (after updating, classes are not removed again).

**Comment by sporritt** [comment]
all of the unit tests written for this still pass. what specifically are you seeing?

**Comment by BellangerK** [comment]
1) source endpoint has never been connected to anything, everything is alright : 

![image](https://user-images.githubusercontent.com/32840014/89389896-4ffd5700-d706-11ea-98e7-e55951d14d55.png)

2) i drag connection from source endpoint to a target (classes are added as expected) : 

![image](https://user-images.githubusercontent.com/32840014/89390121-93f05c00-d706-11ea-815b-be3495b562aa.png)

3) now i detach connection by dragging connection from source endpoint :
![image](https://user-images.githubusercontent.com/32840014/89390327-d2861680-d706-11ea-924b-cff1c41cf417.png)

As you can see, there is still classes i do not want anymore "endpointDrag", "jtk-endpoint-connected" and "jtk-dragging" instead of having the same classes as in step 1. It was fine in RC10 but broken in RC17. 

Since i use those classes to change endpoints colors according to their state (making it red when connected vs grey when not), my CSS is not working anymore. 
`.source-right-point.jtk-endpoint-connected > svg > rect {
    fill: #D3756B;
}`

Result is : 
![image](https://user-images.githubusercontent.com/32840014/89391518-9d7ac380-d708-11ea-9c72-b42218fa4b65.png)

**Comment by BellangerK** [comment]
Seems this is because I do not enter the block : 

![image](https://user-images.githubusercontent.com/32840014/89394136-fef06180-d70b-11ea-9c6a-18840543184e.png)

**Comment by sporritt** [comment]
yes i think it should probably execute that block whether the connection was discarded or not

**Comment by sporritt** [comment]
...try 4.0.0-RC18

**Comment by BellangerK** [comment]
It fixes my issue. Thanks. :)
