### ISSUE TITLE
Mouse scroll direction differs from Firefox to Chrome when zooming

### ISSUE THREAD

**Issue by Lennard-Dietz** [jsplumb/jsplumb#956]
When zooming with the mouse wheel on a rendered graph, the zoom direction differs when using Firefox vs Chrome.

Used Chrome version: 83.0.4103.116
Used Firefox version: 78.0.2

**Comment by sporritt** [comment]
This is for the Toolkit edition?

**Comment by Lennard-Dietz** [comment]
Yes, exactly.

**Comment by sporritt** [comment]
ok. this tracker is for the community edition.

**Comment by sporritt** [comment]
if you are a licensee or evaluator, you can contact support@jsplumbtoolkit.com. this issue will be deleted tomorrow.
