### ISSUE TITLE
Since yesterday draggable is not working anymore

### ISSUE THREAD

**Issue by akreienbring** [jsplumb/jsplumb#958]
Hello,
I'm deploying jsplumb with webpack. I installed it via npm and then it resides in the node_modules folder. Yesterday i updated to the current version 2.14.3. After that I realized (around 19:00 PM) that elements on the canvas can not be dragged anymore!

Reverting to the previous version 2.13.3 did NOT solve the problem. 
Even deleting node_modules and doing a fresh "npm install" with 2.13.3. doesn't help!

ONLY when i go back to a backup of the node_modules folder I'm able to bundle everything and get draggable elements.

As I've updated other things yesterday as well, I'm not sure if that is a jsplumb issue. I will further inspect this and post my findings here.

**Comment by sporritt** [comment]
I think the clue is in the fact that reverting to 2.13.3 didn't fix the issue. It doesnt seem like something caused by the change in jsPlumb version.

**Comment by akreienbring** [comment]
Found the issue: The latest version of  [@panzoom/panzoom](https://github.com/timmywil/panzoom) breaks my draggable elements. I will post this issue there. Thanks.
