### ISSUE TITLE
TS:  'parameters' does not exist in type 'ConnectParams'

### ISSUE THREAD

**Issue by fk1blow** [jsplumb/jsplumb#962]
As per [Connection and Endpoint Parameters](https://docs.jsplumbtoolkit.com/community/current/articles/parameters.html) docs, the `connect` function accepsts a `parameters` object, and although this works, the TS compiler will complain, spitting a ` Object literal may only specify known properties, and 'parameters' does not exist in type 'ConnectParams'.` error.

```
.connect({
      source,
      target,
      anchors: [["RightMiddle", ], "LeftMiddle"],
      endpoint: 'Blank',
      parameters: {
        'xxl': 'xxl+parameter'
      }
})
```

At the same time, i know that i can just ignore that specific line(or cast to any) but ideally, i wouldn't need to do that. Is there a way that i can improve the typings, either by patching them or submit a pr with the fix?

LE: saw that the `EndpointOptions` have a `parameters` field - can i just ignore the line for now(in a hurry) or is this prone to changes(and the `ConnectParams` doesn't include the `parameters` on purpose?)

Thanks!

**Comment by sporritt** [comment]
`parameters` should be in `ConnectParams`. I will add it.

**Comment by sporritt** [comment]
this is present in 2.14.4:

```
interface ConnectParams {
        uuids?: [UUID, UUID];
        source?: ElementRef | Endpoint;
        target?: ElementRef | Endpoint;
        detachable?: boolean;
        deleteEndpointsOnDetach?: boolean;
        endpoint?: EndpointSpec;
        anchor?: AnchorSpec;
        anchors?: [AnchorSpec, AnchorSpec];
        label?: string;
        connector?: ConnectorSpec;
        overlays?:Array<OverlaySpec>;
        cssClass?: string;
        parameters?: Record<string, any>;
    }
```

I also changed `parameters` to be of type `Record<string, any>` in `EndpointOptions`.  `object` is not a good choice; TS always complains that keys are not defined when you use `object` for something like this.

**Comment by fk1blow** [comment]
sure, having a `Record` is better than `object`.

Was about to add that the `Connection` would need a `getParameter` definitions as well - sorry for ignoring it in the first post.

**Comment by sporritt** [comment]
ok that's in 2.14.5 just released

**Comment by fk1blow** [comment]
Thank you!
