### ISSUE TITLE
How to use v4 new drag events

### ISSUE THREAD

**Issue by jordanCht** [jsplumb/jsplumb#963]
Hello, I'm looking for any documentation or example about the new event `drag:move`. It doesn't seem to work for me with 
`this.jsPlumb.bind("drag:move"...`. The aim is to catch a connector dragging event. 

Thanks

**Comment by sporritt** [comment]
`drag:move` is for nodes. There isnt an event that fires continuous for connection drag, but `connectionDrag` fires at the start of a connection drag (which is, i think, unchanged from the 2.x version)
