### ISSUE TITLE
How can I  Re-render a line when the element's width of the endpoints connected by this line changes ? 

### ISSUE THREAD

**Issue by wenhaonan** [jsplumb/jsplumb#964]
thanks!

![Snipaste_2020-07-29_16-55-29](https://user-images.githubusercontent.com/38740692/88779795-bfca8980-d1bc-11ea-83f5-42cda6615f81.png)
![Snipaste_2020-07-29_16-55-46](https://user-images.githubusercontent.com/38740692/88779801-c1944d00-d1bc-11ea-92a2-dbd20c977db8.png)

Just like these two pictures, when I change the width of the element, the line still points to the original position.

**Comment by sporritt** [comment]
you can use `revalidate(someElement or ID)` for this.

**Comment by wenhaonan** [comment]
> you can use `revalidate(someElement or ID)` for this.

Thank you!  I just saw the api `repaint`. I test `revalidate` again now. Boths are fine !  thank you again!
