### ISSUE TITLE
Delete and then add(删除一个元素之后再把这个元素添加进去)

### ISSUE THREAD

**Issue by Kang127** [jsplumb/jsplumb#965]
For example: first add the element with id="a", then use Jsplumbin.remove (ID) to remove, then add the element with id="a" again, it will report an error. What's the reason?
error message ：Cannot read property 'parentNode' of null

**Comment by sporritt** [comment]
Can you provide a codepen/jsfiddle?

**Comment by Kang127** [comment]
> 您可以提供一个codepen / jsfiddle吗？

这个是我自己的问题，我已经修改了。放弃使用了remove，通过修改state的状态重新渲染Dom
