### ISSUE TITLE
Does not connect correctly elements inside a table

### ISSUE THREAD

**Issue by doctormohamed** [jsplumb/jsplumb#966]
Hi,

I'm trying to use the connect function to link elements inside a **table**.
I have made this stackblitz to show that the line is not connecting correctly the two elements:
https://stackblitz.com/edit/angular-jsplumb-hzfb6i
I dont know if I am missing something here or in the connector configuration...

However, with normal divs seems to be working.

Thanks.

**Comment by sporritt** [comment]
It doesn't entirely surprise me..the normal setup is some absolute positioned elements that share a parent. A table is quite different from that. You might need to look into overriding the `getOffset` method in your jsPlumb instance to support that.

**Comment by doctormohamed** [comment]
Thanks sporrit for the quick reply, I am new here and I dont know what you mean by overriding the getOffset method.
I checked the jsPlumb code and I didnt see the function defined in the class neither.

**Comment by sporritt** [comment]
getOffset is in this file

https://github.com/jsplumb/jsplumb/blob/master/src/dom.jsplumb.js#L614

**Comment by doctormohamed** [comment]
Thanks, I have override the getOffset and it works!

**Comment by sporritt** [comment]
Do you think that for the benefit of others you might perhaps share your overridden getOffset method?

**Comment by sporritt** [comment]
@doctormohamed any chance you might share your code?
