### ISSUE TITLE
seek help:How do I get anchor information, such as: UUID

### ISSUE THREAD

**Issue by Kang127** [jsplumb/jsplumb#967]
There are multiple anchor points on two nodes. If the two anchor points are connected manually, how to obtain the UUID of the two anchor points?Now by listening for  "Jsplumbin.bind (' Connection ', function (obj){      });" , there is no UUID in the message

**Comment by Kang127** [comment]
Got it,     targetEndpoint.getUuid()

**Comment by tomcatcn** [comment]
very good ,I'm have find this method for o long time. think!!!!
