### ISSUE TITLE
setZoom is invalid after jsplumb.reset

### ISSUE THREAD

**Issue by feiyuerenhai** [jsplumb/jsplumb#968]
to be specific, setZoom gets invalid, because the _zoom value in _katavario remains the same however setZoom is called.
there is a workaround, ```managed.el._katavorioDrag.k.setZoom(scale);```

**Comment by sporritt** [comment]
setZoom on jsplumb calls setZoom on the katavorio instance though, doesnt it?

**Comment by sporritt** [comment]
I'm going to close this due to lack of follow up. `setZoom` on a jsPlumb instance does call `setZoom` on the katavorio instance. so without seeing the running code i don't know what, if any, error is occurring.
