### ISSUE TITLE
About the performance of the unmark function

### ISSUE THREAD

**Issue by sdfcbs91** [jsplumb/jsplumb#969]
In the unmark function, _setDroppablesActive is used to set other nodes to restore the default style, resulting in poor performance.
For example: when there are 500 nodes (one node is set with 2 points, so 1000 points), I drag a connection and feel very stuck, and find that _setDroppablesActive takes about 1200ms (chome:81.0.4044.138) .

So, can you consider optimizing the performance of unmark?

unmark:
this.unmark = function(e, doNotCheckDroppables) {
            _setDroppablesActive(matchingDroppables, false, true, this);
      ....
}

**Comment by sporritt** [comment]
I don't think there's much chance of this happening in the 2.x branch. 2.x is now being wound down, in favour of the 4.x branch, which is available on npm as `@jsplumb/community`.

There's a blog post announcing the beta release of it here

https://jsplumbtoolkit.com/blog/community-edition-4.x

**Comment by sdfcbs91** [comment]
The core of the 2.x version is to support dom customization,
How many nodes are more suitable for rendering?

4.x, i'll go see

**Comment by sdfcbs91** [comment]
Hello, harass again
I used 4.x, and the first step failed. Is there any call example?
My code:
 `
  import jsPlumbCounty from '@jsplumb/community';
 ...
  this.jsPlumb = jsPlumb.newInstance();`

errorText:
  `
Error in mounted hook: "TypeError: Cannot read property 'setAttribute' of null"
TypeError: Cannot read property 'setAttribute' of null
    at BrowserJsPlumbInstance.setAttribute (jsplumb.js:13414)
    at BrowserJsPlumbInstance.setContainer (jsplumb.js:13652)
    at BrowserJsPlumbInstance.jsPlumbInstance (jsplumb.js:6746)
    at new BrowserJsPlumbInstance (jsplumb.js:13167)
    at Object.newInstance (jsplumb.js:18082)
...
`

**Comment by sporritt** [comment]
from the changelog:

It is imperative that you provide the container for an instance of jsPlumb. We no longer infer the container from the offsetParent of the first element to which an Endpoint is added. If you do not provide container an Error is thrown.



you need to provide container in the newInstance call.

```
jsPlumb.newInstance({
  container:someElement
})
```

there are a bunch of things different in 4.x. best to read the entire changelog.

**Comment by sdfcbs91** [comment]
thanks.
I watch carefully
