### ISSUE TITLE
【4.x-alpha】When dragging the anchor ：<svg> attribute width: Expected length, "-Infinity"

### ISSUE THREAD

**Issue by sdfcbs91** [jsplumb/jsplumb#970]
hi,
When dragging the anchor point of the node, the plug-in will have an svg error: 

`
 Error: <svg> attribute width: Expected length, "-Infinity".
Error: <svg> attribute height: Expected length, "-Infinity".
`

Chomre Debug:
I hit a breakpoint in the debugging code, when the mouse clicked "_downListener".

The structure of the copied point element in the browser at this time is:
`<div id="jsPlumb_1_143" jtk-managed="" style="position: absolute; left: 313px; top: 21px; width: 22px; height: 22px;"></div>`
errorText:
`
 Error: <svg> attribute width: Expected length, "-Infinity".
Error: <svg> attribute height: Expected length, "-Infinity".
`

【4.0RC20】 How to avoid this problem？

![企业微信截图_15993802723324](https://user-images.githubusercontent.com/3993570/92321689-89571880-f05e-11ea-95ee-0b1965687dbf.png)
![企业微信截图_15993804763613](https://user-images.githubusercontent.com/3993570/92321691-8eb46300-f05e-11ea-900a-d4bf48e388b6.png)

**Comment by sporritt** [comment]
do you actually see any functional error?

**Comment by sdfcbs91** [comment]
The actual function has no effect,
The newly copied endPoint will execute paint once, and after it is copied when it is moved
![企业微信截图_15993874241351](https://user-images.githubusercontent.com/3993570/92323706-8152a500-f06d-11ea-8bae-feee820010ab.png)
I think the endPoint copied this time does not need to forcibly set the **width** and **height**.

**Comment by sporritt** [comment]
The error looks like it comes from the connector painting, in fact. I'd say perhaps because at the start of the drag the start point and end point are identical.

**Comment by sdfcbs91** [comment]
Um, I will try other methods or debug the source code

**Comment by sporritt** [comment]
There is no functional error though, right? Just so I'm clear. Everything works, but you see a console message?

**Comment by sdfcbs91** [comment]
Yes. Only console messages

**Comment by sporritt** [comment]
closing this. 4.x ended up a non starter, there was no functional issue, and it hasn't been seen in 5.x.
