### ISSUE TITLE
When there is no event parameter, the off function

### ISSUE THREAD

**Issue by sdfcbs91** [jsplumb/jsplumb#971]
When no parameters are passed in, can the off function clear the bind monitoring manually defined by the user？

E.g：
`
jsplumb.bind('endpointMouseOver',function(e){console.log(1,arguments)})

jsplumb.off('endpointMouseOver')  => jsplumb.off()
`

**Comment by sporritt** [comment]
...um, I suppose it _could_, although it doesn't right now. But if this were possible, some part of the code would be able to arbitrarily mess with some other part of the code. I'm not sure we want that.  The underlying DOM function requires that the handler to be removed be passed in:

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

**Comment by sdfcbs91** [comment]
What you said makes sense.
Such as jquery's off function. It can be unbound at any time.
Or provide accessible listeners properties, when users need to unbind all events, pass in listeners to unbind all

**Comment by sporritt** [comment]
I'm going to close this.
