### ISSUE TITLE
ManagedElements out of sync if element removed and re-inserted

### ISSUE THREAD

**Issue by vongrad** [jsplumb/jsplumb#973]
If an element with specific ID is removed from DOM while it was managed by jtk and subsequently re-inserted with the same ID, the managedElements will not be updated - it will point to DOM element that was previously removed. This causes incorrect offset calculations.

**Comment by sporritt** [comment]
have you tried using the `unmanage` method when the element is removed?

**Comment by vongrad** [comment]
Yes, that’s the way I got it working. I was just thinking that this is worth mentioning as it might be a bug?

**Comment by sporritt** [comment]
um, i dont think its a bug. if you blow away an element you've asked jsplumb to track, you have to tell jsplumb about it.

**Comment by sporritt** [comment]
so i'm going to close this.
