### ISSUE TITLE
Changing css properties of new drag and drop connections

### ISSUE THREAD

**Issue by JahedulAnowar** [jsplumb/jsplumb#974]
I want to visually distinguish between loaded connections and connections that are created by drag and drop.
So, is there a way to assign different color or connector type when i create a drag and drop connection?

**Comment by JahedulAnowar** [comment]
Nevermind, i found a way to change the color.

**Comment by sporritt** [comment]
i dont suppose you feel like helping out future people by sharing what you did, do you?
