### ISSUE TITLE
TypeError: Cannot set property 'getParameter' of undefined

### ISSUE THREAD

**Issue by liumt1993** [jsplumb/jsplumb#975]
os: mac os
chrome version: 85.0.4183.102
jsplumb version: 2.14.6

import { jsPlumb } from 'jsplumb';

![image](https://user-images.githubusercontent.com/4754770/93746715-3073ac80-fc28-11ea-9a74-88bcffbb11ea.png)

I use jsplumb in micro frontends framework 'qiankun'(https://github.com/umijs/qiankun).

jsplumb is worked if not use micro frontends framework.

can you help me resolve this problem?

**Comment by sporritt** [comment]
Can you tell me what you mean when you say it works if you're not using the micro frontends framework?

**Comment by liumt1993** [comment]
> Can you tell me what you mean when you say it works if you're not using the micro frontends framework?

In the past, when I didn't use a micro front-end framework, jsplumb was able to initialize properly.

When I started using the micro frontend framework and separated the part that uses jsplumb into sub-applications, the reference to jsplumb would report an error when the sub-application was loaded. Hint: qiankun does a cleanup of the global variables during the sub-application loading process, is it possible that this is causing this?

I think there might be a problem with the binding of windows or this, but I don't know the details.

**Comment by sporritt** [comment]
i dont think there's a great deal i can suggest without seeing the code in action. you might want to put a breakpoint in there and see what's going on.

**Comment by liumt1993** [comment]
> i dont think there's a great deal i can suggest without seeing the code in action. you might want to put a breakpoint in there and see what's going on.

ok,thanks,i'll try it

**Comment by XiaohuaDuo** [comment]
请问，解决了吗？遇到了同样的问题

**Comment by liumt1993** [comment]
> i dont think there's a great deal i can suggest without seeing the code in action. you might want to put a breakpoint in there and see what's going on.

I debugged it for a while and found that it was the pointing of the variable `root`. When root = this, there is an error. And root = globalThis, it's fine.i guess qiankun clear the global varaibles is the  cause of the error.

i have not time to deep debugger,but the problem is resolved. haha, maybe i can commit a pull request.

**Comment by chris1299** [comment]
@liumt1993 I encountered the same problem, if you solve it, can you help me? thanks

**Comment by sporritt** [comment]
Please migrate to 4.x

https://www.npmjs.com/package/@jsplumb/community

**Comment by MiracleCsf** [comment]
@liumt1993 大佬，请问你是怎么解决这个问题的？
