### ISSUE TITLE
Adding a new connection to an already proxied element

### ISSUE THREAD

**Issue by jfrkennedy** [jsplumb/jsplumb#976]
When using lists (https://docs.jsplumbtoolkit.com/community/current/articles/lists.html), if an element that is out of view, that already has connection that was proxied, receive a new connection, it will not be proxied as well.

This can happen if connections are loaded asynchronously (or by some other external factor), until the user scrolls the element into and out of view, the connection will point to there the element is (off to the top/bottom).

I assume this happens because of this check:
https://github.com/jsplumb/jsplumb/blob/c371e2587b9611d209a39dac620a96b924cc79ea/src/lists.js#L152

which makes sense for performance concerns, but maybe a new connection should be able to force through (and of course, the code would also need to check if the connection has been proxied already or not.

**Comment by sporritt** [comment]
fixed in 4.0.0-RC42, which was just released. closing.
