### ISSUE TITLE
The endpoint drag area does not dynamically change with the height of the element.

### ISSUE THREAD

**Issue by nitroge** [jsplumb/jsplumb#978]
After the node connection has been created, the node content height is changed and the endpoint drag area is still around the initial height.

**Comment by sporritt** [comment]
can you provide a codepen/jsfiddle? it's not entirely clear what you mean.

**Comment by nitroge** [comment]
![img_1.png](https://i.loli.net/2020/10/10/FJCifyuWm79KELR.png)
![img_2.png](https://i.loli.net/2020/10/10/YIsoQrWxKtHagNM.png)
use jsPlumb.repaintEverything() is not valid after the height is modified.

**Comment by nitroge** [comment]
![before](https://res.shiguangkey.com/file/2020/10/10/16023115935683612469155.png)
![after](https://res.shiguangkey.com/file/2020/10/10/16023116130502140275957.png)
use jsPlumb.repaintEverything() method  is not working after the node height has changed

**Comment by sporritt** [comment]
you shouldn't need to use `repaintEverything()` in this case, `revalidate(element or id)` ought to work.

**Comment by nitroge** [comment]
Thank you so much

**Comment by sporritt** [comment]
no problem. ok to close this then?
