### ISSUE TITLE
jsplumb remove endpoints bug

### ISSUE THREAD

**Issue by lianzhidong** [jsplumb/jsplumb#980]
I use this function to add the endpoints to the div:
`    addAllEndpoint(id) {
      this.instance.addEndpoint(id, {
        ...endpointOptions,
        uuid: id + 'Top',
        anchor: 'Top',
        cssClass: 'ctg-endpoint'
      })
      this.instance.addEndpoint(id, {
        ...endpointOptions,
        uuid: id + 'Bottom',
        anchor: 'Bottom',
        cssClass: 'ctg-endpoint'
      })
      this.instance.addEndpoint(id, {
        ...endpointOptions,
        uuid: id + 'Left',
        anchor: 'Left',
        cssClass: 'ctg-endpoint'
      })
      this.instance.addEndpoint(id, {
        ...endpointOptions,
        uuid: id + 'Right',
        anchor: 'Right',
        cssClass: 'ctg-endpoint'
      })
    },`
and the code blow to remove the endpoints
`        this.instance.deleteEndpoint(this.selectedNode.id + 'Top', true)
        this.instance.deleteEndpoint(this.selectedNode.id + 'Bottom', true)
        this.instance.deleteEndpoint(this.selectedNode.id + 'Right', true)
        this.instance.deleteEndpoint(this.selectedNode.id + 'Left', true)`
however, after remove the endpoints and the div,other div's endpoint would out the div.After I drag the div,the endpoints come back to the div.Any suggestion about this?

**Comment by sporritt** [comment]
you have to pass in the Endpoint object, not its UUID, to `deleteEndpoint`.
