### ISSUE TITLE
在微前端qiankun中使用时，报错TypeError: Cannot set property 'getParameter' of undefined

### ISSUE THREAD

**Issue by XiaohuaDuo** [jsplumb/jsplumb#981]
![image](https://user-images.githubusercontent.com/32640423/96101693-51b67880-0f08-11eb-9a39-5ec767792449.png)

**Comment by sporritt** [comment]
Do me a favour and avoid opening duplicates. You've already commented on this exact issue:

https://github.com/jsplumb/jsplumb/issues/975#issuecomment-709002056
