### ISSUE TITLE
how to add z-index in JsPlumb with Angular?

### ISSUE THREAD

**Issue by adarshk007** [jsplumb/jsplumb#982]
I'm struggling with jsPlumb . Actually, I want to add z-index so that the nodes, circle point will be always visible over the connections.

code : [sample code](https://stackblitz.com/edit/angular-jsplumb-test-2uyw3t?file=app/app.component.ts)

Please see the issue image below:
![z-index](https://user-images.githubusercontent.com/23396919/96677449-3ecef880-138d-11eb-8592-d7e6ca2638a2.png)

by adding .jtk-connected {z-index : 999} in css will resolve one issue but create new issues like circle points/ports will shift backwards and they will be partially visible. But in case of ports we can't change the z-index as these are SVGs. Even i tried to add something in cssClass regarding z-index but nothing happened.

**Comment by sporritt** [comment]
`.jtk-endpoint` is the class given to Endpoints.
