### ISSUE TITLE
jsPlumbInstance.draggable method has an incomplete typescript definition

### ISSUE THREAD

**Issue by fk1blow** [jsplumb/jsplumb#983]
the `draggable(el: Object, options?: DragOptions): jsPlumbInstance;`is missing the `grid` field exposed on the DragOptions, therefore needing the `@ts-ignore` flag

```
  plumb?.draggable(id, {
    // @ts-ignore
    grid: [30, 30]
  })
```

**Comment by sporritt** [comment]
Please migrate to 4.x

https://www.npmjs.com/package/@jsplumb/community
