### ISSUE TITLE
AddToPosse on startdrag causes error while dragging

### ISSUE THREAD

**Issue by Zanzavar** [jsplumb/jsplumb#985]
REPLICATION:
- Setting addtoPosse() on two draggable nodes in startdrag event handler
- Getting the following error in devtools during drag of the active node

![image](https://user-images.githubusercontent.com/900831/99233934-8c0f8000-27fc-11eb-8ee0-323237c48b07.png)

NOTE: 
This happens only if the non-active node has not been dragged yet.
Jsplumb version: 2.15.0

CODEPEN:
https://codepen.io/zanzavar/pen/GRqeRZB?editors=1111

**Comment by sporritt** [comment]
Closing this as 2.x is no longer supported. If an issue in 5.x we can take a look.
