### ISSUE TITLE
reconnection error after jsPlumb.deleteConnection(connInfo.connection);

### ISSUE THREAD

**Issue by netmou** [jsplumb/jsplumb#987]
reconnection error after jsPlumb.deleteConnection(connInfo.connection);
 

jsPlumb function failed : TypeError: Cannot read property '0' of null
jsplumb.js:3448 Uncaught Error: 
    at log (jsplumb.js:3448)
    at Object.drop (jsplumb.js:3477)
    at Drop.drop (jsplumb.js:2384)
    at Drag.unmark (jsplumb.js:2232)
    at Drag.<anonymous> (jsplumb.js:2074)

**Comment by sporritt** [comment]
please provide a codepen or something.

**Comment by netmou** [comment]
<!DOCTYPE html>
--
  | <html lang="zh-CN">
  | <head>
  | <meta charset="UTF-8">
  | <title>自定义流程图</title>
  | <link rel="stylesheet" href="http://localhost/jdjwxt/public/css/util.css">
  | <link rel="stylesheet" href="http://localhost/jdjwxt/public/css/jsplumb-demo.css">
  | <link rel="stylesheet" href="http://localhost/jdjwxt/plugins/jQuery-contextMenu-2.4.4/jquery.contextMenu.css">
  | <style>
  | body{
  | height:auto;
  | }
  | .content-wrap{
  | height:500px;
  | }
  | .jsp-canvas{
  | height:100%;
  | border:1px solid #aaa;
  | background:url(http://localhost/jdjwxt/public/images/cross.png) repeat;
  | }
  | .jsp-star-icon{
  | height:14px;
  | width:14px;
  | margin:0 2px;
  | vertical-align:middle;
  | display: inline-block;
  | background:url(http://localhost/jdjwxt/public/images/glyphicons-halflings.png) -120px 0;
  | }
  | .jnode-design{
  | width:480px;
  | }
  | /**节点编辑中tab菜单样式*/
  | .tab-title-wrap{
  | margin:0 8px;
  | }
  | .tab-cont-wrap{
  | border-top:1px solid #ddd;
  | padding:8px 5px 16px;
  | }
  | .tab-title-wrap li{
  | border:1px solid #ddd;
  | background:#f5f5f5;
  | border-bottom:none ;
  | padding:3px 8px;
  | font-size:14px;
  | cursor: pointer;
  | margin:0;
  | }
  | .tab-title-wrap li:first-child{
  | margin-left:20px;
  | }
  | .tab-title-wrap .tab-title-active{
  | padding:3px 8px 5px !important;
  | position: relative;
  | background: #fff;
  | cursor: text !important;
  | color:#c44;
  | background:#fff;
  | bottom: -1px;
  | }
  | .tab-title-active:before{
  | display: inline-block;
  | border-left:2px solid #5871cc;
  | height:16px;
  | width:6px;
  | content:"\20";
  | vertical-align: middle;
  | }
  | .start-node{
  | color: #FFF;
  | text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
  | background-color: #5BB75B;
  | background-image: linear-gradient(to bottom,#62C462,#51A351);
  | background-repeat: repeat-x;
  | border-color: #51A351 #51A351 #387038;
  | border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  | }
  | </style>
  | </head>
  | <body>
  | <div class="tool-bar">
  | <span class="btn btn-active">流程设计</span>
  | <a href="processlist.php" class="btn btn-success">返回</a>
  | </div>
  | <div class="content-wrap">
  | <div class="jsp-canvas" id="jsp-canvas">
  | <div class="jsp-node start-node" id="jsp-node-1" style="top:132px;left:161px;">
  | <div class="jnode-name">班主任审核</div>
  | <div class="jnode-start-point"></div>
  | </div>
  | <div class="jsp-node " id="jsp-node-3" style="top:160px;left:676px;">
  | <div class="jnode-name">系主任审核</div>
  | <div class="jnode-start-point"></div>
  | </div>
  | <div class="jsp-node " id="jsp-node-10" style="top:251px;left:547px;">
  | <div class="jnode-name">444</div>
  | <div class="jnode-start-point"></div>
  | </div>
  | </div>
  | </div>
  | <p class="callout txt-primary fnt-5">
  | <b>操作说明：</b><br />
  | 1. 在网格的空白区域右击可创建流程节点；<br />
  | 2. 在流程节点上右击可编辑、删除该节点；<br />
  | 3. 用鼠标按住流程节点，可拖拽该节点；<br />
  | 4. 拖拽流程节点上的橙色圆点至其他节点可创建连线；<br />
  | 5. 双击流程节点之间的连线可删除连线；<br />
  | <span class="txt-warning">6. 一个流程必须含有开始节点（不支持分支）。</span><br />
  | </p>
  |  
  | <script src="http://localhost/jdjwxt/public/js/jquery-1.12.4.min.js"></script>
  | <script src="http://localhost/jdjwxt/plugins/artDialog-7.0.0/dialog-plus.js"></script>
  | <script src="http://localhost/jdjwxt/plugins/jsPlumb-2.12.x/jsplumb.js"></script>
  | <script src="http://localhost/jdjwxt/plugins/jQuery-contextMenu-2.4.4/jquery.contextMenu.js"></script>
  | <script type="text/javascript">
  | jsPlumb.ready(function () {
  | // setup some defaults for jsPlumb.
  | var instance = jsPlumb.getInstance({
  | Endpoint: [
  | "Dot",
  | {
  | radius: 3
  | }
  | ],
  | Connector:"Flowchart",
  | HoverPaintStyle: {
  | stroke: "#1e8151",
  | strokeWidth: 1
  | },
  | DragOptions : {
  | cursor: "move",
  | },
  | ConnectionOverlays: [
  | [ "Arrow", {
  | location: 1,
  | id: "arrow",
  | length: 12,
  | width:12,
  | foldback: 0.6
  | } ],
  | [ "Label", {
  | label: "下一步",
  | id: "label",
  | cssClass: "jsp-conn-label"
  | }]
  | ],
  | Container: "jsp-canvas"
  | }); //end create instance
  |  
  | instance.registerConnectionType("basic", {
  | anchor:"Continuous",
  | connector:"Flowchart"
  | });
  | var canvas = document.getElementById("jsp-canvas");
  | var nodeSet = jsPlumb.getSelector(".jsp-canvas .jsp-node");
  |  
  | var initNode = function(el) {
  | instance.draggable(el,{
  | drag:function(){},
  | start: function(){},
  | stop: function(){
  | elPosUpdate(el);
  | }
  | });
  | instance.makeSource(el, {
  | filter: ".jnode-start-point",
  | anchor: "Continuous",
  | connectorStyle: {
  | stroke: "#5c96bc",
  | outlineColor:"transparent",
  | },
  | connectionType:"basic",
  | maxConnections: 16,
  | onMaxConnections: function (info, e) {
  | alert("单个节点最多支持：" + info.maxConnections+"个连接，请先删除已有的节点 ");
  | }
  | });
  | instance.makeTarget(el, {
  | anchor: "Continuous",
  | uniqueEndpoint:true,
  | allowLoopback: false
  | });
  | };
  |  
  | var createNode = function(id,nodeName, x, y) {
  | var div = document.createElement("div");
  | div.className = "jsp-node";
  | div.id = (id==null)?jsPlumbUtil.uuid():id;
  | div.innerHTML = '<div class="jnode-name">'+nodeName + '</div><div class="jnode-start-point"></div>';
  | div.style.left = x + "px";
  | div.style.top = y + "px";
  | instance.getContainer().appendChild(div);
  | initNode(div);
  | };
  |  
  | instance.batch(function () {
  | for (var i = 0; i < nodeSet.length; i++) {
  | initNode(nodeSet[i]);
  | }
  | instance.connect({ source: "jsp-node-1", target: "jsp-node-3", type:"basic" });
  | });
  |  
  |  
  | instance.bind("connection", function (connInfo, originalEvent) {
  |  
  | if (connInfo.connection.sourceId == connInfo.connection.targetId) {
  | alert("不能连接自己！");
  | return jsPlumb.deleteConnection(connInfo.connection);
  | }
  | if(connInfo.connection.getOverlay("label")!=null){
  | connInfo.connection.getOverlay("label").setLabel("下一步");
  | }
  |  
  | createConnect(connInfo);
  | });
  | instance.bind("connectionDetached", function (conn, originalEvent) {
  | deleteConnect(conn.sourceId, conn.targetId);
  | });
  | // 双击连接事件，在此事件中加入删除链接的逻辑
  | instance.bind("dblclick", function (conn) {
  | instance.deleteConnection(conn);
  | });
  |  
  |  
  | //相关事件处理函数在此
  | //--节点位置更新处理
  | function elPosUpdate(el){
  | var idInfo=$(el).attr('id').split('-');
  | $.post("process-do.ajax.php?act=move&rand="+Math.random(),{
  | id:idInfo[2],
  | offset_x:$(el).position().left,
  | offset_y:$(el).position().top
  | },function(data){
  | if(data.state!='ok'){
  | alert('会话超时，请重新登录！');
  | }
  | },'json');
  | }
  | //--增加新的链接
  | function createConnect(connInfo){
  | $.post("process-do.ajax.php?act=connect&rand="+Math.random(),{
  | "sourceId":connInfo.connection.sourceId,
  | "targetId":connInfo.connection.targetId,
  | },function(data){
  | if(data.state=='overflow'){
  | alert('连接失败，不支持分支，请先删除连接再重连');
  | return jsPlumb.deleteConnection(connInfo.connection);
  | }
  | if(data.state=='session-expired'){
  | alert('会话超时，请重新登录！');
  | }
  | },'json');
  | }
  | //--删除链接
  | function deleteConnect(sourceId,targetId){
  | $.post("process-do.ajax.php?act=unconnect&rand="+Math.random(),{
  | "sourceId":sourceId,
  | "targetId":targetId,
  | },function(data){
  | if(data.state=='session-expired'){
  | alert('会话超时，请重新登录！');
  | }
  | },'json');
  | }
  | //--获取设计面板的数据
  | function getDesignData(){
  | //基本信息
  | var name=$("input[name='name']").val();
  | var is_start=$("input[name='is_start']:checked").val();
  | var over_able=$("input[name='over_able']:checked").val();
  | var rolid=$("select[name='rolid'] option:selected").val();
  | var depid=$("select[name='depid'] option:selected").val();
  | if(name == ''){
  | alert('请填写节点名称！');
  | return false;
  | }
  | return {
  | "name":name,
  | "is_start":is_start,
  | "over_able":over_able,
  | "rolid":rolid,
  | "depid":depid
  | };
  | }
  | //
  | //节点上的右键菜单及事件(无鼠标事件内容)
  | $.contextMenu({
  | selector: ".jsp-node",
  | items: {
  | edit: {name: "编辑节点", icon:"edit", callback: function(key, opt){
  | context=this;
  | var idInfo=$(this).attr('id').split('-');
  | $.get('process-design.ajax.php?rand='+Math.random(),{'pnode_id':idInfo[2]},function(data){
  | dialog({
  | title:"编辑节点",
  | content:data,
  | okValue:"保存信息",
  | quickClose: true,
  | padding:'8px 16px',
  | ok:function(){
  | var designData=getDesignData();
  | if(designData == false){
  | return false;
  | }
  | designData.id=idInfo[2];
  | $.post("process-do.ajax.php?act=edit&rand="+Math.random(),designData,function(data){
  | $('.jnode-name',context).html(designData.name);
  | },'json');
  | if(designData.is_start==1){
  | $(context).addClass('start-node');
  | }else{
  | $(context).removeClass('start-node')
  | }
  | }
  | }).show();
  | })
  |  
  | }},
  | delete: {name: "删除节点", icon:"delete", callback: function(key, opt){
  | if(confirm('确定要删除节点？')){
  | var idInfo=$(this).attr('id').split('-');
  | var context=this;
  | $.post("process-do.ajax.php?act=delete&rand="+Math.random(),{"id":idInfo[2]},function(data){
  | if(data.state=='session-expired'){
  | alert('会话超时，请重新登录！');
  | return false;
  | }
  | instance.remove(context);
  | },'json');
  | }
  | }}
  | }
  | });
  | //画板上的右键菜单事件（含鼠标事件内容）
  | $.contextMenu({
  | selector: ".jsp-canvas",
  | build:function(trigger, e){
  | return {
  | items: {
  | add: {name: "添加节点", icon:"add", callback: function(key, opt){
  | $.get('process-design.ajax.php',{'pnode_id':0},function(data){
  | dialog({
  | title:"添加新节点",
  | content:data,
  | okValue:"创建节点",
  | quickClose: true,
  | ok:function(){
  | var designData=getDesignData();
  | if(designData==false){
  | return false;
  | }
  | designData.offset_x = e.pageX;
  | designData.offset_y = e.pageY;
  | $.post("process-do.ajax.php?act=add&rand="+Math.random(),designData,function(data){
  | if(data.state=='session-expired'){
  | alert('会话超时，请重新登录！');
  | return false;
  | }
  | createNode('jsp-node-' + data.id, designData.name, designData.offset_x, designData.offset_y);
  | if(designData.is_start==1){
  | $('#jsp-node-' + data.id).addClass('start-node');
  | }else{
  | $('#jsp-node-' + data.id).removeClass('start-node')
  | }
  | },'json');
  | }
  | }).show();
  | });
  | }},
  | }
  | };
  | }
  | });
  | });
  | </script>
  | </body>
  | </html>

**Comment by sporritt** [comment]
thanks, but this can't be run.  I mean what i need to see is the code in action, and the steps to reproduce your error.
