### ISSUE TITLE
Missing type declarations on newest version

### ISSUE THREAD

**Issue by krynble** [jsplumb/jsplumb#989]
Version 2.15.1 came with PR #988 that introduced some definitions without return types.

This is breaking builds on our project as this is a requirement.

More specifically this commit: https://github.com/jsplumb/jsplumb/commit/da2d2da5620210619dcdc143f2bf35a657f3f0c6 on lines 175 and 177

Can this be fixed? We are fixing a previous version as of this issue but this is not ideal.

**Comment by sporritt** [comment]
2.15.2 is on npm now with return types on lines 175 and 177

Did this occur because your package.json is setup to automatically pull in minor releases of jsPlumb without human intervention?

**Comment by krynble** [comment]
Yeah we had package.json set up like this: `"jsplumb": "^2.10.0",`

Thank you for the update =)
