### ISSUE TITLE
Error dragging node after creating connections and deleting them

### ISSUE THREAD

**Issue by sebovzeoueb** [jsplumb/jsplumb#990]
I've made a JSFiddle so you can see my exact setup: https://jsfiddle.net/vajpuwze/1/

## The problem ##

jsPlumb throws `TypeError: Cannot read property 'deleteEndpoint' of undefined` after dragging one of the nodes. According to my DevTools this is coming from a function called `maybePruneEndpoint`.

## How to reproduce ##

In my fiddle you can connect nodes together using the little arrow button. Connect the first node to the second node ~twice~ (on closer inspection, just once seems to be enough), and then remove at least one of the connections by dragging the arrow end off. 

This will already result in 
`REGRESSION: getDragScope will not work now that individual elements are not configured as draggables`
and
`jsPlumb function failed : TypeError: Cannot read property 'removeClass' of null`
being logged to the console.

Then if you drag one of the nodes it will throw that error. You'll see it simply as "Script error" in the JSFiddle console, see the top of this report for the detailed error.

## Conclusion ##

Am I doing something wrong? If so it's not very clear what. This error doesn't actually appear to be breaking anything, as far as I can tell, but it seemed worth reporting because I don't think random errors are usually a good sign.

### EDIT ###

This is for version `@jsplumb/community 4.0.0-RC20`

**Comment by sporritt** [comment]
Thanks for the example. Also nice to know people are using 4.x.

This issue is fixed in dev for 4.0.0-RC21, which I haven't got around to releasing because it also includes a bunch of packaging stuff and I haven't had an opportunity to test it everywhere yet. I will try to get on that.

**Comment by sebovzeoueb** [comment]
Well, thank you for releasing this great piece of software! Glad to know a fix is incoming.

**Comment by sporritt** [comment]
I'm just going to reopen this in order to keep it on my radar until the associated milestone is out.
