### ISSUE TITLE
The readme mentions an "elementsDraggable" setting but I can't find this.

### ISSUE THREAD

**Issue by sebovzeoueb** [jsplumb/jsplumb#991]
The readme mentions that there's an `elementsDraggable` setting in the defaults, which I would really like to set to false instead of having to put the non draggable attribute on each element.

Upon seeing that this didn't work, I did a search on the source code and I actually can't find this feature at all, is it not implemented?

(again 4.x version)

**Comment by sporritt** [comment]
this is present in RC22, along with an `elementsDraggable` property on the jsplumb instance which can be toggled to turn drag on/off.
