### ISSUE TITLE
"allowLoopback: false" doesn't work

### ISSUE THREAD

**Issue by sebovzeoueb** [jsplumb/jsplumb#992]
https://jsfiddle.net/u0b39osL/1/

I've set allowLoopback to false in makeTarget as per the documentation, but I can still create loopback connections.

version: 4.x

**Comment by sporritt** [comment]
there's a fix for this in RC21.  it was also possible to support `allowLoopback` in the options to `makeSource` in 4.x.

**Comment by sporritt** [comment]
@sebovzeoueb i've just published RC21. one of the things it included was some basic reworking of the packaging so this publish is a bit speculative. If you could try switching to RC21 it would be very useful.

**Comment by sebovzeoueb** [comment]
So far so good, allowLoopback: false is working now!

**Comment by sporritt** [comment]
thanks for letting me know. i was pretty confident `allowLoopback:false` was working...but the packaging was a bit of an unknown...
