### ISSUE TITLE
dragOptions don't seem to work

### ISSUE THREAD

**Issue by sebovzeoueb** [jsplumb/jsplumb#993]
https://jsfiddle.net/u0b39osL/6/

note that in my fiddle I have set `dragOptions : {grid: [50, 50], containment: true}` in the newInstance call, but neither of these options seem to do anything.

**Comment by sporritt** [comment]
Yes somehow that has escaped being ported.  I will get this back in but it won't be in RC21, might take a little more time.

**Comment by sebovzeoueb** [comment]
Is there currently any way to set the drag options at all, or it's just completely not re-implemented yet?

**Comment by sporritt** [comment]
The grid stuff? Some dragOptions are currently supported - you can set lifecycle listeners, for instance.  But the grid/containment options are not there yet. It's probably not a huge deal to port them. I just haven't looked at it yet.

**Comment by sporritt** [comment]
`grid` is supported in the `dragOptions` in RC22.
