### ISSUE TITLE
"jsPlumb: fire failed for event..." if the query returns 0 results (looks like select function is actually missing)

### ISSUE THREAD

**Issue by sebovzeoueb** [jsplumb/jsplumb#995]
If you use the select function to query connections in an event listener and the query doesn't return any results it causes a "fire failed" log if you chain anything onto it.

In my opinion the expected behaviour would be that you should be allowed to chain onto an empty query without it throwing and causing the rest of the listener to fail.

Here's my code causing the issue:
```
    instance.bind('connection', info => {
      // if we establish a new connection flowing the opposite way to an existing one we should remove the existing one
      instance.select({source: info.targetId, target: info.sourceId}).delete()
    })
```

I know I could just check the select results before, but I would expect this to work more like a forEach or something where operating on a 0 length array just causes the operation to be performed 0 times.

**Update**

OK, there's actually a bug, because it's still erroring when it should actually be able to find a connection with those IDs. That listener above was working fine in RC20, and now in RC21 it's erroring and not deleting the connection. 

In fact, it looks like the whole select function is just gone from auto-complete, so maybe that's the problem.

**Comment by sporritt** [comment]
`select(..)` exists. But `delete()` does not. You're looking for `deleteAll()` I think:

https://github.com/jsplumb/jsplumb/blob/dev/4.x/dist/core/selection/connection-selection.d.ts

**Comment by sebovzeoueb** [comment]
Huh, my code snippet was working in RC20, then not at all in RC21, can confirm that on RC22 it works using deleteAll. Thanks for fixing!

**Comment by sporritt** [comment]
@sebovzeoueb i was puzzled by your assertion that `select()` was missing from your autocomplete, but someone pointed out in #999 that the core typedefs were not actually included in the browser build.  In 4.0.0-RC23 that's fixed.
