### ISSUE TITLE
jsPlumb.empty() method triggers infinity loop

### ISSUE THREAD

**Issue by hzwz00** [jsplumb/jsplumb#997]
When there is <select> tag inside the element, calling jsPlumb.empty(elment) triggers infinity loop. The problematic code is in the getElement method:  

**_el = typeof el === "string" ? el : el.length != null && el.enctype == null ? el[0] : el;_**  

the 'el' (select tag) will be incorrectly treated as jquery selector. it can be fixed as below:  

**_el = typeof el === "string" ? el : el.length > 0 && el.enctype == null ? el[0] : el;_**

**Comment by sporritt** [comment]
Can you provide an example of the html of an element where you're seeing this?

**Comment by hzwz00** [comment]
I have a Kendo UI Grid control inside a jsPlumb group. The page numbers of grid pager was rendered as below:

`<div class="k-pager-numbers-wrap k-floatwrap"><select class="k-dropdown"><option value="1" selected="selected">1</option></select><ul class="k-pager-numbers"><li><span class="k-link k-state-selected">1</span></li></ul></div>`

That `<select>` tag in above HTML code triggers infinity loop when I call jsPlumb.empty() method on the group. The Kendo UI lib I am using is v2020.3.1118.

**Comment by sporritt** [comment]
What element do you call `empty` on? Can you provide a fiddle or codepen?

**Comment by hzwz00** [comment]
Please check this [sample](https://jsfiddle.net/yvodkmuw/) on jsfiddle. When you click 2nd button '**empty group1**', it freezes and run into an infinity loop.

**Comment by sporritt** [comment]
thanks.  Could you try this version of a fix in your code:

```
el = typeof el === "string" ? el : (el.tagName == null && el.length != null && el.enctype == null) ? el[0] : el;
```

**Comment by hzwz00** [comment]
I've verified that your code does fix the problem. Thanks.

**Comment by sporritt** [comment]
thanks, i will do a release.

**Comment by sporritt** [comment]
2.15.3 was just released.

fyi, the `empty()` method has been in removed in 4.x. 2.15.3 is going to be the last version of the 2.x branch that gets any new features.
