### ISSUE TITLE
4.x-alpha RC21 missing core definitions

### ISSUE THREAD

**Issue by alxAgu** [jsplumb/jsplumb#999]
Hi, I was just testing out RC22 (from RC20) and noticed the `batch` and `connect` methods were no longer part of the `browser-jsplumb-instance` definitions. 'core.d.ts' seems to be missing?

**Comment by sporritt** [comment]
That correlates with what someone said on an issue the other day, that `select()` was missing from his auto complete. In RC21 I switched the packaging around to split out core (for server side only) and the browser build. Although the source pulls in the core code I guess the .d.ts files do not.  I'll put RC23 out with a fix for this later today.

**Comment by sporritt** [comment]
4.0.0-RC23 was just published.  You should be able to access the core defs from the browser build now.

It's good to know people are switching to the 4.x branch now.  I think it's probably mature enough to make it the main release and put 2.x into maintenance mode.

**Comment by alxAgu** [comment]
> 4.0.0-RC23 was just published. You should be able to access the core defs from the browser build now.

Perfect! 
I can confirm that (after updating some of the imports) everything works again. Thanks heaps!

**Comment by sporritt** [comment]
thanks for the confirmation.
